#!/bin/bash
###############################################################################
# Opdracht uitvoeren.
#
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
#
# Auteursrecht (c) 2021 Karel Zimmer.
# GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
#
# ReleaseNumber: 01.01.02
# DateOfRelease: 2021-08-20
###############################################################################

###############################################################################
# Global constants
###############################################################################

readonly    PROGRAM_NAME=$(basename "$0")
readonly    DISPLAY_NAME=${PROGRAM_NAME/kz_/kz }
readonly    PROGRAM_PATH=$(realpath "$(dirname  "$0")")
readonly    CALLED=$(printf '%s' "$0 $*" | xargs --null)
declare -ir SUCCESS=0
declare -ir ERROR=1
declare -ir WARNING=2

readonly    USAGE="\
Gebruik: $DISPLAY_NAME OPDRACHT [ARG]
     of: $DISPLAY_NAME [-l|--list] [-h|--help] [-u|--usage] [-v|--version]"
readonly    HELP="\
Gebruik: $DISPLAY_NAME OPDRACHT [ARG]
         $DISPLAY_NAME OPTIE

Opdracht uitvoeren.

Opties:
  -l --list     toon beschikbare OPDRACHTen
  -h --help     deze hulptekst tonen
  -u --usage    een korte gebruikssamenvatting tonen
  -v --version  de versie tonen
  --            stop verwerken opdrachtregelopties

Argumenten:
  OPDRACHT      uit te voeren opdracht
  ARG           argumenten behorend bij OPDRACHT"


###############################################################################
# Global variables
###############################################################################

declare EXEC=''


###############################################################################
# Functions
###############################################################################

init_script() {
    # Script-hardening.
    set -o errexit
    set -o errtrace
    set -o nounset
    set -o pipefail

    # Script kz_getdeb verwijdert niet kz en kz.1 i.v.m. lokale Git-repo.
    rm --force kz.{2..99}
}


check_input() {
    if ! [[ "$*" ]]; then
        printf "$DISPLAY_NAME: %s\n\n" 'OPDRACHT [ARG] opgeven' >&2
        show_commands
        exit $WARNING
    fi
    if [[ $1 == *-h* ]]; then
        process_option_help
        exit $SUCCESS
    fi
    if [[ $1 == *-l* ]]; then
        show_commands
        exit $SUCCESS
    fi
    if [[ $1 == *-u* ]]; then
        process_option_usage
        exit $SUCCESS
    fi
    if [[ $1 == *-v* ]]; then
        process_option_version
        exit $SUCCESS
    fi
    if ! [[ -e "$PROGRAM_PATH/kz_$1" ]]; then
        printf "$DISPLAY_NAME: %s\n\n" "OPDRACHT '$1' bestaat niet" >&2
        show_commands
        exit $ERROR
    fi
}


show_commands() {
    printf '%s\n' 'De volgende OPDRACHTen zijn beschikbaar:'
    find    "$PROGRAM_PATH"/kz_*    \
            -maxdepth 1             \
            -type f                 \
            -executable             \
            -readable               \
            -not -name '*~'         \
            -not -name 'kz'         \
            -printf '%f\n'          |
    sort                            |
    sed     's/kz_//'
    printf "\n%s\n"  "Typ '$DISPLAY_NAME --help' voor meer informatie."
}


process_option_usage() {
    printf "%s\n\n%s\n" \
            "$USAGE"    \
            "Typ '$DISPLAY_NAME --help' voor meer informatie."
}


process_option_help() {
    printf  "%s\n\n%s\n"    \
            "$HELP"         \
            "Typ 'man $DISPLAY_NAME' voor meer informatie."
}


process_option_version() {
    local release_number='00.00.00'
    local copyright_years='1970'
    local release_date='1970-01-01'

    copyright_years=$(
        grep    --regexp='Auteursrecht '        \
                "$PROGRAM_PATH/$PROGRAM_NAME"   |
        awk     '{print $4;exit}'
        )
    release_number=$(
        awk -F'ReleaseNumber: '                 \
            '/ReleaseNumber: /{print $2;exit}'  \
            "$PROGRAM_PATH/$PROGRAM_NAME"
        )
    release_number=${release_number:0:8}
    release_date=$(
        awk -F'DateOfRelease: '                 \
            '/DateOfRelease: /{print $2;exit}'  \
            "$PROGRAM_PATH/$PROGRAM_NAME"
        )
    release_date=${release_date:0:10}
    printf "%s\n" "$DISPLAY_NAME $release_number ($release_date)

Geschreven door Karel Zimmer <info@karelzimmer.nl>.

Auteursrecht (c) $copyright_years Karel Zimmer.
GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>."
}


process_input() {
    EXEC=${CALLED/kz /kz_}
    # shellcheck disable=SC2086
    exec $EXEC
}


term_script() {
    exit $SUCCESS
}


###############################################################################
# Main line
###############################################################################

main() {
    init_script
    check_input "$@"
    process_input
    term_script
}


main "$@"


# EOF
