#!/bin/bash
###############################################################################
# Opdracht uitvoeren.
#
# Geschreven in 2021 door Karel Zimmer <info@karelzimmer.nl>, Creative Commons
# Publiek Domein Verklaring <http://creativecommons.org/publicdomain/zero/1.0>.
###############################################################################


###############################################################################
# Constants
###############################################################################

readonly program_name='kz'
readonly program_desc='Opdracht uitvoeren'
readonly display_name=${program_name/kz-/kz }

program_path=$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}:-$0}")")" && pwd)
readonly program_path
source "$program_path"/kz_common.sh

readonly usage="Gebruik: $display_name OPDRACHT [ARG]
     of: $display_name [-l|--list] [-u|--usage] [-h|--help] [-v|--version]"
readonly help="Gebruik: $display_name OPDRACHT [ARG]
     of: $display_name OPTIE

$program_desc.

Opties:
  -l, --list     toon beschikbare OPDRACHTen
  -h, --help     toon deze hulptekst
  -u, --usage    toon een korte gebruikssamenvatting
  -v, --version  toon programmaversie

Argumenten:
  OPDRACHT       uit te voeren opdracht
  ARG            argumenten behorend bij OPDRACHT"


###############################################################################
# Variables
###############################################################################


###############################################################################
# Functions
###############################################################################

function check_input {
    # Geen getopt want opgegeven opties zijn voor OPDRACHT, niet voor kz.
    if ! [[ "$*" ]]; then
        info "$display_name:verplicht argument ontbreekt"
        info "$usageline"
        exit $err
    elif [[ $1 == -u* || $1 == --u* ]]; then
        kz_common.process_option_usage
        exit $ok
    elif [[ $1 == -h* || $1 == --h* ]]; then
        kz_common.process_option_help
        exit $ok
    elif [[ $1 == -v* || $1 == --v* ]]; then
        kz_common.process_option_version
        exit $ok
    elif [[ $1 == -l* || $1 == --l* ]]; then
        show_commands
        exit $ok
    elif ! [[ -f "$program_path/kz-$1" ]]; then
        info "$display_name:opdracht '$1' bestaat niet"
        info "$usageline"
        exit $err
    fi
}


function show_commands {
    info 'De volgende OPDRACHTen zijn beschikbaar:

     OPDRACHT'
    find    "$program_path"/kz-*            \
            -maxdepth 1                     \
            -type f                         \
            -executable                     \
            -readable                       \
            -not -name '*~'                 \
            -not -name 'kz'                 \
            -printf '%f\n'                  |
    sort                                    |
    sed     --expression='s/kz-//'          |
            nl      --number-width=2        \
                    --number-format=rn      \
                    --number-separator='] ' \
                    --body-numbering=a      |
            sed     --expression='s/^/[/'
    info "
Om een OPDRACHT uit te voeren:
${blue}$display_name OPDRACHT${normal}"
}


function process_input {
    local exec_program_name=''

    exec_program_name=$1
    shift
    exec "$program_path/kz-$exec_program_name" "$@"
}


function term_script {
    exit $ok
}


###############################################################################
# Script
###############################################################################

function main {
    kz_common.init_script "$@"
    check_input "$@"
    process_input "$@"
    term_script
}

main "$@"
