.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz archive.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" RELEASE_YEAR=2019
.\"
.\" VERSION_NUMBER=04.00.02
.\" VERSION_DATE=2021-09-04
.\"
.\"
.TH KZ-ARCHIVE 1 "KZ Handleiding" "KZ-ARCHIVE(1)" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz archive \- Scripts archiveren.
.\"
.\"
.SH SAMENVATTING
.B kz archive
[OPTIE...] [--] [\fISELECTIE\fR...]
.\"
.\"
.SH BESCHRIJVING
\fBkz archive\fR archiveert scripts en overige bestanden.
.sp
Standaard, tenzij \fISELECTIE\fRs zijn opgegeven, wordt de gebruiker gevraagd
om op te geven wat gearchiveerd dient te worden.
.sp
In de betreffende mappen wordt gezocht naar bestanden overeenkomend met
\fISELECTIE\fR, en gevraagd of een bestand gearchiveerd of verwijderd mag
worden.
.br
Onderscheid tussen hoofdletters en kleine letters wordt genegeerd.
.sp
In een grafische werkomgeving zoals GNOME (e.g. Ubuntu) kan \fBkz archive\fR
worden gestart door te zoeken naar \fBarch\fR, klik op
\fBScripts archiveren\fR.
.\"
.\"
.SH OPTIES
.TP
\fB-d\fR, \fB--debug\fR
Geef foutopsporingsinformatie weer in het logboek (gebruik '[sudo] journalctl
-ab -t kz-archive').
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB--\fR
Een -- geeft het einde van de opties aan en schakelt de verdere verwerking van
opties uit.
.br
Alle argumenten na de -- worden behandeld als bestandsnamen en argumenten.
Een argument van - is gelijk aan --.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH BESTANDEN
~/kz-scripts/*
.RS
Scripts en overige bestanden.
.RE
.sp
~/kz-docs/*
.RS
Checklists en overige bestanden.
.RE
.sp
~/uploads/data/linux/*
.RS
Checklists, scripts, en overige bestanden.
.RE
.sp
~/uploads/data/linux-archief/*
.RS
Checklists, scripts, en overige bestanden archief.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-common.sh\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz archive\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" # EOF
