.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz archive.                                               "
.\"                                                                           "
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.                       "
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-ARCHIVE 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz archive \- Scripts archiveren.
.\"
.\"
.SH SAMENVATTING
.B kz archive
[OPTIE...] [\fISELECTIE\fR...]
.\"
.\"
.SH BESCHRIJVING
\fBkz archive\fR archiveert scripts en overige bestanden.
.sp
Standaard, tenzij \fISELECTIE\fRs zijn opgegeven, wordt de gebruiker gevraagd
om op te geven wat gearchiveerd dient te worden.
.sp
In de betreffende mappen wordt gezocht naar bestanden overeenkomend met
\fISELECTIE\fR, en gevraagd of een bestand gearchiveerd of verwijderd mag
worden.
.br
Onderscheid tussen hoofdletters en kleine letters wordt genegeerd.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
Wordt genegeerd.
.TP
\fB-d\fR, \fB--debug\fR
Neem foutopsporingsinformatie op in het logboek.
Bekijk het logboek met '[sudo] journalctl -ab -t kz-archive'.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH BESTANDEN
~/kz-scripts/*
.RS
Scripts en overige bestanden.
.RE
.sp
~/kz-docs/*
.RS
Checklists en overige bestanden.
.RE
.sp
~/kz-uploads/dist/data/linux/*
.RS
Checklists, scripts, en overige bestanden.
.RE
.sp
~/kz-uploads/app/linux-archief/*
.RS
Checklists, scripts, en overige bestanden archief.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-common.sh\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz archive\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
