#!/bin/bash
# shellcheck source=kz_common.sh
###############################################################################
# Back-up maken.
#
# Geschreven in 2007 door Karel Zimmer <info@karelzimmer.nl>, Creative Commons
# Publiek Domein Verklaring <http://creativecommons.org/publicdomain/zero/1.0>.
###############################################################################

program_path=$(cd "$(dirname "$(realpath "$0")")" && pwd)
source "$program_path"/kz_common.sh


###############################################################################
# Constants
###############################################################################

declare program_name='kz-backup'
declare program_desc='Back-up maken'
declare display_name=${program_name/kz-/kz }

declare usage="Gebruik: $display_name [--delete] [--dry-run] [-g|--gui] \
[-t|--target=DOELMAP]
                   $options_usage"
declare help="Gebruik: $display_name [OPTIE...]

$program_desc.

Opties:
      --delete   uit de Persoonlijke map verwijderde bestanden ook uit de
                 back-up verwijderen (standaard bij optie -g, --gui)
      --dry-run  een proefrun uitvoeren zonder wijzigingen aan te brengen
  -g, --gui      start in grafische modus
  -t, --target=DOELMAP
                 plaats back-up in de DOELMAP
$options_help"
declare options_short+='gt:'
declare options_long+=',delete,dry-run,gui,target:'

declare source=$HOME


###############################################################################
# Variables
###############################################################################

declare medium=''
declare option_delete=''
declare option_delete_excluded=''
declare option_dry_run=''
declare option_gui=false
declare option_target=false
declare target_argument=''
declare target_medium=''
declare target=''


###############################################################################
# Functions
###############################################################################

function check_input {
    local -i getopt_rc=0
    local parsed=''

    parsed=$(
        getopt  --alternative                       \
                --options       "$options_short"    \
                --longoptions   "$options_long"     \
                --name          "$display_name"     \
                --              "$@"
        ) || getopt_rc=$?
    if [[ $getopt_rc -ne $ok ]]; then
        info "$usageline"
        exit $err
    fi
    eval set -- "$parsed"
    kz_common.process_options "$@"

    while true; do
        case $1 in
            --delete)
                option_delete='--delete'
                option_delete_excluded='--delete-excluded'
                shift
                ;;
            --dry-run)
                option_dry_run='--dry-run'
                shift
                ;;
            -g|--gui)
                option_gui=true
                kz_common.reset_terminal_attributes
                shift
                ;;
            -t|--target)
                option_target=true
                target_argument=$2
                shift 2
                ;;
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    if [[ "$*" ]]; then
        info "$display_name:geen argumenten toegestaan"
        info "$usageline"
        exit $err
    fi
}


function process_input {
    if $option_target; then
        if ! [[ -d $target_argument ]]; then
            info "Map $target_argument bestaat niet."
            info "$usageline"
            exit $err
        fi
        target=$target_argument/backup-$HOSTNAME-$USER
        target_medium=$target_argument
    else
        medium=$(ls --directory /media/"$USER"/* 2> >($logcmd) || true)
        if [[ -z $medium ]]; then
            text="Koppel het usb-medium aan waarop de back-up wordt geplaatst."
            warn "$text"
            kz_common.wait_for_enter
            medium=$(ls --directory /media/"$USER"/* 2> >($logcmd) || true)
            if [[ -z $medium ]]; then
                err 'Geen usb-medium gevonden.

Koppel een usb-medium aan, en start daarna backup opnieuw.'
                exit $err
            fi
        fi
        if [[ $(printf '%s\n' "$medium" | wc --lines) -gt 1 ]]; then
            err "Koppel slechts één usb-medium aan.

Nu aangekoppeld zijn:
$medium

Koppel media af via Bestanden, en start daarna backup opnieuw."
            exit $err
        fi
        target=$medium/backup-$HOSTNAME-$USER
        target_medium=$medium
    fi

    kz_common.check_on_ac_power

    title='Instellingen veiligstellen'
    text='Instellingen veiligstellen'
    if $option_gui; then
        backup_settings                 |
        zenity  --progress              \
                --pulsate               \
                --auto-close            \
                --no-cancel             \
                --width     600         \
                --height    50          \
                --title     "$title"    \
                --text      "$text"     2> >($logcmd)
    else
        info "$text..."
        backup_settings
    fi

    create_backup
}


function backup_settings {
    local tgtdir=$HOME/Instellingen

    mkdir --parents "$tgtdir" |& $logcmd
    backup_settings_desktop_background
    backup_settings_favorite_apps
    backup_settings_installed_apps
    backup_settings_user_photo

    # Old folder, lagacy.
    rm --force --recursive "$HOME"/kz-data/
}


function backup_settings_desktop_background {
    local file=$tgtdir/Achtergrond
    local picture_file=''

    picture_file=$(
        gsettings get org.gnome.desktop.background picture-uri  |
        sed --expression='s|%20| |g'                            |
        sed --expression="s/'//g"                               |
        sed --expression='s|file://||'                          || true
        )
    cp --update "$picture_file" "$file" |& $logcmd || true
}


function backup_settings_favorite_apps {
    local file=$tgtdir/Favorieten

    gsettings get org.gnome.shell favorite-apps  > "$file" |& $logcmd || true
}


function backup_settings_installed_apps {
    local file=$tgtdir/Apps
    local header1="[1/3] Deze pakketten zijn geïnstalleerd via Software, \
met een opdracht zoals
      'sudo apt --install <pakket|bestand>', of met kz install:"
    local header2="[2/3] Deze snaps zijn geïnstalleerd via Software, \
met '[sudo] install <snap>',
      of met kz install:"
    local header3="[3/3] Deze pakketbronnen zijn toegevoegd met de \
installatie van een pakket, met
      de opdracht 'sudo add-apt-repository ppa:<ppa-gebruiker>/<ppa-naam>', of
      met kz install:"
    local search=/etc/apt/sources.list

    printf '%b\n' "$header1" > "$file"
    if ! apt list --manual-installed 2> >($logcmd) >> "$file"; then
        true
    fi

    printf '\n%b\n' "$header2" >> "$file"
    if ! snap list 2> >($logcmd) >> "$file"; then
        printf '%s\n' 'snap is niet geïnstalleerd' >> "$file"
    fi

    printf '\n%b\n' "$header3" >> "$file"
    cd  $search.d
    if !    grep    --recursive             \
                    --no-filename           \
                    --regexp='^deb '        \
                    --recursive             \
                    /etc/apt/sources.list   \
                    /etc/apt/sources.list.d |
            grep    --invert-match          \
                    --regexp='ubuntu.com'   |
            sort    --unique                >> "$file"; then
        true
    fi
}


function backup_settings_user_photo {
    local srcdir=/var/lib/AccountsService/icons
    local file=$tgtdir/Gebruikersfoto

    cp --update $srcdir/"$USER" "$file" |& $logcmd || true
}


function create_backup {
    local exclude=''
    local -i rsync_rc=0

    exclude=$(mktemp -t "$program_name-XXXXXXXXXX")

    # Backup solution Déjà Dup exclude these files by default.
    cat << EOF > "$exclude"
.adobe/Flash_Player/AssetCache
.cache
.ccache
.gvfs
.Private
.recent-applications.xbel
.recently-used.xbel
snap/*/*/.cache
.steam/root
.thumbnails
.var/app/*/cache
.xsession-errors
EOF

    # Skip git-controlled directories.
    cat << EOF >> "$exclude"
$(
    find    "$HOME"         \
            -maxdepth 2     \
            -name .git      \
            -type d         \
            -print          |
    cut     --delimiter='/' \
            --fields=4      |
    sort
    )
EOF

    title='Back-up maken'
    text='Backup voorbereiden (dit kan even duren)'
    if $option_gui; then
        rsync   --archive                   \
                --verbose                   \
                --delete                    \
                --exclude-from="$exclude"   \
                --delete-excluded           \
                "$source"/                  \
                "$target"/                  \
                2> >($logcmd)               |
        sed     --expression='s/^/#/'       |
        zenity  --progress                  \
                --auto-close                \
                --no-cancel                 \
                --pulsate                   \
                --width     600             \
                --height    50              \
                --title     "$title"        \
                --text      "$text"         2> >($logcmd) || rsync_rc=$?
    else
        info "$text..."
        rsync   --archive                   \
                --verbose                   \
                --human-readable            \
                $option_dry_run             \
                $option_delete              \
                $option_delete_excluded     \
                --exclude-from="$exclude"   \
                "$source"/                  \
                "$target"/                  2> >($logcmd) || rsync_rc=$?
    fi
   rm "$exclude"

    case $rsync_rc in
        0)
            return $ok
            ;;
        *)
            err "Back-up maken is geeindigd met fouten.

Mogelijk zijn enkele bestanden niet leesbaar, of zijn er bestanden verwijderd
of toegevoegd tijdens het maken van de back-up, of is er te weinig ruimte op
$target."
            exit $err
            ;;
    esac

}


function term_script {
    local dev=''
    local -i rc=0

    text='Gegevens uit tijdelijk geheugen wegschrijven (dit kan even duren)'
    if $option_gui; then
        sync                                        |
        zenity  --progress                          \
                --pulsate                           \
                --auto-close                        \
                --no-cancel                         \
                --width     600                     \
                --height    50                      \
                --title     "$title"                \
                --text      "$text"                 2> >($logcmd) || rc+=$?
    else
        info "
$text..."
        sync |& $logcmd || rc+=$?
    fi

    text=''
    if [[ $target_medium == /media/* ]]; then
        text='Het usb-medium afkoppelen'
        dev='/dev/'$(
            lsblk   --ascii             |
            grep    --before-context=1  \
                    "$target_medium"    |
            head    -1                  |
            cut     --delimiter='-'     \
                    --fields=2          |
            cut     --delimiter=' '     \
                    --fields=1
        )
        if $option_gui; then
            umount "$target_medium";                    \
            udisksctl lock --block-device "$dev";       \
            udisksctl power-off --block-device "$dev"   |
            zenity  --progress                          \
                    --pulsate                           \
                    --auto-close                        \
                    --no-cancel                         \
                    --width     600                     \
                    --height    50                      \
                    --title     "$title"                \
                    --text      "$text"                 2> >($logcmd) || rc+=$?
        else
            info "$text..."
            umount "$target_medium" |& $logcmd || rc+=$?
            udisksctl lock --block-device "$dev" |& $logcmd || rc+=$?
            udisksctl power-off --block-device "$dev" |& $logcmd || rc+=$?
        fi
        if [[ $rc -eq $ok ]]; then
            info "
De back-up is gemaakt.

Het usb-medium kan verwijderd worden."
        else
            warn "
De back-up is gemaakt.

Koppel zelf (veilig!) het usb-medium af."
        fi
    else
        info "
De back-up is gemaakt."
    fi
    exit $ok
}


###############################################################################
# Script
###############################################################################

function main {
    kz_common.init_script "$@"
    check_input "$@"
    process_input
    term_script
}

main "$@"
