.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz_common.py.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" RELEASE_YEAR=2021
.\"
.\" VERSION_NUMBER=02.00.02
.\" VERSION_DATE=2021-09-08
.\"
.\"
.TH KZ_COMMON.PY 1 "KZ Handleiding" "KZ_COMMON.PY(1)" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz_common.py \- Algemene module voor Python scripts.
.\"
.\"
.SH SAMENVATTING
.B import kz_common
.\"
.\"
.SH BESCHRIJVING
Deze module geeft toegang tot algemene functies.
.sp
Algemene functies zoals:
.br
- verwerk optie usage (process_option_usage)
.br
- verwerk optie version (process_option_version)
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Bestand \fBkz_common.py\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
