.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz-common.sh.                                             "
.\"                                                                           "
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.                       "
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-COMMON.SH 1 "KZ Handleiding" "KZ-COMMON.SH(1)" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz-common.sh \- Algemene module voor shell scripts.
.\"
.\"
.SH SAMENVATTING
.B source kz-common.sh
.\"
.\"
.SH BESCHRIJVING
Deze module geeft toegang tot algemene variabelen en functies.
.sp
Algemene variabelen zoals:
.br
- afsluitwaarden (SUCCES, ERROR)
.br
- terminalattributen (GREEN, YELLOW, RED)
.br
- voer script uit als root (RUN_AS_SUPERUSER)
.sp
Algemene functies zoals:
.br
- initiele acties bij starten van een script (init_script)
.br
- verwerk opties zoals usage en help (process_common_options)
.br
- controleer verplicht gebruik van root (check_user_root)
.sp
Tevens zorgt deze module voor script-hardening en foutafhandeling.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Module \fBkz-common.sh\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
