.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz ckhtml.                                                "
.\"                                                                           "
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.                       "
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-CKHTML 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz ckhtml \- Webbestanden valideren.
.\"
.\"
.SH SAMENVATTING
.B kz ckhtml
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz ckhtml\fR valideert HTML- en CSS-bestanden.
.sp
De pagina's (.html) en opmaakbestanden (.css) worden gevalideert met de W3C
Markup- en CSS Validatie Service.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
Wordt genegeerd.
.TP
\fB-d\fR, \fB--debug\fR
Neem foutopsporingsinformatie op in het logboek.
Bekijk het logboek met 'journalctl -ab -t kz-ckhtml'.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH WEBADRESSEN
https://karelzimmer.nl/css
.RS
Map met CSS op internet.
.RE
.sp
https://karelzimmer.nl/html
.RS
Map met HTML op internet.
.RE
.sp
http://jigsaw.w3.org/css-validator/validator?uri=
.RS
CSS-validator.
.RE
.sp
http://validator.w3.org/check?uri=
.RS
HTM-validator.
.RE
.\"
.\"
.SH MAPPEN
~/kz-uploads/dist/css
.RS
Map met CSS (Cascading Style Sheets).
.RE
.sp
~/kz-uploads/dist/html
.RS
Map met HTML (HyperText Markup Language).
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-common.sh\fR(1),
\fBkz-ckname\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz ckhtml\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
