.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz ckname.                                                "
.\"                                                                           "
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.                       "
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-CKNAME 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz ckname \- Bestandsnamen controleren.
.\"
.\"
.SH SAMENVATTING
.B kz ckname
[OPTIE...] [\fIMAP...\fR]
.\"
.\"
.SH BESCHRIJVING
\fBkz ckname\fR controleert map- en bestandsnamen op toegestane tekens voor
NTFS en ext4 bestandssystemen.
.sp
Standaard, tenzij \fIMAP\fR is opgegeven, wordt gezocht in Persoonlijke map.
.sp
Voer deze opdracht uit voor het plaatsen van bestanden op een NTFS
(netwerk)schijf.
.sp
Bij NTFS zijn niet toegestaan de tekens ? " / \ < > * | :
.br
Bij ext4   is niet toegestaan het teken     /
.br
daarom test \fBkz ckname\fR op de tekens      ? "   \ < > * | :
.sp
Bij NTFS zijn ook symbolische verwijzingen niet toegestaan.
.sp
Verder wordt ook de lengte van de map- en bestandsnaam gecontroleerd.
.br
Deze mag voor Versleutelde Persoonlijke Mappen, met eCryptfs, niet langer zijn
dan 142 tekens.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBdetox\fR(1),
\fBkz-common.sh\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz ckname\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
