.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kzcommon.py.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\" Auteursrecht (c) 2021 Karel Zimmer.
.\" Creative Commons Naamsvermelding-GelijkDelen Internationaal-licentie
.\" <https://creativecommons.org/licenses/by-sa/4.0/>.
.\"
.\" ReleaseNumber: 01.00.05
.\" DateOfRelease: 2021-05-08
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZCOMMON.PY 1 "kzcommon.py" "kzscripts 365" "kzcommon.py"
.\"
.\"
.SH NAAM
kzcommon.py \- Algemene module voor Python scripts.
.\"
.\"
.SH SAMENVATTING
.B import kzcommon
.\"
.\"
.SH BESCHRIJVING
Deze module geeft toegang tot algemene functies.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH AUTEURSRECHT
Auteursrecht (c) 2021 Karel Zimmer.
.br
GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH BESCHIKBAARHEID
Bestand kzcommon.py is onderdeel van het pakket kzscripts en is beschikbaar
vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
