#!/bin/bash
# shellcheck source=kz_common.sh
###############################################################################
# Bestandsnamen controleren.
#
# Geschreven in 2012 door Karel Zimmer <info@karelzimmer.nl>, Creative Commons
# Publiek Domein Verklaring <http://creativecommons.org/publicdomain/zero/1.0>.
###############################################################################


###############################################################################
# Global constants
###############################################################################

readonly program_name='kz-ckname'
readonly program_desc='Bestandsnamen controleren'
readonly display_name=${program_name/kz-/kz }

# Redhat reports $0 as '-bash', dirname "$0" -> dirname: invalid option -- 'b'.
program_path=$(realpath "$(dirname  "${0/#-/}")")
readonly program_path
source  "$program_path"/kz_common.sh

readonly usage="Gebruik: $display_name $options_usage
                   [MAP...]"
readonly help="Gebruik: $display_name [OPTIE...] [MAP...]

$program_desc.

Opties:
$options_help

Argumenten:
  MAP            begin te controleren vanaf map MAP"

declare -ir filename_maxlen=142
readonly    start_dflt=$HOME


###############################################################################
# Global variables
###############################################################################

declare     argument_map=false
declare -a  map_arguments=()


###############################################################################
# Functions
###############################################################################

function check_input {
    local -i    getopt_rc=0
    local -i    map_arg_num=0
    local       parsed=''

    parsed=$(
        getopt  --alternative                       \
                --options       "$options_short"    \
                --longoptions   "$options_long"     \
                --name          "$display_name"     \
                --              "$@"
        ) || getopt_rc=$?
    if [[ $getopt_rc -ne $ok ]]; then
        info "$usageline"
        exit $err
    fi
    eval set -- "$parsed"
    kz_common.process_options "$@"

    while true; do
        case $1 in
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    while [[ "$*" ]]; do
        argument_map=true
        map_arguments[$map_arg_num]=$1
        ((++map_arg_num))
        shift
    done
    if ! $argument_map; then
        map_arguments[0]=$start_dflt
    fi
    for dir in "${map_arguments[@]}"; do
        if ! [[ -d $dir ]]; then
            info "Map '$dir' bestaat niet"
            info "$usageline"
            exit $err
        fi
    done
}


function process_input {
    check_files
}


function check_files {
    local       basename
    local -i    count=0
    local       dirname
    local       file
    local       good

    # Het maakt niet uit of in de bestandsnaam speciale tekens voorkomen zoals
    # tab, spatie, enz.  Hiervoor zorgt de find met print0,en de read met IFS=
    # en als delimiter de null character die niet mag voorkomen in een
    # bestandsnaam.  N.B.: In Linux is alles een bestand!
    while IFS= read -r -d $'\0' file; do

        dirname=$(dirname "$file")
        basename=$(basename "$file")

        # Verwijder de slechte tekens, \ is escape voor \.
        good=$(printf '%s'"$file" | tr --delete '?"\\<>*|:')

        if ! [[ $file = "$good" ]]; then
            ((++count))
            if [[ -d "$file" ]]; then
                info "BadName  DIR '$file'."
            elif [[ -f "$file" ]]; then
                info "BadName FILE '$basename' in map '$dirname'."
            else
                info "BadName SYML '$file'."
            fi
        fi

        if [[ ${#basename} -gt $filename_maxlen ]]; then
            ((++count))
            if [[ -d "$file" ]]; then
                info "BadLen.  DIR '$basename'."
            else
                info "BadLen. FILE '$basename' in map '$dirname'."
            fi
        fi

    done < <(
        find    "${map_arguments[@]}"   \
                -not -name '.*'         \
                -not -path '*/.*'       \
                -type f                 \
                -print0                 \
                -or                     \
                -not -name '.*'         \
                -not -path '*/.*'       \
                -type d                 \
                -print0                 \
                -or                     \
                -not -name '.*'         \
                -not -path '*/.*'       \
                -type l                 \
                -print0
        )

    if [[ $count -eq 0 ]]; then
        return $ok
    elif [[ $count -eq 1 ]]; then
        info 'Er is een fout gevonden.'
    else
        info "Er zijn $count fouten gevonden."
    fi
}


function term_script {
    exit $ok
}


###############################################################################
# Script
###############################################################################

function main {
    kz_common.init_script "$@"
    check_input "$@"
    process_input
    term_script
}

main "$@"
