.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kzcommon.sh.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\" Auteursrecht (c) 2019-2021 Karel Zimmer.
.\" Creative Commons Naamsvermelding-GelijkDelen Internationaal-licentie
.\" <https://creativecommons.org/licenses/by-sa/4.0/>.
.\"
.\" ReleaseNumber: 03.04.05
.\" DateOfRelease: 2021-05-08
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZCOMMON.SH 1 "kzcommon.sh" "kzscripts 365" "kzcommon.sh"
.\"
.\"
.SH NAAM
kzcommon.sh \- Algemene module voor shell scripts.
.\"
.\"
.SH SAMENVATTING
.B source kzcommon.sh
.\"
.\"
.SH BESCHRIJVING
Dit bestand geeft toegang tot algemene variabelen en functies.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH AUTEURSRECHT
Auteursrecht (c) 2009-2021 Karel Zimmer.
.br
GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH BESCHIKBAARHEID
Bestand kzcommon.sh is onderdeel van het pakket kzscripts en is beschikbaar
vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
