#!/usr/bin/bash
# shellcheck source=kz-common.sh
###############################################################################
# Bestandsnamen controleren.                                                  #
#                                                                             #
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.                         #
###############################################################################

PROGRAM_PATH=$(realpath "$(dirname  "$0")")
readonly PROGRAM_PATH
source  "$PROGRAM_PATH"/kz-common.sh
readonly PROGRAM_NAME='kz-ckname'
readonly DISPLAY_NAME=${PROGRAM_NAME/kz-/kz }
readonly RELEASE_YEAR=2012

###############################################################################
# Global constants                                                            #
###############################################################################

readonly OPTIONS_SHORT=$OPTIONS_SHORT_COMMON
readonly OPTIONS_LONG=$OPTIONS_LONG_COMMON
readonly USAGE="Gebruik: $DISPLAY_NAME $OPTIONS_USAGE_COMMON
                   [MAP...]"
readonly HELP="Gebruik: $DISPLAY_NAME [OPTIE...] [MAP...]

Bestandsnamen controleren.

Opties:
$OPTIONS_HELP_COMMON

Argumenten:
  MAP            begin te controleren vanaf map MAP"

declare -ir FILENAME_MAXLEN=142
readonly    START_DFLT=$HOME

###############################################################################
# Global variables                                                            #
###############################################################################

declare     ARGUMENT_MAP=false
declare -a  MAP_ARGUMENTS=()

###############################################################################
# Functions                                                                   #
###############################################################################

function check_input {
    local -i    getopt_rc=0
    local -i    map_arg_num=0
    local       parsed=''

    parsed=$(
        getopt  --alternative                       \
                --options       "$OPTIONS_SHORT"    \
                --longoptions   "$OPTIONS_LONG"     \
                --name          "$DISPLAY_NAME"     \
                --              "$@"
        )       || getopt_rc=$?
    if [[ $getopt_rc -ne $SUCCESS ]]; then
        info "$USAGELINE" >&2
        exit $ERROR
    fi
    eval set -- "$parsed"
    process_common_options "$@"

    while true; do
        case $1 in
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    while [[ "$*" ]]; do
        ARGUMENT_MAP=true
        MAP_ARGUMENTS[$map_arg_num]=$1
        ((++map_arg_num))
        shift
    done
    if ! $ARGUMENT_MAP; then
        MAP_ARGUMENTS[0]=$START_DFLT
    fi
    for dir in "${MAP_ARGUMENTS[@]}"; do
        if ! [[ -d $dir ]]; then
            error "Map '$dir' bestaat niet"
            info "$USAGELINE" >&2
            exit $ERROR
        fi
    done

    check_user
}

function process_input {
    check_files_and_folders
}

function check_files_and_folders {
    local       basename
    local -i    count=0
    local       dirname
    local       file
    local       good

    # Het maakt niet uit of in de bestandsnaam speciale tekens voorkomen zoals
    # tab, spatie, enz.  Hiervoor zorgt de find met print0,en de read met IFS=
    # en als delimiter de null character die niet mag voorkomen in een
    # bestandsnaam.  N.B.: In Linux is alles een bestand!
    while IFS= read -r -d $'\0' file; do

        dirname=$(dirname "$file")
        basename=$(basename "$file")

        # Verwijder de slechte tekens, \ is escape voor \.
        good=$(printf '%s'"$file" | tr --delete '?"\\<>*|:')

        if ! [[ $file = "$good" ]]; then
            ((++count))
            if [[ -d "$file" ]]; then
                warning "BadName  DIR '$file'."
            elif [[ -f "$file" ]]; then
                warning "BadName FILE '$basename' in map '$dirname'."
            else
                warning "BadName SYML '$file'."
            fi
        fi

        if [[ ${#basename} -gt $FILENAME_MAXLEN ]]; then
            ((++count))
            if [[ -d "$file" ]]; then
                warning "BadLen.  DIR '$basename'."
            else
                warning "BadLen. FILE '$basename' in map '$dirname'."
            fi
        fi

    done < <(
        find    "${MAP_ARGUMENTS[@]}"   \
                -not -name '.*'         \
                -not -path '*/.*'       \
                -type f                 \
                -print0                 \
                -or                     \
                -not -name '.*'         \
                -not -path '*/.*'       \
                -type d                 \
                -print0                 \
                -or                     \
                -not -name '.*'         \
                -not -path '*/.*'       \
                -type l                 \
                -print0
        )

    if [[ $count -eq 0 ]]; then
        return $SUCCESS
    elif [[ $count -eq 1 ]]; then
        warning 'Er is een fout gevonden.'
    else
        warning "Er zijn $count fouten gevonden."
    fi
}

function term_script {
    exit $SUCCESS
}

###############################################################################
# Main line                                                                   #
###############################################################################

function main {
    init_script "$@"
    check_input "$@"
    process_input
    term_script
}

main "$@"
