#!/bin/bash
# shellcheck source=kz_common.sh
###############################################################################
# Pakket kz distribueren.
#
# Geschreven in 2009 door Karel Zimmer <info@karelzimmer.nl>, Creative Commons
# Publiek Domein Verklaring <http://creativecommons.org/publicdomain/zero/1.0>.
###############################################################################

program_path=$(cd "$(dirname "$(realpath "$0")")" && pwd)
source "$program_path"/kz_common.sh


###############################################################################
# Constants
###############################################################################

declare program_name='kz-deploy'
declare program_desc='Pakket kz distribueren'
declare display_name=${program_name/kz-/kz }

declare usage="Gebruik: $display_name $options_usage"
declare help="Gebruik: $display_name [OPTIE...]

$program_desc.

Opties:
$options_help"

declare scripts_repo=$HOME/kz-scripts
declare uploads_repo=$HOME/kz-uploads
declare uploads_distdir=$uploads_repo/dist


###############################################################################
# Variables
###############################################################################


###############################################################################
# Functions
###############################################################################

function check_input {
    local -i getopt_rc=0
    local parsed=''

    parsed=$(
        getopt  --alternative                       \
                --options       "$options_short"    \
                --longoptions   "$options_long"     \
                --name          "$display_name"     \
                --              "$@"
        ) || getopt_rc=$?
    if [[ $getopt_rc -ne $ok ]]; then
        info "$usage_line"
        exit $err
    fi
    eval set -- "$parsed"
    kz_common.process_options "$@"

    while true; do
        case $1 in
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    if [[ "$*" ]]; then
        info "$display_name:geen argumenten toegestaan"
        info "$usage_line"
        exit $err
    fi

    # Aangemeld als ontwikkelaar?
    if ! kz_common.developer check; then
        kz_common.developer report
        exit $err
    fi
}


function process_input {
    check_names
    check_scripts
    build_package
    upload_website
    install_package
}


function check_names {
    local -i check_rc=0
    local deb_repo=$HOME/kz-deb
    local docs_repo=$HOME/kz-docs
    local app_uploads_repo=$HOME/kz-uploads/app

    info '* controleer bestandsnamen (kz ckname)...'
    log "Check filenames with kz ckname."
    "$scripts_repo"/kz ckname   "$scripts_repo"     \
                                "$docs_repo"        \
                                "$deb_repo"         \
                                "$app_uploads_repo" || check_rc=$?
    if [[ $check_rc -ne $ok ]]; then
        err '
Herstel alle meldingen hierboven en start daarna deploy opnieuw.'
        exit $check_rc
    fi
}


function check_scripts {
    local -i check_rc=0

    info '* controleer scripts (kz ivp)...'
    log "Check scripts with kz ivp."
    "$scripts_repo"/kz ivp || check_rc=$?
    if [[ $check_rc -ne $ok ]]; then
        err '
Herstel alle meldingen hierboven en start daarna deploy opnieuw.'
        exit $check_rc
    fi
}


function build_package {
    local -i check_rc=0

    info '* bouw pakket en website (kz build)...'
    log "Build package and website with kz build."
    "$scripts_repo"/kz build || check_rc=$?
    if [[ $check_rc -ne $ok ]]; then
        err '
Herstel alle meldingen hierboven en start daarna deploy opnieuw.'
        exit $check_rc
    fi
}


function upload_website {
    local ftp_set='set ssl:verify-certificate no'
    local ftp_from=$uploads_distdir
    local ftp_to=/httpdocs
    local ftp_opts='--reverse --delete --verbose'
    local ftp_exclude='--exclude icaclient_20.04.0.21_amd64.deb'
    local ftp_cmd="mirror $ftp_exclude $ftp_opts $ftp_from $ftp_to; exit"
    local ftp_host=server106.hosting2go.nl
    local ftp_user=kzimmer
    local ftp_login=$HOME/.kz-$ftp_host

    info '* upload website (lftp)...'
    if ! [[ -f $ftp_login ]]; then
        read -rsp "Wachtwoord voor 'ftp://$ftp_host': "
        info "$REPLY" > "$ftp_login"
        printf '\n'
        chmod 'u=rw,g=,o=' "$ftp_login" |& $logcmd
    fi
    if ! lftp   --user      "$ftp_user"             \
                --password  "$(cat "$ftp_login")"   \
                -e          "$ftp_set; $ftp_cmd"    \
                "$ftp_host"; then
        rm      "$ftp_login"
        err 'Uploaden website is mislukt.'
        exit $err
    fi
    sleep 5
}


function install_package {
    info '* installeer pakket kz (kz getdeb)...'
    if ! wget -O- karelzimmer.nl/kz 2> >($logcmd) | bash; then
        err 'Installeren pakket kz is niet uitgevoerd.'
        exit $err
    fi
}


function term_script {
    exit $ok
}


###############################################################################
# Script
###############################################################################

function main {
    kz_common.init_script "$@"
    check_input "$@"
    process_input
    term_script
}

main "$@"
