.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz deploy.                                                "
.\"                                                                           "
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.                       "
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-DEPLOY 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz deploy \- Pakket kz distribueren.
.\"
.\"
.SH SAMENVATTING
.B kz deploy
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz deploy\fR distribueert en uploadt scripts en documenten naar
https://karelzimmer.nl.
.br
Dit om de scripts en documenten beschikbaar te stellen voor algemeen gebruik.
.sp
Tevens zijn de scripts en documenten op GitHub geplaatst, te verkrijgen via:
.br
\fBgit clone https://github.com/karelzimmer/kz-deb.git\fR
.br
\fBgit clone https://github.com/karelzimmer/kz-docs.git\fR
.br
\fBgit clone https://github.com/karelzimmer/kz-scripts.git\fR
.sp
Opdracht \fBkz build\fR kan worden uitgevoerd als ontwikkelaar (gebruiker \
'karel'/'Karel Zimmer' op computer 'pc??').
.sp
Mijn eigen Continuous Integration and Delivery (CI/CD) Pipeline.
.sp
Met opdracht \fBkz getdeb\fR kan de scripts-ontwikkelomgeving op een andere
of dezelfde machine neergezet worden.
.sp
De volgende acties worden uitgevoerd:
.RS
1. Controleer scriptnamen (met \fBkz ckname\fR).
.br
2. Controleer scripts (met \fBkz ivp\fR).
.br
3. Bouw pakket (met \fBkz build\fR).
.br
4. Upload website (met \fBlftp\fR).
.br
5. Installer pakket kz (met \fBkz getdeb\fR).
.RE
Mijn eigen CI/CD Pipeline :-).
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-d\fR, \fB--debug\fR
Neem foutopsporingsinformatie op in het logboek.
Bekijk het logboek met opdracht: \fBjournalctl -ab -t kz-deploy\fR
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH MAPPEN
~/kz-uploads/
.RS
Website.
.RE
.\"
.\"
.SH BESTANDEN
~/kz-uploads/downloads/kz/kz_365_all.deb
.RS
Debian-pakket kz.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-build\fR(1),
\fBkz-ckname\fR(1),
\fBkz-common.sh\fR(1),
\fBkz-getdeb\fR(1),
\fBkz-ivp\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz deploy\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
