#!/usr/bin/python3
"""
Wachtwoord genereren. Gebruik Bitwarden om wachtwoorden te beheren.

Dit script genereert een wachtwoord bestaande uit 16 willekeurige tekens.
"""
###############################################################################
# Wachtwoord genereren.
#
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
###############################################################################

import random
import kz_common


###############################################################################
# Global constants
###############################################################################

program_name = 'kz-genpwd'
program_desc = 'Wachtwoord genereren.'
display_name = program_name.replace('kz-', 'kz ')
release_year = 2021


###############################################################################
# Global variables
###############################################################################


###############################################################################
# Functions
###############################################################################

def generate_password():
    lower = 'abcdefghijklmnopqrstuvwxyz'
    upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    numbers = '0123456789'
    symbols = '$%@#[]{}()*;/,_-'

    all = lower + upper + numbers + symbols

    length = 16

    password = ''.join(random.sample(all, length))
    print(f'{password}\n\nGebruik Bitwarden om wachtwoorden te beheren.')


###############################################################################
# Script
###############################################################################

kz_common.process_common_options(display_name, program_desc)

generate_password()
