.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz getdeb.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" RELEASE_YEAR=2019
.\"
.\" VERSION_NUMBER=06.00.03
.\" VERSION_DATE=2021-09-08
.\"
.\"
.TH KZ-GETDEB 1 "KZ Handleiding" "KZ-GETDEB(1)" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz getdeb \- Scripts installeren.
.\"
.\"
.SH SAMENVATTING
.B kz getdeb
.\"
.\"
.SH BESCHRIJVING
\fBkz getdeb\fR downloadt en installeert pakket kz.
.sp
Pakket kz installeert scripts en documenten voor het afronden en beheren van de
installatie van Ubuntu en Debian Linux.
.sp
Als ontwikkelaar (gebruiker 'karel',  Ubuntu Live session user 'ubuntu', of
Debian Live user 'user').) wordt ook een ontwikkelomgeving ingericht, en is
deze na aanpassingen te
distribueren, 'live' te zetten (op https://karelzimmer.nl) met de opdrachten
.br
\fBkz deploy\fR,
.br
\fBgit push in ~/kz-deb\fR,
.br
\fBgit push in ~/kz-docs\fR, en
.br
\fBgit push in ~/kz-scripts\fR.
.sp
Voor de nieuwste versie van \fBkz getdeb\fR én het scriptspakket, start
Terminalvenster en voer
.br
uit (kopie van kz wordt opgeslagen en later \
verwijderd):
.br
    \fBwget karelzimmer.nl/kz\fR
.br
    \fBbash kz\fR
.br
 of (idem hiervoor, nu op 1 regel):
.br
    \fBwget karelzimmer.nl/kz; bash kz\fR
.br
 of (er wordt geen kopie van kz opgeslagen):
.br
    \fBwget -O- karelzimmer.nl/kz | bash\fR
.br
 of (als curl is geïnstalleerd, geen kopie):
.br
    \fBcurl -L karelzimmer.nl/kz | bash\fR
.br
 of (mits pakket kz reeds is geïnstalleerd):
.br
    \fBkz getdeb\fR
.sp
N.B. /kz mag vervangen worden door /s (beide verwijzen naar "pakket kz").
.sp
\fBkz getdeb\fR wordt ook aangeroepen vanuit \fBkz deploy\fR.
.sp
In een grafische werkomgeving zoals GNOME (e.g. Ubuntu) kan \fBkz getdeb\fR
ook worden gestart door te zoeken naar \fBget\fR, klik op
\fBScripts installeren\fR.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
.TP
\fB-d\fR, \fB--debug\fR
Geef foutopsporingsinformatie weer in het logboek (gebruik '[sudo] journalctl
-ab -t kz-archive').
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH MAPPEN
~/kz-deb/
.RS
Scriptspakket raamwerk.
.RE
.sp
~/kz-docs/
.RS
Checklists.
.RE
.sp
~/kz-scripts/
.RS
Scripts.
Inclusief man-pagina's (*.1),
en Tab-completion-scripts (*.completion),
bureaublad-configuratiebestanden (*.desktop),
PolicyKit actiedefinitiebestanden (*.policy),
.RE
.\"
.\"
.SH BESTANDEN
https://karelzimmer.nl/data/linux/scripts/kz-common.sh
.RS
Algemene module voor shell scripts.
.RE
.\"
.\"
.SH VOORBEELDEN
Een website downloaden? Voer dan uit:
.br
\fBmkdir --parents ~/uploads/karelzimmer.nl/httpdocs
.br
lftp --user <USER> --password <PASSWORD> <HOST> -e\
 'set ssl:verify-certificate no; mirror --delete --verbose /httpdocs
~/uploads/karelzimmer.nl/httpdocs; exit'\fR
.sp
Een website uploaden? Voer dan uit:
.br
\fBlftp --user <USER> --password <PASSWORD> <HOST> -e\
 'set ssl:verify-certificate no; mirror --reverse --delete --verbose /httpdocs
~/uploads/karelzimmer.nl/httpdocs; exit'\fR
.sp
Een enkel bestand downloaden? Voer dan uit:
.br
\fBlftp --user <USER> --password <PASSWORD> <HOST> -e\
 'set ssl:verify-certificate no; get -O /httpdocs/<DIR>
~/uploads/karelzimmer.nl/httpdocs/<DIR>/<FILE>; exit'\fR
.sp
Een enkel bestand uploaden? Voer dan uit:
.br
\fBlftp --user <USER> --password <PASSWORD> <HOST> -e\
 'set ssl:verify-certificate no; put -O /httpdocs/<DIR>
~/uploads/karelzimmer.nl/httpdocs/<DIR>/<FILE>; exit'\fR
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-common.sh\fR(1),
\fBkz-deploy\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz getdeb\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
