#!/usr/bin/python3
"""
Systeem bijwerken.

Dit script voert een update uit voor Debian gebaseerde systemen.
"""
###############################################################################
# Systeem bijwerken.
#
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
###############################################################################
import sys
import random
import argparse
import kz_common
import subprocess

program_name = 'kz-go'
display_name = program_name.replace('kz-', 'kz ')
release_year = 2021

version_number = '03.00.03'
version_date = '2021-09-04'


def perform_update():
    # Opdracht als sequence:
    subprocess.run(['sudo', 'apt-get', 'update'])

    # Opdracht als raw text:
    subprocess.run('sudo apt-get upgrade --yes', shell=True)

    # Opdracht als raw text, vang stdout en stderr op:
    subprocess.run('sudo apt-get autoremove --yes', shell=True, check=True)
    subprocess.run('sudo apt-get autoclean --yes', shell=True, check=True)

    # Heeft dit systeem snaps?
    try:
        subprocess.run('sudo snap refresh', shell=True)
    except Exception as ex:
        print(ex)

    # Is een reboot nodig?
    try:
        with open('/var/run/reboot-required') as fh:
            print(f'{display_name}: REBOOT')
    except FileNotFoundError:
        pass
    except Exception as ex:
        print(ex)
        sys.exit(1)


# --- script ---

parser = argparse.ArgumentParser(prog=display_name,
                                 description='Updates uitvoeren.',
                                 epilog="Typ 'man " + display_name +
                                 "' voor meer informatie.")
parser.add_argument('-g', '--gui', action='store_true',
                    help='start in grafische modus')
parser.add_argument('-u', '--usage', action='store_true',
                    help='een korte gebruikssamenvatting tonen')
parser.add_argument('-v', '--version', action='store_true',
                    help='de versie tonen')
args = parser.parse_args()

if args.usage:
    kz_common.process_option_usage(display_name)
elif args.version:
    kz_common.process_option_version(display_name, version_number,
                                     version_date, release_year)
else:
    perform_update()

# Een non-gui script gestart met optie gui.
if args.gui:
    input('Druk op de Enter-toets om verder te gaan [Enter]: ')

# EOF
