.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz gset.                                                  "
.\"                                                                           "
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.                       "
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-GSET 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz gset \- GUI wijzigen.
.\"
.\"
.SH SAMENVATTING
.B kz gset
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz gset\fR toont wijzigingen in de configuratiedatabase na aanpassingen in
de grafische werkomgeving (GUI),
.br
kan een toepassingspictogram (favoriet) toevoegen aan de favorietenbalk (aka
dash of dock), en
.br
kan een appfolder toevoegen om starters te verzamelen (bijv. KZ Scripts) in
de Vaak gebruikt-weergave en Alles-weergave;
.br
na het klikken op de rasterknop in de favorietenbalk (dash/dock).
.sp
Met optie \fB--addfavbegin\fR wordt een toepassingspictogram (favoriet)
toegevoegd aan het begin van de favorietenbalk (dash/dock).
.sp
Met optie \fB--addfavend\fR wordt een toepassingspictogram (favoriet)
toegevoegd aan het einde van de favorietenbalk (dash/dock).
.sp
Met optie \fB--removefav\fR wordt een toepassingspictogram (favoriet)
verwijderd uit de favorietenbalk (dash/dock).
.sp
Deze opties mogen \fBeenmaal\fR worden opgegeven; dus bijvoorbeeld alleen
\fB--addfavbegin\fR of alleen \fB--removefav\fR.
.br
Als een van deze opties worden gebruikt moet ook optie \fB--file\fR meegegeven
te worden met verplicht argument \fIDESKTOPFILE\fR.
.br
Als er al een toepassingspictogram (favoriet) van \fIDESKTOPFILE\fR bestaat
wordt deze niet opnieuw toegevoegd.
.br
Als een toepassingspictogram (favoriet) bovenaan is toegevoegd die onderaan
geplaatst moet worden, moet de bestaande eerst verwijderd te worden met optie
\fB--removefav (\fB-r\fR).
.sp
Met optie \fB--addappfolder\fR wordt een appfolder toegevoegd.
.sp
Met optie \fB--removefavappfolder\fR wordt een appfolder verwijderd.
.sp
Deze opties mogen \fBéénmaal\fR worden opgegeven; dus bijvoorbeeld alleen
\fB--addappfolder\fR of alleen \fB--removeappfolder\fR.
.br
Als een van deze opties worden gebruikt moet ook optie \fB--folder\fR
meegegeven te worden met verplicht argument \fIAPPFOLDER\fR.
.sp
Als er geen opties zijn opgegeven toont \fBkz gset\fR wijzigingen in de
configuratiedatabase na een wijziging in de grafische werkomgeving (GUI).
.br
Het volgende wordt uitgevoerd:
.sp
.RS
1. Inhoud configuratiedatabase ervoor vastleggen.
.br
2. Gebruiker voert wijzigingen met de GUI uit.
.br
3. Inhoud configuratiedatabase erna vastleggen.
.br
4. Wijzigingen in de configuratiedatabase rapporteren.
.RE
.sp
Met de opdracht \fBgsettings set \fIschema\fR\fB[:\fIpath\fR\fB] \fIkey\fR zijn
daarna de wijzigingen op te slaan in de configuratiedatabase, en hoeven deze
niet meer, met de hand, met de GUI te worden uitgevoerd.
.sp
Voor de systemen met LXDE- (bijv. Lubuntu) en Xfce-werkomgeving
(bijv. Xubuntu) kan via het Terminalvenster met opdrachten opgezocht
worden wat er gewijzigd moet worden:
.RS
\fBxfconf-query --list\fR
    Geeft overzicht kanalen/channels.
.sp
\fBxfconf-query --channel \fIkanaal\fR\fB --monitor --verbose\fR
    Breng nu de wijzigingen via de GUI aan.
.sp
\fBxfconf-query --channel \fIkanaal\fR\fB --list --verbose\fR
    Geeft overzicht eigenschappen/properties.
.sp
\fBxfconf-query --channel \fIkanaal\fR\fB --property \fIeigenschap\fR\fB
--set \fIwaarde\fR
    Vul de waarde in voor een property.
.RE
.\"
.\"
.SH OPTIES
.TP
\fB--addappfolder\fR
voeg een appfolder toe.
.TP
\fB--addfavbegin\fR
Voeg een toepassingspictogram (favoriet) toe bovenaan aan de favorietenbalk
(dash/dock).
.TP
\fB--addfavend\fR
Voeg een toepassingspictogram (favoriet) toe onderaan aan de favorietenbalk
(dash/dock).
.TP
\fB--file=\fIDESKTOPFILE\fR
Gebruik opgegeven dsktopbestand (.desktop).
.TP
\fB--folder=\fIAPPFOLDER\fR
Gebruik opgegeven appfolder.
.TP
\fB--removeappfolder\fR
Verwijder een appfolder.
.TP
\fB--removefav\fR
Verwijder een toepassingspictogram (favoriet) uit de favorietenbalk
(dash/dock).
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-d\fR, \fB--debug\fR
Neem foutopsporingsinformatie op in het logboek.
Bekijk het logboek met opdracht: \fBjournalctl -ab -t kz-gset\fR
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH VOORBEELDEN
.sp
\fBkz gset\fR
.RS
Toont wijzigingen in de configuratiedatabase na aanpassingen in de grafische
werkomgeving (GUI).
.RE
.sp
\fBkz gset --addfavbegin --file='idle.desktop'\fR
.RS
Voeg de IDLE (Python’s Integrated Development and Learning Environment)
toepassingspictogram (favoriet) toe bovenaan de favorietenbalk.
.RE
.sp
\fBkz gset --removefav --file='idle.desktop'\fR
.RS
Verwijder de IDLE (Python’s Integrated Development and Learning Environment)
toepassingspictogram (favoriet) uit de favorietenbalk.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBgsettings\fR(1),
\fBkz-common.sh\fR(1),
\fBxfconf-query\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz gset\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
