.\"############################################################################
.\"# Man-pagina voor kz genpwd.
.\"#
.\"# Geschreven in 2021 door Karel Zimmer <info@karelzimmer.nl>, Creative
.\"# Commons Verklaring <http://creativecommons.org/publicdomain/zero/1.0>.
.\"############################################################################
.\"
.TH KZ-GENPWD 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz-genpwd \- Wachtwoord genereren.
.\"
.\"
.SH SAMENVATTING
.B kz genpwd
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz genpwd\fR genereeert een wachtwoord bestaande uit 16 willekeurige tekens.
Gebruik Bitwarden om wachtwoorden te beheren.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH AUTEUR
Geschreven in 2021 door Karel Zimmer <info@karelzimmer.nl>, Creative Commons
Publiek Domein Verklaring <http://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH ZIE OOK
\fBkz_common.py\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz genpwd\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer - Linux - Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
