#!/bin/bash
# shellcheck source=kz-common.sh
###############################################################################
# Pakket kz installeren.
#
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
###############################################################################


###############################################################################
# Global constants
###############################################################################

readonly PROGRAM_NAME='kz-getdeb'
readonly PROGRAM_DESC='Pakket kz installeren'
readonly DISPLAY_NAME=${PROGRAM_NAME/kz-/kz }
readonly PROGRAM_YEAR=2016

PROGRAM_PATH=$(realpath "$(dirname  "$0")")
readonly PROGRAM_PATH
temp_log=$(mktemp -t "$PROGRAM_NAME-XXXXXXXXXX.log")
if ! source "$PROGRAM_PATH"/kz-common.sh &>> "$temp_log"; then
    if ! wget   --no-verbose                                                \
                --output-document=/tmp/kz-common.sh                         \
                'https://karelzimmer.nl/data/linux/scripts/kz-common.sh'    \
                &>> "$temp_log"; then
        printf  '%s\n%s\n'                              \
                'Downloaden kz-common.sh is mislukt.'   \
                "Controleer $temp_log"
        exit 1
    fi
    if ! source /tmp/kz-common.sh &>> "$temp_log"; then
        printf  '%s\n%s\n'                          \
                'Inlezen kz-common.sh is mislukt.'  \
                "Controleer $temp_log"
        exit 1
    fi
fi

readonly OPTIONS_SHORT=$OPTIONS_SHORT_COMMON
readonly OPTIONS_LONG=$OPTIONS_LONG_COMMON
readonly USAGE="Gebruik: $DISPLAY_NAME $OPTIONS_USAGE_COMMON
     of: wget karelzimmer.nl/kz
         bash kz
     of: wget karelzimmer.nl/kz; bash kz
     of: wget -O- karelzimmer.nl/kz | bash
     of: curl -L karelzimmer.nl/kz | bash"
readonly HELP="Gebruik: $DISPLAY_NAME [OPTIE...]
     of: wget karelzimmer.nl/kz
         bash kz
     of: wget karelzimmer.nl/kz; bash kz
     of: wget -O- karelzimmer.nl/kz | bash
     of: curl -L karelzimmer.nl/kz | bash

$PROGRAM_DESC.

Opties:
$OPTIONS_HELP_COMMON"


###############################################################################
# Global variables
###############################################################################
declare TEXT=''
declare TITLE=''


###############################################################################
# Functions
###############################################################################

function check_input {
    local -i    getopt_rc=0
    local       parsed=''

    parsed=$(
        getopt  --alternative                       \
                --options       "$OPTIONS_SHORT"    \
                --longoptions   "$OPTIONS_LONG"     \
                --name          "$DISPLAY_NAME"     \
                --              "$@"
        ) || getopt_rc=$?
    if [[ $getopt_rc -ne $SUCCESS ]]; then
        info "$USAGELINE"
        NOERROR=true exit $ERROR
    fi
    eval set -- "$parsed"
    process_common_options "$@"

    while true; do
        case $1 in
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    if [[ "$*" ]]; then
        info 'Geen argumenten toegestaan.'
        info "$USAGELINE"
        NOERROR=true exit $ERROR
    fi

    clear -x
    if ! check_user_sudo; then
        term_script
    fi
    check_on_ac_power
}


function check_on_ac_power {
    local -i on_battery=0

    on_ac_power &> /dev/null || on_battery=$?
    if [[ $on_battery -eq 1 ]]; then
        TITLE='Waarschuwing'
        TEXT='De computer gebruikt nu alleen de accu voor de stroomvoorziening.

Geadviseerd wordt om de computer aan te sluiten op het stopcontact.'
        whiptail    --backtitle "$DISPLAY_NAME" \
                    --title     "$TITLE"        \
                    --msgbox    "$TEXT"         \
                    10 71
    fi
}


function process_input {
    install_scriptspackage
    populate_kz_data
}


function install_scriptspackage {
    local site_deb='https://karelzimmer.nl/downloads/kz/kz_365_all.deb'
    local temp_deb=''

    check_sudo

    TITLE='Voortgang'
    TEXT='Installeer pakket kz (kan even duren)...'
    TERM=ansi whiptail  --backtitle "$DISPLAY_NAME" \
                        --title     "$TITLE"        \
                        --infobox   "$TEXT"         \
                        7 44

    check_dpkg

    # Bij Ubuntu Live sessie de universe repo aanzetten.
    if  [[ $HOSTNAME = 'ubuntu' && $USER = 'ubuntu' ]]; then
        sudo apt-add-repository --yes universe  |& $LOGCMD
        sudo apt-get update |& $LOGCMD
    fi

    # Installeer pakket kz.
    temp_deb=$(mktemp -t "$PROGRAM_NAME-XXXXXXXXXX.deb")
    wget --no-verbose --output-document="$temp_deb" $site_deb |& $LOGCMD
    sudo    DEBIAN_FRONTEND=noninteractive  \
            apt-get                         \
            reinstall                       \
            --yes                           \
            "$temp_deb"                     |& $LOGCMD
    rm "$temp_deb" |& $LOGCMD
}


function check_sudo {
    if ! sudo -n true 2> /dev/null; then
        while true; do
            TITLE='Authenticatie nodig'
            TEXT='
Authenticatie is vereist om pakket
kz met documenten en scripts van
Karel Zimmer te installeren.

Voer uw wachtwoord in:'
            # Constructie '3>&1 1>&2 2>&3' om stdout en stderr te wisselen.
            if printf '%s\n' "$(
                whiptail    --backtitle     "$DISPLAY_NAME" \
                            --title         "$TITLE"        \
                            --ok-button     'Verifiëren'    \
                            --cancel-button 'Annuleren'     \
                            --passwordbox   "$TEXT"         \
                            13 38                           \
                            3>&1 1>&2 2>&3
                )" | sudo --stdin true 2> /dev/null; then
                break
            else
                clear -x
                TITLE='Fout'
                TEXT='Er is een fout opgetreden.

Mogelijke oorzaak:
1. Geen of verkeerd wachtwoord ingevoerd
2. Op vorig scherm is <Annuleren> gekozen'
                if ! whiptail   --backtitle     "$DISPLAY_NAME" \
                                --title         "$TITLE"        \
                                --yes-button    'Opnieuw'       \
                                --no-button     'Stoppen'       \
                                --yesno         "$TEXT"         \
                                11 45; then
                    TITLE='Gestopt'
                    TEXT='Programma is gestopt door de gebruiker'
                    TERM=ansi whiptail  --backtitle "$DISPLAY_NAME" \
                                        --title     "$TITLE"        \
                                        --infobox   "$TEXT"         \
                                        7 42
                    NOERROR=true exit $ERROR
                fi
            fi
        done
    fi
}


function populate_kz_data {
    local srcdir=/usr/share/doc/kz
    local tgtdir=$HOME/kz-data

    mkdir --parents "$tgtdir" |& $LOGCMD

    # Populate kz-data with checklist installation.
    cp  $srcdir/Checklist*"$(lsb_release --id --short)"*    \
        "$tgtdir"                                           |& $LOGCMD || true
}


function term_script {
    TITLE='Gereed'
    TEXT="Pakket kz is succesvol geïnstalleerd.

Volg nu de stappen zoals beschreven
in de Checklist installatie.

Checklist installatie is te vinden:
- in de Persoonlijke map / kz-data
- in de map /usr/share/doc/kz
- op de site https://karelzimmer.nl,
  onder Linux

Typ 'exit' om dit venster te sluiten."
    TERM=ansi whiptail  --backtitle "$DISPLAY_NAME" \
                        --title     "$TITLE"        \
                        --infobox   "$TEXT"         \
                        18 41
    if developer check; then
        info 'Ontwikkelaar-acties uitvoeren.'
        install_dependencies
        pull_repos
        download_website
        info 'Status repos (gitstat)...'
        /home/"$USER"/bin/gitstat
    fi
    exit $SUCCESS
}


function install_dependencies {
    info 'Installeer afhankelijkheden...'
    sudo    apt-get             \
            install             \
            --yes               \
            fakeroot            \
            ghostscript         \
            git                 \
            lftp                \
            pycodestyle         \
            python3-pycodestyle \
            python3-autopep8    \
            python3-pip         \
            python-is-python3   |& $LOGCMD
    sudo ln --force --relative --symbolic /usr/bin/pycodestyle /usr/bin/pep8
    sudo ln --force --relative --symbolic /usr/bin/pip3 /usr/bin/pip
    # Debian pakket is oud, snap is nieuwer.
    sudo snap install shellcheck |& $LOGCMD
}


function pull_repos {
    local bin_repo=/home/"$USER"/bin

    info 'Pull repos (gitpull)...'
    git config --global pull.ff only |& $LOGCMD
    git config --global credential.helper store |& $LOGCMD
    if ! git    clone                                   \
                https://github.com/karelzimmer/bin.git  \
                "$bin_repo"                             |& $LOGCMD; then
        cd "$bin_repo"
        git pull |& $LOGCMD
    fi
    /home/"$USER"/bin/gitpull |& $LOGCMD
}


function download_website {
    local ftp_set='set ssl:verify-certificate no'
    local ftp_from=/httpdocs
    local ftp_to=$HOME/kz-uploads/dist
    local ftp_opts='--delete --verbose'
    local ftp_cmd="mirror $ftp_opts $ftp_from $ftp_to; exit"
    local ftp_host=server106.hosting2go.nl
    local ftp_user=kzimmer
    local ftp_login=$HOME/.kz-$ftp_host

    info 'Download website (lftp)...'
    if ! command -v lftp 1> /dev/null; then
        sudo apt-get install --yes lftp |& $LOGCMD
    fi
    if ! [[ -f $ftp_login ]]; then
        # < /dev/tty want FD 1 al in gebruik bij 'wget -O- karelzim... | bash'.
        read -rsp "Wachtwoord voor 'ftp://$ftp_host': " < /dev/tty
        printf '%s\n' "$REPLY" > "$ftp_login"
        printf '\n'
        chmod 'u=rw,g=,o=' "$ftp_login" |& $LOGCMD
    fi
    if ! lftp   --user "$ftp_user"                  \
                --password "$(cat "$ftp_login")"    \
                -e "$ftp_set; $ftp_cmd"             \
                "$ftp_host"                         |& $LOGCMD; then
        rm  "$ftp_login"
        info 'Downloaden website is mislukt.'
        info 'Controleer de log...!'
        return  $ERROR
    fi
}


###############################################################################
# Script
###############################################################################

function main {
    init_script "$@"
    check_input "$@"
    process_input
    term_script
}

main "$@"
