.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz genpwd.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" RELEASE_YEAR=2021
.\"
.\" VERSION_NUMBER=03.00.04
.\" VERSION_DATE=2021-10-04
.\"
.\"
.TH KZ-GENPWD 1 "KZ Handleiding" "KZ-GENPWD(1)" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz genpwd \- Wachtwoord genereren.
.\"
.\"
.SH SAMENVATTING
.B kz genpwd
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz genpwd\fR genereeert een wachtwoord bestaande uit 16 willekeurige tekens.
Gebruik Bitwarden om wachtwoorden te beheren.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-common.py\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz genpwd\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
