#!/bin/bash
# shellcheck source=kz-common.sh
###############################################################################
# Scripts controleren.
#
# Geschreven in 2015 door Karel Zimmer <info@karelzimmer.nl>, Creative Commons
# Publiek Domein Verklaring <http://creativecommons.org/publicdomain/zero/1.0>.
###############################################################################


###############################################################################
# Global constants
###############################################################################

readonly PROGRAM_NAME='kz-ivp'
readonly PROGRAM_DESC='Scripts controleren'
readonly DISPLAY_NAME=${PROGRAM_NAME/kz-/kz }

# Redhat reports $0 as '-bash', dirname "$0" -> dirname: invalid option -- 'b'.
PROGRAM_PATH=$(realpath "$(dirname  "${0/#-/}")")
readonly PROGRAM_PATH
source  "$PROGRAM_PATH"/kz-common.sh

readonly USAGE="Gebruik: $DISPLAY_NAME $OPTIONS_USAGE"
readonly HELP="Gebruik: $DISPLAY_NAME [OPTIE...]

$PROGRAM_DESC.

Opties:
$OPTIONS_HELP"


###############################################################################
# Globale variabelen
###############################################################################

declare -i MAXRC=0


###############################################################################
# Functions
###############################################################################

function check-input {
    local -i    getopt_rc=0
    local       parsed=''

    parsed=$(
        getopt  --alternative                       \
                --options       "$OPTIONS_SHORT"    \
                --longoptions   "$OPTIONS_LONG"     \
                --name          "$DISPLAY_NAME"     \
                --              "$@"
        ) || getopt_rc=$?
    if [[ $getopt_rc -ne $SUCCESS ]]; then
        info "$USAGELINE"
        NOERROR=true exit $ERROR
    fi
    eval set -- "$parsed"
    kz-common.process-options "$@"

    while true; do
        case $1 in
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    if [[ "$*" ]]; then
        info 'Geen argumenten toegestaan.'
        info "$USAGELINE"
        NOERROR=true exit $ERROR
    fi

    # Aangemeld als ontwikkelaar?
    if ! kz-common.developer check; then
        kz-common.developer report
        NOERROR=true exit $ERROR
    fi
}


function process-input {
    local script=''
    local scriptsdir=$HOME/kz-scripts

    cd "$scriptsdir"
    for script in *; do
        if ! [[ -f $script ]]; then
            continue
        fi
        case $script in
            README.md|LICENSE)
                continue
                ;;
        esac
        check_trailing_spaces
        case $script in
            *.policy)
                continue
                ;;
            *.1|*.desktop)
                check-record-length
                ;;
            *.completion)
                check-record-length
                check-shellcheck
                ;;
            kz-common.sh)
                check-tags
                check-record-length
                check-shellcheck
                ;;
            *.sh)
                check-tags
                check-record-types
                check-shellcheck
                ;;
            *)
                check-tags
                check-record-length
                check-code
                ;;
        esac
    done
    cd "$HOME"
}


function check-code {
    if grep --quiet --line-regexp --regexp='#!''/bin/bash' "$script"; then
        check-shellcheck
    elif grep   --quiet                         \
                --line-regexp                   \
                --regexp='#!''/usr/bin/python3' \
                "$script"                       || [[ $script = kz_common.py ]]
    then
        check-pycodestyle
    else
        error "
In $script:
    Onbekend script.  Functie 'check-code' kan scriptcode niet controleren."
        MAXRC=$ERROR
    fi
}


function check-pycodestyle {
    local -i check_rc=0

    pycodestyle "$script" || check_rc=$?
    if [[ $check_rc -ne $SUCCESS ]]; then
        MAXRC=$ERROR
    fi
}


function check-record-length {
    local -i max_line_length=79
    local -i max_line_length_found=0

    max_line_length_found=$(wc --max-line-length < "$script")
    if  [[ $max_line_length_found -gt $max_line_length ]]; then
        error "
In $script:
    Één regel is langer dan $max_line_length ($max_line_length_found).
"
        MAXRC=$ERROR
    fi
}


function check-record-types {
    local wrong_record=''

    # Kijk naar regels die beginnen met #1 t/m #9.
    # Goed:
    # #1 en #2
    # #1 foo (bar)              (met optie -a, --app tonen en verwerken)
    # #1-foo (bar)              (met optie -a, --app niet tonen, wel verwerken)
    # #2 Verwijd./reset opdracht
    # Fout:
    # De rest :-)
    wrong_record=$(
        grep --regexp='#[1-9]' "$script" --line-number  |
        grep --regexp='#[1-2]$' --invert-match          |
        grep --regexp='#[1-2] ' --invert-match          |
        grep --regexp='#1-'     --invert-match          || true
        )
    if [[ $wrong_record ]]; then
        error "
In $script:
    Foutieve regel(s) gevonden.
$(
    printf '%s' "$wrong_record" |
                nl --number-width=8 --number-separator='' --body-numbering=n
)
"
        MAXRC=$ERROR
    fi
}


function check-shellcheck {
    local -i check_rc=0

    shellcheck --external-sources "$script" || check_rc=$?
    if [[ $check_rc -ne $SUCCESS ]]; then
        MAXRC=$ERROR
    fi
}


function check-tags {
    if grep --quiet             \
            --word-regexp       \
            --regexp='FIXME'':' \
            --regexp='TODO'':'  \
            "$script"; then
        warning "
In $script:
    Gemarkeerde annotatie gevonden.

$(
    grep    --line-number           \
            --word-regexp           \
            --regexp='FIXME'':'     \
            --regexp='TODO'':'      \
            "$script"               |
    nl      --number-width=4        \
            --number-separator=''   \
            --body-numbering=n
)
"
    while true; do
        read -rp 'Doorgaan? [J/n]: '
        case $REPLY in
            j*|J*|'')
                break
                ;;
            n*|N*)
                exit $SUCCESS
                break
                ;;
            *)
                printf '%s' "${REWRITE_LINE}"
                continue
                ;;
        esac
    done
    fi
}


function check_trailing_spaces {
    if grep --quiet --regexp=' ''$' "$script"; then
        error "
In $script:
    Eindspaties gevonden.
$(
    grep    --line-number --regexp=' ''$' "$script" |
    nl      --number-width=4  --number-separator='' --body-numbering=n
)
"
        MAXRC=$ERROR
    fi
}


function term-script {
    NOERROR=true exit $MAXRC
}


###############################################################################
# Script
###############################################################################

function main {
    kz-common.init-script "$@"
    check-input "$@"
    process-input
    term-script
}

main "$@"
