.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz install.                                               "
.\"                                                                           "
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.                       "
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-INSTALL 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz install \- Apps installeren.
.\"
.\"
.SH SAMENVATTING
.B kz install
[OPTIE...] [\fIAPP\fR...] [\fIBESTAND\fR...]
.\"
.\"
.SH BESCHRIJVING
\fBkz install\fR installeert apps en wijzigt systeeminstellingen.
.sp
In een grafische werkomgeving kan opdracht \fBkz install\fR worden uitgevoerd
door te zoeken naar \fBapps\fR, klik op \fBApps installeren\fR.
.sp
Gebruik (hierna) \fBkz setup\fR voor het instellen van apps en het wijzigen van
gebruikersinstellingen.
.sp
De opdrachten die standaard meegeleverd worden bij \fBkz install\fR zijn
idempotent; herhaaldelijk utvoeren leidt steeds tot hetzelfde resultaat.
.sp
Standaard verwerkt \fBkz install\fR de volgende twee installatiebestanden:
.br
- /usr/bin/kz-install-<distributie>-<versie>-\fIEDITIE\fR.sh
.br
- /usr/bin/kz-install-<distributie>-<versie>-\fIEDITIE\fR-<computernaam>.sh
.sp
Bijvoorbeeld kz-install-ubuntu-20.04-desktop.sh en
kz-install-ubuntu-20.04-desktop-pc02.sh.
.sp
Deze installatiebestanden bevatten opdrachten voor het installeren van apps en
het wijzigen van systeeminstellingen voor de huidige distributie, versie, en
\fIEDITIE\fR, bijvoorbeeld ubuntu 20.04 desktop.
Standaard wordt als \fIEDITIE\fR desktop gebruikt.
.sp
Voor de indeling van de installatiebestanden zie de sectie
\fBBESTANDSINDELING\fR hieronder.
.sp
Als er geen \fIAPP\fRs of \fIBESTAND\fRen zijn opgegeven worden de namen van de
aanwezige standaard installatiebestanden opgenomen in de lijst van te verwerken
bestanden.
.sp
Met optie \fB-e\fR, \fB--editie\fR is de \fIEDITIE\fR aan te passen,
bijvoorbeeld \fIEDITIE\fR server.
.sp
Optie \fB-f\fR, \fB--files\fR geeft een lijst van installatiebestanden aanwezig
op het systeem.
.sp
Het is mogelijk om \fIBESTAND\fRen op te geven; deze bestanden dienen te
beginnen met '\fBkz-install-\fR' en te eindigen met '\fB.sh\fR'.
.br
Iets anders wordt beschouwd als een \fIAPP\fR, zie hierna.
.br
De opgegeven \fIBESTAND\fRen worden opgenomen in de lijst van te verwerken
bestanden.
.sp
Optie \fB-a\fR, \fB--apps\fR geeft een lijst van apps die beschikbaar zijn in
alle installatiebestanden voor de huidige distributie en versie, bijvoorbeeld
ubuntu 20.04.
.sp
Het is mogelijk om \fIAPP\fRs op te geven.
.br
Per opgegeven \fIAPP\fR worden de bijbehorende regels met opdrachten opgezocht
in alle standaard installatiebestanden en worden de eerstgevonden opdrachten
gekopieerd naar een tijdelijk bestand.
.br
De naam van dit tijdelijk bestand wordt opgenomen in de lijst van te verwerken
bestanden.
.sp
Bijvoorbeeld voor ubuntu 20.04 op pc02 worden de apps opgezocht in
kz-install-ubuntu-20.04-desktop.sh, kz-install-ubuntu-20.04-desktop-pc01.sh,
kz-install-ubuntu-20.04-desktop-pc02.sh,
kz-install-ubuntu-20.04-desktop-pc03.sh, en
kz-install-ubuntu-20.04-desktop-pc04.sh.
.sp
Optie \fB-c\fR, \fB--cat\fR geeft de inhoud van de installatiebestanden.
.sp
Optie \fB-l\fR, \fB--list\fR legt de installatie vast in Persoonlijke map /
kz-data.
.br
In map kz-data staat bestand Apps met gegevens over eerder geïnstalleerde
pakketten.
.br
Deze gevens zijn te gebruiken om de installatie te controleren op volledigheid.
.sp
Met optie \fB-r\fR, \fB--remove\fR kan de installatie ongedaan worden gemaakt.
.\"
.\"
.SH BESTANDSINDELING
De te verwerken bestanden dienen te beginnen met '\fBkz-install-\fR' en te
eindigen met '\fB.sh\fR'.
.sp
De regels worden verwerkt op de volgorde zoals deze in de bestanden voorkomen.
.br
De opdrachten standaard meegeleverd bij \fBkz install\fR zijn zodanig opgesteld
dat bij herhaaldelijk uitvoeren het resultaat hetzelfde blijft; idempotentie.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels (eerste twee posities op een
regel) er zijn en hoe deze regels verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een voorbeeld van de \fBvolgorde\fR van deze regels in
een installatiebestand.
Meer voorbeelden zijn te zien via de opdracht \fBkz install --cat\fR.
.sp
.sp
.br
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regelsoort
T}:T{
Beschrijving
T}
.T&
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
#1 APP (BESCHRIJVING)
T}:T{
Bevat APP naam en een BESCHRIJVING van de app.
T}
T{
#1-APP (BESCHRIJVING)
T}:T{
Idem, wordt niet getoond bij optie -a, --apps.
T}
T{
#2 VERWIJDER-opdracht
T}:T{
Opdracht voor het VERWIJDERen van APPs.
T}
T{
.sp
T}:T{
Wordt overgeslagen (is leeg).
T}
T{
#
T}:T{
Wordt overgeslagen (is commentaar).
T}
T{
*
T}:T{
Wordt als opdracht verwerkt (idempotent).
T}
.TE
.sp
.sp
.br
.B Tabel 2. Voorbeeld van volgorde van regels in een installatiebestand
.TS
box tab(:);
lb | lb.
T{
Regelsoort
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l
l | l
l | l
l | l.
T{
# Software installeren
T}:T{
Commentaar.
T}
T{
.sp
T}:T{
Lege regel.
T}
T{
#1 google-chrome (webbrowser)
T}:T{
Naam APP met BESCHRIJVING tussen haakjes.
T}
T{
sudo apt-get install --yes google-chrome-stable
T}:T{
Installeer-opdracht.
T}
T{
#2 sudo apt-get remove --yes google-chrome-stable
T}:T{
VERWIJDER-opdracht; voor optie -r, --remove.
T}
.TE
.\"
.\"
.sp
.SH OPTIES
.TP
\fB-a\fR, \fB--apps\fR
Toon een lijst van te installeren apps.
.TP
\fB-c\fR, \fB--cat\fR
Toon de inhoud van bestanden.
.br
Ieder bestand wordt voorafgegaan door een commentaarregel met de bestandsnaam.
.TP
\fB-e\fR, \fB--edition=\fIEDITIE\fR
Gebruik editie \fIEDITIE\fR.
.TP
\fB-f\fR, \fB--files\fR
Toon een lijst van bestanden aanwezig op het systeem.
.TP
\fB-l\fR, \fB--list\fR
Maak bestand Apps aan in Persoonlijke map / kz-data met informatie over eerder
geïnstalleerde pakketten.
.TP
\fB-r\fR, \fB--remove\fR
Toon instructies voor het verwijderen van apps.
.TP
\fB-s\fR, \fB--simulate\fR
Geen actie, maar simuleer de installatie, en toon de opdrachten die uitgevoerd
zouden worden.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus
(gui=graphical user interface; grafische gebruikersinterface).
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.\"
.\"
.SH BESTANDEN
/usr/bin/kz-install-<distributie>-<versie>-\fIEDITIE\fR.sh
.RS
Standaard installatiebestand, \fIEDITIE\fR is standaard desktop.
.RE
.sp
/usr/bin/kz-install-<distributie>-<versie>-\fIEDITIE\fR-<computernaam>.sh
.RS
Standaard installatiebestand voor <computernaam>, \fIEDITIE\fR is standaard
desktop.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX.apps
.RS
Tijdelijk installatiebestand met opdrachten behorend bij opgegeven apps.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX.cmds
.RS
Tijdelijk installatiebestand met alle uit te voeren opdrachten.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX.sim
.RS
Tijdelijk simulatiebestand.
.RE
.sp
~/kz-data/Applist
.RS
Lijst met geïnstalleerde apps.
.RE
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl
.RE
.\"
.\"
.SH VOORBEELDEN
.sp
\fBkz install\fR
.RS
Installeer alles wat in de standaard installatiebestanden staat.
Hiervoor is ook starter \fBApps installeren\fR beschikbaar.
.RE
.sp
\fBkz install google-chrome\fR
.RS
Installeer Google Chrome.
.RE
.sp
\fBkz install --remove google-chrome\fR
.RS
Verwijder Google Chrome.
.RE
.sp
\fBkz install --cat bitwarden\fR
.RS
Toon installatie-opdrachten voor bitwarden.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-common.sh\fR(1),
\fBkz-menu\fR(1),
\fBkz-setup\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz install\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
