.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz install.                                               "
.\"                                                                           "
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.                       "
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-INSTALL 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz install \- Apps installeren.
.\"
.\"
.SH SAMENVATTING
.B kz install
[OPTIE...] [\fIAPP\fR...] [\fIBESTAND\fR...]
.\"
.\"
.SH BESCHRIJVING
\fBkz install\fR installeert apps en wijzigt systeeminstellingen.
.sp
De opdrachten die standaard meegeleverd worden bij \fBkz install\fR zijn
idempotent; herhaaldelijk utvoeren leidt steeds tot hetzelfde resultaat.
.sp
Standaard verwerkt \fBkz install\fR de volgende bestanden:
.br
- /usr/bin/kz-install-<distributie>-<versie>-\fIEDITIE\fR.sh (verplicht
aanwezig)
.br
- /usr/bin/kz-install-<distributie>-<versie>-\fIEDITIE\fR-<computernaam>.sh
(niet verplicht aanwezig)
.br
Deze bestanden bevatten opdrachten voor het installeren van apps en het
wijzigen van systeeminstellingen voor de huidige distributie, versie, en
\fIEDITIE\fR (bijv. Debian 11 desktop of Ubuntu 20.04 desktop).
.sp
De regels in deze bestanden worden gekopieerd naar een tijdelijk bestand.
.br
Het tijdelijk bestand wordt opgenomen in de lijst van te verwerken bestanden.
.sp
Standaard wordt als \fIEDITIE\fR desktop gebruikt, met optie \fB-e\fR,
\fB--editie\fR is dat aan te passen (bijv. \fIEDITIE\fR server).
.sp
Optie \fB-f\fR, \fB--files\fR geeft een lijst van beschikbare
installatiebestanden voor de huidige distributie, bijv. Debian of Ubuntu.
.br
Het is mogelijk om \fIBESTAND\fRen op te geven; deze bestanden dienen te
beginnen met '\fBinstal-\fR' en te eindigen met '\fB.sh\fR'.
.br
Iets anders wordt beschouwd als een \fIAPP\fR, zie hierna.
.sp
Voor de indeling van de installatiebestanden zie de sectie
\fBBESTANDSINDELING\fR hieronder.
.sp
Optie \fB-a\fR, \fB--apps\fR geeft een lijst van apps die beschikbaar zijn voor
de huidige distributie en versie, bijv. Debian 11 of Ubuntu 20.04.
.br
Het is mogelijk om \fIAPP\fRs op te geven.
.sp
Als \fIAPP\fRs zijn opgegeven worden de regels van deze app opgezocht in alle
installatiebestanden en worden de regels gekopieerd naar een tijdelijk bestand.
.br
Het tijdelijk bestand wordt opgenomen in de lijst van te verwerken bestanden.
.sp
Het is mogelijk dat na het uitvoeren van \fBkz install\fR er extra acties nodig
zijn.
Optie \fB-i\fR, \fB--info\fR geeft dan aanvullende instructies weer.
.sp
Optie \fB-l\fR, \fB--list\fR maakt een applijst aan in bestand
kz-install-applist in map Documenten.
Hierin informatie over welke pakketten handmatig zijn geïnstalleerd, welke
snaps zijn geïnstalleerd, en welke pakketbronnen ("repositories" of "repo's")
zijn toegevoegd.
.br
Deze gevens zijn te gebruiken om de installatie te controleren op volledigheid.
\.sp
Alhoewel \fBkz install\fR gericht is op het installeren, met optie\fB-r\fR,
\fB--remove\fR worden er instructies getoond om de installatie ongedaan te
maken.
.sp
In een grafische werkomgeving zoals GNOME (bijv. Debian of Ubuntu) kan
\fBkz install\fR worden gestart door te zoeken naar \fBapps\fR, klik op
\fBApps installeren\fR.
.sp
Gebruik (hierna) \fBkz setup\fR voor het aanpassen van de
gebruikersinstellingen.
.\"
.\"
.SH BESTANDSINDELING
De te verwerken bestanden dienen te beginnen met '\fBkz-install-\fR' en te
eindigen met '\fB.sh\fR'.
.sp
De regels worden verwerkt op de volgorde zoals deze in de bestanden voorkomen.
.br
De opdrachten standaard meegeleverd bij \fBkz install\fR zijn zodanig opgesteld
dat bij herhaaldelijk uitvoeren het resultaat hetzelfde blijft; idempotentie.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels (eerste twee posities op een
regel) er zijn en hoe deze regels verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een voorbeeld van de \fBvolgorde\fR van deze regels in
een installatiebestand.
Meer voorbeelden zijn te zien via de opdracht \fBkz install --cat\fR.
.sp
.sp
.br
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regelsoort
T}:T{
Beschrijving
T}
.T&
l | l
l | l
l | l
l | l
l | l
l | l.
T{
#1 APP (BESCHRIJVING)
T}:T{
Bevat APP naam en een BESCHRIJVING van de opdrachten.
T}
T{
#2 INSTRUCTIE
T}:T{
Bevat aanvullende INSTRUCTIEs na het installeren van APP.
T}
T{
#3 INSTRUCTIE
T}:T{
Bevat INSTRUCTIEs voor het verwijderen van APP.
T}
T{
.sp
T}:T{
Wordt overgeslagen (is leeg).
T}
T{
#
T}:T{
Wordt overgeslagen (is commentaar).
T}
T{
*
T}:T{
Wordt als opdracht verwerkt (idempotent).
T}
.TE
.sp
.sp
.br
.B Tabel 2. Volgorde van regels in een installatiebestand
.TS
box tab(:);
lb | lb.
T{
Regelsoort
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
# Software installeren
T}:T{
Commentaar.
T}
T{
.sp
T}:T{
Lege regel.
T}
T{
#1 google-chrome (Webbrowser)
T}:T{
Naam APP met BESCHRIJVING tussen haakjes.
T}
T{
sudo apt-get install --yes google-chrome-stable
T}:T{
Opdracht.
T}
T{
#2 1. Start Google Chrome.
T}:T{
Installatie-INSTRUCTIEs; voor optie info.
T}
T{
#2 2. Controleer de werking.
T}:T{
    "               "
T}
T{
#3 Start Terminalvenster en voer uit:
T}:T{
Verwijder-INSTRUCTIEs; voor optie remove.
T}
T{
#3    sudo apt remove google-chrome-stable
T}:T{
    "               "
T}
.TE
.\"
.\"
.sp
.SH OPTIES
.TP
\fB-a\fR, \fB--apps\fR
Toon een lijst van te installeren apps.
.TP
\fB-c\fR, \fB--cat\fR
Toon de inhoud van de (opgegeven) installatiebestanden.
.br
Ieder bestand wordt voorafgegaan door een commentaarregel met de bestandsnaam.
.TP
\fB-e\fR, \fB--edition=\fIEDITIE\fR
Gebruik editie \fIEDITIE\fR.
.TP
\fB-f\fR, \fB--files\fR
Toon een lijst van beschikbare installatiebestanden.
.TP
\fB-i\fR, \fB--info\fR
Toon aanvullende instructies na het installeren van apps.
.TP
\fB-l\fR, \fB--list\fR
Maak applist aan.
.TP
\fB-r\fR, \fB--remove\fR
Toon instructies voor het verwijderen van apps.
.TP
\fB-s\fR, \fB--simulate\fR
Geen actie, maar simuleer de installatie, en toon de opdrachten die uitgevoerd
zouden worden.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
.TP
\fB-d\fR, \fB--debug\fR
Neem foutopsporingsinformatie op in het logboek.
.br
Bekijk het logboek met opdracht: \fBjournalctl -ab -t kz-install\fR
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH BESTANDEN
/usr/bin/kz-install-<distributie>-<versie>-\fIEDITIE\fR.sh
.RS
Standaard installatiebestand als er geen \fIBESTAND\fRen zijn opgegeven, \
\fIEDITIE\fR is standaard desktop.
.RE
.sp
/usr/bin/kz-install-<distributie>-<versie>-\fIEDITIE\fR-<computernaam>.sh
.RS
Installatiebestand voor <computernaam> als er geen \fIBESTAND\fRen zijn
opgegeven, \fIEDITIE\fR is standaard desktop.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX.cmds
.RS
Tijdelijk installatiebestand.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX.text
.RS
Tijdelijk tekstbestand.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX.list
.RS
Tijdelijk applijstbestand.
.RE
.sp
~/Documenten/kz-install/kz-install-applist
.RS
Applijst met geïnstalleerde apps.
.RE
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl
.RE
.\"
.\"
.SH VOORBEELDEN
.sp
\fBkz install\fR
.RS
Installeer alles wat in de standaard installatiebestenden staat.
Hiervoor is ook starter \fBApps installeren\fR beschikbaar.
.RE
.sp
\fBkz install google-chrome\fR
.RS
Installeer Google Chrome.
.RE
.sp
\fBkz install google-chrome --info\fR
.RS
Toon aanvullende instructies na het installeren van Google Chrome.
Rechtsklik op starter 'Apps installeren' en kies
'Installatie-instructies tonen'.
.RE
.sp
\fBkz install google-chrome --remove\fR
.RS
Toon instructies voor het verwijderen van Google Chrome.
Rechtsklik op starter 'Apps installeren' en kies 'Verwijder-instructies tonen'.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-common.sh\fR(1),
\fBkz-menu\fR(1),
\fBkz-setup\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz install\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
