.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz menu.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" RELEASE_YEAR=2019
.\"
.\" VERSION_NUMBER=04.00.03
.\" VERSION_DATE=2021-09-08
.\"
.\"
.TH KZ-MENU 1 "KZ Handleiding" "KZ-MENU(1)" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz menu \- Installatiemenu.
.\"
.\"
.SH SAMENVATTING
.B kz menu
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz menu\fR voert opdrachten uit via een menu.
.sp
Toon een menu waarmee een aantal opdrachten achter elkaar uitgevoerd worden
zodat Ubuntu en Debian direct te installeren en te gebruiken is.
.sp
In een grafische werkomgeving zoals GNOME (e.g. Ubuntu) kan \fBkz menu\fR
worden gestart door te zoeken naar \fBmenu\fR, klik op \fBInstallatiemenu\fR.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
.TP
\fB-d\fR, \fB--debug\fR
Geef foutopsporingsinformatie weer in het logboek (gebruik '[sudo] journalctl
-ab -t kz-archive').
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-backup\fR(1),
\fBkz-common.sh\fR(1),
\fBkz-getdeb\fR(1),
\fBkz-install\fR(1),
\fBkz-lsinstal\fR(1),
\fBkz-nas\fR(1),
\fBkz-restore\fR(1),
\fBkz-setup\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz menu\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
