.\"############################################################################
.\"# Man-pagina voor kz menu.
.\"#
.\"# Geschreven in 2019 door Karel Zimmer <info@karelzimmer.nl>, Creative
.\"# Commons Verklaring <http://creativecommons.org/publicdomain/zero/1.0>.
.\"############################################################################
.\"
.TH KZ-MENU 1 "" "kz 365" "kz"
.\"
.\"
.SH NAAM
kz-menu \- Installatiemenu.
.\"
.\"
.SH SAMENVATTING
.B kz menu
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz menu\fR voert opdrachten uit via een menu op Debian en op Debian
gebaseerd systeem zoals Ubuntu.
.sp
In een grafische werkomgeving zoals Ubuntu met GNOME kan opdracht \fBkz menu\fR
worden uitgevoerd door te zoeken naar \fBmenu\fR, klik op
\fBInstallatiemenu\fR.
.sp
Toon een menu waarmee een aantal opdrachten achter elkaar uitgevoerd worden
zodat bijvoorbeeld Ubuntu Linux direct te installeren en te gebruiken
is.
.sp
De keuzes in het menu volgen de Hoofdstukken in de Checklist installatie.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus
(gui=graphical user interface; grafische gebruikersinterface).
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl/html/linux.html#documenten
.RE
.\"
.\"
.SH AUTEUR
Geschreven 2015 door Karel Zimmer <info@karelzimmer.nl>, Creative Commons
Publiek Domein Verklaring <http://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH ZIE OOK
\fBkz-backup\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-install\fR(1),
\fBkz-restore\fR(1),
\fBkz-setup\fR(1),
\fBkz-wifi\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz menu\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer - Linux - Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
