.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz nas.                                                   "
.\"                                                                           "
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.                       "
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-NAS 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz nas \- Netwerkschijf aankoppelen.
.\"
.\"
.SH SAMENVATTING
.B kz nas
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz nas\fR koppelt een NAS aan tijdens het opstarten.
.sp
Er wordt een systemd mount-bestand aangemaakt en geactiveerd.
.sp
Het aan te maken systemd mount-bestand wordt samengesteld met standaardwaarden.
.br
Bij het uitvoeren van dit script worden deze standaardwaarden getoond tussen []
en zijn deze op te geven.
.br
Als er al regels voorkomen voor de NAS wordt de optie geboden deze te
verwijderen.
Doen, want nu wordt systemd gebruikt!
.sp
Zorg dat de NAS een vast IP-adres heeft.  Hiervoor is nodig:
.sp
 -  het MAC-adres van de NAS (ziet eruit als aa:bb:cc:dd:ee:ff)
 -  toegang tot de NAS via een webbrowser
 -  toegang tot de router via een webbrowser
.sp
 1. Kies in de router met het MAC-adres van de NAS een IP-adres buiten het
bereik van DHCP die automatisch de IP-adressen uitdeelt (vaak 192.168.0.200).
 2. Kies in de NAS het vaste IP-adres en zet DHCP uit.
.sp
NAS is een acroniem (letterwoord), en een afkorting, van network-attached
storage.
.sp
In een grafische werkomgeving zoals GNOME, bijvoorbeeld Ubuntu, kan opdracht
\fBkz nas\fR worden uitgevoerd door te zoeken naar \fBnas\fR, klik op
\fBNetwerkschijf aankoppelen\fR.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus
(gui=graphical user interface;grafische gebruikersinterface).
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.\"
.\"
.SH BESTANDEN
/etc/kz-naslogin
.RS
NAS-login gegevens.
.RE
.sp
/etc/systemd/system/mnt-nas.mount
.RS
Systemd mount-bestand.
.RE
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-common.sh\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz nas\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
