.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz restore.                                               "
.\"                                                                           "
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.                       "
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-RESTORE 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz restore \- Back-up terugzetten.
.\"
.\"
.SH SAMENVATTING
.B kz restore
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz restore\fR zet een back-up (reservekopie) van de Persoonlijke map terug.
.sp
De back-up wordt verwacht op een aangekoppeld USB-medium zoals een USB externe
harddisk in map \fBbackup-<computernaam>-<gebruikersnaam>\fR, bijvoorbeeld
/media/jan/backupdisk/backup-pc01-jan.
.sp
Met optie \fB-s\fR, \fB--source\fR kan een andere locatie opgegeven worden.
Bijvoorbeeld /tmp in plaats van /media/jan/backupdisk (onverstandig want /tmp
wordt leeggegooid na een herstart).
.sp
Optie \fB--dry-run\fR voert een proefrun uit zonder wijzigingen aan te brengen.
Het wordt meestal gebruikt in om te zien wat een rsync-commando gaat doen
voordat men het daadwerkelijk uitvoert.
.sp
Voor het terugzetten van de back-up wordt rsync gebruikt.
.sp
Met opdracht \fBkz backup\fR kan de Persoonlijke map veiliggesteld worden.
.sp
In een grafische werkomgeving zoals GNOME, bijvoorbeeld Ubuntu, kan opdracht
\fBkz restore\fR worden uitgevoerd door te zoeken naar \fBback\fR, klik op
\fBReservekopie terugzetten\fR.
.\"
.\"
.SH OPTIES
.TP
\fB--dry-run\fR
Een proefrun uitvoeren zonder wijzigingen aan te brengen.
.TP
\fB-s\fR, \fB--source=\fIBRONMAP\fR
Gebruik back-ups in de \fIBRONMAP\fR.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl
.RE
.\"
.\"
.SH VOORBEELDEN
.sp
\fBkz restore\fR
.RS
Zet alles in de back-up terug.
.br
Hiervoor is ook starter \fBBack-up terugzetten\fR beschikbaar.
.RE
.sp
\fBkz restore --dry-run\fR
.RS
Toon bestanden die teruggezet zouden worden uit de back-up.
.RE
.sp
\fBkz restore\
 --source=smb://fileserver/backups\fR
.RS
Zet de back-up terug vanaf SMB-share 'backups' op 'fileserver' uit de map\
 'backup-pc01-jan'.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-backup\fR(1),
\fBkz-common.sh\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz restore\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
