#!/bin/bash
# shellcheck source=kz-common.sh
###############################################################################
# Back-up terugzetten.                                                        #
#                                                                             #
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.                         #
###############################################################################

PROGRAM_PATH=$(realpath "$(dirname  "$0")")
readonly PROGRAM_PATH
source  "$PROGRAM_PATH"/kz-common.sh
readonly PROGRAM_NAME='kz-restore'
readonly DISPLAY_NAME=${PROGRAM_NAME/kz-/kz }
readonly RELEASE_YEAR=2007

###############################################################################
# Global constants                                                            #
###############################################################################

readonly OPTIONS_SHORT=$OPTIONS_SHORT_COMMON'gs:'
readonly OPTIONS_LONG=$OPTIONS_LONG_COMMON',dry-run,gui,source:'
readonly USAGE="Gebruik: $DISPLAY_NAME [--dry-run] [-g|--gui] \
[-s|--source=BRONMAP]
                    $OPTIONS_USAGE_COMMON"
readonly HELP="Gebruik: $DISPLAY_NAME [OPTIE...]

Back-up terugzetten.

Opties:
      --dry-run  een proefrun uitvoeren zonder wijzigingen aan te brengen
  -g, --gui      start in grafische modus
  -s, --source=BRONMAP
                 gebruik back-up in de BRONMAP
$OPTIONS_HELP_COMMON"

MEDIUM=$(ls --directory /media/"$USER"/* 2> /dev/null)
readonly MEDIUM
TARGET=$HOME

###############################################################################
# Global variables                                                            #
###############################################################################

declare OPTION_DRY_RUN=''
declare OPTION_GUI=false
declare OPTION_SOURCE=false
declare SOURCE_ARGUMENT=''
declare SOURCE=''

###############################################################################
# Functions                                                                   #
###############################################################################

function check_input {
    local -i    getopt_rc=0
    local       parsed=''

    parsed=$(
        getopt  --alternative                       \
                --options       "$OPTIONS_SHORT"    \
                --longoptions   "$OPTIONS_LONG"     \
                --name          "$DISPLAY_NAME"     \
                --              "$@"
        )       || getopt_rc=$?
    if [[ $getopt_rc -ne $SUCCESS ]]; then
        info "$USAGELINE" >&2
        exit $ERROR
    fi
    eval set -- "$parsed"
    process_common_options "$@"

    while true; do
        case $1 in
            -g|--gui)
                OPTION_GUI=true
                if [[ -t 1 ]]; then
                    reset_terminal_attributes
                fi
                shift
                ;;
            --dry-run)
                OPTION_DRY_RUN='--dry-run'
                shift
                ;;
            -s|--source)
                if $OPTION_SOURCE; then
                    error "Optie '$1' eenmaal opgeven."
                    info "$USAGELINE" >&2
                    exit $ERROR
                else
                    OPTION_SOURCE=true
                    SOURCE_ARGUMENT=$2
                fi
                shift 2
                ;;
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    if [[ "$*" ]]; then
        error 'Geen argumenten toegestaan.'
        info "$USAGELINE" >&2
        exit $ERROR
    fi

    check_user
}

function process_input {
    if $OPTION_SOURCE; then
        SOURCE=$SOURCE_ARGUMENT
        if ! [[ -d $SOURCE ]]; then
            error "Map $SOURCE bestaat niet."
            info "$USAGELINE" >&2
            exit $ERROR
        fi
    else
        SOURCE=$MEDIUM/backup-$HOSTNAME-$USER
        if [[ -z $MEDIUM ]]; then
            warning 'Geen back-up teruggezet.

Geen USB-medium gevonden.

Koppel een USB-medium aan, en start daarna opnieuw.'
            exit $WARNING
        elif [[ $(printf '%s\n' "$MEDIUM" | wc --lines) -gt 1 ]]; then
            warning "Koppel slechts één USB-medium aan.

Nu aangekoppeld zijn:
$MEDIUM

Koppel media af via Bestanden, en start daarna opnieuw."
            exit $WARNING
        elif ! [[ -d $SOURCE ]]; then
            warning "Geen back-up teruggezet.

Geen correct USB-medium gevonden.

Koppel een USB-medium aan met hierop de map \
backup-$HOSTNAME-$USER, en start daarna opnieuw."
            exit $WARNING
        fi
    fi

    check_on_ac_power
    restore_backup
}

function restore_backup {
    local -i rsync_rc=0

    TITLE='Back-up terugzetten'
    TEXT="Restore voorbereiden..."
    if $OPTION_GUI; then
        rsync   --archive                   \
                --verbose                   \
                "$SOURCE"/                  \
                "$TARGET"                   \
                2> >($LOGCMD)               |
        awk     '{print "#"$0}'             |
        zenity  --progress                  \
                --auto-close                \
                --no-cancel                 \
                --pulsate                   \
                --width 600                 \
                --height 50                 \
                --title "$TITLE"            \
                --text "$TEXT"              2> >($LOGCMD) || rsync_rc=$?
    else
        rsync   --archive                   \
                --verbose                   \
                --human-readable            \
                $OPTION_DRY_RUN             \
                "$SOURCE"/                  \
                "$TARGET"                   2> >($LOGCMD) || rsync_rc=$?
    fi

    case $rsync_rc in
        0)
            return $SUCCESS
            ;;
        11)
            log 'Te weinig ruimte.'
            warning "
Back-up terugzetten is mislukt.

Te weinig ruimte op $(df "$TARGET" | awk 'END{print $6}').

Gebruik een medium met meer ruimte, en start daarna opnieuw."
            exit $ERROR
            ;;
        23)
            log 'Niet alle bestanden waren leesbaar?'
            warning "
Back-up terugzetten is gedeeltelijk gelukt.

Mogelijk zijn enkele bestanden niet leesbaar, of zijn er bestanden
verwijderd of toegevoegd tijdens het terugzetten van de back-up.

Probeer opnieuw de back-up terug te zetten.
Als dat niet lukt, controleer de log in het Terminalvenster met:
    ${BLUE}$LOGCMD_CHECK${NORMAL}"
            exit $WARNING
            ;;
        *)
            warning "
Back-up terugzetten is mislukt.

Foutcode rsync is $rsync_rc.

Probeer opnieuw de back-up terug te zetten.
Als dat niet lukt, controleer de log in het Terminalvenster met:
    ${BLUE}$LOGCMD_CHECK${NORMAL}"
            exit $ERROR
            ;;
    esac
}

function term_script {
    info "
${GREEN}De back-up is teruggezet.${NORMAL}

${YELLOW}Koppel zelf (veilig!) het USB-medium af.${NORMAL}"
    exit $SUCCESS
}

###############################################################################
# Main line                                                                   #
###############################################################################

function main {
    init_script "$@"
    check_input "$@"
    process_input
    term_script
}

main "$@"
