#!/usr/bin/bash
# shellcheck source=kz-common.sh
###############################################################################
# Back-up terugzetten.                                                        #
#                                                                             #
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.                         #
###############################################################################

PROGRAM_PATH=$(realpath "$(dirname  "$0")")
source "$PROGRAM_PATH"/kz-common.sh
PROGRAM_NAME=kz-restore
DISPLAY_NAME=${PROGRAM_NAME/kz-/kz }
RELEASE_YEAR=2007


###############################################################################
# Global constants                                                            #
###############################################################################

readonly OPTIONS_SHORT=$OPTIONS_SHORT_COMMON'en'
readonly OPTIONS_LONG=$OPTIONS_LONG_COMMON',dry-run'
readonly USAGE="Gebruik: $DISPLAY_NAME [-n|--dry-run]
                    $OPTIONS_USAGE_COMMON"
readonly HELP="Gebruik: $DISPLAY_NAME [OPTIE...]

Back-up terugzetten.

Opties:
  -n --dry-run  een proefrun uitvoeren zonder wijzigingen aan te brengen
$OPTIONS_HELP_COMMON"

SOURCE=$(ls --directory /media/"$USER"/*/backup-"$HOSTNAME-$USER" 2> /dev/null)
readonly SOURCE
TARGET=$HOME


###############################################################################
# Global variables                                                            #
###############################################################################

declare OPTION_DRY_RUN=''


###############################################################################
# Functions                                                                   #
###############################################################################

function check_input {
    local   -i  getopt_rc=0
    local       parsed=''

    parsed=$(
        getopt  --alternative                       \
                --options       "$OPTIONS_SHORT"    \
                --longoptions   "$OPTIONS_LONG"     \
                --name          "$DISPLAY_NAME"     \
                --              "$@"
        )       || getopt_rc=$?
    if [[ $getopt_rc -ne $SUCCESS ]]; then
        printf '%s\n' "$USAGELINE" >&2
        exit $ERROR
    fi
    eval set -- "$parsed"
    process_common_options "$@"

    while true; do
        case $1 in
            -n|--dry-run)
                OPTION_DRY_RUN='--dry-run'
                shift
                ;;
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    if [[ "$*" ]]; then
        TEXT='geen argumenten opgeven'
        printf "$DISPLAY_NAME: %s\n%s\n" "$TEXT" "$USAGELINE" >&2
        exit $ERROR
    fi

    check_user
}


function process_input {

    if [[ -z $SOURCE ]]; then
        warning "Koppel een back-up-medium aan met map \
'backup-$HOSTNAME-$USER'."
        exit $WARNING
    elif [[ $(printf '%s\n' "$SOURCE" | wc --lines) -gt 1 ]]; then
        warning "Koppel slechts één back-up-medium aan met map \
'backup-$HOSTNAME-$USER'.

Nu aangekoppeld zijn:
$SOURCE

Koppel media af via app Bestanden."
        exit $WARNING
    fi

    TITLE='Back-up terugzetten'
    TEXT='Controleer beschikbare schijfruimte (kan even duren)...'
    if $OPTION_GUI; then
        check_space > >(
            zenity  --progress              \
                    --pulsate               \
                    --auto-close            \
                    --no-cancel             \
                    --width     600         \
                    --height    50          \
                    --title     "$TITLE"    \
                    --text      "$TEXT"     2> >($LOGCMD)
            )
    else
        info "$TEXT"
        check_space
    fi

    TEXT="Backup terugzetten..."
    check_on_ac_power
    restore_backup
}


function check_space {
    local       capacity_human=''
    local       mounted=''
    local       need_human=''
    local   -i  capacity_bytes=0
    local   -i  need_bytes=0

    need_bytes=$(
        du  --apparent-size \
            --block-size=1  \
            --summarize     \
            --total         \
            "$SOURCE"       \
            2> >($LOGCMD)   |
        awk 'END{print $1}'
        )
    capacity_bytes=$(df --block-size=1 "$TARGET" | awk 'END{print $2}')

    if [[ $need_bytes -gt $capacity_bytes ]]; then
        need_human=$(
            du  --apparent-size     \
                --block-size=1      \
                --human-readable    \
                --summarize         \
                --total             \
                "$SOURCE"           \
                2> >($LOGCMD)       |
            awk 'END{print $1}'
            )
        capacity_human=$(df --human-readable "$TARGET" | awk 'END{print $2}')
        mounted=$(df "$TARGET" | awk 'END{print $6}')
        error "
Back-up terugzetten is mislukt.

Te weinig ruimte op $mounted.

Benodigd is ${need_human}iB, beschikbaar is ${capacity_human}iB.

Gebruik een ander restore-medium met minimaal ${need_human}iB beschikbaar."
        exit $ERROR
    fi
}


function restore_backup {
    local   -i  rsync_rc=0

    if $OPTION_GUI; then
        rsync   --archive                   \
                --verbose                   \
                "$SOURCE"/                  \
                "$TARGET"                   \
                2> >($LOGCMD)               |
        awk     '{print "#"$0}'             |
        zenity  --progress                  \
                --auto-close                \
                --no-cancel                 \
                --pulsate                   \
                --width 600                 \
                --height 50                 \
                --title "$TITLE"            \
                --text "$TEXT"              2> >($LOGCMD) || rsync_rc=$?
    else
        rsync   --archive                   \
                --verbose                   \
                --human-readable            \
                $OPTION_DRY_RUN             \
                "$SOURCE"/                  \
                "$TARGET"                   2> >($LOGCMD) || rsync_rc=$?
    fi

    case $rsync_rc in
        0)
            return $SUCCESS
            ;;
        11)
            log 'Te weinig ruimte.'
            error "
Back-up terugzetten is mislukt.

Te weinig ruimte op $(df "$TARGET" | awk 'END{print $6}')."
            exit $ERROR
            ;;
        23)
            log 'Niet alle bestanden waren leesbaar?'
            warning "
Back-up terugzetten is gedeeltelijk gelukt.

Mogelijk zijn enkele bestanden niet leesbaar.

Voor details: start app Logboeken en zoek in Alles op rsync"
            exit $WARNING
            ;;
        *)
            error "
Back-up terugzetten is mislukt.

Foutcode rsync is $rsync_rc.

Voor details: start app Logboeken en zoek in Alles op rsync"
            exit $ERROR
            ;;
    esac
}


function term_script {
    info "
De back-up is teruggezet.
${BOLD}$OPTION_DRY_RUN${NORMAL}
Koppel zelf (veilig!) het back-up-medium af."
    exit $SUCCESS
}


###############################################################################
# Main line                                                                   #
###############################################################################

function main {
    init_script "$@"
    check_input "$@"
    process_input
    term_script
}


main "$@"
