.\"############################################################################
.\"# Man-pagina voor kz setup.
.\"#
.\"# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"############################################################################
.\"
.TH KZ-SETUP 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz setup \- Apps instellen.
.\"
.\"
.SH SAMENVATTING
.B kz setup
[OPTIE...] [\fIAPP\fR...] [\fIBESTAND\fR...]
.\"
.\"
.SH BESCHRIJVING
\fBkz setup\fR stelt apps in en wijzigt gebruikersinstellingen.
.sp
In een grafische werkomgeving zoals Ubuntu met GNOME kan opdracht
\fBkz setup\fR worden uitgevoerd door te zoeken naar \fBapps\fR, klik op
\fBApps instellen\fR.
.sp
Gebruik (eerst) \fBkz install\fR voor het installeren van apps en het wijzigen
van systeeminstellingen.
.sp
\fBkz setup\fR verwerkt zogenaamde instelbestanden die opdrachten bevatten voor
het instellen van apps en het wijzigen van gebruikersinstellingen.
.sp
Standaard verwerkt \fBkz setup\fR de volgende twee instelbestanden:
.br
- /usr/bin/kz-setup-<distributie>-<versie>-\fIEDITIE\fR.sh
.br
- /usr/bin/kz-setup-<distributie>-<versie>-\fIEDITIE\fR-<computernaam>-\
<gebruikersnaam>.sh
.sp
<distributie>, <versie>, <computernaam>, en <gebruikersnaam> worden ingevuld
met waarden van de huidige computer en gebruiker.
.br
Voor \fIEDITIE\fR wordt standaard 'desktop' gebruikt.
.sp
Bijvoorbeeld kz-setup-ubuntu-20.04-desktop.sh en
kz-setup-ubuntu-20.04-desktop-pc02-jan.sh.
.br
Deze instelbestanden bevatten opdrachten voor ubuntu 20.04 desktop op
pc02 voor jan.
.sp
Wat ingesteld wordt met \fBkz setup\fR vastleggen in instelbestanden wordt ook
wel Infrastructuur als Code (IaC) of programmeerbare infrastructuur genoemd;
het definiëren en beheren van infrastructuur door middel van code.
Herhaalbaarheid is één van de principes van IaC.
.br
Ook de voospelbaarheid, wat wordt er ingesteld, hoort bij IaC.
.br
De opdrachten zijn vastgelegd, en worden onderhouden, in versiebeheer (GitHub),
een ander principe van IaC.
.sp
De opdrachten die standaard meegeleverd worden bij \fBkz setup\fR zijn
idempotent; herhaaldelijk utvoeren leidt steeds tot hetzelfde resultaat.
Herhaalbaarheid (idempotentie) is een van de principes van IaC.
De opdrachten zijn vastgelegd in versiebeheer (GitHub), een ander principe van
IaC.
.sp
Voor de indeling van de instelbestanden zie de sectie \fBBESTANDSINDELING\fR
hieronder.
.sp
Als er geen \fIAPP\fRs of \fIBESTAND\fRen zijn opgegeven worden de namen van de
aanwezige standaard instelbestanden opgenomen in de lijst van te verwerken
bestanden.
.sp
Met optie \fB-e\fR, \fB--editie\fR is de \fIEDITIE\fR aan te passen,
bijvoorbeeld \fIEDITIE\fR server.
.sp
Optie \fB-f\fR, \fB--files\fR geeft een lijst van instelbestanden aanwezig op
het systeem.
.sp
Het is mogelijk om \fIBESTAND\fRen op te geven; deze bestanden dienen te
beginnen met '\fBkz-setup-\fR' en te eindigen met '\fB.sh\fR'.
.br
Iets anders wordt beschouwd als een \fIAPP\fR, zie hierna.
.br
De opgegeven \fIBESTAND\fRen worden opgenomen in de lijst van te verwerken
bestanden.
.sp
Optie \fB-a\fR, \fB--apps\fR geeft een lijst van apps die beschikbaar zijn in
alle instelbestanden voor de huidige distributie en versie, bijvoorbeeld ubuntu
20.04.
.sp
Het is mogelijk om \fIAPP\fRs op te geven.
.br
Per opgegeven \fIAPP\fR worden de bijbehorende regels met opdrachten opgezocht
alle instelbestanden voor de huidige distributie en versie, bijvoorbeeldubuntu
20.04, en worden de eerstgevonden opdrachten gekopieerd naar een tijdelijk
bestand.
.br
Het tijdelijk bestand wordt opgenomen in de lijst van te verwerken bestanden.
.sp
Bijvoorbeeld voor ubuntu 20.04 op pc02 worden de apps opgezocht in
kz-setup-ubuntu-20.04-desktop.sh, kz-setup-ubuntu-20.04-desktop-pc01.sh,
kz-setup-ubuntu-20.04-desktop-pc02.sh, kz-setup-ubuntu-20.04-desktop-pc03.sh,
en kz-setup-ubuntu-20.04-desktop-pc04.sh.
.sp
Optie \fB-c\fR, \fB--cat\fR geeft de inhoud van de instelbestanden.
.sp
Optie \fB-l\fR, \fB--list\fR legt de instellingen vast in Persoonlijke map /
kz-data.
.br
In map kz-data staan bestanden met eerder gekozen Achtergrond, Gebruikersfoto,
en Favorieten.
.br
Deze gevens zijn te gebruiken om het instellen te controleren op volledigheid.
.sp
.sp
Met optie \fB-r\fR, \fB--reset\fR kan het instellen ongedaan worden gemaakt.
.\"
.\"
.SH BESTANDSINDELING
De te verwerken bestanden dienen te beginnen met '\fBkz-setup-\fR' en te
eindigen met '\fB.sh\fR'.
.sp
De regels worden verwerkt op de volgorde zoals deze in de bestanden voorkomen.
.br
De opdrachten standaard meegeleverd bij \fBkz setup\fR zijn zodanig opgesteld
dat bij herhaaldelijk uitvoeren het resultaat hetzelfde blijft; idempotentie.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels (eerste twee posities op een
regel) er zijn en hoe deze regels verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een voorbeeld van de \fBvolgorde\fR van deze regels in
een instelbestand.
Meer voorbeelden zijn te zien via de opdracht \fBkz setup --cat\fR.
.\"
.\"
.sp
.br
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regelsoort
T}:T{
Beschrijving
T}
.T&
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
#1 APP (BESCHRIJVING)
T}:T{
Bevat APP naam en een BESCHRIJVING van de app.
T}
T{
#1-APP (BESCHRIJVING)
T}:T{
Idem, wordt niet getoond bij optie -a, --apps.
T}
T{
#2 RESET-opdracht
T}:T{
Bevat opdrachten voor het RESETten van APPs.
T}
T{
.sp
T}:T{
Wordt overgeslagen (is leeg).
T}
T{
#
T}:T{
Wordt overgeslagen (is commentaar).
T}
T{
*
T}:T{
Wordt als opdracht verwerkt (idempotent).
T}
.TE
.sp
.sp
.br
N.B. Regelsoort '#1-APP (BESCHRIJVING)' is bedoeld voor opdrachten die
     specifiek zijn voor een computer, bijvoorbeeld voor pc02.
.sp
.sp
.br
.B Tabel 2. Voorbeeld van volgorde van regels in een instelbestand
.TS
box tab(:);
lb | lb.
T{
Regelsoort
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l
l | l
l | l
l | l.
T{
# Software instellen
T}:T{
Commentaar.
T}
T{
.sp
T}:T{
Lege regel.
T}
T{
#1 google-chrome (webbrowser)
T}:T{
Naam APP met BESCHRIJVING tussen haakjes.
T}
T{
:
T}:T{
Instel-opdracht.
T}
T{
#2 kz-gset --delfav=google-chrome
T}:T{
RESET-opdracht; voor optie -r, --reset.
T}
.TE
.\"
.\"
.sp
.SH OPTIES
.TP
\fB-a\fR, \fB--apps\fR
Toon een lijst van in te stellen apps.
.TP
\fB-c\fR, \fB--cat\fR
Toon de inhoud van bestanden.
.br
Ieder bestand wordt voorafgegaan door een commentaarregel met de bestandsnaam.
.TP
\fB-e\fR, \fB--edition=\fIEDITIE\fR
Gebruik editie \fIEDITIE\fR.
.TP
\fB-f\fR, \fB--files\fR
Toon een lijst van bestanden aanwezig op het systeem.
.TP
\fB-l\fR, \fB--list\fR
Maakt een instellijst aan met informatie over gemaakte instellingen.
.TP
\fB-r\fR, \fB--reset\fR
Toon instructies voor het resetten van apps.
.TP
\fB-s\fR, \fB--simulate\fR
Geen actie, maar simuleer het instellen, en toon de opdrachten die uitgevoerd
zouden worden.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus
(gui=graphical user interface; grafische gebruikersinterface).
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH BESTANDEN
/usr/bin/kz-setup-<distributie>-<versie>-\fIEDITIE\fR.sh
.RS
Standaard instelbestand, \fIEDITIE\fR is standaard desktop.
.RE
.sp
/usr/bin/kz-setup-<distributie>-<versie>-\fIEDITIE\fR-<computernaam>.sh
.RS
Standaard instelbestand voor <computernaam>, \fIEDITIE\fR is standaard
desktop.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX.apps
.RS
Tijdelijk instelbestand met opdrachten behorend bij opgegeven apps.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX.cmds
.RS
Tijdelijk instelbestand met alle uit te voeren opdrachten.
.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX.sim
.RS
Tijdelijk simulatiebestand.
.RE
.sp
~/kz-data/Gebruikersfoto
.RS
Ingestelde gebruikersfoto.
.RE
.sp
~/kz-data/Bureaubladachtergrond
.RS
Ingestelde bureaubladachtergrond.
.RE
.sp
~/kz-data/Favorieten
.RS
Ingestelde favorieten in de favorietenbalk (dash/dock).
.RE
.sp
~/kz-data/Opdrachtgeschiedenis
.RS
Geschiedenis van gebruikte opdrachten in het Terminalvenster.
.RE
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl
.RE
.\"
.\"
.SH VOORBEELDEN
.sp
\fBkz setup\fR
.RS
Stel in alles wat in de standaard instelbestanden staat.
Hiervoor is ook starter \fBApps instellen\fR beschikbaar.
.RE
.sp
\fBkz setup google-chrome\fR
.RS
Stel in Google Chrome.
.RE
.sp
\fBkz setup --reset google-chrome\fR
.RS
Reset Google Chrome.
.RE
.sp
\fBkz setup --cat bitwarden\fR
.RS
Toon instel-opdrachten voor bitwarden.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz-common.sh\fR(1),
\fBkz-install\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz setup\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer - Linux - Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
