#!/usr/bin/python3
"""
Systeem bijwerken.

Dit script voert een repair en update uit op Debian of Debian-gebaseerd systeem
zoals Ubuntu.
"""
###############################################################################
# Systeem bijwerken.
#
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
###############################################################################

import kz_common
import subprocess
import sys


###############################################################################
# Global constants
###############################################################################

program_name = 'kz-update'
program_desc = 'Systeem bijwerken'
display_name = program_name.replace('kz-', 'kz ')
program_year = 2021


###############################################################################
# Global variables
###############################################################################

command = ''


###############################################################################
# Functions
###############################################################################

def perform_repair():
    command = 'dpkg --configure --pending'
    perform_command(command)

    command = 'apt-get update --fix-missing'
    perform_command(command)

    command = 'apt-get install --fix-broken'
    perform_command(command)


def perform_update():
    command = 'apt-get update'
    perform_command(command)

    command = 'apt-get upgrade --yes'
    perform_command(command)

    command = 'apt-get autoremove --yes'
    perform_command(command)


def perform_command(command):
    print(f'Uitvoeren {command}...')
    kz_common.check_dpkgd_snapd()
    try:
        subprocess.run(f'sudo {command}', shell=True, check=True)
    except Exception as ex:
        print(ex)
    print()


def snap_refresh():
    print('Uitvoeren snap refresh...')
    kz_common.check_dpkgd_snapd()
    try:
        subprocess.run('sudo snap refresh', shell=True)
    except Exception as ex:
        print(ex)


def check_reboot():
    try:
        with open('/var/run/reboot-required') as fh:
            print('\nDe computer moet herstarten om het installeren van '
                  'updates af te ronden.')
    except FileNotFoundError:
        pass
    except Exception as ex:
        print(ex)
        sys.exit(1)


###############################################################################
# Main
###############################################################################

kz_common.process_common_options(display_name, program_desc)

kz_common.check_sudo()

perform_repair()

perform_update()

snap_refresh()

check_reboot()
