.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz update.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" RELEASE_YEAR=2021
.\"
.\" VERSION_NUMBER=01.01.01
.\" VERSION_DATE=2021-10-04
.\"
.\"
.TH KZ-UPDATE 1 "KZ Handleiding" "KZ-UPDATE(1)" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz update \- Systeem bijwerken.
.\"
.\"
.SH SAMENVATTING
.B kz update
.\"
.\"
.SH BESCHRIJVING
\fBkz update\fR voert een update uit voor Debian gebaseerde systemen.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz update\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
