.\"############################################################################
.\"# Man-pagina voor kz update.
.\"#
.\"# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"############################################################################
.\"
.TH KZ-UPDATE 1 "" "kz 365" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz update \- Systeem bijwerken.
.\"
.\"
.SH SAMENVATTING
.B kz update
.\"
.\"
.SH BESCHRIJVING
\fBkz update\fR voert een repair en update uit voor op Debian gebaseerde
systemen.
.sp
Achtereenvolgens wordt uitgevoerd:
.br
- Als repair:
.br
  - sudo dpkg --configure --pending
.br
  - sudo apt-get update --fix-missing
.br
  - sudo apt-get install --fix-broken
.br
- De eigenlijke update:
.br
  - sudo apt-get update
.br
  - sudo apt-get upgrade --yes
.br
  - sudo apt-get autoremove --yes
.br
  - sudo snap refresh (als snaps aanwezig zijn)
.br
- Melding "reboot" geven als bestand /var/run/reboot-required bestaat.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz update\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer - Linux - Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
