#!/bin/bash
# shellcheck source=kz_common.sh
###############################################################################
# Wifi-gegevens tonen.
#
# Geschreven in 2022 door Karel Zimmer <info@karelzimmer.nl>, Creative Commons
# Publiek Domein Verklaring <http://creativecommons.org/publicdomain/zero/1.0>.
###############################################################################

set -o errexit
program_path=$(cd "$(dirname "$(realpath "$0")")" && pwd)
source "$program_path"/kz_common.sh


###############################################################################
# Constants
###############################################################################

declare program_name='kz-wifi'
declare program_desc='Wifi-informatie tonen'
declare display_name=${program_name/kz-/kz }

declare usage="Gebruik: $display_name $options_usage [-g|--gui]"
declare help="Gebruik: $display_name [OPTIE...]

$program_desc.

Opties:
$options_help
  -g, --gui      start in grafische modus"
declare options_short+='g'
declare options_long+=',gui'


###############################################################################
# Variables
###############################################################################

declare option_gui=false


###############################################################################
# Functions
###############################################################################

function check_input {
    local -i getopt_rc=0
    local parsed=''

    parsed=$(
        getopt  --alternative                       \
                --options       "$options_short"    \
                --longoptions   "$options_long"     \
                --name          "$display_name"     \
                --              "$@"
        ) || getopt_rc=$?
    if [[ $getopt_rc -ne $ok ]]; then
        info "$usage_line"
        exit $err
    fi
    eval set -- "$parsed"
    kz_common.process_options "$@"

    while true; do
        case $1 in
            -g|--gui)
                option_gui=true
                kz_common.reset_terminal_attributes
                shift
                ;;
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    if [[ "$*" ]]; then
        printf  "$display_name: %s: %s\n$usage_line\n" \
                "$*" 'argumenten zijn niet toegestaan'
        exit $err
    fi
}


function process_input {
    local nmcli_output=''
    local -i nmcli_rc=''
    local text='Leg deze gegevens vast, en gebruik die om (later)
verbinding te maken met het draadloze netwerk.'

    if $option_gui; then
        if nmcli_output=$(nmcli device wifi show-password 2> >($logcmd)); then
            info "Wifi-gegevens:

$nmcli_output

$text"
        else
            info 'Geen wifi-apparaat gevonden.'
        fi
    else
        info 'Wifi-gegevens:
'
        nmcli device wifi show-password || nmcli_rc=$?
        if [[ $nmcli_rc -eq 0 ]]; then
            info "
$text"
        else
            info 'Geen wifi-apparaat gevonden.'
        fi
    fi
}


function term_script {
    exit $ok
}


###############################################################################
# Script
###############################################################################

function main {
    kz_common.init_script "$@"
    check_input "$@"
    process_input
    term_script
}

main "$@"
