.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" RELEASE_YEAR=2021
.\"
.\" VERSION_NUMBER=01.02.00
.\" VERSION_DATE=2021-09-27
.\"
.\"
.TH KZ 1 "KZ Handleiding" "KZ(1)" "KZ Handleiding"
.\"
.\"
.SH NAAM
kz \- Opdracht uitvoeren.
.\"
.\"
.SH SAMENVATTING
.B kz \fIOPDRACHT\fR [\fIARG\fR]
.br
.B kz \fBOPTIE\fR
.\"
.\"
.SH BESCHRIJVING
\fBkz\fR is een verzameling scripts voor het afronden en beheren van de
installatie van Ubuntu en Debian Linux.
.sp
\fBkz\fR voert \fIOPDRACHT\fR uit, eventueel met het opgegeven \fIARG\fR.
.sp
Zie \fBKZ OPDRACHTEN\fR voor welke \fIOPDRACHT\fRen worden ondersteund door
\fBkz\fR.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.\"
.\"
.SH KZ OPDRACHTEN
.PP
\fBarchive\fR
.RS
Scripts archiveren.
.RE
.PP
\fBbackup\fR
.RS
Backup maken.
.RE
.PP
\fBckhtml\fR
.RS
Webbestanden valideren.
.RE
.PP
\fBckname\fR
.RS
Bestandsnamen controleren.
.RE
.PP
\fBbuild\fR
.RS
Pakket bouwen.
.RE
.PP
\fBdeploy\fR
.RS
Pakket distribueren.
.RE
.PP
\fBdliso\fR
.RS
Beeldbestanden downloaden.
.RE
.PP
\fBgenpwd\fR
.RS
Wachtwoord genereren. Gebruik Bitwarden om wachtwoorden te beheren.
.RE
.PP
\fBgetdeb\fR
.RS
Pakket installeren.
.RE
.PP
\fBgo\fR
.RS
Updates uitvoeren.
.RE
.PP
\fBzgset\fR
.RS
GUI wijzigen.
.RE
.PP
\fBinstall\fR
.RS
Apps installeren.
.RE
.PP
\fBivp\fR
.RS
Scripts controleren.
.RE
.PP
\fBmenu\fR
.RS
Installatiemenu tonen.
.RE
.PP
\fBmkusb\fR
.RS
USB-sticks maken.
.RE
.PP
\fBnas\fR
.RS
Netwerkschijf aankoppelen.
.RE
.PP
\fBrestore\fR
.RS
Backup terugzetten.
.RE
.PP
\fBsetup\fR
.RS
Apps instellen.
.RE
.PP
\fBspsum\fR
.RS
Controlebestanden opsplitsen.
.RE
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH VOORBEELDEN
.sp
\fBkz\fR
.RS
Waarschuwing en beschikbare \fIOPDRACHT\fRen tonen.
.RE
.sp
\fBkz archive\fR
.RS
Start \fBarchive\fR uit de verzameling van \fBkz\fR scripts.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
