.\"############################################################################
.\"# Man-pagina voor kz.
.\"#
.\"# Geschreven door Karel Zimmer <info@karelzimmer.nl>, CC Publiek Domein
.\"# Verklaring <http://creativecommons.org/publicdomain/zero/1.0/deed.nl>.
.\"############################################################################
.\"
.TH KZ 1 "" "kz 365" "kz"
.\"
.\"
.SH NAAM
kz \- Opdracht uitvoeren.
.\"
.\"
.SH SAMENVATTING
.B kz \fIOPDRACHT\fR [\fIARG\fR]
.br
.B kz \fBOPTIE\fR
.\"
.\"
.SH BESCHRIJVING
\fBkz\fR voert opdrachten uit op Debian en op Debian gebaseerd systeem zoals
Ubuntu.
.sp
Pakket \fBkz\fR is een verzameling scripts en checklists voor het afronden en
beheren van de installatie en de instellingen van bijvoorbeeld Ubuntu Linux.
.sp
\fBkz\fR voert \fIOPDRACHT\fR uit, eventueel met het opgegeven \fIARG\fR.
.sp
Gebruik optie \fB-l\fR, \fB--list\fR voor een lijst van beschikbare
\fIOPDRACHT\fRen.
.
.\"
.\"
.SH OPTIES
.TP
\fB-l\fR, \fB--list\fR
Toon de beschikbare opdrachten.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH NOTITIES
.sp
Pakket \fBkz\fR geeft met de checklists en scripts invulling aan en
ondersteuning voor:
.br
\fB1. IaC\fR
.br
\fB2. CI/CD\fR
.br
\fB3. Day 0/Day 1/Day 2 Operations\fR
.br
Begrippen uit de moderne wereld van software-ontwikkeling, -distributie, en
beheer.
.sp
\fB1. IaC\fR (Infrastructure as Code) (Infrastructuur als Code, of
programmeerbare infrastructuur)
.br
Het definiëren en beheren van infrastructuur door middel van code.
.br
De opdrachten die standaard meegeleverd worden bij pakket kz zijn
idempotent; herhaaldelijk utvoeren leidt steeds tot hetzelfde resultaat.
.br
Herhaalbaarheid (idempotentie) is één van de principes van IaC.
.br
De checklists en scripts worden vastgelegd en onderhouden in versiebeheer
(GitHub), een ander principe van IaC.
.br
Voorbeelden zijn \fBkz-install-ubuntu-desktop.sh\fR (installatiebestand
gebruikt door \fBkz install\fB) en \fBkz-setup-ubuntu-desktop.sh\fR
(instelbestand gebruikt door \fBkz setup\fR).
.sp
\fB2. CI/CD\fR (Continuous Integration and Delivery) (Continue integratie en
levering)
.br
CI/CD is de gecombineerde praktijk van continuous integration (CI) en (vaker)
continuous delivery of (minder vaak) continuous deployment (CD).
.br
CI (continuous integration) is het meerdere keren per dag de werkkopieën van
alle ontwikkelaars samenvoegen tot een gedeelde hoofdlijn.
.br
CD (continuous delivery) is software produceren in korte cycli, ervoor zorgen
dat de software op elk moment betrouwbaar kan worden vrijgegeven en, bij het
vrijgeven van de software, zonder dit handmatig te doen.
.br
CD (continuous deployment) is een aanpak waarbij softwarefunctionaliteiten vaak
en via geautomatiseerde implementaties worden geleverd.
.br
Een \fBCI/CD Pipeline\fR is een reeks stappen die moet worden uitgevoerd om
geautomatiseerd een nieuwe softwareversie te leveren.
.br
Voorbeelden zijn \fBkz build\fR en \fBkz deploy\fR.
.sp
\fB3. Day 0/Day 1/Day 2 Operations\fR
.br
In IT verwijzen de termen Day 0/Day 1/Day 2 Operations naar verschillende fasen
van software-ontwikkeling, -distributie, en beheer.
.sp
.RS 3
\fBDay 0 Operations\fR (Dag 0 Activiteiten)
.br
Dit is de ontwerpfase (design), waarin projectvereisten worden gespecificeerd
en de architectuur van de oplossing wordt bepaald.
.br
Hierbij gebruik ik Visual Studio Code en GitHub, en programmeer ik in Bash en
Python.
.sp
\fBDay 1 Operations\fR (Dag 1 Activiteiten)
.br
Omvat het ontwikkelen en implementeren (development and deploy) van software
die is ontworpen in de dag 0-fase.
.br
Hierbij wordt onder andere gebruik gemaakt van \fBIaC\fR en
\fBCI/CD Pipelines\fR (voor uitleg zie zie verderop), en het uitvoeren van
Ansible Playbooks.
.br
Voorbeelden zijn Checklist installatie, en \fBkz getdeb\fR en \fBkz menu\fR.
.sp
\fBDay 2 Operations\fR (Dag 2 Activiteiten)
.br
Hier gaat de meeste aandacht uit naar het onderhouden, bewaken en optimaliseren
(maintaining, monitoring, and optimizing) van het systeem.
.br
Voorbeelden zijn \fBkz update\fR en \fBkz backup\fR.
.RE
.\"
.\"
.SH VOORBEELDEN
\fBkz\fR
.RS
Waarschuwing en beschikbare \fIOPDRACHT\fRen tonen.
.RE
.sp
\fBkz update\fR
.RS
Systeem bijwerken.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>, Creative Commons Publiek
Domein Verklaring <http://creativecommons.org/publicdomain/zero/1.0/deed.nl>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer - Linux - Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
