.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz-common.sh.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\" Auteursrecht (c) 2019-2021 Karel Zimmer.
.\" Creative Commons Naamsvermelding-GelijkDelen Internationaal-licentie
.\" <https://creativecommons.org/licenses/by-sa/4.0/>.
.\"
.\" ReleaseNumber: 04.00.00
.\" DateOfRelease: 2021-08-08
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ-COMMON.SH 1 "kz-common.sh" "kz 365" "kz-common.sh"
.\"
.\"
.SH NAAM
kz-common.sh \- Algemene module voor shell scripts.
.\"
.\"
.SH SAMENVATTING
.B source kz-common.sh
.\"
.\"
.SH BESCHRIJVING
Dit bestand geeft toegang tot algemene variabelen en functies.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH AUTEURSRECHT
Auteursrecht (c) 2009-2021 Karel Zimmer.
.br
GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het kz(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Bestand kz-common.sh is onderdeel van het pakket kz en is beschikbaar vanaf
Karel Zimmer Linux Scripts <https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
