.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz-common.py.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\" Auteursrecht (c) 2021 Karel Zimmer.
.\" Creative Commons Naamsvermelding-GelijkDelen Internationaal-licentie
.\" <https://creativecommons.org/licenses/by-sa/4.0/>.
.\"
.\" ReleaseNumber: 02.00.00
.\" DateOfRelease: 2021-08-08
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ_COMMON.PY 1 "Kz Handleiding" "KZ_COMMON.PY(1)" "Kz Handleiding"
.\"
.\"
.SH NAAM
kz_common.py \- Algemene module voor Python scripts.
.\"
.\"
.SH GEBRUIK
.B import kz_common
.\"
.\"
.SH BESCHRIJVING
Deze module geeft toegang tot algemene functies.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH AUTEURSRECHT
Auteursrecht (c) 2021 Karel Zimmer.
.br
GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Bestand \fBkz_common.py\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
