.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz_common.sh.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" FIRST_RELEASED=2019
.\" 
.\" VERSION_NUMBER=04.00.01
.\" VERSION_DATE=2021-08-22
.\" 
.\"
.TH KZ_COMMON.SH 1 "Kz Handleiding" "KZ_COMMON.SH(1)" "Kz Handleiding"
.\"
.\"
.SH NAAM
kz_common.sh \- Algemene module voor shell scripts.
.\"
.\"
.SH SAMENVATTING
.B source kz_common.sh
.\"
.\"
.SH BESCHRIJVING
Dit bestand geeft toegang tot algemene variabelen en functies.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Bestand \fBkz_common.sh\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
