#!/bin/bash
# shellcheck source=kz_common.sh
###############################################################################
# Pakket distribueren.
#
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
#
# Auteursrecht (c) 2009-2021 Karel Zimmer.
# GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
#
# ReleaseNumber: 62.02.00
# DateOfRelease: 2021-08-19
###############################################################################
source "$(dirname "$0")"/kz_common.sh

###############################################################################
# Global constants
###############################################################################

readonly    OPTIONS_SHORT=$OPTIONS_SHORT_COMMON
readonly    OPTIONS_LONG=$OPTIONS_LONG_COMMON
readonly    USAGE="Gebruik: $DISPLAY_NAME $OPTIONS_USAGE_COMMON"
readonly    HELP="Gebruik: $DISPLAY_NAME [OPTIE...] [--]

Pakket distribueren.

Opties:
$OPTIONS_HELP_COMMON"

readonly    DEB_DIR=$HOME/kz_deb
readonly    DEB_TEMP_DIR=/tmp/kz
readonly    DEB_NAME=kz_365_all.deb
readonly    DOCS_DIR=$HOME/kz_docs
readonly    SCRIPTS_DIR=$HOME/kz_scripts
readonly    SITE_DIR=$HOME/uploads/karelzimmer.nl/httpdocs

readonly -A SOURCE_DEB=(
                [DEB]=$DEB_DIR
               [DOCS]=$DOCS_DIR
            [SCRIPTS]=$SCRIPTS_DIR
    )
readonly -A TARGET_DEB=(
                [DEB]=$DEB_TEMP_DIR
       [APPLICATIONS]=$DEB_TEMP_DIR/usr/share/applications
        [BACKGROUNDS]=$DEB_TEMP_DIR/usr/share/backgrounds
    [BACKGROUND_PROP]=$DEB_TEMP_DIR/usr/share/gnome-background-properties
                [BIN]=$DEB_TEMP_DIR/usr/bin
                [DOC]=$DEB_TEMP_DIR/usr/share/doc/kz
                [MAN]=$DEB_TEMP_DIR/usr/share/man/man1
           [POLICY_1]=$DEB_TEMP_DIR/usr/share/polkit-1/actions
           [TABCOMPL]=$DEB_TEMP_DIR/usr/share/bash-completion/completions
    )

readonly -A SOURCE_UPLOADS=(
       [DOCS]=$DOCS_DIR
    [SCRIPTS]=$SCRIPTS_DIR
    )
readonly -A TARGET_UPLOADS=(
        [DEB]=$SITE_DIR/apps/kz
       [DOCS]=$SITE_DIR/data/linux/documents
       [PDFS]=$SITE_DIR/data/linux/pdfs
    [SCRIPTS]=$SITE_DIR/data/linux/scripts
    )


###############################################################################
# Global variables
###############################################################################


###############################################################################
# Functions
###############################################################################

check_input() {
    local karel_full_name=''
    local ubuntu_full_name=''

    PARSED=$(
        getopt  --alternative                       \
                --options       "$OPTIONS_SHORT"    \
                --longoptions   "$OPTIONS_LONG"     \
                --name          "$DISPLAY_NAME"     \
                --              "$@"
        )       || GETOPT_RC=$?
    if [[ $GETOPT_RC -ne $SUCCESS ]]; then
        printf '%s\n' "$USAGELINE" >&2
        exit $ERROR
    fi
    eval set -- "$PARSED"
    process_general_options "$@"

    while true; do
        case $1 in
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    if [[ "$*" ]]; then
        TEXT='geen argumenten opgeven'
        printf  "$DISPLAY_NAME: %s\n%s\n"   \
                "$TEXT"                     \
                "$USAGELINE"                >&2
        exit    $ERROR
    fi

    karel_full_name=$(
        getent  passwd  karel           |
        awk     -F:     '{print $5}'    |
        awk     -F,     '{print $1}'    || true
        )
    ubuntu_full_name=$(
        getent  passwd  ubuntu          |
        awk     -F:     '{print $5}'    |
        awk     -F,     '{print $1}'    || true
        )
    debian_full_name=$(
        getent  passwd  user            |
        awk     -F:     '{print $5}'    |
        awk     -F,     '{print $1}'    || true
        )
    if ! [[ ($USER = karel  && $karel_full_name  = 'Karel Zimmer'    )  ||
            ($USER = ubuntu && $ubuntu_full_name = 'Live session user') ||
            ($USER = user   && $debian_full_name = 'Debian Live user')  ]]
    then
            TEXT='alleen uitvoeren als ontwikkelaar'
            printf  "$DISPLAY_NAME: %s\n%s\n"   \
                    "$TEXT"                     \
                    "$USAGELINE"                >&2
            exit    $ERROR
    fi

    # Een non-gui script gestart met optie gui.
    if $OPTION_GUI; then
        OPTION_GUI=false
        TERMINAL=true
    fi

    check_user

    # Regel sudo maar gelijk voor verderop.
    sudo true
}


process_input() {
    pre_actions
    create_package
    upload_website
    install_package
}


pre_actions() {
    check_names
    check_scripts
    rsync   --archive               \
            --delete                \
            --exclude='README.md'   \
            "${SOURCE_DEB[DEB]}"/   \
            "${TARGET_DEB[DEB]}"
    sync_pdf_kz_docs
    sync_all_kz_docs
    sync_pdf_kz_scripts
    sync_all_kz_scripts
    sync_deb_kz_backgrounds
}

check_dependencies() {
    if ! command -v enscript 1> /dev/null; then
        info 'Installeer enscript...'
        sudo apt-get install --yes enscript |& $LOGCMD
    fi
    if ! command -v fakeroot 1> /dev/null; then
        info 'Installeer fakeroot...'
        sudo apt-get install --yes fakeroot |& $LOGCMD
    fi
    if ! command -v ghostscript 1> /dev/null; then
        # Voor ps2pdf.
        info 'Installeer ghostscript...'
        sudo apt-get install --yes ghostscript |& $LOGCMD
    fi
    if ! command -v lftp 1> /dev/null; then
        info 'Installeer lftp...'
        sudo apt-get install --yes lftp |& $LOGCMD
    fi
    if ! command -v rsync 1> /dev/null; then
        info 'Installeer rsync...'
        sudo apt-get install --yes rsync |& $LOGCMD
    fi
}


check_names() {
    local -i check_rc=0

    info 'Controleer bestandsnamen (kz ckname)...'
    "$SCRIPTS_DIR"/kz ckname    "$DEB_DIR"      \
                                "$DOCS_DIR"     \
                                "$SCRIPTS_DIR"  || check_rc=$?
    if [[ $check_rc -ne $SUCCESS ]]; then
        warning "
Herstel alle meldingen hierboven en start daarna weer $DISPLAY_NAME."
        exit $check_rc
    fi
}


check_scripts() {
    local -i check_rc=0

    info 'Controleer scripts (kz ivp)...'
    "$SCRIPTS_DIR"/kz ivp || check_rc=$?
    if [[ $check_rc -ne $SUCCESS ]]; then
        warning "
Herstel alle meldingen hierboven en start daarna weer $DISPLAY_NAME."
        exit $check_rc
    fi
}


sync_pdf_kz_docs() {
    local txtfile=''
    local basefile=''
    local changes=false

    info 'Gewijzigde documenten...'

    cd "${SOURCE_UPLOADS[DOCS]}" || exit $ERROR

    # Vanuit gedit aangemaakt.
    rm --force "$HOME"/Documenten/*.pdf

    # Vanuit LibreOffice aangemaakt.
    rm --force "$HOME"/Documenten/Checklists/*.pdf |& $LOGCMD

    for docfile in *.odt *.txt; do
        basefile=$(basename "$docfile" .odt)

        # Maak pdf aan als het bestand nieuw of gewijzigd is (deltabepaling).
        if ! diff   "$docfile"                          \
                    "${TARGET_UPLOADS[DOCS]}/$docfile"  &> /dev/null; then
            lowriter    --headless                          \
                        --convert-to pdf                    \
                        --outdir "${TARGET_UPLOADS[PDFS]}"  \
                        "$docfile"                          |& $LOGCMD
            changes=true
            info "    $docfile"
        fi
    done

    if ! $changes; then
        info '    Geen documenten gewijzigd'
    fi
    cd "$HOME" || exit $ERROR
}


sync_all_kz_docs() {
    # De exclude en delete-excluded i.v.m. de lokale git repository.
    rsync   --archive               \
            --delete                \
            --exclude='LICENSE'     \
            --exclude='README.md'   \
            --exclude='.git*'       \
            --delete-excluded       \
            "${SOURCE_DEB[DOCS]}"/  \
            "${TARGET_DEB[DOC]}"    |& $LOGCMD

    cd "${SOURCE_UPLOADS[DOCS]}" || exit $ERROR
    for txtfile in *.txt; do
        basefile=$(basename "$txtfile" .txt)
        cp  --archive                               \
            --update                                \
            "${TARGET_UPLOADS[PDFS]}/$basefile.pdf" \
            "${TARGET_DEB[DOC]}"
    done
    for docfile in *.odt; do
        basefile=$(basename "$docfile" .odt)
        cp  --archive                               \
            --update                                \
            "${TARGET_UPLOADS[PDFS]}/$basefile.pdf" \
            "${TARGET_DEB[DOC]}"
    done
    cd "$HOME" || exit $ERROR

    rsync   --archive                       \
            --delete                        \
            --exclude='LICENSE'             \
            --exclude='README.md'           \
            --exclude='.git*'               \
            --delete-excluded               \
            "${SOURCE_UPLOADS[DOCS]}"/      \
            "${TARGET_UPLOADS[DOCS]}"       |& $LOGCMD
}


sync_pdf_kz_scripts() {
    local changes=false
    local scriptfile=''

    info 'Gewijzigde scripts...'

    cd "${SOURCE_UPLOADS[SCRIPTS]}" || exit $ERROR
    for scriptfile in *; do

        if [[ $scriptfile = LICENSE || $scriptfile = README.md ]]; then
            continue
        elif [[ -d "$scriptfile" ]]; then
            continue
        fi

        # Verwerk het bestand als deze nieuw of gewijzigd is (deltabepaling).
        if ! diff   "$scriptfile"                               \
                    "${TARGET_UPLOADS[SCRIPTS]}/$scriptfile"    &> /dev/null
        then
            if grep --quiet --regexp='^''.TH ' "$scriptfile"; then
                # Man-pagina.
                man     --troff                                     \
                        "${SOURCE_UPLOADS[SCRIPTS]}/$scriptfile"    |
                ps2pdf  - "${TARGET_UPLOADS[PDFS]}/$scriptfile.pdf" |& $LOGCMD
            else
                # Script inclusief *.1, *.completion, *.desktop, en *.policy.
                if grep --quiet                         \
                        --line-regexp                   \
                        --regexp='#!''/usr/bin/python3' \
                        "$scriptfile"; then
                        highlight=python
                elif [[ $scriptfile = *.py ]]; then
                        highlight=python
                elif [[ $scriptfile = *.policy ]]; then
                        highlight=html
                else
                        highlight=bash
                fi
                enscript    --quiet                                     \
                            --highlight=$highlight                      \
                            --line-numbers                              \
                            --title="$scriptfile"                       \
                            --output=-                                  \
                            "$scriptfile"                               |
                ps2pdf      -                                           \
                            "${TARGET_UPLOADS[PDFS]}/$scriptfile.pdf"   \
                            |& $LOGCMD
            fi
            changes=true
            info "    $scriptfile"
        fi
    done
    if ! $changes; then
        info '    Geen scripts gewijzigd'
    fi
    cd "$HOME" || exit $ERROR
}


sync_all_kz_scripts() {
    local basename=''
    local file=''
    local newfile=''
    local prefix='nl.karelzimmer.'

    chmod 'u=rwx,g=rx,o=rx' -- "$SCRIPTS_DIR"/*
    chmod 'a-x' -- "$SCRIPTS_DIR"/*.* "$SCRIPTS_DIR"/LICENSE

    # Deze rsync is inclusief *.1, *.completion, *.desktop, en *.policy.
    # De exclude en delete-excluded i.v.m. de lokale git repository en pycache.
    rsync   --archive                   \
            --delete                    \
            --exclude='__pycache__'     \
            --exclude='LICENSE'         \
            --exclude='README.md'       \
            --exclude='.git*'           \
            --delete-excluded           \
            "${SOURCE_DEB[SCRIPTS]}"/   \
            "${TARGET_DEB[BIN]}"        |& $LOGCMD

    # Man-pagina's (.1)
    rsync   --archive                   \
            --delete                    \
            --remove-source-files       \
            "${TARGET_DEB[BIN]}"/*.1    \
            "${TARGET_DEB[MAN]}"        |& $LOGCMD
    gzip --best --force "${TARGET_DEB[MAN]}"/*.1 |& $LOGCMD

    # Tab-completion-scripts (.completion)
    for file in "${TARGET_DEB[BIN]}"/*.completion; do
        basename=$(basename "$file" .completion)
        mv "$file" "${TARGET_DEB[TABCOMPL]}/$basename" |& $LOGCMD
    done

    # Bureaublad-configuratiebestanden (.desktop)
    for file in "${TARGET_DEB[BIN]}"/*.desktop; do
        basename=$(basename "$file")
        mv "$file" "${TARGET_DEB[APPLICATIONS]}/$basename" |& $LOGCMD
    done

    # PolicyKit actiedefinitiebestanden (.policy)
    for file in "${TARGET_DEB[BIN]}"/*.policy; do
        basename=$(basename "$file")
        newfile="${TARGET_DEB[POLICY_1]}/$prefix$basename"
        mv "$file" "$newfile" |& $LOGCMD
    done

    rsync   --archive                       \
            --delete                        \
            --exclude='__pycache__'         \
            --exclude='LICENSE'             \
            --exclude='README.md'           \
            --exclude='.git*'               \
            --delete-excluded               \
            "${SOURCE_UPLOADS[SCRIPTS]}"/   \
            "${TARGET_UPLOADS[SCRIPTS]}"    |& $LOGCMD
}


sync_deb_kz_backgrounds() {
    local wallpaper=''
    local wallpapers_config_file=kz_wallpapers.xml

    {
    printf '%s\n' '<?xml version="1.0" encoding="UTF-8"?>'
    printf '%s\n' '<!DOCTYPE wallpapers SYSTEM "gnome-wp-list.dtd">'
    printf '%s\n' '<wallpapers>'
    } > "${TARGET_DEB[BACKGROUND_PROP]}/$wallpapers_config_file"

    cd "${TARGET_DEB[BACKGROUNDS]}" || exit $ERROR
    for wallpaper in *; do
        # Verwijder DEB_TEMP_DIR uit TARGET_DEB[BACKGROUNDS].  Voorbeeld:
        # /tmp/kz/usr/share/backgrounds/kz_gnome.png ->
        # /usr/share/backgrounds/kz_gnome.png
        filename=${TARGET_DEB[BACKGROUNDS]}/$wallpaper
        filename=${filename/$DEB_TEMP_DIR/}
        printf '%s\n' "    <wallpaper>
        <name>${wallpaper%.*}</name>
        <filename>$filename</filename>
        <options>zoom</options>
        <pcolor>#000000</pcolor>
        <scolor>#000000</scolor>
        <shade_type>solid</shade_type>
    </wallpaper>"           \
            >> "${TARGET_DEB[BACKGROUND_PROP]}/$wallpapers_config_file"
    done
    printf  '%s\n' \
            '</wallpapers>' >> "${TARGET_DEB[BACKGROUND_PROP]}/\
$wallpapers_config_file"
    cd "$HOME" || exit $ERROR
}


create_package() {
    info 'Maak scriptspakket...'
    fakeroot    dpkg-deb                            \
                --build                             \
                "$DEB_TEMP_DIR"                     \
                "${TARGET_UPLOADS[DEB]}/$DEB_NAME"  |& $LOGCMD
    rm --force --recursive "$DEB_TEMP_DIR"
}


upload_website() {
    local ftp_set='set ssl:verify-certificate no'
    local ftp_from=$SITE_DIR
    local ftp_to=/httpdocs
    local ftp_opts='--reverse --delete --verbose'
    local ftp_cmd="mirror $ftp_opts $ftp_from $ftp_to"
    local ftp_host=server106.hosting2go.nl
    local ftp_user=kzimmer
    local ftp_login=$HOME/.kz_$ftp_host

    info 'Upload website...'
    if ! [[ -f $ftp_login ]]; then
        read -rsp "FTP-wachtwoord voor $ftp_host: "
        printf '%s\n' "$REPLY" > "$ftp_login"
        printf '\n'
        chmod 'u=rw,g=,o=' "$ftp_login" |& $LOGCMD
    fi
    if ! lftp   --user      "$ftp_user"                 \
                --password  "$(cat "$ftp_login")"       \
                -e          "$ftp_set; $ftp_cmd; exit"  \
                "$ftp_host"                             |& $LOGCMD; then
        rm      "$ftp_login"
        warning 'Uploaden website is mislukt.'
        warning 'Controleer de log...!'
        exit $WARNING
    fi
    sleep 5
}


install_package() {
    info 'Installeer pakket kz (kz getdeb)...'
    # Constructie '2> >($LOGCMD)' om stderr naar de log te krijgen.
    if ! wget -O- karelzimmer.nl/kz 2> >($LOGCMD) | bash; then
        warning 'Installeren pakket kz is niet uitgevoerd.'
        exit $WARNING
    fi
}


term_script() {
    exit $SUCCESS
}


###############################################################################
# Main line
###############################################################################

main() {
    init_script
    check_input "$@"
    process_input
    term_script
}


main "$@"


# EOF
