.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz deploy.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\" Auteursrecht (c) 2019-2021 Karel Zimmer.
.\" Creative Commons Naamsvermelding-GelijkDelen Internationaal-licentie
.\" <https://creativecommons.org/licenses/by-sa/4.0/>.
.\"
.\" ReleaseNumber: 07.00.00
.\" DateOfRelease: 2021-08-08
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ_DEPLOY 1 "Kz Handleiding" "KZ_DEPLOY(1)" "Kz Handleiding"
.\"
.\"
.SH NAAM
kz deploy \- Scripts distribueren.
.\"
.\"
.SH SAMENVATTING
.B kz deploy
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz deploy\fR distribueert en uploadt scripts en documenten naar
http://karelzimmer.nl.
.br
Dit om de scripts en documenten beschikbaar te stellen voor algemeen gebruik.
.sp
Tevens zijn de scripts en documenten op GitHub geplaatst, te verkrijgen via:
.br
\fBgit clone https://github.com/karelzimmer/kz_scripts.git\fR
.br
\fBgit clone https://github.com/karelzimmer/kz_docs.git\fR
.sp
\fBkz deploy\fR kan worden uitgevoerd als ontwikkelaar (gebruiker 'karel' of\
 'ubuntu').
.sp
Mijn eigen Continuous Integration and Delivery (CI/CD) Pipeline.
.sp
Als ontwikkelen en testen gereed is, kan er een 'git push' en \fBkz deploy\fR
uitgevoerd worden, waarbij er een nieuw scriptspakket wordt gegenereerd.
.sp
Met opdracht \fBkz getdeb\fR kan de scripts-ontwikkelomgeving op een andere
of dezelfde machine neergezet worden.
.sp
De volgende acties uitgevoerd:
.RS
1. Aanmaken scriptspakket.
.br
   1.1. Controleer afhankelijkheden.
.br
   1.2. Controleer scriptnamen (met \fBkz ckname\fR).
.br
   1.2. Controleer scripts (met \fBkz ivp\fR).
.br
2. Upload website.
.br
   2.1. Verwerk documenten (pdf aanmaken).
.br
   2.1. Verwerk scripts (pdf aanmaken).
.br
3. Installer scriptspakket (met \fBkz getdeb\fR).
.RE
Mijn eigen CI/CD Pipeline :-).
.sp
In een grafische werkomgeving zoals GNOME (e.g. Ubuntu) kan \fBkz deploy\fR
worden gestart door te zoeken naar \fBdepl\fR, klik op
\fBScripts distribueren\fR.
.\"
.\"
.SH OPTIES
.TP
\fB-d\fR, \fB--debug\fR
Geef foutopsporingsinformatie weer in het logboek (gebruik '[sudo] journalctl
-ab -t kz-deploy').
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB--\fR
Een -- geeft het einde van de opties aan en schakelt de verdere verwerking van
opties uit.
.br
Alle argumenten na de -- worden behandeld als bestandsnamen en argumenten.
Een argument van - is gelijk aan --.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH MAPPEN
~/kzscripts.deb/
.RS
Scriptspakket.
.RE
.sp
~/Documenten/Checklists/
.RS
Checklists.
.RE
.sp
~/kzscripts/
.RS
Scripts.
.br
Inclusief man-pagina's (*.1),
Tab-completion-scripts (*.completion),
bureaublad-configuratiebestanden (*.desktop), en
PolicyKit actiedefinitiebestanden (*.policy).
.RE
.sp
~/uploads/
.RS
Website.
.RE
.\"
.\"
.SH BESTANDEN
~/uploads/karelzimmer.nl/httpdocs/apps/kz/kz_365_all.deb
.RS
Scriptspakket.
.RE
.sp
/usr/share/gnome-background-properties/kz_wallpapers.xml
.RS
Bureaubladachtergronden-configuratiebestand.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH AUTEURSRECHT
Auteursrecht (c) 2009-2021 Karel Zimmer.
.br
GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
.\"
.\"
.SH ZIE OOK
\fBkz_ckname\fR(1),
\fBkz_common.sh\fR(1),
\fBkz_getdeb\fR(1),
\fBkz_ivp\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz deploy\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
