#!/usr/bin/python3
"""
Wachtwoord genereren. Gebruik Bitwarden om wachtwoorden te beheren.

Dit script genereert een wachtwoord bestaande uit 16 willekeurige tekens.
"""
###############################################################################
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
# Auteursrecht (c) 2021 Karel Zimmer.
# GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
#
# ReleaseNumber: 03.00.02
# DateOfRelease: 2021-08-21
###############################################################################
import os
import sys
import random
import argparse
import kz_common

program_name = os.path.basename(__file__)
display_name = program_name.replace('kz_', 'kz ')


def generate_password():
    lower = 'abcdefghijklmnopqrstuvwxyz'
    upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    numbers = '0123456789'
    symbols = '$%@#[]{}()*;/,_-'

    all = lower + upper + numbers + symbols

    length = 16

    password = ''.join(random.sample(all, length))
    print(f'{password}\n\nGebruik Bitwarden om wachtwoorden te beheren.')


def process_option_usage():
    print(f"""Gebruik: {display_name} [-g|--gui] [-h|--help] [-u|--usage] \
[-v|--version]

Typ '{display_name} --help' voor meer informatie.""")


# --- script ---

parser = argparse.ArgumentParser(prog=display_name,
                                 description='Wachtwoord genereren.',
                                 epilog="Typ 'man " + display_name +
                                 "' voor meer informatie.")
parser.add_argument('-g', '--gui', action='store_true',
                    help='start in grafische modus')
parser.add_argument('-u', '--usage', action='store_true',
                    help='een korte gebruikssamenvatting tonen')
parser.add_argument('-v', '--version', action='store_true',
                    help='de versie tonen')
args = parser.parse_args()

if args.usage:
    process_option_usage()
elif args.version:
    rc = kz_common.process_option_version(program_name)
    if rc != 0:
        sys.exit(rc)
else:
    generate_password()

# Een non-gui script gestart met optie gui.
if args.gui:
    input('Druk op de Enter-toets om verder te gaan [Enter]: ')

# EOF
