#!/usr/bin/python3
"""
Updates uitvoeren.

Dit script voert updates uit voor Debian pakketten en snaps.
"""
###############################################################################
# Kortere weg vooor:
#   sudo apt-get update                                         &&
#   sudo apt-get upgrade --yes                                  &&
#   sudo apt-get autoremove --yes                               &&
#   sudo apt-get autoclean --yes                                &&
#   if command -v snap 1> /dev/null; then sudo snap refresh; fi &&
#   if [[ -f /var/run/reboot-required ]]; then echo REBOOT; fi
#
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
# Auteursrecht (c) 2021 Karel Zimmer.
# GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
#
# ReleaseNumber: 02.01.00
# DateOfRelease: 2021-08-21
###############################################################################
import sys
import subprocess

program_name = 'kz_go'
display_name = program_name.replace('kz_', 'kz ')
option_gui = 0

# --- script ---

# Alleen optie gui toegestaan, verder geen argumenten.
try:
    if sys.argv[1] == '--gui':
        option_gui = 1
    elif sys.argv[1]:
        print(f'Gebruik: {display_name}')
        sys.exit(0)
except Exception:
    pass

# Opdracht als sequence:
subprocess.run(['sudo', 'apt-get', 'update'])

# Opdracht als raw text:
subprocess.run('sudo apt-get upgrade --yes', shell=True)

# Opdracht als raw text, vang stdout en stderr op:
subprocess.run('sudo apt-get autoremove --yes', shell=True, check=True)
subprocess.run('sudo apt-get autoclean --yes', shell=True, check=True)

# Heeft dit systeem snaps?
try:
    subprocess.run('sudo snap refresh', shell=True)
except Exception as ex:
    print(ex)

# Is een reboot nodig?
try:
    with open('/var/run/reboot-required') as fh:
        print(f'{display_name}: REBOOT')
except FileNotFoundError:
    pass
except Exception as ex:
    print(ex)
    sys.exit(1)

# Een non-gui script gestart met optie gui.
if option_gui:
    input('Druk op de Enter-toets om verder te gaan [Enter]: ')

# EOF
