.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz genpwd.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" RELEASE_YEAR=2021
.\" 
.\" VERSION_NUMBER=03.00.01
.\" VERSION_DATE=2021-08-22
.\" 
.\"
.TH KZ_GENPWD 1 "Kz Handleiding" "KZ_GENPWD(1)" "Kz Handleiding"
.\"
.\"
.SH NAAM
kz genpwd \- Wachtwoord genereren.
.\"
.\"
.SH SAMENVATTING
.B kz genpwd
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz genpwd\fR genereeert een wachtwoord bestaande uit 16 willekeurige tekens.
Gebruik Bitwarden om wachtwoorden te beheren.
.sp
In een grafische werkomgeving zoals GNOME (e.g. Ubuntu) kan \fBkz genpwd\fR
worden gestart door te zoeken naar \fBgenpw\fR, klik op
\fBWachtwoord genereren\fR.
.\"
.\"
.SH OPTIES
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz_common.py\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz genpwd\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
