#!/usr/bin/python3
"""
Wachtwoord genereren. Gebruik Bitwarden om wachtwoorden te beheren.

Dit script genereert een wachtwoord bestaande uit 16 willekeurige tekens.
"""
###############################################################################
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
###############################################################################
import sys
import random
import argparse
import kz_common

program_name = 'kz_genpwd'
display_name = program_name.replace('kz_', 'kz ')
release_year = 2021

version_number = '03.00.03'
version_date = '2021-08-22'


def generate_password():
    lower = 'abcdefghijklmnopqrstuvwxyz'
    upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    numbers = '0123456789'
    symbols = '$%@#[]{}()*;/,_-'

    all = lower + upper + numbers + symbols

    length = 16

    password = ''.join(random.sample(all, length))
    print(f'{password}\n\nGebruik Bitwarden om wachtwoorden te beheren.')


# --- script ---

parser = argparse.ArgumentParser(prog=display_name,
                                 description='Wachtwoord genereren.',
                                 epilog="Typ 'man " + display_name +
                                 "' voor meer informatie.")
parser.add_argument('-g', '--gui', action='store_true',
                    help='start in grafische modus')
parser.add_argument('-u', '--usage', action='store_true',
                    help='een korte gebruikssamenvatting tonen')
parser.add_argument('-v', '--version', action='store_true',
                    help='de versie tonen')
args = parser.parse_args()

if args.usage:
    kz_common.process_option_usage(display_name)
elif args.version:
    kz_common.process_option_version(display_name, version_number,
                                     version_date, release_year)
else:
    generate_password()

# Een non-gui script gestart met optie gui.
if args.gui:
    input('Druk op de Enter-toets om verder te gaan [Enter]: ')

# EOF
