.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz go.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" RELEASE_YEAR=2021
.\"
.\" VERSION_NUMBER=01.00.01
.\" VERSION_DATE=2021-08-22
.\"
.\"
.TH KZ_GO 1 "Kz Handleiding" "KZ_GO(1)" "Kz Handleiding"
.\"
.\"
.SH NAAM
kz go \- Update uitvoeren.
.\"
.\"
.SH SAMENVATTING
.B kz go
.\"
.\"
.SH BESCHRIJVING
\fBkz go\fR voert update uit.
.sp
In een grafische werkomgeving zoals GNOME (e.g. Ubuntu) kan \fBkz go\fR
worden gestart door te zoeken naar \fBgo\fR, klik op
\fBUpdates uitvoeren\fR.
.\"
.\"
.SH OPTIES
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz go\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
