#!/bin/bash
# shellcheck source=kz_common.sh
###############################################################################
# Applijst maken.
#
# Geschreven door Karel Zimmer <info@karelzimmer.nl>.
#
# Auteursrecht (c) 2013-2021 Karel Zimmer.
# GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
#
# ReleaseNumber: 19.01.00
# DateOfRelease: 2021-08-14
###############################################################################
source "$(dirname "$0")"/kz_common.sh


###############################################################################
# Global constants
###############################################################################

readonly OPTIONS_SHORT=$OPTIONS_SHORT_COMMON
readonly OPTIONS_LONG=$OPTIONS_LONG_COMMON
readonly USAGE="Gebruik: ${PROGRAM_NAME/kz_/kz } $OPTIONS_USAGE_COMMON"
readonly HELP="Gebruik: ${PROGRAM_NAME/kz_/kz } [OPTIE...]

Applijst maken.

Opties:
$OPTIONS_HELP_COMMON"

readonly ID=$(lsb_release --id --short | tr '[:upper:]' '[:lower:]')
readonly OUTPUTFILE_0=/usr/local/etc/${PROGRAM_NAME}_${HOSTNAME}_$ID
readonly OUTPUTFILE_1=${OUTPUTFILE_0}_deb-bestanden
readonly OUTPUTFILE_2=${OUTPUTFILE_0}_pakketbronnen
readonly OUTPUTFILE_3=${OUTPUTFILE_0}_pakketten
readonly OUTPUTFILE_4=${OUTPUTFILE_0}_snaps
readonly RUN_AS_SUPERUSER=true


###############################################################################
# Global variables
###############################################################################


###############################################################################
# Functions
###############################################################################

check_input() {
    PARSED=$(
        getopt  --alternative                               \
                --options       "$OPTIONS_SHORT"            \
                --longoptions   "$OPTIONS_LONG"             \
                --name          "${PROGRAM_NAME/kz_/kz }"   \
                -- "$@"
        )       || GETOPT_RC=$?
    if [[ $GETOPT_RC -ne $SUCCESS ]]; then
        printf '%s\n' "$USAGELINE" >&2
        exit $ERROR
    fi
    eval set -- "$PARSED"
    process_general_options "$@"

    while true; do
        case $1 in
            --)
                shift
                break
                ;;
            *)
                shift
                ;;
        esac
    done

    if [[ "$*" ]]; then
        TEXT='geen argumenten opgeven'
        printf "${PROGRAM_NAME/kz_/kz }: %s\n%s\n" "$TEXT" "$USAGELINE" >&2
        exit $ERROR
    fi

    check_user
}


process_input() {
    local text0='Opdrachten worden verwerkt'
    local text1="[1/4]  Bepaal welke deb-bestanden (Debian-pakketten) zijn \
geïnstalleerd"
    local text2="[2/4]  Bepaal welke pakketbronnen (\"repositories\" of \
\"repo's\") zijn toegevoegd"
    local text3="[3/4]  Bepaal welke pakketten door de gebruiker zijn \
geïnstalleerd"
    local text4='[4/4]  Bepaal welke snaps zijn geïnstalleerd'

    TITLE='Applijst maken'
    # Constructie '2> >($LOGCMD)' om stderr naar de log te krijgen.
    # Voorbeeld: Unable to init server: Kon niet verbinden:
    #            Verbinding is geweigerd
    #        en: (zenity:47712): Gtk-WARNING **: 10:35:49.339:
    #            cannot open display:
    if $OPTION_GUI; then
        (
        printf '%s\n' "#$text1"
        create_file_installed_without_repo
        printf '%s\n' "#$text2"
        create_file_added_repos
        printf '%s\n' "#$text3"
        create_file_installed_by_user
        printf '%s\n' "#$text4"
        create_file_snaps
        ) |&
        zenity  --progress              \
                --pulsate               \
                --auto-close            \
                --no-cancel             \
                --width     600         \
                --height    50          \
                --title     "$TITLE"    \
                --text      "$text0"    2> >($LOGCMD)
    else
        create_file_installed_without_repo  #1
        create_file_added_repos             #2
        create_file_installed_by_user       #3
        create_file_snaps                   #4
    fi
}


create_file_installed_without_repo() {
    local       header="Dit zijn gedownloade deb-bestanden geïnstalleerd via \
Software, of met een opdracht zoals 'sudo apt-get --install <bestand.deb>'."
    local       footer=''
    local   -i  number_of_lines=0
    local       plural='geïnstalleerde deb-bestanden'

    printf '%s\n' "$text1..."

    touch "$OUTPUTFILE_1" |& $LOGCMD

    printf '%b\n' "$header\n$DASHES" > "$OUTPUTFILE_1"

    apt-show-versions --initialize |& $LOGCMD
    if !    apt-show-versions                       \
            --brief                                 |
            grep    --word-regexp                   \
                    --regexp='No available version' |
            cut     --delimiter=':'                 \
                    --fields=1                      >> "$OUTPUTFILE_1"; then
        true
    fi

    number_of_lines=$(wc --lines < "$OUTPUTFILE_1")
    number_of_lines=$((number_of_lines - 2))
    if [[ $number_of_lines -eq 1 ]]; then
        plural='geïnstalleerd deb-bestand'
    fi
    footer="Dit bestand bevat $number_of_lines door de gebruiker $plural.
Meer via de opdracht: apt-cache show <bestand> | grep --regexp='Description:'"
    printf '%b\n' "$DASHES\n$footer" >> "$OUTPUTFILE_1"
}


create_file_added_repos() {
    local       header="Deze pakketbronnen zijn meestal toegevoegd met de \
opdracht 'sudo add-apt-repository ppa:<ppa-gebruiker>/<ppa-naam>'."
    local       footer=''
    local   -i  number_of_lines=0
    local       plural='pakketbronnen'

    printf '%s\n' "$text2..."

    touch "$OUTPUTFILE_2" |& $LOGCMD

    printf '%b\n' "$header\n$DASHES" > "$OUTPUTFILE_2"

    # shellcheck disable=SC2062,SC2022
    if !    grep    --recursive             \
                    --no-filename           \
                    --regexp='^deb '        \
                    /etc/apt/sources.list*  |
            grep    --invert-match          \
                    --regexp='ubuntu.com'   |
            sort    --unique                >> "$OUTPUTFILE_2"; then
        true
    fi

    number_of_lines=$(wc --lines < "$OUTPUTFILE_2")
    number_of_lines=$((number_of_lines - 2))
    if [[ $number_of_lines -eq 1 ]]; then
        plural='pakketbron'
    fi
    footer="Dit bestand bevat $number_of_lines door de gebruiker toegevoegde \
$plural."
    printf '%b\n' "$DASHES\n$footer" >> "$OUTPUTFILE_2"
}


create_file_installed_by_user() {
    local       header="Deze pakketten zijn meestal geïnstalleerd met \
Software of met de opdracht 'sudo apt install <pakketnaam>'."
    local       footer=''
    local   -i  number_of_lines=0
    local       plural='geïnstalleerde pakketten'

    printf '%s\n' "$text3..."

    touch "$OUTPUTFILE_3" |& $LOGCMD

    printf '%b\n' "$header\n$DASHES" > "$OUTPUTFILE_3"

    aptitude    search                              \
                '~i!~M!~E!~prequired!~pimportant'   |
    awk         '{print $2}'                        >> "$OUTPUTFILE_3"

    number_of_lines=$(wc --lines < "$OUTPUTFILE_3")
    number_of_lines=$((number_of_lines - 2))
    if [[ $number_of_lines -eq 1 ]]; then
        plural='geïnstalleerd pakket'
    fi
    footer="Dit bestand bevat $number_of_lines door de gebruiker $plural.
Meer info via de opdracht: apt-cache show <pakketnaam> | grep \
--regexp='Description:'"
    printf '%b\n' "$DASHES\n$footer" >> "$OUTPUTFILE_3"
}


create_file_snaps() {
    local       header="Deze snaps zijn geïnstalleerd met '[sudo] install \
SNAP' of met Software."
    local       footer=''
    local   -i  number_of_lines=0
    local       plural='snaps'

    printf '%s\n' "$text4..."

    touch "$OUTPUTFILE_4" |& $LOGCMD

    printf '%b\n' "$header\n$DASHES" > "$OUTPUTFILE_4"

    if ! snap list 2> /dev/null >> "$OUTPUTFILE_4"; then
        TEXT='snap is niet geïnstalleerd op dit systeem'
        printf '%s\n' "$TEXT" >> "$OUTPUTFILE_4"
    fi
    number_of_lines=$(wc --lines < "$OUTPUTFILE_4")
    number_of_lines=$((number_of_lines - 3))
    if [[ $number_of_lines -eq 1 ]]; then
        plural='snap'
    fi
    footer="Dit bestand bevat $number_of_lines $plural."
    printf '%b\n' "$DASHES\n$footer" >> "$OUTPUTFILE_4"
}


term_script() {
    info "
De bestanden zijn aangemaakt: ${OUTPUTFILE_0}_*
Deze bestanden kunnen gebruikt worden om de volledigheid van de
installatie, later door kz install, te controleren."
    exit $SUCCESS
}


###############################################################################
# Main line
###############################################################################

main() {
    init_script
    check_input "$@"
    process_input
    term_script
}


main "$@"


# EOF
