.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz mkusb.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\" Auteursrecht (c) 2019-2021 Karel Zimmer.
.\" Creative Commons Naamsvermelding-GelijkDelen Internationaal-licentie
.\" <https://creativecommons.org/licenses/by-sa/4.0/>.
.\"
.\" ReleaseNumber: 04.00.00
.\" DateOfRelease: 2021-08-08
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\"
.TH KZ_MKUSB 1 "Kz Handleiding" "KZ_MKUSB(1)" "Kz Handleiding"
.\"
.\"
.SH NAAM
kz mkusb \- USB-sticks maken.
.\"
.\"
.SH GEBRUIK
.B kz mkusb
[OPTIE...] [MAP] [--]
.\"
.\"
.SH BESCHRIJVING
\fBkz mkusb\fR maakt opstartbare USB-sticks.
.sp
Alle beeldbestanden (.iso) worden gelezen uit MAP, en per beeldbestand (.iso)
wordt er een opstartbare USB-stick aangemaakt (met \fBdd\fR).
.sp
De beeldbestanden worden verwacht in map ~/Downloads.
Met optie \fB--source\fR (\fB-s\fR) kan een andere locatie opgegeven worden.
.sp
De USB-sticks worden verwacht in map /dev/sdb.
Met optie \fB--target\fR (\fB-t\fR) kan een andere locatie opgegeven worden.
.sp
Nadat de USB-stick is gemaakt wordt deze gecontroleerd door deze te starten als
een (KVM) virtuele machine.
.sp
In een grafische werkomgeving zoals GNOME (e.g. Ubuntu) kan \fBkz mkusb\fR
worden gestart door te zoeken naar \fBusb\fR, klik op \fBUSB-sticks maken\fR.
.\"
.\"
.SH OPTIES
.TP
\fB-s\fR, \fB--source=\fIBRONMAP\fR
Gebruik beeldbestanden in de BRONMAP.
.TP
\fB-t\fR, \fB--target=\fIAPPARAAT\fR
Gebruik de opgegeven USB-stick-device.
.TP
\fB-d\fR, \fB--debug\fR
Geef foutopsporingsinformatie weer in het logboek (gebruik '[sudo] journalctl
-ab -t kz-mkusb').
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB--\fR
Een -- geeft het einde van de opties aan en schakelt de verdere verwerking van
opties uit.
.br
Alle argumenten na de -- worden behandeld als bestandsnamen en argumenten.
Een argument van - is gelijk aan --.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH MAPPEN
~/Downloads/
.RS
Als er geen \fIBRONMAP\fR is opgegeven worden de beeldbestanden (.iso) hier
verwacht.
.RE
.\"
.\"
.SH BESTANDEN
/dev/sdb/
.RS
Als er geen \fIAPPARAAT\fR is opgegeven wordt dit device gebruikt als
USB-stick.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH AUTEURSRECHT
Auteursrecht (c) 2014-2021 Karel Zimmer.
.br
GNU Algemene Publieke Licentie <https://www.gnu.org/licenses/gpl.html>.
.\"
.\"
.SH ZIE OOK
\fBkz_common.sh\fR(1),
\fBkz_dliso\fR(1),
\fBkz_spsum\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz mkusb\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
