.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" Man-pagina voor kz setup.
.\"
.\" Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" FIRST_RELEASED=2019
.\" 
.\" VERSION_NUMBER=06.00.01
.\" VERSION_DATE=2021-08-22
.\" 
.\"
.TH KZ_SETUP 1 "Kz Handleiding" "KZ_SETUP(1)" "Kz Handleiding"
.\"
.\"
.SH NAAM
kz setup \- Apps instellen.
.\"
.\"
.SH SAMENVATTING
.B kz setup
[OPTIE...] [--] [\fIAPP\fR...] [\fIBESTAND\fR...]
.\"
.\"
.SH BESCHRIJVING
\fBkz setup\fR stelt apps in en wijzigt gebruikersinstellingen.
.sp
De opdrachten die standaard meegeleverd worden bij \fBkz setup\fR zijn
idempotent; herhaaldelijk utvoeren leidt steeds tot hetzelfde resultaat.
.sp
Standaard wordt met \fBkz setup\fR de regels in het bestand\
 '/usr/bin/kz_setup_<distributie>_<versie>_\fIEDITIE\fR.sh' gekopieerd
naar een tijdelijk bestand.
.br
Het tijdelijk bestand wordt opgenomen in de lijst van te verwerken bestanden.
.br
Dit bestand bevat opdrachten voor het instellen van apps en het wijzigen van
gebruikersinstellingen voor de huidige distributie, versie, en \fIEDITIE\fR
(e.g. Ubuntu 20.04 desktop).
.sp
Als daarna ook bestand\
 '/usr/bin/kz_setup_<distributie>_<versie>_\fIEDITIE\fR_<computernaam>.sh'
aanwezig is worden de regels daarin voor computernaam toegevoegd aan het
eerder aangemaakte tijdelijk bestand.
.sp
Standaard wordt als \fIEDITIE\fR desktop gebruikt, met optie \fB--editie\fR is
dat aan te passen (e.g. \fIEDITIE\fR server).
.sp
Optie \fB--files\fR geeft een lijst van beschikbare instellingsbestanden voor
de huidige distributie, e.g. Ubuntu.
.br
Het is mogelijk om \fIBESTAND\fRen op te geven; deze bestanden dienen te
beginnen met '\fBsetup-\fR' en te eindigen met '\fB.sh\fR'.
.br
Iets anders wordt beschouwd als een app, zie hierna.
.sp
Voor de indeling van de instellingsbestanden zie sectie \fBBESTANDSINDELING\fR
hieronder.
.sp
Optie \fB--apps\fR geeft een lijst van apps die beschikbaar zijn voor de
huidige distributie en versie, e.g. Ubuntu 20.04.
.br
Het is mogelijk om \fIAPP\fRs op te geven.
.sp
Als \fIAPP\fRs zijn opgegeven worden de regels van deze app opgezocht in een
instellingsbestand en worden de regels gekopieerd naar een tijdelijk bestand.
.br
Het tijdelijke bestand wordt opgenomen in de lijst van te verwerken bestanden.
.sp
Het is mogelijk dat na het uitvoeren van \fBkz setup\fR er extra acties nodig
zijn.
Optie \fB--info\fR geeft dan aanvullende instructies weer.
.sp
Optie \fB--list\fR legt instellingen vast in map \fBkz_setup\fR in de
Persoonlijke map.
In deze map een 5-tal bestanden met gegevens over eerder gekozen
gebruikersfoto, bureaubladachtergrond, favorieten, en opdrachtgeschiedenis.
.br
Deze gevens zijn te gebruiken om het instellen te controleren op volledigheid.
.sp
Alhoewel \fBkz setup\fR gericht is op het instellen, met optie \fB--reset\fR
worden er instructies getoond om het instellen ongedaan te maken.
.sp
In een grafische werkomgeving zoals GNOME (e.g. Ubuntu) kan \fBkz setup\fR
worden gestart door te zoeken naar \fBapps\fR, klik op \fBApps instellen\fR.
.sp
Gebruik (eerst) \fBkz install\fR voor het installeren van apps en het aanpassen
van systeeminstellingen.
.\"
.\"
.SH BESTANDSINDELING
De te verwerken bestanden dienen te beginnen met '\fBkz_setup_\fR' en te
eindigen met '\fB.sh\fR'.
.sp
De regels worden verwerkt op de volgorde zoals deze in de bestanden voorkomen.
.br
De opdrachten standaard meegeleverd bij \fBkz setup\fR zijn zodanig opgesteld
dat bij herhaaldelijk uitvoeren het resultaat hetzelfde blijft; idempotentie.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels (eerste twee posities op een
regel) er zijn en hoe deze regels verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een voorbeeld van de \fBvolgorde\fR van deze regels in
een instellingsbestand.
Meer voorbeelden zijn te zien via de opdracht \fBkz setup --cat\fR.
.\"
.\"
.sp
.br
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regelsoort
T}:T{
Beschrijving
T}
.T&
l | l
l | l
l | l
l | l
l | l
l | l.
T{
#1 APP
T}:T{
Wordt gebruikt om regels te vinden voor APP.
T}
T{
#2 BESCHRIJVING
T}:T{
Bevat een BESCHRIJVING van de opdrachten.
T}
T{
#3 INSTRUCTIE
T}:T{
Bevat INSTRUCTIEs na het instellen van APP.
T}
T{
#4 INSTRUCTIE
T}:T{
Bevat INSTRUCTIEs voor het resetten van APP.
T}
T{
.sp
T}:T{
Wordt overgeslagen (is leeg).
T}
T{
#
T}:T{
Wordt overgeslagen (is commentaar).
T}
T{
*
T}:T{
Wordt als opdracht verwerkt (idempotent).
T}
.TE
.sp
.sp
.br
.B Tabel 2. Volgorde van regels in een instellingsbestand
.TS
box tab(:);
lb | lb.
T{
Regelsoort
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
# Software instellen
T}:T{
Commentaar.
T}
T{
.sp
T}:T{
Lege regel.
T}
T{
#1 google-chrome
T}:T{
Naam voor Google Chrome; voor argument APP.
T}
T{
#2 Google Chrome instellen
T}:T{
Beschrijving.
T}
T{
:
T}:T{
Opdracht.
T}
T{
#3 1. Start Google Chrome.
T}:T{
Instel-instructies; voor optie info.
T}
T{
#3 2. Controleer de werking.
T}:T{
    "           "
T}
T{
#4 1. Start Google Chrome.
T}:T{
Reset-instructies; voor optie reset.
T}
T{
#4 2. Verwijder de snelkoppeling.
T}:T{
    "           "
T}
.TE
.\"
.\"
.sp
.SH OPTIES
.TP
\fB-a\fR, \fB--apps\fR
Toon een lijst van in te stellen apps.
.TP
\fB-c\fR, \fB--cat\fR
Toon de inhoud van de (opgegeven) instellingsbestanden.
.br
Ieder bestand wordt voorafgegaan door een commentaarregel met de bestandsnaam.
.TP
\fB-e\fR, \fB--edition=\fIEDITIE\fR
Gebruik editie \fIEDITIE\fR.
.TP
\fB-f\fR, \fB--files\fR
Toon een lijst van beschikbare instellingsbestanden.
.TP
\fB-i\fR, \fB--info\fR
Toon aanvullende instructies na het instellen van apps.
.TP
\fB-l\fR, \fB--list\fR
Maak instellist aan.
.TP
\fB-r\fR, \fB--reset\fR
Toon instructies voor het resetten van apps.
.TP
\fB-s\fR, \fB--simulate\fR
Geen actie, maar simuleer het instellen, en toon de opdrachten die uitgevoerd
zouden worden.
.TP
\fB-d\fR, \fB--debug\fR
Geef foutopsporingsinformatie weer in het logboek (gebruik '[sudo] journalctl
-ab -t kz_setup').
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui = graphical user interface).
.TP
\fB-h\fR, \fB--help\fR
Toon een een korte omschrijving van de beschikbare opties.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB--\fR
Een -- geeft het einde van de opties aan en schakelt de verdere verwerking van
opties uit.
.br
Alle argumenten na de -- worden behandeld als bestandsnamen en argumenten.
Een argument van - is gelijk aan --.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde 1.
.br
Als er een waarschuwing optreedt, is de afsluitwaarde 2.
.\"
.\"
.SH BESTANDEN
/usr/bin/kz_setup_<distributie>_<versie>_\fIEDITIE\fR.sh
.RS
Standaard instellingsbestand als er geen \fIBESTAND\fRen zijn opgegeven,
\fIEDITIE\fR is standaard desktop.
.RE
.sp
/usr/bin/kz_setup_<distributie>_<versie>_\fIEDITIE\fR_<computernaam>.sh
.RS
Standaard instellingsbestand als er geen \fIBESTAND\fRen zijn opgegeven,\
 \fIEDITIE\fR is standaard
desktop.
.RE
.sp
/tmp/kz_setup_XXXXXXXXXX.cmds
.RS
Tijdelijk instellingsbestand.
.RE
.sp
/tmp/kz_setup_XXXXXXXXXX.text
.RS
Tijdelijk tekstbestand.
.RE
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl
.RE
.\"
.\"
.SH VOORBEELDEN
.sp
\fBkz setup\fR
.RS
Stel in alles wat in de standaard instellingsbestenden staat.
Hiervoor is ook starter 'Apps instellen' beschikbaar.
.RE
.sp
\fBkz setup google-chrome\fR
.RS
Stel in Google Chrome.
.RE
.sp
\fBkz setup google-chrome --info\fR
.RS
Toon aanvullende instructies na het instellen van Google Chrome.
Rechtsklik op starter 'Apps instellen' en kies 'Instal-instructies tonen'.
.RE
.sp
\fBkz setup google-chrome --reset\fR
.RS
Toon instructies voor het resetten van Google Chrome.
Rechtsklik op starter 'Apps instellen' en kies 'Reset-instructies tonen'.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz_common.sh\fR(1),
\fBkz_install\fR(1),
\fBkz_menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz setup\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar vanaf Karel Zimmer Linux Scripts
<https://karelzimmer.nl/html/linux.html#scripts>.
.sp
.\" EOF
