.\"############################################################################
.\"# Man-pagina voor kz-build.
.\"#
.\"# Written in 2021 by Karel Zimmer <info@karelzimmer.nl>, Creative Commons
.\"# Public Domain Dedication
.\"# <https://creativecommons.org/publicdomain/zero/1.0>.
.\"############################################################################
.\"
.TH KZ-BUILD 1 "Handleiding kz" "kz 365" "Handleiding kz"
.\"
.\"
.SH NAAM
kz-build \- Pakket kz bouwen.
.\"
.\"
.SH SAMENVATTING
.B kz build
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz build\fR bouwt het pakket kz én de website https://karelzimmer.nl.
.sp
Het gebouwde pakket kz wordt vervolgens lokaal geïnstalleerd.
.sp
Dit om het pakket, de website, en de installatie te kunnen ontwikkelen, testen,
en later te distribueren met \fBkz deploy\fR.
.sp
Als invoer worden de lokale Git-repositories kz-docs en kz-scripts gebruikt.
Van tekstbestanden worden pdf-bestanden gemaakt met 'lowriter convert-to pdf'.
.sp
Met opdracht \fBkz deploy\fR kan de website (inclusief pakket kz) geplaatst
worden op het internet zodat de scripts en documenten beschikbaar zijn voor
algemeen gebruik.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH MAPPEN
~/kz-deb/app/
.RS
Basis-bestanden pakket kz (Git).
.RE
.sp
~/kz-deb/dist/
.RS
Distributie-bestanden pakket kz.
.RE
.sp
~/kz-docs/
.RS
Checklists (Git).
.RE
.sp
~/kz-scripts/
.RS
Scripts (Git).
.br
Inclusief man-pagina's (usr/share/man/man1/ en usr/share/man/nl/man1/),
.br
Tabvoltooiingsscript (usr/share/bash-completion/completions/),
.br
Bureaubladconfiguratiebestand (usr/share/applications/), en
.br
PolicyKit actiedefinitiebestanden (usr/share/policypolkit-1/actions/).
.RE
.sp
~/kz-uploads/app/
.RS
Basis-bestanden website karelzimmer.nl (Git).
.RE
.sp
~/kz-uploads/dist/
.RS
Distributie-bestanden website karelzimmer.nl.
.RE
.\"
.\"
.SH BESTANDEN
~/kz-uploads/dist/downloads/kz/kz_365_all.deb
.RS
Debian-pakket kz.
.RE
.\"
.\"
.SH NOTITIES
.IP " 1." 4
CI/CD en Day 1 Operations
.RS 4
\fBkz build\fR wordt voornamelijk gebruikt voor \fBCI/CD\fR en
\fBDay 1 Operations\fR. Zie \fBkz\fR(1) voor een uitleg.
.RE
.\"
.\"
.SH AUTEUR
Geschreven in 2021 door Karel Zimmer <info@karelzimmer.nl>, Creative Commons
Publiek Domein Verklaring <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-ckname\fR(1),
\fBkz-deploy\fR(1),
\fBkz-ivp\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz build\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar op de website van Karel Zimmer
.br
<https://karelzimmer.nl/html/nl/linux.html#scripts>.
