.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-backup (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-BACKUP" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-backup - maak een back-up (reservekopie) van de Persoonlijke map

.SH SAMENVATTING
.SY kz\ backup
[<opties>]
.YS

.SH BESCHRIJVING
\fBkz backup\fR maakt een back-up (reservekopie) van de Persoonlijke map.
.sp
In een desktopomgeving kan opdracht \fBkz backup\fR worden uitgevoerd door te
zoeken naar \fBback\fR, klik op \fBKZ Back-up Persoonlijke map\fR-pictogram.
.sp
Voordat er een back-up wordt gemaakt worden, indien mogelijk, ingestelde
bureaubladachtergrond, gebruikersfoto, favorieten en WiFi informatie
opgeslagen. Zie de sectie \fBBESTANDEN\fR hieronder voor de preciese lokatie.
.sp
De back-up wordt geplaatst op een aangekoppeld usb-medium zoals een usb
externe harddisk in map \fBBACKUP-<gebruikersnaam>@<computernaam>\fR, deze map
wordt aangemaakt als nodig, bijvoorbeeld
/media/karel/backupdisk/BACKUP-karel@pc-van-karel voor Karel op pc-van-karel.
.sp
Met optie \fB-g\fR, \fB--gui\fR wordt \fBkz backup\fR in grafische modus
uitgevoerd. Een desktopomgeving is vereist.
.sp
Met optie \fB-t\fR, \fB--target\fR \fI<map>\fR kan een andere locatie opgegeven
worden. Bijvoorbeeld /media/karel/usbstick in plaats van
/media/karel/backupdisk.
.sp
Locaties die genegeerd worden door \fBkz backup\fR zijn de door Git beheerde
mappen ("git-managed").
Voorbeeld: ~/kz-scripts wordt overgeslagen vanwege de aanwezigheid van
~/kz-scripts/.git.
.sp
Voor het maken van de back-up wordt rsync gebruikt.
.br
Bestanden die verwijderd zijn uit de Persoonlijke map worden ook verwijderd uit
de back-up (rsync's optie --delete wordt gebruikt).
.sp
Als er fouten worden gevonden, wordt een overzicht van de foutmeldingen
gegeven.
.sp
Met opdracht \fBkz restore\fR is de Persoonlijke map te herstellen.

.SH OPTIES
Verplichte argumenten voor lange opties zijn ook verplicht voor korte opties.
.TP
\fB-g\fR, \fB--gui\fR
Draai in grafische modus (gui=graphical user interface; grafische
gebruikersinterface). Een desktopomgeving is vereist.
.TP
\fB-t\fR, \fB--target \fI<map>\fR
Plaats de back-up in de opgegeven map.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-m\fR, \fB--manual\fR
Toon de handleidingpagina.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur en het auteursrecht.

.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.

.SH BESTANDEN
~/Instellingen/apps.txt
.RS
Lijst van geïnstalleerde apps. Ter controle van de installatie.
.RE
.sp
~/Instellingen/avatar.ico
.RS
Back-up van de avatar, indien beschikbaar.
.RE
.sp
~/Instellingen/avatar.txt
.RS
Instructies voor het terugzetten van de avatar, indien beschikbaar.
.RE
.sp
~/Instellingen.ico
.RS
Back-up van bureaubladachtergrond, indien beschikbaar.
.RE
.sp
~/Instellingen/desktop.txt
.RS
Instructies voor het terugzetten van bureaubladachtergrond.
.RE
.sp
~/Instellingen/favs.txt
.RS
Ingestelde favorieten in de favorietenbalk (dash/dock). Ter controle van de
instellingen.
.RE
.sp
~/Instellingen/users.txt
.RS
Instructies voor het toevoegen van extra gebruikers.
.RE
.sp
~/Instellingen/wifi.txt
.RS
Opgeslagen Wifi-informatie.
.RE
.sp
/tmp/kz-backup-XXXXXXXXXX.exclude
.RS
Uitsluitenbestand, bijvoorbeeld kz-backup-4VkzCfrDsU.exclude.
.RE
.sp
/tmp/kz-backup-XXXXXXXXXX-error.log
.RS
Foutlogbestand, e.g. kz-backup-4VkzCfrDsU-error.log.
.RE

.SH VOORBEELDEN
.EX
.sp
\fBkz backup\fR
.RS
Maak een back-up (reservekopie) van de Persoonlijke map. Hiervoor is in een
desktopomgeving ook starter \fBKZ Back-up maken\fR beschikbaar.
.RE
.sp
\fBkz backup --target /media/karel/usbstick\fR
.RS
Maak een back-up van de Persoonlijke map van Karel op pc-van-karel naar
/media/karel/usbstick in de map karel@pc-van-karel (deze map wordt aangemaakt
als nodig).
.RE
.EE

.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1),
\fBkz-restore\fR(1)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.

.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
.UR https://karelzimmer.nl/nl
.UE
.RE
.IP " 2." 4
Day 2 Operations
.RS 4
\fBkz backup\fR wordt voornamelijk gebruikt voor Day 2 Operations. Zie
\fBkz\fR(1) voor een uitleg.
.RE
