.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-build (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-BUILD" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-build - bouw website en kz-pakketten

.SH SAMENVATTING
.SY kz\ build
[<opties>]
.YS

.SH BESCHRIJVING
\fBkz build\fR bouwt de website karelzimmer.nl én het Debian- en RPM-pakket kz.
.sp
Het gebouwde Debian-pakket kz wordt vervolgens lokaal geïnstalleerd.
.sp
Met optie \fB-d\fR, \fB--dev\fR wordt de ontwikkelingsversie van het kz-pakket
gebouwd.
.sp
Als de ontwikkelingsrepositories niet op main staan of niet schoon zijn, wordt
er ook een ontwikkelingsversie gemaakt (kz-dev-....).
.sp
Dit om het pakket, de website en de installatie te kunnen ontwikkelen, testen,
en later te distribueren met \fBkz deploy\fR.
.sp
Als invoer worden de lokale Git-repositories kz-docs en kz-scripts gebruikt.
Van tekstbestanden worden pdf-bestanden gemaakt met 'lowriter convert-to pdf'.
.sp
Met opdracht \fBkz deploy\fR kan de website en de kz-pakketten geplaatst
worden op het internet zodat de scripts en documenten beschikbaar zijn voor
algemeen gebruik.
.sp
Opdracht \fBkz build\fR kan alleen worden uitgevoerd op een desktop.

.SH OPTIES
.TP
\fB-d\fR, \fB--dev\fR
Bouw de ontwikkelingsversie van pakket kz.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-m\fR, \fB--manual\fR
Toon de handleidingpagina.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur en het auteursrecht.

.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.

.SH BESTANDEN
~/kz-deb/src/*
.RS
Bronbestanden Debian-pakket kz (Git).
.RE
.sp
~/kz-deb/dist/*
.RS
Distributie-bestanden Debian-pakket kz.
.RE
.sp
~/kz-rpm/src/*
.RS
Bronbestanden RPM-pakket kz (Git).
.RE
.sp
~/kz-rpm/dist/*
.RS
Distributie-bestanden RPM-pakket kz.
.RE
.sp
~/kz-docs/*
.RS
Checklists (Git).
.RE
.sp
~/kz-scripts/*
.RS
Scripts (Git).
.br
Bevat bijvoorbeeld vertaalbestanden, handleidingen en
Polkit-actiedefinitiebestanden.
.RE
.sp
~/kz-uploads/src/*
.RS
Bronbestanden website karelzimmer.nl (Git).
.RE
.sp
~/kz-uploads/dist/*
.RS
Distributie-bestanden website karelzimmer.nl.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz_4.2.1-1_all.deb
.RS
Debian-pakket kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-dev_4.2.1-1_all.deb
.RS
Debian-ontwikkelpakket kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-4.2.1-1.noarch.rpm
.RS
RPM-pakket kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-dev-4.2.1-1.noarch.rpm
.RS
RPM-ontwikkelpakket kz.
.RE
.sp
/usr/share/doc/kz/build.id
.RS
Build-id bestand.
.RE

.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-check\fR(1),
\fBkz-deploy\fR(1)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.

.SH NOTITIES
.IP " 1." 4
CI/CD en Day 1 Operations
.RS 4
\fBkz build\fR wordt voornamelijk gebruikt voor \fBCI/CD\fR en
\fBDay 1 Operations\fR. Zie \fBkz\fR(1) voor een uitleg.
.RE
