.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-check (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-CHECK" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-check - controleer scripts en website

.SH SAMENVATTINGmsg
.SY kz\ check
[<opties>]
.YS

.SH BESCHRIJVING
\fBkz check\fR voert een controle uit.
.sp
Voert controles uit waarbij scripts inhoudelijk en met shellcheck, mypy, en
pycodestyle worden gecontroleerd en de website op inhoud en dode links.
.sp
Gecontroleerd wordt onder andere:
.br
vertaling   - Gettext bestanden zoals .pot, .po en .mo
.br
tags        - TODO/FIXME/BUG-tags
.br
regels      - aantal regels en regellengte
.br
velden      - zoals vrijgavejaar
.br
spaties     - eindspaties
.br
shellcheck  - shellscript analyse tool
.br
mypy        - Python-script analyse tool
.br
pycodestyle - Python-script stijlcontroleur
.sp
Opdracht \fBkz check\fR wordt ook aangeroepen vanuit \fBkz deploy\fR.
.sp
Opdracht \fBkz check\fR kan alleen worden uitgevoerd op een desktop.

.SH OPTIES
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-m\fR, \fB--manual\fR
Toon de handleidingpagina.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur en het auteursrecht.

.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.

.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-build\fR(1),
\fBkz-deploy\fR(1)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.

.SH NOTITIES
.IP " 1." 4
Day 1 Operations en CI/CD
.RS 4
\fBkz check\fR wordt voornamelijk gebruikt voor \fBDay 1 Operations\fR en
\fBCI/CD\fR. Zie \fBkz\fR(1) voor een uitleg.
.RE
