.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-dev (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-DEV" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-dev - ontwikkelomgeving bouwen

.SH SAMENVATTING
.SY kz\ dev
[<opties>]
.YS

.SH BESCHRIJVING
\fBkz dev\fR downloadt de website karelzimmer.nl en bouwt de ontwikkelomgeving
voor het Debian- en RPM-pakket kz.
.sp
Dit om het pakket en de website te kunnen ontwikkelen, testen en later te
distribueren met \fBkz deploy\fR.
.sp
Als invoer worden diverse remote Git-repositories gebruikt.
.sp
Met opdracht \fBkz build\fR kan het pakket kz en de website gebouwd worden.
.br
Met opdracht \fBkz deploy\fR kan het pakket kz en de website geplaatst worden
op het internet.
.sp
Opdracht \fBkz dev\fR kan alleen worden uitgevoerd op een desktopomgeving.

.SH OPTIES
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-m\fR, \fB--manual\fR
Toon de handleidingpagina.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur en het auteursrecht.

.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.

.SH BESTANDEN
~/kz-deb/src/*
.RS
Bronbestanden pakket kz (Git).
.RE
.sp
~/kz-deb/dist/*
.RS
Distributie-bestanden pakket kz.
.RE
.sp
~/kz-docs/*
.RS
Checklists (Git).
.RE
.sp
~/kz-scripts/*
.RS
Scripts (Git).
.br
Inclusief man-pagina's (usr/share/man/),
.br
Tabvoltooiingsscripts (usr/share/bash-completion/completions/),
.br
Bureaubladconfiguratiebestanden (usr/share/applications/) en
.br
Polkit actiedefinitiebestanden (usr/share/policypolkit-1/actions/).
.RE
.sp
~/kz-uploads/src/*
.RS
Bronbestanden website karelzimmer.nl (Git).
.RE
.sp
~/kz-uploads/dist/*
.RS
Distributie-bestanden website karelzimmer.nl.
.RE
.sp
~/bin/gitclone
.RS
Git clone van alle publieke remote repo's in de Persoonlijke map.
.RE
.sp
~/bin/gitpull
.RS
Git pull van alle lokale branches in de Persoonlijke map.
.RE
.sp
~/bin/gitstatus
.RS
Git-status van alle lokale branches in de Persoonlijke map.
.RE
.sp
~/kz-uploads/dist/assets/packages/-1_all.deb
.RS
Debian-pakket kz.
.RE

.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-build\fR(1),
\fBkz-deploy\fR(1),
\fBkz-get\fR(1),
\fBkz-install\fR(1),
\fBkz-setup\fR(1)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.

.SH NOTITIES
.IP " 1." 4
CI/CD en Day 0 Operations
.RS 4
\fBkz dev\fR wordt voornamelijk gebruikt voor \fBCI/CD\fR en
\fBDay 0 Operations\fR. Zie \fBkz\fR(1) voor een uitleg.
.RE
