.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-get (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ_GET" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-get - download en installeer Debian- of RPM-pakket kz

.SH SAMENVATTING
.SY kz\ get
[<opties>]
.YS
.SY wget\ karelzimmer.nl/getkz;\ bash\ getkz
.YS

.SH BESCHRIJVING
\fBkz get\fR downloadt en installeert Debian- of RPM-pakket kz.
.sp
Met optie \fB-d\fR, \fB--dev\fR wordt de ontwikkelingsversie van het kz-pakket
verwerkt.
.sp
Debian-pakket kz bevat scripts om Debian en Debian-gebaseerde systemen zoals
Ubuntu soepel en bruikbaar te installeren.
.sp
RPM-pakket kz bevat scripts om Red Hat en Red Hat-gebaseerde systemen zoals
Rocky Linux soepel en bruikbaar te installeren en te beheren.
.sp
Voor de nieuwste versie van \fBkz get\fR én pakket kz, start een
Terminalvenster en voer uit (kopie van getkz wordt opgeslagen en later
verwijderd):
.br
    \fBwget karelzimmer.nl/getkz\fR
.br
    \fBbash getkz\fR
.br
 of (idem hiervoor, nu op 1 regel):
.br
    \fBwget karelzimmer.nl/getkz; bash getkz\fR
.br
 of (er wordt geen kopie van getkz opgeslagen):
.br
    \fBwget -O- karelzimmer.nl/getkz | bash\fR
.br
 of (als curl is geïnstalleerd, geen kopie):
.br
    \fBcurl -L karelzimmer.nl/getkz | bash\fR
.br
 of (als pakket kz al is geïnstalleerd):
.br
    \fBkz get\fR
.sp
Als om één of andere reden het installeren mislukt, op een Debian-gebaseerd
systeem kunt u het volgende proberen:
    sudo dpkg --configure --pending
    sudo apt-get update --fix-missing
    sudo apt-get install --fix-broken
.br
Op een Red Hat-gebaseerd systeem probeer het volgende:
    sudo dnf clean all
    sudo dnf makecache
.sp
Met opdracht \fBkz dev\fR kan de ontwikkelomgeving ingesteld worden op de
locale computer zodat het pakket en de website ontwikkeld en getest kan worden.

.SH OPTIES
.TP
\fB-d\fR, \fB--dev\fR
Download en installeer de ontwikkelingsversie van het kz-pakket.

.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.

.SH BESTANDEN
/tmp/kz-get-XXXXXXXXXX.deb
.RS
Gedownload debian-bestand, bijvoorbeeld kz-get-AEOzIjJyie.deb.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz_4.2.1-1_all.deb
.RS
Debian-pakket kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-dev_4.2.1-1_all.deb
.RS
Debian-ontwikkelpakket kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-4.2.1-1.noarch.rpm
.RS
RPM-pakket kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-dev-4.2.1-1.noarch.rpm
.RS
RPM-ontwikkelpakket kz.
.RE

.SH ZIE OOK
\fBkz\fR(1),
\fBkz-dev\fR(1)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.

.SH NOTITIES
.IP " 1." 4
IaC en Day 1 Operations
.RS 4
\fBkz get\fR wordt voornamelijk gebruikt voor \fBIaC\fR en
\fBDay 1 Operations\fR. Zie \fBkz\fR(1) voor een uitleg.
.RE
