.\"############################################################################
.\"# SPDX-FileComment: Man page for kz-install-cmd (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ-INSTALL-CMD" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-install-cmd - kz-install opdracht uitvoeren en uitvoer vastleggen

.SH SAMENVATTING
.nf
.B pkexec /usr/bin/kz-install-cmd <opdracht>
.YS

.SH BESCHRIJVING
\fBkz-install-cmd\fR Voert de opdracht uit die als argument aan de aanroep is
meegegeven en registreert de uitvoer in het logboek.
.sp
Hierbij wordt PolicyKit (polkit) profiel
/usr/share/polkit-1/actions/nl.karelzimmer.kz-install.policy gebruikt.

.SH ZIE OOK
\fBkz-install\fR(1)
