.\"############################################################################
.\"# SPDX-FileComment: Man page for kz-install-cmd (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ-INSTALL-CMD" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-install-cmd - voer de kz-install pdracht uit (wrapperscript)

.SH SAMENVATTING
.nf
.B pkexec /usr/bin/kz-install-cmd <opdracht>
.YS

.SH BESCHRIJVING
Wanneer aangeroepen door \fBkz-install\fR, voert \fBkz-install-cmd\fR de
opdracht uit die als argument aan de aanroep is doorgegeven.

.SH ZIE OOK
\fBkz-install\fR(1),
\fBkz\fR(1)

