.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-install (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-INSTALL" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-install - apps installeren

.SH SAMENVATTING
.SY kz\ install
[<opties>] [--] [\fI<app>\fR...]
.YS

.SH BESCHRIJVING
\fBkz install\fR installeert apps en wijzigt systeeminstellingen.
.sp
In een desktopomgeving kan opdracht \fBkz install\fR worden uitgevoerd door te
zoeken naar \fBapps\fR, klik op \fBApps installeren\fR-pictogram.
.sp
Installeer eerst Linux, \fBkz install\fR is een post-installatie-script.
.sp
Gebruik \fBkz setup\fR (na \fBkz install\fR) voor het instellen van apps en het
wijzigen van gebruikersinstellingen.
.sp
\fBkz install\fR verwerkt installatiebestanden die opdrachten bevat voor het
installeren van apps en het wijzigen van systeeminstellingen.
.sp
Standaard verwerkt \fBkz install\fR de installatiebestanden
/usr/bin/kz-install.sh en /usr/bin/kz-install.sh.gpg, dat opdrachten bevat voor
alle hierin opgenomen computers.
.br
Opdrachten met persoonlijke informatie zoals een gebruikersnaam zijn opgenomen
in versleuteld installatiebestand /usr/bin/kz-install.sh.gpg.
Dit bestand wordt ontsleuteld voordat de opdrachten worden gebruikt.
.sp
De opdrachten meegeleverd bij \fBkz install\fR zijn zodanig opgesteld dat bij
herhaaldelijk uitvoeren het resultaat hetzelfde blijft (idempotent).
.sp
Bij het verwerken van de installatiebestanden worden de opdrachten voor iedere
en de huidige computer geselecteerd en gekopieerd naar het opdrachtbestand.
.br
De opdrachten in het opdrachtbestand worden uitgevoerd.
.br
Na succesvolle voltooiing wordt de computer opnieuw opgestart.
.sp
Als er fouten zijn geconstateerd wordt een overzicht gegeven van deze
meldingen.
.sp
Voor de indeling van de installatiebestanden zie \fBman kz-install.sh\fR en
\fBman kz-install.sh.gpg\fR.
.sp
Voor instructies over het toevoegen van extra gebruikers, zie de sectie
\fBBESTANDEN\fR hieronder.
.sp
Optie \fB-a\fR, \fB--apps\fR geeft een lijst van alle apps die beschikbaar zijn
in het installatiebestand.
.sp
Naar keuze kunnen te verwerken apps opgegeven worden met argument \fI<app>\fR.
.br
Per opgegeven app worden de opdrachten geselecteerd uit het installatiebestand
en gekopieerd naar het opdrachtbestand.
.sp
Met optie \fB-b\fR, \fB--browse\fR kan gebladerd worden door de
installatiebestanden.
.sp
Optie \fB-c\fR, \fB--cat\fR geeft de inhoud van het opdrachtbestand.
.sp
Met optie \fB-f\fR, \fB--file\fR \fI<bestand>\fR kan een ander
installatiebestand opgegeven worden. Deze optie kan herhaaldelijk gebruikt
worden.
.sp
Met optie \fB-g\fR, \fB--gui\fR wordt \fBkz install\fR in grafische modus
uitgevoerd. Een desktopomgeving is vereist.
.sp
Met optie \fB-r\fR, \fB--remove\fR kan de installatie ongedaan worden gemaakt.
.sp
Om een app te verwijderen, op een Debian systeem gebruik:
    sudo apt-get remove --purge --assume-yes <app>
.br
Op een Red Hat systeem gebruik:
   sudo dnf remove --assumeyes <app>
.sp
Als om één of andere reden het installeren van apps mislukt, op een
Debian systeem kunt u het volgende proberen:
    sudo dpkg --configure --pending
    sudo apt-get update --fix-missing
    sudo apt-get install --fix-broken
.br
Op een Red Hat systeem probeer het volgende:
    sudo dnf clean all
    sudo dnf makecache

.SH OPTIES
Verplichte argumenten voor lange opties zijn ook verplicht voor korte opties.
.TP
\fB-a\fR, \fB--apps\fR
Toon een lijst van te installeren apps.
.TP
\fB-b\fR, \fB--browse\fR
Blader door het installatiebestand.
.TP
\fB-c\fR, \fB--cat\fR
Toon de inhoud van het opdrachtbestand.
.TP
\fB-f\fR, \fB--file\fR \fI<bestand>\fR
Verwerk de opgegeven bestand. Deze optie kan herhaaldelijk gebruikt worden.
.TP
\fB-g\fR, \fB--gui\fR
Draai in grafische modus (gui=graphical user interface; grafische
gebruikersinterface). Een desktopomgeving is vereist.
.TP
\fB-r\fR, \fB--remove\fR
Verwijder de apps.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-m\fR, \fB--manual\fR
Toon de handleidingpagina.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur en het auteursrecht.

.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.

.SH BESTANDEN
/usr/bin/kz-install.sh
.RS
Installatiebestand.
.RE
.sp
/usr/bin/kz-install.sh.gpg
.RS
Versleuteld installatiebestand.
.RE
.sp
/usr/share/kz/kz-public-key.gpg
.RS
OpenPGP publieke sleutel voor pakket kz. Nodig om kz-install.sh.gpg te
ontsleutelen.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX-decryptd.sh.gpg
.RS
Onsleuteld bestand met aanvullende opdrachten die worden toegevoegd aan het
opdrachtbestand, bijvoorbeeld kz-install-SkQLswclj3-decryptd.sh.gpg.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX-commands.sh.
.RS
Opdrachtbestand, bijvoorbeeld kz-install-SYpGEKVWZI-commands.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX-error.log
.RS
Foutlogbestand, e.g. kz-install-agr1ZErXoI-error.log.
.RE
sp
~/Instellingen/users.txt
.RS
Instructies voor het toevoegen van extra gebruikers.
.RE

.SH VOORBEELDEN
.EX
.sp
\fBkz install\fR
.RS
Installeer alles wat in het standaard installatiebestand staat. Hiervoor is in
een desktopomgeving ook starter \fBApps installeren\fR beschikbaar.
.RE
.sp
\fBkz install google-chrome\fR
.RS
Installeer Google Chrome.
.RE
.sp
\fBkz install --remove google-chrome\fR
.RS
Verwijder Google Chrome..RE
.RE
.sp
\fBkz install --cat google-chrome\fR
.RS
Toon installatie-opdrachten voor Google Chrome.
.RE
.sp
\fBkz install --cat --remove google-chrome\fR
.RS
Toon verwijder-opdrachten voor Google Chrome.
.RE

.SH ZIE OOK
\fBkz_common.sh\fR(1),
\fBkz-install-pkexec\fR(1),
\fBkz-menu\fR(1),
\fBkz-setup\fR(1),
\fBkz-update\fR(1),
\fBkz\fR(1),
\fBkz-install.sh\fR(5),
\fBkz-install.sh.gpg\fR(5)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.

.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
.UR https://karelzimmer.nl/nl
.UE
.RE
.IP " 2." 4
~/Instellingen/apps.txt
.RS 4
In bestand apps staan namen van eerder geïnstalleerde pakketten. Dit bestand is
te gebruiken om de installatie te controleren op volledigheid.
.RE
.IP " 3." 4
IaC en Day 1 Operations
.RS 4
\fBkz install\fR wordt voornamelijk gebruikt voor \fBIaC\fR en
\fBDay 1 Operations\fR. Zie \fBkz\fR(1) voor een uitleg.
.RE
