.\"############################################################################
.\"# SPDX-FileComment: Man page for kz-install-pkexec (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ-INSTALL-PKEXEC" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-install-pkexec - wrapper-script voor kz-install

.SH SAMENVATTING
.nf
.B pkexec /usr/bin/kz-install-pkexec <opdracht>
.YS

.SH BESCHRIJVING
Wanneer aangeroepen vanuit \fBkz-install\fR, voert \fBkz-install-pkexec\fR de
opdracht uit waarvoor root-rechten nodig zijn.

.SH ZIE OOK
\fBkz-install\fR(1),
\fBpkexec\fR(1),
\fBpolkit\fR(8)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.
