.\"############################################################################
.\"# SPDX-FileComment: Man page for kz-install
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################
.\"
.TH "KZ-INSTALL" "1" "Handleiding kz" "kz 4.2.1" "Handleiding kz"
.\"
.\"
.SH NAAM
kz-install \- Apps installeren.
.\"
.\"
.SH SAMENVATTING
.B kz install
[OPTIE...] [\fIAPP\fR...]
.\"
.\"
.SH BESCHRIJVING
\fBkz install\fR installeert apps en wijzigt systeeminstellingen.
.sp
In een grafische werkomgeving kan opdracht \fBkz install\fR worden uitgevoerd
door te zoeken naar \fBapps\fR, klik op \fBApps installeren\fR.
.sp
Gebruik \fBkz setup\fR (na \fBkz install\fR) voor het instellen van apps en het
wijzigen van gebruikersinstellingen.
.sp
\fBkz install\fR verwerkt een invoerbestand ("installatiebestand") die
opdrachten bevat voor het installeren van apps en het wijzigen van
systeeminstellingen.
.sp
Voor de indeling van het invoerbestand zie het deel \fBBESTANDSINDELING\fR
hieronder.
.sp
Standaard verwerkt \fBkz install\fR het invoerbestand
/usr/bin/kz-install-<distributie>-<editie>.sh, bijvoorbeeld
kz-install-ubuntu-desktop.sh.
.br
De <distributie> en <editie> (desktop of server) worden ingevuld met de waarden
van de huidige computer.
.sp
Dit invoerbestand bevat installatie-opdrachten voor alle hierin opgenomen
computers voor Ubuntu desktop.
.br
Bij het verwerken van het invoerbestand worden de opdrachten voor iedere en de
huidige computer geselecteerd en gekopieerd naar het opdrachtbestand.
.sp
Optie \fB-a\fR, \fB--apps\fR geeft een lijst van apps die beschikbaar zijn in
het invoerbestand.
.sp
Het is mogelijk om \fIAPP\fRs op te geven. Per opgegeven \fIAPP\fR worden de
opdrachten geselecteerd uit het invoerbestand en gekopieerd naar het
opdrachtbestand.
.sp
De opdrachten in het opdrachtbestand worden uitgevoerd.
Na succesvolle voltooiing wordt de computer opnieuw opgestart.
.sp
Optie \fB-c\fR, \fB--cat\fR geeft de inhoud van het opdrachtbestand.
.sp
Met optie \fB-r\fR, \fB--remove\fR kan de installatie ongedaan worden gemaakt,
de modus wijzigt dan van Install naar Remove.
.sp
De optie \fB-l\fR, \fB--list\fR geeft een lijst met installatiebestanden weer.
.sp
Met optie \fB-f\fR, \fB--file\fR \fIFILE\fR kan een ander invoerbestand
opgegeven worden, de bestandsnaam moet beginnen met \fBkz-install-\fR en
eindigen met \fB.sh\fR.
.sp
Een -- signaleert het einde van opties en schakelt verdere verwerking van
opties uit.
.\"
.\"
.SH BESTANDSINDELING
De naamgeving van de meegeleverde invoerbestanden is
kz-install-<distribution>-<edition>.sh, voor een door de gebruiker
aangeleverd invoerbestand is het kz-install-*.sh.
.br
De regels worden verwerkt op de volgorde zoals deze in de bestanden voorkomen.
.sp
De opdrachten meegeleverd bij \fBkz install\fR zijn zodanig opgesteld dat bij
herhaaldelijk uitvoeren het resultaat hetzelfde blijft (idempotent).
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels er zijn en hoe deze regels
verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een \fBvoorbeeld\fR van deze regels in
voorbeeldbestand kz-install-ubuntu-desktop.sh voor computer pc02.
Meer voorbeelden zijn te zien met de opdracht \fBkz install --cat\fR.
.sp
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
l | l
l | l
l | l
l | l
l | l.
T{
T}:T{
Lege regel
T}
T{
# Install APP <appnaam> HOST <computernaam>...
T}:T{
De applicatie <appnaam> installeren op computer <computernaam>
T}
T{
# Remove APP <appnaam> HOST <computernaam>...
T}:T{
De applicatie <appnaam> verwijderen van computer <computernaam> (optie remove)
T}
T{
#...
T}:T{
Commentaarregel
T}
T{
Opdracht
T}:T{
Installatie/Verwijder-opdracht
T}
.TE
.sp
.sp
Bij het gebruik van optie \fB-a\fR, \fB--apps\fR wordt er alleen geselecteerd
op <appnaam>, en niet op niet op <computernaam>.
.sp
.B Tabel 2. Regels in voorbeeldbestand kz-install-ubuntu-desktop.sh
.TS
box tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
# Install APP gnome-gmail HOST *
T}:T{
Installeer de gnome-gmail op iedere computer, zie [1]
T}
T{
sudo apt-get install --yes gnome-gmail
T}:T{
T}
T{
T}:T{
T}
T{
# Remove APP gnome-gmail HOST *
T}:T{
Verwijder de gnome-gmail van iedere computer, zie [1]
T}
T{
sudo apt-get remove --yes gnome-gmail
T}:T{
T}
T{
T}:T{
T}
T{
# Install APP ufw HOST pc02
T}:T{
Installeer ufw alleen op pc02, zie [2]
T}
T{
sudo apt-get install --yes gufw
T}:T{
T}
T{
T}:T{
T}
T{
# Install APP kvm HOST pc01 pc02
T}:T{
Installeer kvm op pc01 en pc02, zie [3]
T}
T{
sudo apt-get install --yes qemu-kvm
T}:T{
T}
T{
T}:T{
T}
T{
# Install APP google-earth HOST
T}:T{
Standaard niet google-earth installeren, zie [4]
T}
T{
sudo apt-get install --yes google-earth
T}:T{
T}
.TE
.sp
.sp
[1]
.br
De regel met '*' zorgt ervoor dat de bijbehorende opdrachten op alle computers
worden uitgevoerd.
.sp
[2]
.br
De regel met 'pc02' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc02 worden uitgevoerd.
.br
De APP kan alsnog worden geïnstalleerd op een andere computer met de opdracht \
'kz install gnome'.
.sp
[3]
.br
De regel met 'pc01 pc02' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc01 en pc02 worden uitgevoerd.
.br
De APP kan alsnog worden geïnstalleerd op een andere computer met de opdracht \
'kz install kvm'.
.sp
[4]
.br
De regel zonder computernaam achter HOST zorgt ervoor dat de bijbehorende
opdrachten standaard niet worden uitgevoerd.
.br
De APP kan alsnog worden geïnstalleerd met de opdracht 'kz install google-eart\
h'.
.\"
.\"
.sp
.SH OPTIES
Verplichte argumenten voor lange opties zijn ook verplicht voor korte opties.
.TP
\fB-a\fR, \fB--apps\fR
Toon een lijst van te installeren apps.
.TP
\fB-c\fR, \fB--cat\fR
Toon de inhoud van het opdrachtbestand.
.TP
\fB-l\fR, \fB--list\fR
Toon een lijst van standaardbestanden.
.TP
\fB-r\fR, \fB--remove\fR
Verwijder apps.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-m\fR, \fB--manual\fR
Toon de handleidingpagina.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui=graphical user interface;
grafische gebruikersinterface).
.TP
\fB--\fR
Signaleert het einde van opties en schakelt verdere verwerking van opties uit.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH BESTANDEN
/usr/bin/kz-install-debian-desktop.sh
.RS
Installatiebestand voor Debian desktop.
.RE
.sp
/usr/bin/kz-install-ubuntu-desktop.sh
.RS
Installatiebestand voor Ubuntu desktop.
.RE
.sp
/tmp/kz-install-<distributie>-<editie>-XXXXXXXXXX.sh
.RS
Opdrachtbestand, bijvoorbeeld kz-install-ubuntu-desktop-SYpGEKVWZI.sh.
.RE
.sp
~/.kz/apps
.RS
Lijst van geïnstalleerde apps ter controle. Aangemaakt door kz-backup.
.RE
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl, onder Linux
.RE
.IP " 2." 4
Persoonlijke map / .kz / apps
.RS 4
In bestand apps staan namen van eerder geïnstalleerde pakketten. Dit bestand is
te gebruiken om de installatie te controleren op volledigheid.
.RE
.IP " 3." 4
IaC en Day 1 Operations
.RS 4
\fBkz install\fR wordt voornamelijk gebruikt voor \fBIaC\fR en
\fBDay 1 Operations\fR. Zie \fBkz\fR(1) voor een uitleg.
.RE
.\"
.\"
.SH VOORBEELDEN
.sp
\fBkz install\fR
.RS
Installeer alles wat in het standaard installatiebestand staat.
Hiervoor is in een grafische werkomgeving ook starter \fBApps installeren\fR
beschikbaar.
.RE
.sp
\fBkz install google-chrome\fR
.RS
Installeer Google Chrome.
.RE
.sp
\fBkz install --remove google-chrome\fR
.RS
Verwijder Google Chrome.
.RE
.sp
\fBkz install --cat google-chrome\fR
.RS
Toon installatie-opdrachten voor Google Chrome.
.RE
.sp
\fBkz install --cat --remove google-chrome\fR
.RS
Toon verwijder-opdrachten voor Google Chrome.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>, Creative Commons Zero 1.0
licentie <https://creativecommons.org/publicdomain/zero/1.0/deed.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1),
\fBkz-setup\fR(1),
\fBkz-update\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar zijn maker, Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz install\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar op de website van Karel Zimmer <https://karelzimmer.nl>, onder
Linux.
