.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-post-migrate (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-POST-MIGRATE" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-post-migrate - post-migratie hulp-script voor na de migratie naar Linux

.SH SAMENVATTING
.SY kz-post-migrate
.YS

.SH BESCHRIJVING
Na de migratie naar Linux, zoek naar Windows-specifieke bestanden [1] en
verwijder deze.
.br
De zoekopdracht begint in de huidige map en omvat alle submappen.
.br
Eerst worden de bestanden opgezocht en getoond, daarna is er de keuze om deze
te verwijderen.

[1]
Bestanden met namen (hoofdletter ongevoelig) die overeenkomen met de volgende
patronen worden beschouwd als Windows-specifiek:
.br
    ~*
.br
    *.bat
.br
    *.exe
.br
    *.lnk
.br
    desktop.ini
.br
    thumbs.db

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.
