.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-post-migrate (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-POST-MIGRATE" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-post-migrate - post-migratie script

.SH SAMENVATTING
.SY kz-post-migrate
.YS

.SH BESCHRIJVING
Zoek naar Windows-specifieke bestanden en verwijder deze na de migratie naar
Linux.
.br
De zoekopdracht begint in de huidige map en omvat alle submappen.
.br
Eerst worden de bestanden opgezocht en getoond, daarna is er de keuze om deze
te verwijderen.

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.
