.\"############################################################################
.\"# SPDX-FileComment: Man page for kz-setup
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################
.\"
.TH "KZ-SETUP" "1" "4.2.1" "Kz" "Handleiding kz"
.\"
.\"
.SH NAAM
kz-setup \- Apps instellen
.\"
.\"
.SH SAMENVATTING
.B kz setup
[<opties>] [--] [\fI<app>\fR...]
.\"
.\"
.SH BESCHRIJVING
\fBkz setup\fR stelt apps in en wijzigt gebruikersinstellingen.
.sp
In een desktopomgeving kan opdracht \fBkz setup\fR worden uitgevoerd door te
zoeken naar \fBapps\fR, klik op \fBApps instellen\fR.
.sp
Gebruik (eerst) \fBkz install\fR voor het installeren van apps en het wijzigen
van systeeminstellingen, \fBkz setup\fR is een post-installatie-instelscript.
.sp
\fBkz setup\fR verwerkt een instelbestand die opdrachten bevat voor het
instellen van apps en het wijzigen van gebruikersinstellingen.
.sp
Standaard verwerkt \fBkz setup\fR het instelbestand /usr/bin/kz-setup.sh dat
opdrachten bavat voor alle hierin opgenomen gebruikers.
.br
De opdrachten meegeleverd bij \fBkz setup\fR zijn zodanig opgesteld dat bij
herhaaldelijk uitvoeren het resultaat hetzelfde blijft (idempotent).
.sp
Bij het verwerken van het instelbestand worden de opdrachten voor iedere en de
huidige gebruiker geselecteerd en gekopieerd naar het opdrachtbestand.
.br
De opdrachten in het opdrachtbestand worden uitgevoerd.
Na succesvolle voltooiing wordt de gebruiker uitgelogd.
.sp
Voor de indeling van het instelbestand zie de sectie \fBBESTANDSINDELING\fR
hieronder.
.sp
Optie \fB-a\fR, \fB--apps\fR geeft een lijst alle van apps die beschikbaar zijn
in het instelbestand.
.sp
Naar keuze kunnen in te stellen apps opgegeven worden met argument \fI<app>\fR.
Per opgegeven app worden de opdrachten geselecteerd uit het instelbestand en
gekopieerd naar het opdrachtbestand.
.sp
Met optie \fB-b\fR, \fB--browse\fR kan gebladerd worden door het instelbestand.
.sp
Optie \fB-c\fR, \fB--cat\fR geeft de inhoud van het opdrachtbestand.
.sp
Met optie \fB-f\fR, \fB--file\fR \fI<bestand>\fR kan een ander instelbestand
opgegeven worden.
.sp
Met optie \fB-g\fR, \fB--gui\fR wordt \fBkz setup\fR in grafische modus
uitgevoerd. Een desktopomgeving is vereist.
.sp
Met optie \fB-r\fR, \fB--reset\fR kan het instellen ongedaan worden gemaakt.
.sp
Een -- signaleert het einde van opties en schakelt verdere verwerking van
opties uit.
.\"
.\"
.SH BESTANDSINDELING
In het instelbestand staan zogenaamde \fBApp-regels\fR en
\fBOpdracht-regels\fR.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels er zijn en hoe deze regels
verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een \fBvoorbeeld\fR van deze deze regels en hoe deze
regels verwerkt worden.
Meer voorbeelden zijn te zien met de opdracht \fBkz setup --cat\fR.
.sp
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
l | l
l | l.
T{
# Setup \fI<app>\fR on <host>...
T}:T{
De \fI<app>\fR instellen op <host>s (\fBApp-regel\fR)
T}
T{
# Commentaar...
T}:T{
Commentaarregel
T}
T{
Opdracht
T}:T{
Instel-opdracht (één of meer \fBOpdracht-regels\fR)
T}
T{
T}:T{
Lege regel
T}
T{
# Reset \fI<app>\fR on <host>...
T}:T{
De \fI<app>\fR resetten op <host>s (\fBApp-regel\fR voor optie reset)
T}
T{
Opdracht
T}:T{
Reset-opdracht (één of meer \fBOpdracht-regels\fR)
T}
.TE
.sp
.sp
.B Tabel 2. Voorbeeld van regels en hun verwerking
.TS
box tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l.
T{
# Setup google-chrome for *
T}:T{
Stel google-chrome in op iedere computer, zie [1]
T}
T{
kz-desktop --addbef=google-chrome
T}:T{
T}
T{
T}:T{
T}
T{
# Reset google-chrome for *
T}:T{
Reset google-chrome op iedere computer, zie [1]
T}
T{
kz-desktop --delete=google-chrome
T}:T{
T}
T{
T}:T{
T}
T{
# Setup gnome on pc02
T}:T{
Stel gnome in alleen op pc02, zie [2]
T}
T{
gsettings set org.gnome.shell...
T}:T{
T}
T{
T}:T{
T}
T{
# Setup kvm on pc01 pc02
T}:T{
Stel kvm in op pc01 en pc02, zie [3]
T}
T{
kz-desktop --addaft=virt-manager
T}:T{
T}
T{
T}:T{
T}
T{
# Setup google-earth for -none
T}:T{
Standaard niet google-earth instellen, zie [4]
T}
T{
kz-desktop --addaft=google-earth
T}:T{
T}
.TE
.sp
.sp
[1]
.br
De regel met '*' zorgt ervoor dat de bijbehorende opdrachten op alle computers
worden uitgevoerd.
.sp
[2]
.br
De regel met 'pc02' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc02 worden uitgevoerd.
.br
De app kan alsnog worden ingesteld op een andere computer met de opdracht 'kz \
setup gnome'.
.sp
[3]
.br
De regel met 'pc01 pc02' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc01 en pc02 worden uitgevoerd.
.br
De app kan alsnog worden ingesteld op een andere computer met de opdracht 'kz \
setup kvm'.
.sp
[4]
.br
De regel met '-none' zorgt ervoor dat de bijbehorende opdrachten standaard niet
worden uitgevoerd (OPMERKING: '-none' is geen geldige gebruikersnaam en wordt
daarom nooit standaard geselecteerd).
.br
De app kan alsnog worden ingesteld met de opdracht 'kz setup google-earth'.
.\"
.\"
.sp
.SH OPTIES
Verplichte argumenten voor lange opties zijn ook verplicht voor korte opties.
.TP
\fI<app>\fR...
Stel de opgegeven apps in.
.TP
\fB-a\fR, \fB--apps\fR
Toon een lijst van in te stellen apps.
.TP
\fB-b\fR, \fB--browse\fR
Blader door het instelbestand.
.TP
\fB-c\fR, \fB--cat\fR
Toon de inhoud van het opdrachtbestand.
.TP
\fB-f\fR, \fB--file\fR \fI<bestand>\fR
Verwerk het opgegeven bestand.
.TP
\fB-g\fR, \fB--gui\fR
Draai in grafische modus (gui=graphical user interface; grafische
gebruikersinterface). Een desktopomgeving is vereist.
.TP
\fB-r\fR, \fB--reset\fR
Reset de apps.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-m\fR, \fB--manual\fR
Toon de handleidingpagina.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB--\fR
Signaleert het einde van opties en schakelt verdere verwerking van opties uit.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH BESTANDEN
/usr/bin/kz-setup.sh
.RS
Instelbestand.
.RE
.sp
~/kz-backup/avatar
.RS
Back-up van de avatar, indien beschikbaar.
.RE
.sp
~/kz-backup/avatar.txt
.RS
Instructies voor het terugzetten van de avatar, indien beschikbaar.
.RE
.sp
/tmp/kz-setup-commands-XXXXXXXXXX
.RS
Opdrachtbestand, bijvoorbeeld kz-setup-commands-SYpGEKVWZI.
.RE
.sp
/tmp/kz-setup-errors-XXXXXXXXXX
.RS
Foutbestand, bijvoorbeeld kz-setup-errors-jx7oyBzR0m.
.RE
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl, onder Linux
.RE
.IP " 2." 4
~/kz-backup/favs.txt
.RS 4
In bestand Favorieten staan eerder ingestelde favorieten.
Is te gebruiken om de favorieten te controleren op volledigheid.
.RE
.IP " 3." 4
IaC en Day 1 Operations
.RS 4
\fBkz setup\fR wordt voornamelijk gebruikt voor \fBIaC\fR en
\fBDay 1 Operations\fR. Zie \fBkz\fR(1) voor een uitleg.
.RE
.\"
.\"
.SH VOORBEELDEN
.sp
\fBkz setup\fR
.RS
Stel alles in wat in het standaard instelbestand staat. Hiervoor is in een
desktopomgeving ook starter \fBApps instellen\fR beschikbaar.
.RE
.sp
\fBkz setup google-chrome\fR
.RS
Stel Google Chrome in.
.RE
.sp
\fBkz setup --reset google-chrome\fR
.RS
Reset Google Chrome.
.RE
.sp
\fBkz setup --cat google-chrome\fR
.RS
Toon instel-opdrachten voor Google Chrome.
.RE
.sp
\fBkz setup --cat --reset google-chrome\fR
.RS
Toon reset-opdrachten voor Google Chrome.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.br
Licentie CC0 1.0 <https://creativecommons.org/publicdomain/zero/1.0/deed.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-install\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker, Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz setup\fR is onderdeel van het pakket \fBkz\fR en is beschikbaar
op de website van Karel Zimmer <https://karelzimmer.nl>, onder Linux.
