.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-setup (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-SETUP" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-setup - apps instellen

.SH SAMENVATTING
.SY kz\ setup
[<opties>] [--] [\fI<app>\fR...]
.YS

.SH BESCHRIJVING
\fBkz setup\fR stelt apps in en wijzigt gebruikersinstellingen.
.sp
In een desktopomgeving kan opdracht \fBkz setup\fR worden uitgevoerd door te
zoeken naar \fBapps\fR, klik op \fBApps instellen\fR-pictogram.
.sp
Gebruik (eerst) \fBkz install\fR voor het installeren van apps en het wijzigen
van systeeminstellingen, \fBkz setup\fR is een post-installatie-instelscript.
.sp
\fBkz setup\fR verwerkt instelbestanden die opdrachten bevat voor het
instellen van apps en het wijzigen van gebruikersinstellingen.
.sp
Standaard verwerkt \fBkz setup\fR de instelbestanden /usr/bin/kz-setup.sh en
/usr/bin/kz-setup.sh.gpg dat opdrachten bevat voor alle hierin opgenomen
computers.
.br
Opdrachten met persoonlijke informatie zoals een gebruikersnaam zijn opgenomen
in versleuteld instelbestand /usr/bin/kz-setup.sh.gpg.
Dit bestand wordt ontsleuteld voordat de opdrachten worden gebruikt.
.sp
De opdrachten meegeleverd bij \fBkz setup\fR zijn zodanig opgesteld dat bij
herhaaldelijk uitvoeren het resultaat hetzelfde blijft (idempotent).
.sp
Bij het verwerken van de instelbestanden worden de opdrachten voor voor iedere
en de huidige computer geselecteerd en gekopieerd naar het opdrachtbestand.
.br
De opdrachten in het opdrachtbestand worden uitgevoerd.
.sp
Na succesvolle voltooiing wordt de gebruiker uitgelogd.
.sp
Als er fouten zijn geconstateerd wordt een overzicht gegeven van deze
meldingen.
.sp
Voor de indeling van de instelbestanden zie \fBman kz-setup.sh\fR en
\fBman kz-setup.sh.gpg\fR.
.sp
Optie \fB-a\fR, \fB--apps\fR geeft een lijst alle van apps die beschikbaar zijn
in het instelbestand.
.sp
Naar keuze kunnen te verwerken apps opgegeven worden met argument \fI<app>\fR.
.br
Per opgegeven app worden de opdrachten geselecteerd uit het instelbestand en
gekopieerd naar het opdrachtbestand.
.sp
Met optie \fB-b\fR, \fB--browse\fR kan gebladerd worden door de
instelbestanden.
.sp
Optie \fB-c\fR, \fB--cat\fR geeft de inhoud van het opdrachtbestand.
.sp
Met optie \fB-f\fR, \fB--file\fR \fI<bestand>\fR kan een andere instelbestand
opgegeven worden. Deze optie kan herhaaldelijk gebruikt worden.
.sp
Met optie \fB-g\fR, \fB--gui\fR wordt \fBkz setup\fR in grafische modus
uitgevoerd. Een desktopomgeving is vereist.
.sp
Met optie \fB-r\fR, \fB--reset\fR kan het instellen ongedaan worden gemaakt.

.SH OPTIES
Verplichte argumenten voor lange opties zijn ook verplicht voor korte opties.
.TP
\fB-a\fR, \fB--apps\fR
Toon een lijst van in te stellen apps.
.TP
\fB-b\fR, \fB--browse\fR
Blader door het instelbestand.
.TP
\fB-c\fR, \fB--cat\fR
Toon de inhoud van het opdrachtbestand.
.TP
\fB-f\fR, \fB--file\fR \fI<bestand>\fR
Verwerk de opgegeven bestand. Deze optie kan herhaaldelijk gebruikt worden.
.TP
\fB-g\fR, \fB--gui\fR
Draai in grafische modus (gui=graphical user interface; grafische
gebruikersinterface). Een desktopomgeving is vereist.
.TP
\fB-r\fR, \fB--reset\fR
Stel de apps in op standaardwaarden
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-m\fR, \fB--manual\fR
Toon de handleidingpagina.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur en het auteursrecht.

.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.

.SH FILES
/usr/bin/kz-setup.sh
.RS
Instelbestand.
.RE
.sp
/usr/bin/kz-setup.sh.gpg
.RS
Versleuteld instelbestand.
.RE
.sp
/usr/share/kz/kz-public-key.gpg
.RS
OpenPGP publieke sleutel voor pakket kz. Nodig om kz-setup.sh.gpg te
ontsleutelen.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX-decryptd.sh.gpg
.RS
Onsleuteld instelbestand met aanvullende opdrachten die worden toegevoegd aan
het opdrachtbestand, bijvoorbeeld kz-setup-SkQLswclj3-decryptd.sh.gpg.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX-commands.sh.
.RS
Opdrachtbestand, bijvoorbeeld kz-setup-SYpGEKVWZI-commands.
.RE
.sp
~/Instellingen/avatar
.RS
Back-up van de avatar, indien beschikbaar.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX-error.log
.RS
Foutlogbestand, e.g. kz-setup-agr1ZErXoI-error.log.
.RE
.sp
~/Instellingen/avatar.txt
.RS
Instructies voor het herstellen van de avatar, indien beschikbaar.
.RE
.sp
~/Settings/xfce.txt
.RS
Instructies voor het instellen van Xfce werkbalk en Whiskermenu.
.RE

.SH VOORBEELDEN
.EX
.sp
\fBkz setup\fR
.RS
Stel alles in wat in het standaard instelbestand staat. Hiervoor is in een
desktopomgeving ook starter \fBApps instellen\fR beschikbaar.
.RE
.sp
\fBkz setup google-chrome\fR
.RS
Stel Google Chrome in.
.RE
.sp
\fBkz setup --reset google-chrome\fR
.RS
Reset Google Chrome.
.RE
.sp
\fBkz setup --cat google-chrome\fR
.RS
Toon instel-opdrachten voor Google Chrome.
.RE
.sp
\fBkz setup --cat --reset google-chrome\fR
.RS
Toon reset-opdrachten voor Google Chrome.
.RE
.EE

.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-install\fR(1),
\fBkz-menu\fR(1),
\fBkz-setup.sh\fR(5),
\fBkz-setup.sh.gpg\fR(5)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.

.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
.UR https://karelzimmer.nl/nl
.UE
.RE
.IP " 2." 4
~/Instellingen/favs.txt
.RS 4
Het favorietenbestand bevat eerder ingestelde favorieten.
Kan worden gebruikt om de favorieten op volledigheid te controleren.
.RE
.IP " 3." 4
IaC en Day 1 Operations
.RS 4
\fBkz install\fR wordt voornamelijk gebruikt voor \fBIaC\fR en
\fBDay 1 Operations\fR. Zie \fBkz\fR(1) voor een uitleg.
.RE
