.\"############################################################################
.\"# Man-pagina voor kz-setup.
.\"#
.\"# Geschreven door Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universeel
.\"# <https://creativecommons.org/publicdomain/zero/1.0/deed.nl>, 2019-2023.
.\"############################################################################
.\"
.TH "KZ-SETUP" "1" "2013-2023" "kz 365" "Handleiding kz"
.\"
.\"
.SH NAAM
kz-setup \- Apps instellen.
.\"
.\"
.SH SAMENVATTING
.B kz setup
[OPTIE...] [\fIAPP\fR...]
.\"
.\"
.SH BESCHRIJVING
\fBkz setup\fR stelt apps in en wijzigt gebruikersinstellingen.
.sp
In een grafische werkomgeving kan opdracht \fBkz setup\fR worden uitgevoerd
door te zoeken naar \fBapps\fR, klik op \fBApps instellen\fR.
.sp
Gebruik (eerst) \fBkz install\fR voor het installeren van apps en het wijzigen
van gebruikersinstellingen.
.sp
\fBkz setup\fR verwerkt een invoerbestand ("instelbestand") die opdrachten
bevat voor het instellen van apps en het wijzigen van gebruikersinstellingen.
.sp
Voor de indeling van het invoerbestand zie het deel \fBBESTANDSINDELING\fR
hieronder.
.sp
Standaard verwerkt \fBkz setup\fR het invoerbestand,
/usr/bin/kz-setup-setup-<distributie>-<editie>.sh, <distributie> (b.v.
ubuntu) en <editie> (desktop of server) worden ingevuld met de waarden van de
huidige computer.
Bijvoorbeeld kz-setup-setup-ubuntu-desktop.sh.
.sp
Dit invoerbestand bevat instel-opdrachten voor alle hierin opgenomen gebruikers
voor Ubuntu desktop.
Bij het verwerken van het invoerbestand worden de opdrachten voor iedere en de
huidige gebruiker geselecteerd en gekopieerd naar het opdrachtbestand.
.sp
Optie \fB-a\fR, \fB--apps\fR geeft een lijst van apps die beschikbaar zijn in
het invoerbestand.
.sp
Het is mogelijk om \fIAPP\fRs op te geven. Per opgegeven \fIAPP\fR worden de
opdrachten geselecteerd uit het invoerbestand en gekopieerd naar het
opdrachtbestand.
.sp
De opdrachten in het opdrachtbestand worden uitgevoerd.
Na succesvolle voltooiing wordt de gebruiker uitgelogd.
.sp
Optie \fB-c\fR, \fB--cat\fR geeft de inhoud van het opdrachtbestand.
.sp
Met optie \fB-r\fR, \fB--reset\fR kan het instellen ongedaan worden gemaakt, de
modus wijzigt dan van setup naar reset.
Dan wordt bijvoorbeeld bestand /usr/bin/kz-setup-reset-ubuntu-desktop.sh
("resetbestand") verwerkt.
.sp
De optie \fB-l\fR, \fB--list\fR geeft een lijst met installatiebestanden weer.
.sp
Met optie \fB-f\fR, \fB--file\fR \fIFILE\fR kan een ander invoerbestand
opgegeven worden, de bestandsnaam moet beginnen met \fBkz-setup-\fR en eindigen
met \fB.sh\fR.
.sp
Een -- signaleert het einde van opties en schakelt verdere verwerking van
opties uit.
.\"
.\"
.SH BESTANDSINDELING
De naamgeving van de standaard invoerbestanden is
kz-setup-<mode>-<distribution>-<edition>.sh, voor een door de gebruiker
aangeleverd invoerbestand is het kz-setup-*.sh.
De regels worden verwerkt op de volgorde zoals deze in de bestanden voorkomen.
.sp
De opdrachten standaard meegeleverd bij \fBkz setup\fR zijn zodanig opgesteld
dat bij herhaaldelijk uitvoeren het resultaat hetzelfde blijft.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels er zijn en hoe deze regels
verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een \fBvoorbeeld\fR van deze deze regels in
voorbeeldbestand kz-setup-setup-ubuntu-desktop.sh voor gebruiker Jan.
Meer voorbeelden zijn te zien via de opdracht \fBkz setup --cat\fR.
.sp
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
l | l
l | l
l | l
l | l.
T{
# APP <appnaam> <gebruikersnaam>@<computernaam>...
T}:T{
De APP <appnaam> en gebruiker <gebruikersnaam>@<computernaam>.
T}
T{
T}:T{
Wordt overgeslagen (is leeg).
T}
T{
#...
T}:T{
Wordt overgeslagen (is commentaar).
T}
T{
Opdracht
T}:T{
Opdracht voor het instellen van APP.
T}
.TE
.sp
.sp
.B Tabel 2. Regels in voorbeeldbestand kz-setup-setup-ubuntu-desktop.sh
.TS
box tab(:);
lb | lb.
T{
Regelsoort
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l
l | l
l | l
l | l.
T{
# APP google-chrome *
T}:T{
Stel APP in op voor iedere gebruiker, zie [1].
T}
T{
kz-gset --addfavbef=google-chrome
T}:T{
Instel-opdracht.
T}
T{
T}:T{
Lege regel.
T}
T{
# APP gnome jan@pc02
T}:T{
Stel APP in alleen voor Jan, zie [2].
T}
T{
gsettings set org.gnome.shell...
T}:T{
Instel-opdracht.
T}
.TE
.sp
.sp
[1]
De regel met '*' zorgt ervoor dat de bijbehorende opdrachten voor iedere
gebruiker worden uitgevoerd.
.sp
[2]
De regel met 'jan@pc02' zorgt ervoor dat de bijbehorende opdrachten alleen voor
Jan op pc02 worden uitgevoerd.
.\"
.\"
.sp
.SH OPTIES
.TP
\fB-a\fR, \fB--apps\fR
Toon een lijst van in te stellen apps.
.TP
\fB-c\fR, \fB--cat\fR
Toon de inhoud van het opdrachtbestand.
.TP
\fB-l\fR, \fB--list\fR
Toon een lijst van standaardbestanden.
.TP
\fB-r\fR, \fB--reset\fR
Reset apps.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui=graphical user interface;
grafische gebruikersinterface).
.TP
\fB--\fR
Signaleert het einde van opties en schakelt verdere verwerking van opties uit.
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH BESTANDEN
/usr/bin/kz-setup-setup-debian-desktop.sh
.RS
Standaard instelbestand voor Debian desktop.
.RE
.sp
/usr/bin/kz-setup-setup-ubuntu-desktop.sh
.RS
Standaard instelbestand voor Ubuntu desktop.
.RE
.sp
/usr/bin/kz-setup-reset-debian-desktop.sh
.RS
Standaard resetbestand voor Debian desktop.
.RE
.sp
/usr/bin/kz-setup-reset-ubuntu-desktop.sh
.RS
Standaard resetbestand voor Ubuntu desktop.
.RE
.sp
/tmp/kz-setup-<modus>-<distributie>-<editie>-XXXXXXXXXX.sh
.RS
Opdrachtbestand, bijvoorbeeld kz-setup-setup-ubuntu-desktop-SYpGEKVWZI.sh.
.RE
.sp
~/Instellingen/Achtergrond
.RS
Ingestelde bureaubladachtergrond. Ter controle. Aangemaakt door kz-backup.
.RE
.sp
~/Instellingen/Favorieten
.RS
Ingestelde favorieten in de favorietenbalk (dash/dock). Ter controle.
Aangemaakt door kz-backup
.RE
.sp
~/Instellingen/Gebruikersfoto
.RS
Ingestelde gebruikersfoto. Ter controle. Aangemaakt door kz-backup.
.RE
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Checklist installatie
.RS 4
https://karelzimmer.nl/html/nl/linux.html#documents
.RE
.IP " 2." 4
Persoonlijke map / Instellingen / Favorieten
.RS 4
In bestand Favorieten staan eerder ingestelde favorieten.
Is te gebruiken om de favorieten te controleren op volledigheid.
.RE
.IP " 3." 4
IaC en Day 1 Operations
.RS 4
\fBkz setup\fR wordt voornamelijk gebruikt voor \fBIaC\fR en
\fBDay 1 Operations\fR. Zie \fBkz\fR(1) voor een uitleg.
.RE
.\"
.\"
.SH VOORBEELDEN
.sp
\fBkz setup\fR
.RS
Stel alles in wat in de standaard instelbestanden staat.
Hiervoor is in een grafische werkomgeving ook starter \fBApps instellen\fR
beschikbaar.
.RE
.sp
\fBkz setup google-chrome\fR
.RS
Stel Google Chrome in.
.RE
.sp
\fBkz setup --reset google-chrome\fR
.RS
Reset Google Chrome.
.RE
.sp
\fBkz setup --cat google-chrome\fR
.RS
Toon instel-opdrachten voor Google Chrome.
.RE
.sp
\fBkz setup --cat --reset google-chrome\fR
.RS
Toon reset-opdrachten voor Google Chrome.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universeel
<https://creativecommons.org/publicdomain/zero/1.0/deed.nl>, 2013-2023.
.\"
.\"
.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-install\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar zijn maker, Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz setup\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar op de website van Karel Zimmer
<https://karelzimmer.nl/html/nl/linux.html#scripts>.
