.\"############################################################################
.\"# Man-pagina voor kz-wifi.
.\"#
.\"# Geschreven door Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universeel
.\"# <https://creativecommons.org/publicdomain/zero/1.0/deed.nl>, 2022-2023.
.\"############################################################################
.\"
.TH "KZ-WIFI" "1" "2022-2023" "kz 365" "Handleiding kz"
.\"
.\"
.SH NAAM
kz-wifi\ - Wifi-gegevens tonen.
.\"
.\"
.SH SAMENVATTING
.B kz build
[OPTIE...]
.\"
.\"
.SH BESCHRIJVING
\fBkz wifi\fR toont wifi-gegevens.
.sp
In een grafische werkomgeving kan opdracht \fBkz wifi\fR worden uitgevoerd door
te zoeken naar \fBwifi\fR, klik op \fBWifi-gegevens tonen\fR.
.\"
.\"
.SH OPTIES
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.
.TP
\fB-g\fR, \fB--gui\fR
Start in grafische modus (gui=graphical user interface;
grafische gebruikersinterface).
.\"
.\"
.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.
.\"
.\"
.SH NOTITIES
.IP " 1." 4
Day 1 Operations
.RS 4
\fBkz wifi\fR wordt voornamelijk gebruikt voor \fBDay 1 Operations\fR. Zie
\fBkz\fR(1) voor een uitleg.
.RE
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universeel
<https://creativecommons.org/publicdomain/zero/1.0/deed.nl>, 2022-2023.
.\"
.\"
.SH ZIE OOK
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar zijn maker, Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Opdracht \fBkz wifi\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar op de website van Karel Zimmer
<https://karelzimmer.nl/html/nl/linux.html#scripts>.
