.\"############################################################################
.\"# SPDX-FileComment: Man page for kz-wifi-pkexec (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ-WIFI-PKEXEC" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz-wifi-pkexec - voer nmcli uit (wrapperscript)

.SH SAMENVATTING
.nf
.B pkexec /usr/bin/kz-wifi-pkexec
.YS

.SH BESCHRIJVING
Wanneer aangeroepen vanuit \fBkz_wifi\fR, voert \fBkz-wifi-pkexec\fR nmcli uit
waarvoor root-rechten nodig zijn.

.SH ZIE OOK
\fBkz_wifi\fR(1),
\fBpkexec\fR(1),
\fBpolkit\fR(8)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.
