.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz - voer de kz-opdracht uit

.SH SAMENVATTING
.SY kz
[<opties>] \fI<opdracht>\fR [\fI<argumenten>\fR]
.YS

.SH BESCHRIJVING
\fBkz\fR voert \fI<opdracht>\fR uit, geïnstalleerd door pakket kz, eventueel
met de opgegeven \fI<argumenten>\fR die horen bij de \fI<opdracht>\fR.
.sp
Pakket kz bevat scripts voor het installeren en beheren van Debian en
Debian-gebaseerde systemen zoals Ubuntu, en Red Hat en Red Hat-gebaseerde
systemen zoals Rocky Linux.
.sp
Pakket kz is getest op Debian, Ubuntu, en Rock Linux in combinatie met
verschillende desktopomgevingen zoals GNOME en Xfce.
.sp
Gebruik optie \fB-l\fR, \fB--list\fR voor een lijst van beschikbare opdrachten.

.SH OPTIES
.TP
\fB-l\fR, \fB--list\fR
Toon de beschikbare opdrachten.
.TP
\fB-h\fR, \fB--help\fR
Toon een korte omschrijving van de beschikbare opties.
.TP
\fB-m\fR, \fB--manual\fR
Toon de handleidingpagina.
.TP
\fB-u\fR, \fB--usage\fR
Toon de beschikbare opties.
.TP
\fB-v\fR, \fB--version\fR
Toon de versie, de auteur, en het auteursrecht.

.SH STOPSTATUS
Normaal wordt afsluitwaarde 0 teruggegeven; als er een fout optreedt, is de
afsluitwaarde ongelijk 0.

.SH VOORBEELDEN
.EX
\fBkz update\fR
.RS
Werk systeem bij.
.RE
.sp
\fBkz install google-chrome\fR
.RS
Installeer Google Chrome.
.RE
.sp
\fBkz setup --cat google-chrome\fR
.RS
Toon instel-opdrachten voor Google Chrome.
.RE
.EE

.SH ZIE OOK
\fBkz-menu\fR(1)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.

.SH NOTITIES
.sp
De opdrachten van \fBkz\fR zijn verdeeld in opdrachten op hoog niveau
("porcelein") en opdrachten op laag niveau ("loodgieterswerk").

.SS Opdrachten op hoog niveau (porcelein)
.br
Deze opdrachten zijn uit te voeren in een desktopomgeving met het
Installatiemenu of door te zoeken naar de opdracht, en in het Terminalvenster.
.TP
\fBkz-backup\fR(1)
Back-up persoonlijke map.
.TP
\fBkz-install\fR(1)
Apps installeren.
.TP
\fBkz-menu\fR(1)
Installatiemenu.
.TP
\fBkz-restore\fR(1)
Herstel persoonlijke map.
.TP
\fBkz-setup\fR(1)
Apps instellen.
.TP
\fBkz-update\fR(1)
Systeem bijwerken en opschonen.
.TP
\fBkz-wifi\fR(1)
Wifi-informatie weergeven.

.SS Opdrachten op laag niveau (loodgieterswerk)
.br
Deze opdrachten zijn alleen uit te voeren in het Terminalvenster en zijn
ondersteunend voor het beheer en gebruik van kz en Linux.
.TP
\fBkz_common-pkexec\fR(1)
Wrapper-script voor kz_common.
.TP
\fBkz-build\fR(1)
Website bouwen inclusief pakket kz.
.TP
\fBkz-check\fR(1)
Controleer scripts en website.
.TP
\fBkz-deb\fR(1)
Download en installeer Debian-pakket kz.
.TP
\fBkz-deploy\fR(1)
Website distribueren inclusief kz pakketten.
.TP
\fBkz-desktop\fR(1)
Desktopomgeving wijzigen.
.TP
\fBkz-dev\fR(1)
Ontwikkelomgeving bouwen.
.TP
\fBkz-get\fR(1)
Download en installeer Debian- of RPM-pakket kz.
.TP
\fBkz-install-pkexec\fR(1)
Wrapper-script voor kz-install.
.TP
\fBkz-wifi-pkexec\fR(1)
Wrapper-script voor kz-wifi.
.TP
\fBgitclone\fR
Git clone van alle publieke remote repo's in de Persoonlijke map.
.TP
\fBgitpull\fR
Git pull van alle lokale branches in de Persoonlijke map.
.TP
\fBgitstatus\fR
Git status van alle lokale branches in de Persoonlijke map.

.SS Modern
Pakket \fBkz\fR geeft met de documenten en scripts invulling aan en biedt
ondersteuning voor:
.br
\fB1. IaC\fR
.br
\fB2. CI/CD\fR
.br
\fB3. Day 0/Day 1/Day 2 Operations\fR
.br
Begrippen uit de moderne wereld van software-ontwikkeling, -distributie, en
beheer.
.sp
\fB1. IaC\fR (Infrastructure as Code, Infrastructuur als Code of
programmeerbare infrastructuur)
.br
Het definiëren en beheren van infrastructuur door middel van code.
.br
De opdrachten die meegeleverd worden bij pakket kz zijn idempotent;
herhaaldelijk utvoeren leidt steeds tot hetzelfde resultaat.
.br
Herhaalbaarheid (idempotentie) is één van de principes van IaC.
.br
De documenten en scripts worden vastgelegd en onderhouden in versiebeheer
(GitHub), een ander principe van IaC.
.br
Voorbeelden zijn \fBkz-install.sh\fR (installatiebestand gebruikt door
\fBkz install\fB) en \fBkz-setup.sh\fR (instelbestand gebruikt door
\fBkz setup\fR).
.sp
\fB2. CI/CD\fR (Continuous Integration and Delivery, Continue integratie en
levering)
.br
CI/CD is de gecombineerde praktijk van continuous integration (CI) en (vaker)
continuous delivery of (minder vaak) continuous deployment (CD).
.br
CI (Continuous Integration, Continue integratie) is het meerdere keren per dag
de werkkopieën van alle ontwikkelaars samenvoegen tot een gedeelde hoofdlijn.
.br
CD (Continuous Delivery, Continue levering) is software produceren in korte
cycli, ervoor zorgen dat de software op elk moment betrouwbaar kan worden
vrijgegeven en, bij het vrijgeven van de software, zonder dit handmatig te
doen.
.br
CD (Continuous Deployment, Continue doorzetten) is een aanpak waarbij
softwarefunctionaliteiten vaak en via geautomatiseerde implementaties worden
geleverd.
.br
Een \fBCI/CD Pipeline\fR is een reeks stappen die moet worden uitgevoerd om
geautomatiseerd een nieuwe softwareversie te leveren.
.br
Voorbeelden zijn \fBkz build\fR en \fBkz deploy\fR.
.sp
\fBCI/CD Pipeline flow\fR
.br
Code -----> SCM ----->  Build -----> Test ----->  QA -----> Deploy ----->
.sp
.sp
vscode      GitHub      kz-build     CLI/TUI/GUI  kz-check  kz-deploy
.sp
.sp
+------- DEV --------+  +-------- TEST --------+  +-------- PROD -------+
.sp
SCM staat voor Source Code Management, Broncodebeheer.
.sp
QA staat voor Quality Assurance, Kwaliteitsborging.
.sp
\fB3. Day 0/Day 1/Day 2 Operations\fR
.br
In IT verwijzen de termen Day 0/Day 1/Day 2 Operations naar verschillende fasen
van software-ontwikkeling, -distributie, en beheer.
.sp
\fB3.1 Day 0 Operations\fR (Dag 0 Activiteiten)
.br
Dit is de ontwerpfase (design), waarin projectvereisten worden gespecificeerd
en de architectuur van de oplossing wordt bepaald.
.br
Pakket kz wordt ontwikkeld met Visual Studio Code en GitHub, en geprogrammeerd
in Bash en Python.
.br
Voorbeelden zijn Google Keep (ideeën vastleggen en ticketsysteem) en
\fBkz dev\fR.
.sp
\fB3.2 Day 1 Operations\fR (Dag 1 Activiteiten)
.br
Omvat het ontwikkelen en implementeren (development and deploy) van software
die is ontworpen in de dag 0-fase.
.br
Hierbij wordt onder andere gebruik gemaakt van \fBIaC\fR en
\fBCI/CD Pipelines\fR, en het uitvoeren van Ansible Playbooks.
.br
Voorbeelden zijn Checklist installatie, en \fBkz get\fR en \fBkz menu\fR.
.sp
\fB3.3 Day 2 Operations\fR (Dag 2 Activiteiten)
.br
Hier gaat de meeste aandacht uit naar het onderhouden, bewaken en optimaliseren
(maintaining, monitoring, and optimizing) van het systeem.
.br
Voorbeelden zijn \fBkz backup\fR en \fBkz update\fR.
