.\"############################################################################
.\"# Man-pagina voor kz_common.py.
.\"#
.\"# Written in 2021 by Karel Zimmer <info@karelzimmer.nl>, Creative Commons
.\"# Public Domain Dedication
.\"# <https://creativecommons.org/publicdomain/zero/1.0>.
.\"############################################################################
.\"
.TH "KZ_COMMON.PY" "1" "12-05-2023" "kz 365" "Handleiding kz"
.\"
.\"
.SH NAAM
kz_common.py \- Algemene module voor Python scripts.
.\"
.\"
.SH SAMENVATTING
.B import kz_common
.\"
.\"
.SH BESCHRIJVING
Deze module geeft toegang tot algemene variabelen en functies.
.sp
Algemene variabelen zoals:
.br
- afsluitwaarden (ok, err)
.sp
Algemene functies zoals:
.br
- verwerk opties (kz_common.process_option)
.br
- controleer gebruik van superuser, root (kz_common.check_user_sudo)
.\"
.\"
.SH AUTEUR
Geschreven in 2021 door Karel Zimmer <info@karelzimmer.nl>, Creative Commons
Publiek Domein Verklaring <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH ZIE OOK
\fBkz\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Module \fBkz_common.py\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar op de website van Karel Zimmer
.br
<https://karelzimmer.nl/html/nl/linux.html#scripts>.
