.\"############################################################################
.\"# Man page for kz_common.py.
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################
.\"
.TH "KZ_COMMON.PY" "1" "Handleiding kz" "kz 4.2.1" "Handleiding kz"
.\"
.\"
.SH NAAM
kz_common.py \- Algemene module voor Python scripts.
.\"
.\"
.SH SAMENVATTING
.B import kz_common
.\"
.\"
.SH BESCHRIJVING
Deze module geeft toegang tot algemene variabelen en functies.
.sp
Algemene variabelen zoals:
.br
- afsluitwaarden (ok, err)
.sp
Algemene functies zoals:
.br
- verwerk opties (kz_common.process_common_options)
.br
- controleer gebruik van superuser, root (kz_common.become_root_check)
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>, CC0-1.0
<https://creativecommons.org/publicdomain/zero/1.0/deed.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar zijn maker, Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Module \fBkz_common.py\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar op de website van Karel Zimmer <https://karelzimmer.nl>, onder
Linux.
