.\"############################################################################
.\"# Man-pagina voor kz_common.sh.
.\"#
.\"# Geschreven door Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universeel
.\"# <https://creativecommons.org/publicdomain/zero/1.0/deed.nl>, 2019-2024.
.\"############################################################################
.\"
.TH "KZ_COMMON.SH" "1" "2009-2024" "kz 2.4.7" "Handleiding kz"
.\"
.\"
.SH NAAM
kz_common.sh \- Algemene module voor shell scripts.
.\"
.\"
.SH SAMENVATTING
.B source kz_common.sh
.\"
.\"
.SH BESCHRIJVING
Deze module geeft toegang tot algemene variabelen en functies.
.sp
Algemene variabelen zoals:
.br
- afsluitwaarden (ok, err)
.br
- terminalattributen (green, red)
.sp
Algemene functies zoals:
.br
- initiele acties bij starten van een script (init_script)
.br
- verwerk opties zoals usage en help (process_common_options)
.br
- controleer gebruik van superuser, root (become_root)
.sp
Tevens zorgt deze module voor script-hardening en foutafhandeling.
.\"
.\"
.SH AUTEUR
Geschreven door Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universeel
<https://creativecommons.org/publicdomain/zero/1.0/deed.nl>, 2009-2024.
.\"
.\"
.SH ZIE OOK
\fBkz\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar zijn maker, Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Module \fBkz_common.sh\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar op de website van Karel Zimmer
<https://karelzimmer.nl/html/nl/linux.html#scripts>.
