.\"############################################################################
.\"# SPDX-FileComment: Man page for kz_common.sh (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ_COMMON.SH" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz_common.sh \- Algemene module voor shell scripts

.SH SAMENVATTING
.SY source\ kz_common.sh
.YS

.SH BESCHRIJVING
Deze module biedt toegang tot globale constanten en functies.
.LP
Algemene variabelen zoals:
.br
- afsluitwaarden (OK, ERR)
.br
- terminalattributen (BOLD, RED)
.sp
Algemene functies zoals:
.br
- initiele acties bij starten van een script (init)
.br
- verwerk opties zoals usage en help (process_options)
.br
- controleer gebruik van superuser, root (become_root)
.sp
Tevens zorgt deze module voor script-hardening en foutafhandeling.

.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.py\fR(1),
.UR https://karelzimmer.nl
.UE
