.\"############################################################################
.\"# SPDX-FileComment: Man page for kz_common.py (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################
.\"
.TH "KZ_COMMON.PY" "1" "4.2.1" "kz"
.\"
.\"
.SH NAAM
kz_common.py \- Algemene module voor Python scripts
.\"
.\"
.SH SAMENVATTING
.B import kz_common
.\"
.\"
.SH BESCHRIJVING
Deze module biedt toegang tot globale constanten en functies.
.sp
Algemene variabelen zoals:
.br
- afsluitwaarden (kz_common.OK, kz_common.ERR)
.sp
Algemene functies zoals:
.br
- verwerk opties (kz_common.process_options)
.br
- controleer gebruik van superuser, root (kz_common.become_root_check)
.\"
.\"
.SH AUTEURS
Geschreven door Karel Zimmer <info@karelzimmer.nl>.
.br
Licentie CC0 1.0 <https://creativecommons.org/publicdomain/zero/1.0/deed.nl>.
.\"
.\"
.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Onderdeel van het \fBkz\fR(1) pakket, genoemd naar de maker, Karel Zimmer.
.\"
.\"
.SH BESCHIKBAARHEID
Module \fBkz_common.py\fR is onderdeel van het pakket \fBkz\fR en is
beschikbaar op de website van Karel Zimmer <https://karelzimmer.nl>, onder
Linux.
