.\"############################################################################
.\"# SPDX-FileComment: Man page for kz_common.sh (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ_COMMON.SH" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz_common.sh - algemene module voor kz Bash scripts

.SH SAMENVATTING
.SY source\ kz_common.sh
.YS

.SH BESCHRIJVING
Deze module biedt toegang tot algemene functies voor kz Bash scripts.
.LP
Algemene functies zoals:
.br
- initiele acties bij starten van een script (kz.init)
.br
- controleer gebruik van superuser, root (kz.become_check)
.sp
Tevens zorgt deze module voor script-hardening en foutafhandeling.

.SH ZIE OOK
\fBkz\fR(1),
\fBkz_common.py\fR(1
