.\"############################################################################
.\"# SPDX-FileComment: Man page for kz_common-pkexec (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ_COMMON-PKEXEC" "1" "4.2.1" "kz" "Gebruikersopdrachten"

.SH NAAM
kz_common-pkexec - wrapper script voor kz-common

.SH SAMENVATTING
.nf
.B pkexec /usr/bin/kz_common-pkexec
.YS

.SH BESCHRIJVING
Wanneer aangeroepen vanuit \fBkz_common\fR, voert \fBkz_common-pkexec\fR de
opdracht uit waarvoor root-rechten nodig zijn.

.SH ZIE OOK
\fBkz_commons.py\fR(1),
\fBkz_commons.sh\fR(1),
\fBpkexec\fR(1),
\fBpolkit\fR(8)

.SH KZ
Onderdeel van het \fBkz\fR(1)-pakket.
