.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-install.sh
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-INSTALL.SH" "5" "4.2.1" "kz" "File format"

.SH NAME
kz-install.sh - installation file for use with kz install

.SH SYNOPSIS
.SY kz-install.sh
.YS

.SH DESCRIPTION
This file contains commands to process as an installation file with kz install.
.br
Commands containing personal information, such as a username, are included in
an GPG-encrypted installation file, kz-install.sh.gpg.
.sp
The installation file contains so-called \fBapp record\fRs and
\fBcommand record\fRs.
.sp
The \fBapp record\fR indicates where the commands should be executed and is
followed by one or more lines of commands (\fBcommand record\fRs).
.sp
An \fBapp record\fR consists of four parts, each part separated by at least one
space, like '# INSTALL <app> <host>' and '# REMOVE <app> <host>'.
.br
1. #        (comment symbol)
.br
2. <action> (INSTALL or REMOVE)
.br
3. <app>    (the name of the app)
.br
4. <host>   (the name of the computers or *)
.br
This is followed by one or more \fBcommand record\fRs containing commands for
<app>.
.sp
See \fBTable 1\fR which \fBtypes\fR of records there are and how these records
are processed.
.sp
See \fBTable 2\fR for an \fBexample\fR of these records and how these records
are processed.
.br
More examples can be seen through the \fBkz install --browse\fR and
\fBkz install --cat\fR commands.
.LP
.B Table 1. Record types and their processing
.TS
allbox tab(:);
lb | lb.
T{
Record
T}:T{
Description
T}
.T&
l | l
l | l.
T{
# INSTALL <app> <host>
T}:T{
Install the app <app> on <host> (\fBapp record\fR)
T}
T{
# Comment...
T}:T{
Comment line (none, one or more)
T}
T{
Command
T}:T{
Install app command (one or more \fBcommand record\fRs)
T}
T{
T}:T{
Empty line (none, one or more)
T}
T{
# REMOVE <app> <host>
T}:T{
Remove the app <app> from <host> (\fBapp record\fR for option \fB-r\fR,
\fB--remove\fR)
T}
T{
Command
T}:T{
Remove app command (one or more \fBcommand record\fRs)
T}
.TE
.LP
.B Table 2. Example of records and their processing
.TS
box tab(:);
lb | lb.
T{
Record
T}:T{
Description
T}
.T&
- | -
l | l
l | l.
T{
# INSTALL calibre *
T}:T{
Install calibre on any computer, see [1].
T}
T{
sudo apt-get install --assume-yes calibre
T}:T{
T}
T{
T}:T{
T}
T{
# REMOVE calibre *
T}:T{
Remove calibre from any computer, see [1].
T}
T{
sudo apt-get remove --assume-yes calibre
T}:T{
T}
T{
T}:T{
T}
T{
# INSTALL calibre pc01
T}:T{
Install calibre only on pc01, see [2].
T}
T{
sudo apt-get install --assume-yes calibre
T}:T{
T}
T{
T}:T{
T}
T{
# INSTALL calibre pc01 pc02
T}:T{
Install calibre on pc01 and pc02, see [3].
T}
T{
sudo apt-get install --assume-yes calibre
T}:T{
T}
T{
T}:T{
T}
T{
# INSTALL calibre #none
T}:T{
Do not install calibre by default, see [4].
T}
T{
sudo apt-get install --assume-yes calibre
T}:T{
T}
.TE
.sp
.sp
[1]
.br
The line with '*' causes the associated commands to run on all computers.
.sp
[2]
.br
The line with 'pc01' ensures that the associated commands are executed only on
host pc01 by default.
.br
The app can still be installed on another computer with the command 'kz instal\
l calibre'.
.sp
[3]
.br
The line with 'pc01 pc02' ensures that the associated commands are executed
only on pc01 and pc02 by default.
.br
The app can still be installed on another computer with the command 'kz instal\
l calibre'.
.sp
[4]
.br
The line with '#none' ensures that the associated commands are not executed on
a computer by default (NOTE: '#none' is not a valid computername and will
therefore never be selected by default).
.br
The app can still be installed with the command 'kz install calibre'.

.SH EXAMPLES
.EX
# INSTALL calibre pc01
# -----------------------------------------------------------------------------
# E-book manager.
# -----------------------------------------------------------------------------
if grep --quiet debian /etc/os-release; then sudo apt-get install --a\
ssume-yes calibre; fi
if grep --quiet rhel   /etc/os-release; then sudo --validate && wget \
--output-document=- https://download.calibre-ebook.com/linux-installer.sh | su\
do sh; fi

# REMOVE calibre pc01
# -----------------------------------------------------------------------------
# E-book manager.
# -----------------------------------------------------------------------------
if grep --quiet debian /etc/os-release; then sudo apt-get remove --as\
sume-yes calibre; fi
if grep --quiet rhel   /etc/os-release; then sudo calibre-uninstall; \
fi
.EE

.SH SEE ALSO
\fBkz-install\fR(1),
\fBkz-install.sh.gpg\fR(5)
