.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-install.sh.
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-INSTALL.SH" "5" "4.2.1" "kz" "File format"
.ad l

.SH NAME
kz-install.sh - installation file for use with kz install

.SH SYNOPSIS
.SY kz-install.sh
.YS

.SH DESCRIPTION
This file contains commands to process as an installation file with kz install.
.br
Commands containing personal information, such as a username, are included in
an GPG-encrypted installation file, kz-install.sh.gpg.
.sp
The installation file contains so-called \fBapp-\fR and \fBcommand record\fRs.
.sp
The \fBapp record\fR indicates for which app and which computer the commands
should be executed and provides a description of the app.
.br
Such a record is formatted as a psv record (pipe-separated values), the fields
are separated by the pipe character '|':
.br
#|ACTION|APP|HOST|DESCRIPTION
.TS
box tab(^);
lb lb lbx
l l l.
Field number^Field^Description
1^#^Hash, comment symbol
2^ACTION^Action, 'install' or 'remove'
3^APP^Name of the app
4^HOST^Name of the computer(s) on which the command should be executed
5^DESCRIPTION^Description of the app
.TE
.sp
This record is followed by one or more records with commands, the
\fBcommand record\fRs.
.br
These commands can also be executed in the Terminal window on the command line.
.sp
See \fBTable 1\fR which \fBtypes\fR of records there are and how these records
are processed.
.sp
See \fBTable 2\fR for an \fBexample\fR of these records and how these records
are processed.
.br
More examples can be seen through the \fBkz install --browse\fR and
\fBkz install --cat\fR commands.
.LP
.B Table 1. Record types and their processing
.TS
allbox tab(^);
lb lbx
l l.
Record^Description
#|install|APP|HOST|DESCRIPTION^Install the app (\fBapp record\fR), wil\
l be processed.
# Comment^Comment line (none, one or more), will be skipped.
Command^Install command (one or more \fBcommand record\fRs), will be executed.
^Empty line (none, one or more), will be skipped.
#|remove|APP|HOST|DESCRIPTION^Remove the app (\fBapp record\fR for opt\
ion \fB-r\fR, \fB--remove\fR), will be processed.
Command^Remove command (one or more \fBcommand record\fRs), will be executed.
.TE
.LP
.B Table 2. Example of records and their processing
.TS
box tab(^);
lb | lbx
- | -
l | l.
Record^Description
#|install|calibre|*|Powerful and easy to use e-book manager^Install calib\
re on every computer, see [1].
sudo apt-get install --assume-yes calibre^Install command for calibre.
^
#|remove|calibre|*|Powerful and easy to use e-book manager^Remove calibre\
 on every computer, see [1].
sudo apt-get remove --assume-yes calibre^Remove command for calibre.
^
^
#|install|vscode|pc06 pc07|Code editing. Redefined^Install vscode on pc06\
 and pc07, see [2].
sudo apt-get install --assume-yes code^Install command for vscode.

#|remove|vscode|pc06 pc07|Code editing. Redefined^Remove vscode from pc06\
 and pc07, see [2].
sudo apt-get remove --assume-yes code^Remove command for vscode.
.TE
.sp
[1]
.br
The line with '*' as HOST causes the associated commands to run on all
computers.
.sp
A line with 'pc01' as HOST ensures that the associated commands are executed
only on pc01 by default.
.br
A line with 'pc01 pc02' as HOST ensures that the associated commands are
executed only on pc01 and pc02 by default.
.br
A line with '#none' as HOST ensures that the associated commands are not
executed on any computer by default (NOTE: '#none' is not a valid computername
and will therefore never be selected by default).
.sp
[2]
.br
An app can still be installed on another computer with the command 'kz install
APP', e.g. 'kz install vscode'. In that case, the content of HOST is ignored.

.SH SEE ALSO
\fBkz-install\fR(1),
\fBkz-install.sh.gpg\fR(5)
