.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-setup.sh
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-SETUP.SH" "5" "4.2.1" "kz" "File format"

.SH NAME
kz-setup.sh - settings file for use with kz setup

.SH SYNOPSIS
.SY kz-setup.sh
.YS

.SH DESCRIPTION
This file contains commands to process as an settings file with kz setup.
.br
Commands containing personal information, such as a username, are included in
an GPG-encrypted settings file, kz-setup.sh.gpg.
.sp
The settings file contains so-called \fBapp record\fRs and
\fBcommand record\fRs.
.sp
The \fBapp record\fR indicates where the commands should be executed and is
followed by one or more lines of commands (\fBcommand record\fRs).
.sp
An \fBapp record\fR consists of four parts, each part separated by at least one
space, like '# SETUP <app> <host>' and '# RESET <app> <host>'.
.br
1. #        (comment symbol)
.br
2. <action> (SETUP or RESET)
.br
3. <app>    (the name of the app)
.br
4. <host>   (the name of the computer or computers)
.br
This is followed by one or more \fBcommand record\fRs containing commands for
<app>.
.sp
See \fBTable 1\fR for which \fBtypes\fR records there are and how these records
are processed.
.sp
See \fBTable 2\fR for an \fBexample\fR of these records in file
kz-setup.sh.
.br
More examples can be seen through the \fBkz setup --browse\fR and
\fBkz setup --cat\fR commands.
.LP
.B Table 1. Record types and their processing
.TS
allbox tab(:);
lb | lb.
T{
Record
T}:T{
Description
T}
.T&
l | l
l | l.
T{
# SETUP <app> <host>
T}:T{
Set up <app> on <host> (\fBapp record\fR)
T}
T{
# Comment...
T}:T{
Comment line (none, one or more)
T}
T{
Command
T}:T{
Setup command (one or more \fBcommand record\fRs)
T}
T{
T}:T{
Empty line (none, one or more)
T}
T{
# RESET <app> <host>
T}:T{
Reset the app <app> on <host> (\fBapp record\fR for option
\fB-r\fR, \fB--remove\fR)
T}
T{
Opdracht
T}:T{
Reset command (one or more \fBcommand record\fRs)
T}
.TE
.LP
.B Table 2. Example of records and their processing
.TS
box tab(:);
lb | lb.
T{
Record
T}:T{
Description
T}
.T&
- | -
l | l
l | l.
T{
# SETUP google-chrome *
T}:T{
Set up google-chrome on any computer, see [1]
T}
T{
kz-desktop --addbef=google-chrome
T}:T{
T}
T{
T}:T{
T}
T{
# RESET google-chrome *
T}:T{
Reset app google-chrome on any computer, see [1]
T}
T{
kz-desktop --delete=google-chrome
T}:T{
T}
T{
T}:T{
T}
T{
# SETUP gnome pc01
T}:T{
Set up gnome only on pc01, see [2]
T}
T{
gsettings set org.gnome.shell...
T}:T{
T}
T{
T}:T{
T}
T{
# SETUP kvm pc01 pc02
T}:T{
Set up kvm on pc01 and pc02, see [3]
T}
T{
kz-desktop --addaft=virt-manager
T}:T{
T}
T{
T}:T{
T}
T{
# SETUP google-earth #none
T}:T{
Do not set up Google Earth by default, see [4]
T}
T{
kz-desktop --addaft=google-earth
T}:T{
T}
.TE
.sp
.sp
[1]
.br
The line with '*' causes the associated commands to run on all computers.
.sp
[2]
.br
The line with 'pc01' ensures that the associated commands are executed only on
host pc01 by default.
.br
The app can still be set up on another computer with the command 'kz setup goo\
gle-earth'.
.sp
[3]
.br
The line with 'pc01 pc02' ensures that the associated commands are executed
only on pc01 and pc02 by default.
.br
The app can still be set up on another computer with the command 'kz setup kvm\
'.
.sp
[4]
.br
The line with '#none' ensures that the associated commands are not executed by
default (NOTE: '#none' is not a valid computername and will therefore never
be selected by default).
.br
The app can still be set up with the command 'kz setup google-earth'.
.br
A line with '#gpg' indicates that the command in question is executed in
kz-setup.sh.gpg, the GPG-encrypted version of kz-setup.sh with personal
information such as a username.

.SH EXAMPLES
.EX
# SETUP spotify pc01 pc02 pc06 pc07
# -----------------------------------------------------------------------------
# Music and podcasts.
# -----------------------------------------------------------------------------
# Web app: https://open.spotify.com
# -----------------------------------------------------------------------------
if grep --quiet debian  /etc/os-release; then kz-desktop --addaft=spotify; fi
if grep --quiet rhel    /etc/os-release; then kz-desktop --addaft=kz-spotify; \
fi
.EE

.SH SEE ALSO
\fBkz-setup\fR(1),
\fBkz-setup.sh.gpg\fR(5)
