.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-setup.sh.gpg
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-SETUP.SH.GPG" "5" "4.2.1" "kz" "File format"

.SH NAME
kz-setup.sh.gpg - GPG-encrypted settings file for use with kz setup

.SH SYNOPSIS
.SY kz-setup.sh.gpg
.YS

.SH DESCRIPTION
This file contains commands to process as an settings file with kz setup.
.sp
Commands with personal information such as a username are included in this
GPG-encrypted settings file.
.sp
It is created with e.g. commands:
.br
gpg --import /usr/share/kz/kz-public-key.gpg
.br
gpg --output ~/kz-scripts/usr/bin/kz-setup.sh.gpg --sign ~/kz-setup.sh.gpg.sh
.sp
This encrypted file is decrypted before the commands are used in script
kz-setup with e.g. commands:
.br
gpg --import /usr/share/kz/kz-public-key.gpg
.br
gpg --output ~/kz-setup.sh.gpg.sh --decrypt
~/kz-scripts/usr/bin/kz-setup.sh.gpg
.sp
For the format of the records in this installation file please use
\fBman kz setup.sh\fR.

.SH SEE ALSO
\fBkz-setup\fR(1),
\fBkz-setup.sh\fR(5)
