.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-install.sh.gpg (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-INSTALL.SH.GPG" "5" "4.2.1" "kz" "Bestandsindeling"

.SH NAAM
kz-install.sh.gpg - GPG-versleuteld installatiebestand voor gebruik met kz
install

.SH SAMENVATTING
.SY kz-install.sh.gpg
.YS

.SH BESCHRIJVING
Dit bestand bevat opdrachten om te verwerken als installatiebestand met kz
install.
.sp
Opdrachten met persoonlijke informatie zoals een gebruikersnaam zijn opgenomen
in dit versleuteld installatiebestand.
.br
Deze opdrachten zijn in het niet-versleutelde tijdelijke installatiebestand
aangegeven met '#gpg' aan het einde van de regel.
.sp
Dit bestand is aangemaakt met de volgende voorbeeld opdrachten:
.br
gpg --import /usr/share/kz/kz-public-key.gpg
.br
gpg --output ~/kz-scripts/usr/bin/kz-install.sh.gpg --sign
~/kz-install.sh.gpg.bash
.sp
Dit bestand wordt ontsleuteld voordat de opdrachten worden gebruikt in script
kz-install met bijvoorbeeld de opdrachten:
.br
gpg --import /usr/share/kz/kz-public-key.gpg
.br
gpg --output ~/kz-install.sh.gpg.bash --decrypt
~/kz-scripts/usr/bin/kz-install.sh.gpg
.sp
Gebruik voor de opmaak van de records in dit installatiebestand
\fBman kz install.sh\fR.

.SH ZIE OOK
\fBkz-install\fR(1),
\fBkz-install.sh\fR(5)
