.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-install.sh (Dutch).
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-INSTALL.SH" "5" "4.2.1" "kz" "Bestandsindeling"
.ad l

.SH NAAM
kz-install.sh - installatiebestand voor gebruik met kz install

.SH SAMENVATTING
.SY kz-install.sh
.YS

.SH BESCHRIJVING
Dit bestand bevat opdrachten om te verwerken als installatiebestand met kz
install.
.br
Opdrachten met persoonlijke informatie zoals een gebruikersnaam zijn opgenomen
in een versleuteld installatiebestand, kz-install.sh.gpg.
.sp
In het installatiebestand staan zogenaamde \fBapp-\fR en \fBopdracht-regel\fRs.
.sp
De \fBapp-regel\fR geeft aan voor welke app en welke computer de opdrachten
uitgevoerd moeten worden en geeft een beschrijving van de app.
.br
Zo'n regel is ingedeeld als een psv-regel (pipe-separated values), de velden
worden gescheiden door het pipe-teken '|':
.br
#|ACTIE|APP|HOST|BESCHRIJVING
.TS
box tab(^);
lb lb lbx
l l l.
Veld-nummer^Veld^Beschrijving
1^#^Hekje, commentaarsymbool
2^ACTIE^Actie, 'install' of 'remove'
3^APP^Naam van de app
4^HOST^Naam van de computer(s) waarop de opdracht uitgevoerd moet worden
5^BESCHRIJVING^Beschrijving van de app
.TE
.sp
Deze regels worden gevolgd door één of meer regels met opdrachten, de
\fBopdracht-regel\fRs.
.br
Deze opdrachten kunnen ook in het Terminalvenster op de opdrachtregel worden
uitgevoerd.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels er zijn en hoe deze regels
verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een \fBvoorbeeld\fR van deze regels en hoe deze regels
verwerkt worden.
.br
Meer voorbeelden zijn te zien met de opdrachten \fBkz install --browse\fR en
\fBkz install --cat\fR.
.LP
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(^);
lb lbx
l l.
Regel^Beschrijving
#|install|APP|HOST|BESCHRIJVING^De app installeren (\fBapp-regel\fR), \
wordt verwerkt.
# Commentaar^Commentaarregel (geen, één of meer), wordt overgeslagen.
Opdracht^Installatie-opdracht (één of meer \fBopdracht-regel\fRs), wordt uitge\
voerd.
^Lege regel (geen, één of meer), wordt overgeslagen.
#|remove|APP|HOST|BESCHRIJVING^De app verwijderen (\fBapp-regel\fR voo\
r optie \fB-r\fR, \fB--remove\fR), wordt verwerkt.
Opdracht^Verwijder-opdracht (één of meer \fBopdracht-regel\fRs), wordt uitgevo\
erd.
.TE
.LP
.B Tabel 2. Voorbeeld van regels en hun verwerking
.TS
box tab(^);
lb | lbx
- | -
l | l.
Regel^Beschrijving
#|install|calibre|*|Powerful and easy to use e-book manager^Calibre insta\
lleren op iedere computer, zie [1].
sudo apt-get install --assume-yes calibre^Installatie-opdracht voor calibre.
^
#|remove|calibre|*|Powerful and easy to use e-book manager^Verwijder cali\
bre van iedere computer, zie [1].
sudo apt-get remove --assume-yes calibre^Verwijder-opdracht voor calibre.
^
^
#|install|vscode|pc06 pc07|Code editing. Redefined^Vscode installeren op \
pc06 en pc07, zie [2].
sudo apt-get install --assume-yes code^Installatie-opdracht voor vscode.

#|remove|vscode|pc06 pc07|Code editing. Redefined^Verwijder vscode van pc\
06 en pc07, zie [2].
sudo apt-get remove --assume-yes code^Verwijder-opdracht voor vscode.
.TE
.sp
[1]
.br
De regel met '*' als HOST zorgt ervoor dat de bijbehorende opdrachten op alle
computers worden uitgevoerd.
.sp
Een regel met 'pc01' als HOST zorgt ervoor dat de bijbehorende opdrachten
standaard alleen op pc01 worden uitgevoerd.
.br
Een regel met 'pc01 pc02' als HOST zorgt ervoor dat de bijbehorende opdrachten
standaard alleen op pc01 en pc02 worden uitgevoerd.
.br
Een regel met '#none' als HOST zorgt ervoor dat de bijbehorende opdrachten
standaard niet worden uitgevoerd (OPMERKING: '#none' is geen geldige
computernaam en wordt daarom nooit standaard geselecteerd).
.sp
[2]
.br
Een app kan alsnog worden geïnstalleerd op een andere computer met de opdracht\
 'kz install APP', zoals 'kz install vscode'. In dat geval wordt de
inhoud van HOST genegeerd.

.SH ZIE OOK
\fBkz-install\fR(1),
\fBkz-install.sh.gpg\fR(5)
