.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-install.sh (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-INSTALL.SH" "5" "4.2.1" "kz" "Bestandsindeling"

.SH NAAM
kz-install.sh - installatiebestand voor gebruik met kz install

.SH SAMENVATTING
.SY kz-install.sh
.YS

.SH BESCHRIJVING
Dit bestand bevat opdrachten om te verwerken als installatiebestand met kz
install.
.br
Opdrachten met persoonlijke informatie zoals een gebruikersnaam zijn opgenomen
in een versleuteld installatiebestand, kz-install.sh.gpg.
.sp
In het installatiebestand staan zogenaamde \fBapp-regel\fRs en
\fBopdracht-regel\fRs.
.sp
De \fBapp-regel\fR geeft aan waar de opdrachten uitgevoerd moeten worden en
wordt gevolgd door één of meer regels met opdrachten (\fBopdracht-regel\fRs).
.sp
Een \fBapp-regel\fR bestaat uit vijf delen, elk deel gescheiden door minstens
één spatie, zoals '# install <app> on <hosts>' en '# remove <app> from
<hosts>'.
.br
1. #        (commentaarsymbool)
.br
2. <actie>  (install of remove)
.br
3. <app>    (de naam van de app)
.br
4. on       (from als <actie> remove is)
.br
5. <hosts>  (de naam van de computer of computers)
.br
Hierna volgen één of meer \fBopdracht-regel\fRs met opdrachten voor <app>.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels er zijn en hoe deze regels
verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een \fBvoorbeeld\fR van deze regels en hoe deze regels
verwerkt worden.
Meer voorbeelden zijn te zien met de opdrachten \fBkz install --browse\fR en
\fBkz install --cat\fR.
.LP
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
l | l
l | l.
T{
# install \fI<app>\fR on <hosts>
T}:T{
De app \fI<app>\fR installeren op <hosts> (\fBapp-regel\fR)
T}
T{
# Commentaar...
T}:T{
Commentaarregel (geen, één of meer)
T}
T{
Opdracht
T}:T{
App installatie-opdracht (één of meer \fBopdracht-regel\fRs)
T}
T{
T}:T{
Lege regel (geen, één of meer)
T}
T{
# remove \fI<app>\fR from <hosts>
T}:T{
De app \fI<app>\fR verwijderen van <hosts> (\fBapp-regel\fR voor optie
\fB-r\fR, \fB--remove\fR)
T}
T{
Opdracht
T}:T{
Verwijder-opdracht (één of meer \fBopdracht-regel\fRs)
T}
.TE
.LP
.B Tabel 2. Voorbeeld van regels en hun verwerking
.TS
box tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l.
T{
# install libreoffice on *
T}:T{
Installeer app libreoffice op iedere computer, zie [1]
T}
T{
sudo apt-get install --assume-yes libreoffice
T}:T{
T}
T{
T}:T{
T}
T{
# remove libreoffice from *
T}:T{
Verwijder app libreoffice van iedere computer, zie [1]
T}
T{
sudo apt-get remove --purge --assume-yes libreoffice
T}:T{
T}
T{
T}:T{
T}
T{
# install ufw on pc01
T}:T{
Installeer app ufw alleen op pc01, zie [2]
T}
T{
sudo apt-get install --assume-yes gufw
T}:T{
T}
T{
T}:T{
T}
T{
# install kvm on pc01 pc02
T}:T{
Installeer app kvm op pc01 en pc02, zie [3]
T}
T{
sudo apt-get install --assume-yes qemu-kvm
T}:T{
T}
T{
T}:T{
T}
T{
# install google-earth on #none
T}:T{
Standaard niet app google-earth installeren, zie [4]
T}
T{
sudo apt-get install --assume-yes google-earth
T}:T{
T}
.TE
.sp
.sp
[1]
.br
De regel met '*' zorgt ervoor dat de bijbehorende opdrachten op alle computers
worden uitgevoerd.
.sp
[2]
.br
De regel met 'pc01' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc01 worden uitgevoerd.
.br
De app kan alsnog worden geïnstalleerd op een andere computer met de opdracht \
'kz install gnome'.
.sp
[3]
.br
De regel met 'pc01 pc02' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc01 en pc02 worden uitgevoerd.
.br
De app kan alsnog worden geïnstalleerd op een andere computer met de opdracht \
'kz install kvm'.
.sp
[4]
.br
De regel '#none' zorgt ervoor dat de bijbehorende opdrachten standaard niet
worden uitgevoerd op een computer (OPMERKING: '#none' is geen geldige
computernaam en wordt daarom nooit standaard geselecteerd).
.br
De app kan alsnog worden geïnstalleerd met de opdracht 'kz install google-eart\
h'.

.SH VOORBEELDEN
.EX
# install gnome-tweaks on pc01 pc06 pc07
# Adjust advanced settings.
if grep --quiet debian  /etc/os-release && [[ -n ${DISPLAY-} ]]; then sudo apt\
-get install --assume-yes gnome-tweaks; fi
if grep --quiet rhel    /etc/os-release && [[ -n ${DISPLAY-} ]]; then sudo dnf\
 install --assumeyes gnome-tweaks; fi
.sp
.RS
Met "if grep --quiet debian  /etc/os-release" wordt gecontroleerd of het een D\
ebian of Debian-gebaseerd systeem is, zoals Ubuntu.
Met "if grep --quiet rhel    /etc/os-release" wordt gecontroleerd of het een R\
ed Hat of Red Hat-gebaseerd systeem is, zoals Rocky Linux.
De "if [[ -n ${DISPLAY-} ]]" is om te controleren of er een grafische \
omgeving is.
.RE
.EE

.SH ZIE OOK
\fBkz-install\fR(1),
\fBkz-install.sh.gpg\fR(5)
