.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-install.sh (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-INSTALL.SH" "5" "4.2.1" "kz" "Bestandsindeling"

.SH NAAM
kz-install.sh - installatiebestand voor gebruik met kz install

.SH SAMENVATTING
.SY kz-install.sh
.YS

.SH BESCHRIJVING
Dit bestand bevat opdrachten om te verwerken als installatiebestand met kz
install.
.br
Opdrachten met persoonlijke informatie zoals een gebruikersnaam zijn opgenomen
in een versleuteld installatiebestand, kz-install.sh.gpg.
.sp
In het installatiebestand staan zogenaamde \fBapp-regel\fRs en
\fBopdracht-regel\fRs.
.sp
De \fBapp-regel\fR geeft aan waar de opdrachten uitgevoerd moeten worden en
wordt gevolgd door één of meer regels met opdrachten (\fBopdracht-regel\fRs).
.sp
Een \fBapp-regel\fR bestaat uit vier delen, elk deel gescheiden door minstens
één spatie, zoals '# INSTALL <app> <host>' en '# REMOVE <app> <host>'.
.br
1. #        (commentaarsymbool)
.br
2. <actie>  (INSTALL of REMOVE)
.br
3. <app>    (de naam van de app)
.br
4. <host>   (de naam van de computers of *)
.br
Hierna volgen één of meer \fBopdracht-regel\fRs met opdrachten voor <app>.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels er zijn en hoe deze regels
verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een \fBvoorbeeld\fR van deze regels en hoe deze regels
verwerkt worden.
.br
Meer voorbeelden zijn te zien met de opdrachten \fBkz install --browse\fR en
\fBkz install --cat\fR.
.LP
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
l | l
l | l.
T{
# INSTALL <app> <host>
T}:T{
De app <app> installeren op <host> (\fBapp-regel\fR)
T}
T{
# Commentaar...
T}:T{
Commentaarregel (geen, één of meer)
T}
T{
Opdracht
T}:T{
App installatie-opdracht (één of meer \fBopdracht-regel\fRs)
T}
T{
T}:T{
Lege regel (geen, één of meer)
T}
T{
# REMOVE <app> <host>
T}:T{
De app <app> verwijderen van <host> (\fBapp-regel\fR voor optie
\fB-r\fR, \fB--remove\fR)
T}
T{
Opdracht
T}:T{
Verwijder-opdracht (één of meer \fBopdracht-regel\fRs)
T}
.TE
.LP
.B Tabel 2. Voorbeeld van regels en hun verwerking
.TS
box tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l.
T{
# INSTALL calibre *
T}:T{
Installeer calibre op iedere computer, zie [1]
T}
T{
sudo apt-get install --assume-yes calibre
T}:T{
T}
T{
T}:T{
T}
T{
# REMOVE calibre *
T}:T{
Verwijder calibre van iedere computer, zie [1]
T}
T{
sudo apt-get remove --assume-yes calibre
T}:T{
T}
T{
T}:T{
T}
T{
# INSTALL calibre pc01
T}:T{
Installeer calibre alleen op pc01, zie [2]
T}
T{
sudo apt-get install --assume-yes calibre
T}:T{
T}
T{
T}:T{
T}
T{
# INSTALL calibre pc01 pc02
T}:T{
Installeer calibre op pc01 en pc02, zie [3]
T}
T{
sudo apt-get install --assume-yes calibre
T}:T{
T}
T{
T}:T{
T}
T{
# INSTALL calibre #none
T}:T{
Installeer calibre niet standaard, zie [4]
T}
T{
sudo apt-get install --assume-yes calibre
T}:T{
T}
.TE
.sp
.sp
[1]
.br
De regel met '*' zorgt ervoor dat de bijbehorende opdrachten op alle computers
worden uitgevoerd.
.sp
[2]
.br
De regel met 'pc01' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc01 worden uitgevoerd.
.br
De app kan alsnog worden geïnstalleerd op een andere computer met de opdracht \
'kz install calibre'.
.sp
[3]
.br
De regel met 'pc01 pc02' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc01 en pc02 worden uitgevoerd.
.br
De app kan alsnog worden geïnstalleerd op een andere computer met de opdracht \
'kz install calibre'.
.sp
[4]
.br
De regel '#none' zorgt ervoor dat de bijbehorende opdrachten standaard niet
worden uitgevoerd op een computer (OPMERKING: '#none' is geen geldige
computernaam en wordt daarom nooit standaard geselecteerd).
.br
De app kan alsnog worden geïnstalleerd met de opdracht 'kz install calibre'.

.SH VOORBEELDEN
.EX
# INSTALL calibre pc01
# -----------------------------------------------------------------------------
# E-book manager.
# -----------------------------------------------------------------------------
if grep --quiet debian /etc/os-release; then sudo apt-get install --a\
ssume-yes calibre; fi
if grep --quiet rhel   /etc/os-release; then sudo --validate && wget \
--output-document=- https://download.calibre-ebook.com/linux-installer.sh | su\
do sh; fi

# REMOVE calibre pc01
# -----------------------------------------------------------------------------
# E-book manager.
# -----------------------------------------------------------------------------
if grep --quiet debian /etc/os-release; then sudo apt-get remove --as\
sume-yes calibre; fi
if grep --quiet rhel   /etc/os-release; then sudo calibre-uninstall; \
fi
.EE

.SH ZIE OOK
\fBkz-install\fR(1),
\fBkz-install.sh.gpg\fR(5)
