.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-setup.sh (Dutch).
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-SETUP.SH" "5" "4.2.1" "kz" "Bestandsindeling"
.ad l

.SH NAAM
kz-setup.sh - instellingenbestand voor gebruik met kz setup

.SH SAMENVATTING
.SY kz-setup.sh
.YS

.SH BESCHRIJVING
Dit bestand bevat opdrachten om te verwerken als instellingenbestand met kz
setup.
.br
Opdrachten met persoonlijke informatie zoals een gebruikersnaam zijn opgenomen
in een versleuteld instellingenbestand, kz-setup.sh.gpg.
.sp
In het instellingenbestand staan zogenaamde \fBapp-\fR, \fBdesc-\fR,
\fBhost-\fR en \fBopdracht-regel\fRs.
.sp
De \fBapp-regel\fR geeft aan voor welke app de opdrachten uitgevoerd moeten
worden, de \fBdesc-regel\fR geeft een beschrijving van de app en de
\fBhost-regel\fR geeft aan op welke computers de opdrachten uitgevoerd moeten
worden.
.br
Deze regels worden gevolgd door één of meer regels met opdrachten, de
\fBopdracht-regel\fRs.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels er zijn en hoe deze regels
verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een \fBvoorbeeld\fR van deze regels en hoe deze regels
verwerkt worden.
.br
Meer voorbeelden zijn te zien met de opdrachten \fBkz setup --browse\fR en
\fBkz setup --cat\fR.
.LP
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
l | l
l | l.
T{
# Setup: <app>
T}:T{
Welke app instellen (\fBapp-regel\fR), wordt verwerkt.
T}
T{
# Desc:  <desc>
T}:T{
Een beschrijving van de app (\fBdesc-regel\fR), wordt verwerkt.
T}
T{
# Host:  <host>
T}:T{
Op welke computers de app ingesteld moet worden (\fBhost-regel\fR), wordt
verwerkt.
T}
T{
Opdracht
T}:T{
Instel-opdracht (één of meer \fBopdracht-regel\fRs), wordt uitgevoerd.
T}
T{
T}:T{
Lege regel (geen, één of meer), wordt overgeslagen.
T}
T{
# Reset: <app>
T}:T{
De app resetten (\fBapp-regel\fR voor optie \fB-r\fR, \fB--reset\fR), wordt
verwerkt.
.br
De beschrijving en computers worden overgenomen van de
.br
vooorgaande '# Setup: <app>' regel.
T}
T{
Opdracht
T}:T{
Reset-opdracht (één of meer \fBopdracht-regel\fRs), wordt uitgevoerd.
T}
T{
T}:T{
T}
T{
# Commentaar
T}:T{
Commentaarregel (geen, één of meer), wordt overgeslagen.
T}
.TE
.LP
.B Tabel 2. Voorbeeld van regels en hun verwerking
.TS
box tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l.
T{
# Setup: calibre
T}:T{
Stel calibre in.
T}
T{
# Desc:  Powerful and easy to use e-book manager.
T}:T{
Beschrijving van calibre.
T}
T{
# Host:  *
T}:T{
Calibre instellen op iedere computer, zie [1].
T}
T{
kz-desktop --addbef=calibre
T}:T{
Instel-opdracht voor calibre.
T}
T{
T}:T{
T}
T{
# Reset: calibre
T}:T{
Reset calibre.
T}
T{
kz-desktop --delete=calibre
T}:T{
Reset-opdracht voor calibre.
T}
.TE
.sp
[1]
.br
De regel met 'HOST *' zorgt ervoor dat de bijbehorende opdrachten op alle
computers worden uitgevoerd.
.sp
Een regel met 'HOST pc01' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc01 worden uitgevoerd.
.br
Een regel met 'HOST pc01 pc02' zorgt ervoor dat de bijbehorende opdrachten
standaard alleen op pc01 en pc02 worden uitgevoerd.
.br
Een regel met 'HOST #none' zorgt ervoor dat de bijbehorende opdrachten
standaard niet worden uitgevoerd (OPMERKING: '#none' is geen geldige\
computernaam en wordt daarom nooit standaard geselecteerd).
.br
Een app kan alsnog worden ingesteld met de opdracht 'kz setup <app>',
zoals 'kz setup calibre'.

.SH VOORBEELDEN
.EX
# Setup: calibre
# Desc:  Powerful and easy to use e-book manager.
# Host:  pc06
kz-desktop --addaft=calibre-gui

# Reset: calibre
kz-desktop --delete=calibre-gui
.EE

.SH ZIE OOK
\fBkz-setup\fR(1),
\fBkz-setup.sh.gpg\fR(5)
