.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-setup.sh (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-SETUP.SH" "5" "4.2.1" "kz" "Bestandsindeling"

.SH NAAM
kz-setup.sh - instelbestand voor gebruik met kz setup

.SH SAMENVATTING
.SY kz-setup.sh
.YS

.SH BESCHRIJVING
Dit bestand bevat opdrachten om te verwerken als instelbestand met kz setup.
.br
Opdrachten met persoonlijke informatie zoals een gebruikersnaam zijn opgenomen
in een versleuteld instelbestand, kz-setup.sh.gpg.
.sp
In het instelbestand staan zogenaamde \fBapp-regel\fRs en
\fBopdracht-regel\fRs.
.sp
De \fBapp-regel\fR geeft aan waar de opdrachten uitgevoerd moeten worden en
wordt gevolgd door één of meer regels met opdrachten (\fBopdracht-regel\fRs).
.sp
Een \fBapp-regel\fR bestaat uit vijf delen, elk deel gescheiden door minstens
één spatie, zoals '# setup <app> on <hosts>' en '# reset <app> on <hosts>'.
.br
1. #        (commentaarsymbool)
.br
2. <actie>  (setup of reset)
.br
3. <app>    (de naam van de app)
.br
4. on
.br
5. <hosts>  (de naam van de computer of computers)
.br
Hierna volgen één of meer \fBopdracht-regel\fRs met opdrachten voor <app>.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels er zijn en hoe deze regels
verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een \fBvoorbeeld\fR van deze deze regels en hoe deze
regels verwerkt worden.
Meer voorbeelden zijn te zien met de opdrachten \fBkz setup --browse\fR en
\fBkz setup --cat\fR.
.LP
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
l | l
l | l.
T{
# setup \fI<app>\fR on <hosts>
T}:T{
De app \fI<app>\fR instellen op <hosts> (\fBapp-regel\fR)
T}
T{
# Commentaar...
T}:T{
Commentaarregel
T}
T{
Opdracht
T}:T{
App instel-opdracht (één of meer \fBopdracht-regel\fRs)
T}
T{
T}:T{
Lege regel (geen, één of meer)
T}
T{
# reset \fI<app>\fR on <hosts>
T}:T{
De app \fI<app>\fR resetten op <hosts> (\fBapp-regel\fR voor optie
\fB-r\fR, \fB--reset\fR)
T}
T{
Opdracht
T}:T{
Reset-opdracht (één of meer \fBopdracht-regel\fRs)
T}
.TE
.LP
.B Tabel 2. Voorbeeld van regels en hun verwerking
.TS
box tab(:);
lb | lb.
T{
Regel
T}:T{
Beschrijving
T}
.T&
- | -
l | l
l | l.
T{
# setup google-chrome on *
T}:T{
Stel app google-chrome in op iedere computer, zie [1]
T}
T{
kz-desktop --addbef=google-chrome
T}:T{
T}
T{
T}:T{
T}
T{
# reset google-chrome on *
T}:T{
Reset app google-chrome op iedere computer, zie [1]
T}
T{
kz-desktop --delete=google-chrome
T}:T{
T}
T{
T}:T{
T}
T{
# setup gnome on pc01
T}:T{
Stel app gnome in alleen op pc01, zie [2]
T}
T{
gsettings set org.gnome.shell...
T}:T{
T}
T{
T}:T{
T}
T{
# setup kvm on pc01 pc02
T}:T{
Stel app kvm in op pc01 en pc02, zie [3]
T}
T{
kz-desktop --addaft=virt-manager
T}:T{
T}
T{
T}:T{
T}
T{
# setup google-earth on #none
T}:T{
Standaard niet app google-earth instellen, zie [4]
T}
T{
kz-desktop --addaft=google-earth
T}:T{
T}
.TE
.sp
.sp
[1]
.br
De regel met '*' zorgt ervoor dat de bijbehorende opdrachten op alle computers
worden uitgevoerd.
.sp
[2]
.br
De regel met 'pc01' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc01 worden uitgevoerd.
.br
De app kan alsnog worden ingesteld op een andere computer met de opdracht 'kz \
setup gnome'.
.sp
[3]
.br
De regel met 'pc01 pc02' zorgt ervoor dat de bijbehorende opdrachten standaard
alleen op pc01 en pc02 worden uitgevoerd.
.br
De app kan alsnog worden ingesteld op een andere computer met de opdracht 'kz \
setup kvm'.
.sp
[4]
.br
De regel met '#none' zorgt ervoor dat de bijbehorende opdrachten standaard
niet worden uitgevoerd (OPMERKING: '#none' is geen geldige computernaam en
wordt daarom nooit standaard geselecteerd).
.br
De app kan alsnog worden ingesteld met de opdracht 'kz setup google-earth'.

.SH VOORBEELDEN
.EX
# setup spotify on pc01 pc02 pc06 pc07
# Music and podcasts.
# Web app: https://open.spotify.com
if grep --quiet debian /etc/os-release && [[ -n ${DISPLAY-} ]]; then kz-deskto\
p --addaft=spotify; fi
if grep --quiet rhel   /etc/os-release && [[ -n ${DISPLAY-} ]]; then kz-deskto\
p --addaft=kz-spotify; fi
.sp
.RS
Met "if grep --quiet debian /etc/os-release" wordt gecontroleerd of het een De\
bian of Debian-gebaseerd systeem is, zoals Ubuntu.
Met "if grep --quiet rhel   /etc/os-release" wordt gecontroleerd of het een Re\
d Hat of Red Hat-gebaseerd systeem is, zoals Rocky Linux.
De "if [[ -n ${DISPLAY-} ]]" is om te controleren of er een grafische \
omgeving is.
.RE
.EE

.SH ZIE OOK
\fBkz-setup\fR(1),
\fBkz-setup.sh.gpg\fR(5)
