.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-setup.sh.gpg (Dutch)
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-SETUP.SH.GPG" "5" "4.2.1" "kz" "Bestandsindeling"

.SH NAAM
kz-setup.sh.gpg - GPG-versleuteld instellingenbestand voor gebruik met kz setup

.SH SAMENVATTING
.SY kz-setup.sh.gpg
.YS

.SH BESCHRIJVING
Dit bestand bevat opdrachten om te verwerken als instellingenbestand met kz
setup.
.sp
Opdrachten met persoonlijke informatie zoals een gebruikersnaam zijn opgenomen
in dit versleuteld instellingenbestand.
.br
Deze opdrachten zijn aangegeven met '#gpg' aan het einde van de regel.
.sp
Dit bestand is aangemaakt met de volgende voorbeeldopdrachten:
.br
gpg --import /usr/share/kz/kz-public-key.gpg
.br
gpg --output ~/kz-scripts/usr/bin/kz-setup.sh.gpg --sign ~/kz-setup.sh.gpg.sh
.sp
Dit bestand wordt ontsleuteld voordat de opdrachten worden gebruikt in script
kz-setup met bijvoorbeeld de opdrachten:
.br
gpg --import /usr/share/kz/kz-public-key.gpg
.br
gpg --output ~/kz-setup.sh.gpg.sh --decrypt
~/kz-scripts/usr/bin/kz-setup.sh.gpg
.sp
Gebruik voor de opmaak van de records in dit instellingenbestand
\fBman kz setup.sh\fR.

.SH ZIE OOK
\fBkz-setup\fR(1),
\fBkz-setup.sh\fR(5)
