.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-setup.sh (Dutch).
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-SETUP.SH" "5" "4.2.1" "kz" "Bestandsindeling"
.ad l

.SH NAAM
kz-setup.sh - instellingenbestand voor gebruik met kz setup

.SH SAMENVATTING
.SY kz-setup.sh
.YS

.SH BESCHRIJVING
Dit bestand bevat opdrachten om te verwerken als instellingenbestand met kz
setup.
.br
Opdrachten met persoonlijke informatie zoals een gebruikersnaam zijn opgenomen
in een versleuteld instellingenbestand, kz-setup.sh.gpg.
.sp
In het instellingenbestand staan zogenaamde \fBapp-\fR en
\fBopdracht-regel\fRs.
.sp
De \fBapp-regel\fR geeft aan voor welke app en welke computer de opdrachten
uitgevoerd moeten worden en geeft een beschrijving van de app.
.sp
De \fBapp-regel\fR geeft aan voor welke app en welke computer de opdrachten
uitgevoerd moeten worden en geeft een beschrijving van de app.
.br
Zo'n regel is ingedeeld als een psv-regel (pipe-separated values), de velden
worden gescheiden door het pipe-teken '|':
.br
#|ACTIE|APP|HOST|BESCHRIJVING
.TS
box tab(^);
lb lb lbx
l l l.
Veld-nummer^Veld^Beschrijving
1^#^Hekje, commentaarsymbool
2^ACTIE^Actie, 'setup' of 'reset'
3^APP^Naam van de app
4^HOST^Naam van de computer(s) waarop de opdracht uitgevoerd moet worden
5^BESCHRIJVING^Beschrijving van de app
.TE
.sp
Deze regels worden gevolgd door één of meer regels met opdrachten, de
\fBopdracht-regel\fRs.
.br
Deze opdrachten kunnen ook in het Terminalvenster op de opdrachtregel worden
uitgevoerd.
.sp
Zie \fBTabel 1\fR voor welke \fBsoorten\fR regels er zijn en hoe deze regels
verwerkt worden.
.sp
Zie \fBTabel 2\fR voor een \fBvoorbeeld\fR van deze regels en hoe deze regels
verwerkt worden.
.br
Meer voorbeelden zijn te zien met de opdrachten \fBkz setup --browse\fR en
\fBkz setup --cat\fR.
.LP
.B Tabel 1. Soorten regels en hun verwerking
.TS
allbox tab(^);
lb lbx
l l.
Regel^Beschrijving
#|setup|APP|HOST|BESCHRIJVING^De app instellen (\fBapp-regel\fR), word\
t verwerkt.
# Commentaar^Commentaarregel (geen, één of meer), wordt overgeslagen.
Opdracht^Instel-opdracht (één of meer \fBopdracht-regel\fRs), wordt uitgevoerd.
^Lege regel (geen, één of meer), wordt overgeslagen.
#|reset|APP|HOST|BESCHRIJVING^De app resetten (\fBapp-regel\fR voor op\
tie \fB-r\fR, \fB--reset\fR), wordt verwerkt.
Opdracht^Reset-opdracht (één of meer \fBopdracht-regel\fRs), wordt uitgevoerd.
.TE
.LP
.B Tabel 2. Voorbeeld van regels en hun verwerking
.TS
box tab(^);
lb | lbx
- | -
l | l.
Regel^Beschrijving
#|setup|calibre|*|Powerful and easy to use e-book manager^Calibre instell\
en op iedere computer, zie [1].
kz-desktop --addbef=calibre-gui^Instel-opdracht voor calibre.
^
#|reset|calibre|*|Powerful and easy to use e-book manager^Calibre resette\
n op iedere computer, zie [1].
kz-desktop --delete=calibre-gui^Reset-opdracht voor calibre.
^
^
#|setup|vscode|pc06 pc07|Code editing. Redefined^Vscode instell\
en op pc06 en pc07, zie [2].
# kz-desktop --addaft=code^Instel-opdracht voor vscode.
^
#|reset|vscode|pc06 pc07|Code editing. Redefined^Vscode resetten op pc06 \
en pc07, zie [2].
kz-desktop --delete=code^Reset-opdracht voor vscode.
.TE
.sp
[1]
.br
De regel met '*' als HOST zorgt ervoor dat de bijbehorende opdrachten op alle
computers worden uitgevoerd.
.sp
Een regel met 'pc01' als HOST zorgt ervoor dat de bijbehorende opdrachten
standaard alleen op pc01 worden uitgevoerd.
.br
Een regel met 'pc01 pc02' als HOST zorgt ervoor dat de bijbehorende opdrachten
standaard alleen op pc01 en pc02 worden uitgevoerd.
.br
Een regel met '#none' als HOST zorgt ervoor dat de bijbehorende opdrachten
standaard niet worden uitgevoerd (OPMERKING: '#none' is geen geldige
computernaam en wordt daarom nooit standaard geselecteerd).
.sp
[2]
.br
Een app kan alsnog worden ingesteld op een andere computer met de opdracht 'kz
setup APP', zoals 'kz setup vscode'. In dat geval wordt de inhoud
van HOST genegeerd.

.SH ZIE OOK
\fBkz-setup\fR(1),
\fBkz-setup.sh.gpg\fR(5)
