.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-backup
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-BACKUP" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-backup - backup home folder

.SH SYNOPSIS
.SY kz\ backup
[<options>]
.YS

.SH DESCRIPTION
\fBkz backup\fR makes a backup copy of the Home folder.
.sp
In a desktop environment command \fBkz backup\fR can be executed by
searching for \fBback\fR, click on \fBKZ Backup home folder\fR pictogram.
.sp
Before a backup is made, if possible, the set desktop background, user picture,
favorites, and WiFi information are saved. See \fBFILES\fR section below for
the exact location.
.sp
The backup is placed on a mounted USB medium such as a USB external hard disk
in folder \fB<username>@<computername>\fR, this folder is created as needed,
for example /media/karel/backupdisk/karel@pc-of-karel for Karel at pc-of-karel.
.sp
With option \fB-g\fR, \fB--gui\fR, \fBkz backup\fR runs in graphical mode. A
desktop environment is required.
.sp
With option \fB-t\fR, \fB--target\fR \fI<directory>\fR another location can be
specified. For example /media/karel/usbstick instead of
/media/karel/backupdisk.
.sp
Locations ignored by \fBkz backup\fR are directories managed by Git.
Example: ~/kz-scripts is skipped due to the presence of ~/kz-scripts/.git.
.sp
Tool rsync is used to create the backup.
.br
Files deleted from the Home folder are also removed from the backup (rsync's
--delete option is used).
.sp
If errors are found, an overview of these messages is given.
.sp
With command \fBkz restore\fR the Home folder can be restored.

.SH OPTIONS
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB-g\fR, \fB--gui\fR
Run in graphical mode (gui=graphical user interface). A desktop environment is
required.
.TP
\fB-t\fR, \fB--target \fI<directory>\fR
Place the backup in the specified directory.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Show the version, author, and copyright.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH FILES
~/Settings/apps.txt
.RS
List of installed apps. For checking installation.
.RE
.sp
~/Settings/avatar
.RS
Backup of user avatar, if available.
.RE
.sp
~/Settings/avatar.txt
.RS
Instructions for restoring the user avatar, if available.
.RE
.sp
~/Settings/desktop
.RS
Backup of desktop background, if available.
.RE
.sp
~/Settings/desktop.txt
.RS
Instructions for restoring the desktop background, if available.
.RE
.sp
~/Settings/favs.txt
.RS
Set favorites in the favorites bar (dash/dock). For checking set up.
.RE
.sp
~/Settings/users.txt
.RS
Instructions for adding additional users.
.RE
.sp
~/Settings/wifi.txt
.RS
Saved WiFi information.
.RE
.sp
/tmp/kz-backup-XXXXXXXXXX.exclude
.RS
Exclude file, e.g. kz-backup-4VkzCfrDsU.exclude.
.RE
.sp
/tmp/kz-backup-XXXXXXXXXX-error.log
.RS
Error log file, e.g. kz-backup-Nndq1y3iFo-errorl.og.
.RE

.SH EXAMPLES
.EX
.sp
\fBkz backup\fR
.RS
Make a backup copy of the Home folder.
Starter \fBMake a backup\fR is also available for this in a desktop
environment.
.RE
.sp
\fBkz backup --target /media/karel/usbstick\fR
.RS
Back up the Home folder of Karel on pc-of-karel to /media/karel/usbstick in the
folder karel@pc-of-karel (this folder will be created as needed).
.RE
.EE

.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1),
\fBkz-restore\fR(1)

.SH KZ
Part of the \fBkz\fR(1) package.

.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
.UR https://karelzimmer.nl/en
.UE
.RE
.IP " 2." 4
Day 2 Operations
.RS 4
\fBkz backup\fR is mainly used for Day 2 Operations. See \fBkz\fR(1) for an
explanation.
.RE
