.\"############################################################################
.\"# Man page for kz-backup.
.\"#
.\"# Written by Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
.\"# <https://creativecommons.org/publicdomain/zero/1.0>.
.\"############################################################################
.\"
.TH "KZ-BACKUP" "1" "Kz Manual" "kz 4.2.1" "Kz Manual"
.\"
.\"
.SH NAME
kz-backup \- Make backup.
.\"
.\"
.SH SYNOPSIS
.B kz backup
[OPTION...]
.\"
.\"
.SH DESCRIPTION
\fBkz backup\fR makes a backup copy of the Home folder.
.sp
In a graphical working environment command \fBkz backup\fR can be executed by
searching for \fBback\fR, click on \fBMake backup\fR.
.sp
n a graphical working environment before a backup is made, the set desktop
background, userphoto, favorites, and list of apps are backed up in Home / .kz.
.sp
The backup is placed on a mounted USB medium such as a USB external hard disk
in folder \fBbackup-<computer name>-<user_name>\fR, this folder is
created as needed, for example /media/john/backupdisk/backup-pc02-john for John
at pc02.
.sp
With option \fB-t\fR, \fB--target\fR \fIDIRECTORY\fR another location can be
specified. For example /media/john/usbstick instead of /media/john/backupdisk.
.sp
Option \fB-d\fR, \fB--dry-run\fR performs a trial run without making any
changes. It is usually used in conjunction with rsync's --delete option to see
what an rsync command will do before actually executing it.
.sp
These locations are ignored by default:
.RS
 .adobe/Flash_Player/AssetCache
 .cache
 .ccache
 .gvfs
 .Private
 .recent-applications.xbel
 .recently-used.xbel
 .steam/root
 .thumbnails
 .var/src/*/cache
 .xsession-errors
 snap/*/*/.cache
 *CACHEDIR.TAG*
.RE
Also, directories managed by Git are not backed up.
Example: ~/bin is skipped due to the presence of ~/bin/.git.
.sp
rsync is used to create the backup.
.sp
Files deleted from the Home folder are also removed from the backup (rsync's
--delete option is used).
.sp
With command \fBkz restore\fR the Home folder can be restored.
.\"
.\"
.SH OPTIONS
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB-d\fR, \fB--dry-run\fR
Perform a test run without making any changes.
.TP
\fB-t\fR, \fB--target \fIDIRECTORY\fR
Place the backup in the \fIDIRECTORY\fR.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.TP
\fB-g\fR, \fB--gui\fR
Start in graphical mode (gui graphical user interface).
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.
.\"
.\"
.SH FILES
~/.kz/apps
.RS
List of installed apps.
.RE
.sp
~/.kz/background
.RS
Set desktop background.
.RE
.sp
~/.kz/favorites
.RS
Set favorites in the favorites bar (dash/dock).
.RE
.sp
~/.kz/userphoto
.RS
Set user photo.
.RE
.\"
.\"
.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
https://karelzimmer.nl/html/en/linux.html#documents
.RE
.IP " 2." 4
Day 2 Operations
.RS 4
\fBkz backup\fR is mainly used for Day 2 Operations. See \fBkz\fR(1) for an
explanation.
.RE
.\"
.\"
.SH EXAMPLES
.sp
\fBkz backup\fR
.RS
Make a backup copy of the Home folder.
Starter \fBMake a backup\fR is also available for this in a graphical work
environment.
.RE
.sp
\fBkz backup --dry-run\fR
.RS
Show files that would otherwise be added and removed in the backup.
.RE
.sp
\fBkz backup --target /media/john/usbstick\fR
.RS
Back up the Home folder of John on pc02 to /media/john/usbstick in the folder
backup-pc02-john (this folder will be created as needed).
.RE
.\"
.\"
.SH AUTHOR
Written by Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
<https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1),
\fBkz-restore\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator, Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz backup\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website <https://karelzimmer.nl/en>, under Linux.
