.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-build
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-BUILD" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-build - build website and kz packages

.SH SYNOPSIS
.SY kz\ build
[<options>]
.YS

.SH DESCRIPTION
\fBkz build\fR builds the website karelzimmer.nl and the Debian and RPM package
kz.
.sp
The built Debian package, kz, will then be installed locally.
.sp
With option \fB-d\fR, \fB--dev\fR the development version of the kz package is
created.
.sp
If the development repositories are not on main or not clean, also a
development version will be created (kz-dev-....).
.sp
This is to develop and test the package, the website, and the installation, and
to distribute it later with \fBkz deploy\fR.
.sp
The local kz-docs and kz-scripts Git repositories are used as inputs. Text
files are converted into pdf files with 'lowriter convert-to pdf'.
.sp
With command \fBkz deploy\fR the website and kz packages can be placed
on the internet so that the scripts and documents are available for general
use.
.sp
Command \fBkz build\fR can only be run in a desktop environment.

.SH OPTIONS
.TP
\fB-d\fR, \fB--dev\fR
Build the development version of package kz.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Show the version, author, and copyright.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH FILES
~/kz-deb/src/*
.RS
Source files Debian package kz (Git).
.RE
.sp
~/kz-deb/dist/*
.RS
Distribution files Debian package kz.
.RE
.sp
~/kz-rpm/src/*
.RS
Source files RPM package kz (Git).
.RE
.sp
~/kz-rpm/dist/*
.RS
Distribution files RPM package kz.
.RE
.sp
~/kz-docs/*
.RS
Checklists (Git).
.RE
.sp
~/kz-scripts/*
.RS
Scripts (Git).
.br
Includes e.g. translation files, manual pages, and Polkit action definition
files.
.RE
.sp
~/kz-uploads/src/*
.RS
Source files website karelzimmer.nl (Git).
.RE
.sp
~/kz-uploads/dist/*
.RS
Distribution files website karelzimmer.nl.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz_4.2.1-1_all.deb
.RS
Debian package kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-dev_4.2.1-1_all.deb
.RS
Debian development package kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-4.2.1-1.noarch.rpm
.RS
RPM package kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-dev-4.2.1-1.noarch.rpm
.RS
RPM development package kz.
.RE
.sp
/usr/share/doc/kz/build.id
.RS
Build ID file.
.RE

.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-check\fR(1),
\fBkz-deploy\fR(1)

.SH KZ
Part of the \fBkz\fR(1) package.

.SH NOTES
.IP " 1." 4
CI/CD and Day 1 Operations
.RS 4
\fBkz build\fR is mainly used for \fBCI/CD\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
