.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-dev
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-DEV" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-dev - build development environment

.SH SYNOPSIS
.SY kz\ dev
[<options>]
.YS

.SH DESCRIPTION
\fBkz dev\fR downloads the website karelzimmer.nl and builds the development
environment for the the Debian and RPM package kz.
.sp
This is to test the package and the website, and to distribute it later with
\fBkz deploy\fR.
.sp
Various remote Git repositories are used as input.
.sp
With command \fBkz build\fR the package kz and the website can be built.
.br
With command \fBkz deploy\fR the package kz and the website can be placed on
the internet.
.sp
Command \fBkz dev\fR can only be run in a desktop environment.

.SH OPTIONS
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Show the version, author, and copyright.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH FILES
~/kz-deb/src/*
.RS
Source files package kz (Git).
.RE
.sp
~/kz-deb/dist/*
.RS
Distribution files package kz.
.RE
.sp
~/kz-docs/*
.RS
Checklists (Git).
.RE
.sp
~/kz-scripts/*
.RS
Scripts (Git).
.br
Includes manual pages (usr/share/man/),
.br
Tab completion scripts (usr/share/bash-completion/completions/),
.br
Desktop configuration files (usr/share/applications/) en
.br
Polkit action definition files (usr/share/policypolkit-1/actions/).
.RE
.sp
~/kz-uploads/src/*
.RS
Source files website karelzimmer.nl (Git).
.RE
.sp
~/kz-uploads/dist/*
.RS
Distribution files website karelzimmer.nl.
.RE
.sp
~/bin/gitclone
.RS
Git clone of all public remote repos in the home directory.
.RE
.sp
~/bin/gitpull
.RS
Git pull of all local branches in the home directory.
.RE
.sp
~/bin/gitstatus
.RS
Git status of all local branches in the home directory.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz_4.2.1-1_all.deb
.RS
Debian package kz.
.RE

.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-build\fR(1),
\fBkz-deploy\fR(1),
\fBkz-get\fR(1),
\fBkz-install\fR(1),
\fBkz-setup\fR(1)

.SH KZ
Part of the \fBkz\fR(1) package.

.SH NOTES
.IP " 1." 4
CI/CD and Day 0 Operations
.RS 4
\fBkz dev\fR is mainly used for \fBCI/CD\fR and \fBDay 0 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
