.\"############################################################################
.\"# Man page for kz-deploy.
.\"#
.\"# Written in 2019 by Karel Zimmer <info@karelzimmer.nl>, Creative Commons
.\"# Public Domain Dedication
.\"# <https://creativecommons.org/publicdomain/zero/1.0>.
.\"############################################################################
.\"
.TH KZ-DEPLOY 1 "Kz Manual" "kz 365" "Kz Manual"
.\"
.\"
.SH NAME
kz-deploy \- Distribute kz package.
.\"
.\"
.SH SYNOPSIS
.B kz deploy
[OPTION...]
.\"
.\"
.SH DESCRIPTION
\fBkz deploy\fR distributes package kz.
.br
This is to make the scripts and documents available for general use.
.sp
The scripts and documents have also been placed on GitHub, which can be
obtained via:
.br
\fBgit clone https://github.com/karelzimmer/kz-docs.git\fR
.br
\fBgit clone https://github.com/karelzimmer/kz-scripts.git\fR
.sp
Sequentially performs a check, builds package kz, distributes website, and
installs.
.\"
.\"
.SH OPTIONS
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value not equal
to 0.
.\"
.\"
.SH DIRECTORIES
~/kz-uploads/app
.RS
Base files website (Git).
.RE
.sp
~/kz-uploads/dist
.RS
Distribution files website.
.RE
.\"
.\"
.SH FILES
~/kz-uploads/downloads/kz/kz_365_all.deb
.RS
Debian package kz.
.RE
.\"
.\"
.SH NOTES
.IP " 1." 4
CI/CD and Day 1 Operations
.RS 4
\fBkz deploy\fR is mainly used for \fBCI/CD\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
.\"
.\"
.SH AUTHOR
Written in 2009 by Karel Zimmer <info@karelzimmer.nl>, Creative Commons
Public Domain Dedication <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-build\fR(1),
\fBkz-ckname\fR(1),
\fBkz-deploy\fR(1),
\fBkz-getdeb\fR(1),
\fBkz-getdev\fR(1),
\fBkz-ivp\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz deploy\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website
.br
<https://karelzimmer.nl/html/en/linux.html#scripts>.
