.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-deploy
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-DEPLOY" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-deploy - distribute website and kz packages

.SH SYNOPSIS
.SY kz\ deploy
[<options>]
.YS

.SH DESCRIPTION
\fBkz deploy\fR builds and distributes package kz and the website.
.sp
The \fBkz deploy\fR command builds and places the kz package and the website on
the Internet so that the scripts and documents are available for general use.
.sp
With option \fB-d\fR, \fB--dev\fR the development version of the kz package is
distributed.
.sp
With command \fBkz get\fR package kz can be installed on the local computer.
.sp
With command \fBkz dev\fR the development environment (website plus package kz)
can be placed on the local computer.
.sp
Command \fBkz deploy\fR can only be run in a desktop environment.

.SH OPTIONS
.TP
\fB-d\fR, \fB--dev\fR
Deploy the development version of package kz.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Show the version, author, and copyright.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH FILES
~/kz-deb/src/*
.RS
Source files package kz (Git).
.RE
.sp
~/kz-deb/dist/*
.RS
Distribution files package kz.
.RE
.sp
~/kz-docs/*
.RS
Checklists (Git).
.RE
.sp
~/kz-scripts/*
.RS
Scripts (Git).
.br
Includes e.g. translation files, manual pages, and Polkit action definition
files.
.RE
.sp
~/kz-uploads/src/*
.RS
Source files website karelzimmer.nl (Git).
.RE
.sp
~/kz-uploads/dist/*
.RS
Distribution files website karelzimmer.nl.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz_4.2.1-1_all.deb
.RS
Debian package kz.
.RE

.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-check\fR(1),
\fBkz-build\fR(1),
\fBkz-dev\fR(1),
\fBkz-get\fR(1)

.SH KZ
Part of the \fBkz\fR(1) package.

.SH NOTES
.IP " 1." 4
CI/CD and Day 1 Operations
.RS 4
\fBkz deploy\fR is mainly used for \fBCI/CD\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
