.\"############################################################################
.\"# Man page for kz-getdev.
.\"#
.\"# Written Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
.\"# <https://creativecommons.org/publicdomain/zero/1.0>, 2023.
.\"############################################################################
.\"
.TH "KZ-GETDEV" "1" "2023" "kz 2.4.7" "Kz Manual"
.\"
.\"
.SH NAME
kz-getdev \- Build development environment.
.\"
.\"
.SH SYNOPSIS
.B kz getdev
[OPTION...]
.\"
.\"
.SH DESCRIPTION
\fBkz getdev\fR builds the development environment for the kz package and the
website https://karelzimmer.nl.
.sp
This is to test the package and the website, and to distribute it later with
\fBkz deploy\fR.
.sp
Various remote Git repositories are used as input.
.sp
With command \fBkz build\fR the package kz and the website can be built.
.sp
With command \fBkz deploy\fR the package kz and the website can be placed on
the internet.
.\"
.\"
.SH OPTIONS
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value not equal
to 0.
.\"
.\"
.SH DIRECTORIES
~/kz-deb/app/
.RS
Base files package kz (Git).
.RE
.sp
~/kz-deb/dist/
.RS
Distribution files package kz.
.RE
.sp
~/kz-docs/
.RS
Checklists (Git).
.RE
.sp
~/kz-scripts/
.RS
Scripts (Git).
Includes manual pages (usr/share/man/man1/ and usr/share/man/nl/man1/),
Tab completion scripts (usr/share/bash-completion/completions/),
Desktop configuration files (usr/share/applications/), en
PolicyKit action definition files (usr/share/policypolkit-1/actions/).
.RE
.sp
~/kz-uploads/app/
.RS
Base files website karelzimmer.nl (Git).
.RE
.sp
~/kz-uploads/dist/
.RS
Distribution files website karelzimmer.nl.
.RE
.\"
.\"
.SH FILES
~/bin/gitpull
.RS
Git pull (or git clone) of all public remote repos.
.RE
.sp
~/bin/gitstat
.RS
Git status of all local branches.
.RE
.sp
~/kz-uploads/dist/assets/kz/kz_2.4.7_all.deb
.RS
Debian package kz.
.RE
.\"
.\"
.SH NOTES
.IP " 1." 4
CI/CD and Day 0 Operations
.RS 4
\fBkz getdev\fR is mainly used for \fBCI/CD\fR and \fBDay 0 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
.\"
.\"
.SH AUTHOR
Written by Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
<https://creativecommons.org/publicdomain/zero/1.0>, 2023.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-build\fR(1),
\fBkz-deploy\fR(1),
\fBkz-getdeb\fR(1),
\fBhttps://karelzimmer.nl\fR,
\fBgitpull\fR,
\fBgitstat\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator, Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz getdev\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website <https://karelzimmer.nl/html/en/linux.html#scripts>.
