.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-get
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-GET" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-get - download and install Debian or RPM package kz

.SH SYNOPSIS
.SY kz\ get
[<options>]
.YS
.SY wget\ karelzimmer.nl/getkz;\ bash\ getkz
.YS

.SH DESCRIPTION
\fBkz get\fR downloads and installs Debian or RPM package kz.
.sp
With option \fB-d\fR, \fB--dev\fR the development version of the kz package is
processed.
.sp
Debian package kz contains scripts to install Debian and Debian-based systems
such as Ubuntu smoothly and usably.
.br
RPM package kz contains scripts to install and manage Red Hat-based systems
such as Rocky Linux smoothly and usably.
.sp
For the latest version of \fBkz get\fR and package kz, launch a Terminal and
run (copy of getkz will be saved and later deleted):
.br
    \fBwget karelzimmer.nl/getkz\fR
.br
    \fBbash getkz\fR
.br
 or (same as before, now on 1 line):
.br
    \fBwget karelzimmer.nl/getkz; bash getkz\fR
.br
 or (no copy of getkz is saved):
.br
    \fBwget -O- karelzimmer.nl/getkz | bash\fR
.br
 or (if curl is installed, no copy):
.br
    \fBcurl -L karelzimmer.nl/getkz | bash\fR
.br
 or (if package kz is already installed):
.br
    \fBkz get\fR
.sp
If the install fails for some reason, on a Debian or Debian-based system you
can try the following:
    sudo dpkg --configure --pending
    sudo apt-get update --fix-missing
    sudo apt-get install --fix-broken
.br
On a Red Hat or Red Hat-based system try the following:
    sudo dnf clean all
    sudo dnf makecache
.sp
With command \fBkz dev\fR the development environment can be placed on the
local computer so that the package and the website can be developed and tested.

.SH OPTIONS
.TP
\fB-d\fR, \fB--dev\fR
Download and install the development version of the kz package.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH FILES
/tmp/kz-get-XXXXXXXXXX.deb
.RS
Downloaded debian file, e.g. kz-get-AEOzIjJyie.deb.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz_4.2.1-1_all.deb
.RS
Debian package kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-dev_4.2.1-1_all.deb
.RS
Debian development package kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-4.2.1-1.noarch.rpm
.RS
RPM package kz.
.RE
.sp
~/kz-uploads/dist/assets/packages/kz-dev-4.2.1-1.noarch.rpm
.RS
RPM development package kz.
.RE

.SH SEE ALSO
\fBkz\fR(1),
\fBkz-dev\fR(1)

.SH KZ
Part of the \fBkz\fR(1) package.

.SH NOTES
.IP " 1." 4
IaC en Day 1 Operations
.RS 4
\fBkz get\fR is mainly used for \fBIaC\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
