.\"############################################################################
.\"# Man page for kz-getdeb.
.\"#
.\"# Written in 2019 by Karel Zimmer <info@karelzimmer.nl>, Creative Commons
.\"# Public Domain Dedication
.\"# <https://creativecommons.org/publicdomain/zero/1.0>.
.\"############################################################################
.\"
.TH KZ-GETDEB 1 "Kz Manual" "kz 365" "Kz Manual"
.\"
.\"
.SH NAME
kz-getdeb \- Install kz package.
.\"
.\"
.SH SYNOPSIS
.B kz getdeb
[OPTION...]
.\"
.\"
.SH DESCRIPTION
\fBkz getdeb\fR assets and installs package kz.
.sp
Package kz puts documents and scripts from Karel Zimmer for installing and
managing Debian and Debian based system like Ubuntu.
.sp
For the latest version of \fBkz getdeb\fR and kz package, launch a Terminal and
run (copy of kz will be saved and later deleted):
.br
    \fBwget karelzimmer.nl/kz\fR
.br
    \fBbash kz\fR
.br
 or (same as before, now on 1 line):
.br
    \fBwget karelzimmer.nl/kz; bash kz\fR
.br
 or (no copy of kz is saved):
.br
    \fBwget -O- karelzimmer.nl/kz | bash\fR
.br
 or (if curl is installed, no copy):
.br
    \fBcurl -L karelzimmer.nl/kz | bash\fR
.br
 or (if package kz is already installed):
.br
    \fBkz getdeb\fR
.sp
With command \fBkz getdev\fR the development environment can be placed on the
local computer so that the package and the website can be developed and tested.
.\"
.\"
.SH OPTIONS
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value not equal
to 0.
.\"
.\"
.SH NOTES
.IP " 1." 4
IaC en Day 1 Operations
.RS 4
\fBkz getdeb\fR is mainly used for \fBIaC\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
.\"
.\"
.SH EXAMPLES
Download a website? Then run:
.br
\fBmkdir --parents ~/uploads/karelzimmer.nl/httpdocs
.br
lftp --user <USER> --password <PASSWORD> <HOST> -e\
 'set ssl:verify-certificate no; mirror --delete --verbose /httpdocs
~/uploads/karelzimmer.nl/httpdocs; exit'\fR
.sp
Upload a website? Then run:
.br
\fBlftp --user <USER> --password <PASSWORD> <HOST> -e\
 'set ssl:verify-certificate no; mirror --reverse --delete --verbose /httpdocs
~/uploads/karelzimmer.nl/httpdocs; exit'\fR
.sp
Download a single file? Then run:
.br
\fBlftp --user <USER> --password <PASSWORD> <HOST> -e\
 'set ssl:verify-certificate no; get -O /httpdocs/<DIR>
~/uploads/karelzimmer.nl/httpdocs/<DIR>/<FILE>; exit'\fR
.sp
Upload a single file? Then run:
.br
\fBlftp --user <USER> --password <PASSWORD> <HOST> -e\
 'set ssl:verify-certificate no; put -O /httpdocs/<DIR>
~/uploads/karelzimmer.nl/httpdocs/<DIR>/<FILE>; exit'\fR
.\"
.\"
.SH AUTHOR
Written in 2016 by Karel Zimmer <info@karelzimmer.nl>, Creative Commons
Public Domain Dedication <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-getdev\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz getdeb\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website
.br
<https://karelzimmer.nl/html/en/linux.html#scripts>.
