.\"############################################################################
.\"# Man page for kz-install.
.\"#
.\"# Written Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
.\"# <https://creativecommons.org/publicdomain/zero/1.0>, 2023.
.\"############################################################################
.\"
.TH "KZ-INSTALL" "1" "2009-2023" "kz 365" "Kz Manual"
.\"
.\"
.SH NAME
kz-install \- Install apps.
.\"
.\"
.SH SYNOPSIS
.B kz install
[OPTION...] [\fIAPP\fR...] [\fIFILE\fR...]
.\"
.\"
.SH DESCRIPTION
\fBkz install\fR installs apps and changes system settings.
.sp
In a graphical work environment command \fBkz install\fR can be executed by
searching for \fBapps\fR, click on \fBApps install\fR.
.sp
Use \fBkz setup\fR (after \fBkz install\fR) to set up apps and change user
settings.
.sp
\fBkz install\fR handles so-called installation files that contain commands for
installing apps and changing system settings.
.sp
By default, \fBkz install\fR handles the following two installation files:
.br
- /usr/bin/kz-install-<distribution>-desktop.sh
.br
- /usr/bin/kz-install-<distribution>-desktop-<computername>.sh (if present)
.sp
<distribution> and <computername> are populated with values from the current
computer.
.sp
For example, kz-install-ubuntu-desktop.sh and
kz-install-ubuntu-desktop-pc02.sh.
.br
These installation files contain commands for ubuntu desktop general and ubuntu
desktop on pc02.
.sp
For the format of the installation files see the section \fBFILE FORMAT\fR
below.
.sp
If no \fIAPP\fRs or \fIFILE\fRs are specified, the names of the default
installation files are included in the list of files to process.
.sp
With option \fB--server\fR server is used instead of desktop.
.sp
Option \fB-f\fR, \fB--files\fR lists installation files.
.sp
It is possible to specify \fIFILE\fRs; these files should be starting with
\fBkz-install-\fR and ending with \fB.sh\fR.
.br
Anything else is considered an \fIAPP\fR, see below.
.br
The specified \fIFILE\fRs are included in the list of files to be processed.
.sp
Option \fB-a\fR, \fB--apps\fR lists apps available in all installation files
(files starting with \fBkz-install-\fR and ending with \fB.sh\fR).
.sp
It is possible to specify \fIAPP\fRs.
.br
Per specified \fIAPP\fR, the first available app is found in all installation
files and is copied to a temporary file together with the corresponding
commands.
.br
The name of this temporary file is included in the list of installation files
to be processed.
.sp
Option \fB-c\fR, \fB--cat\fR lists the contents of the installation files.
.sp
With option \fB-r\fR, \fB--remove\fR the installation can be uninstalled.
.sp
A -- signals the end of options and disables further option processing.
.\"
.\"
.SH FILE FORMAT
The files to be processed should start with \fBkz-install-\fR and end with
\fB.sh\fR.
.sp
The records are processed in the order they appear in the files.
.br
The commands supplied by default with \fBkz install\fR are arranged in such a
way that the result remains the same when executed repeatedly.
.sp
See \fBTable 1\fR which \fBtypes\fR of records (first two positions on a line)
there are and how these records are processed.
.sp
See \fBTable 2\fR for an \fBexample\fR of these records in sample file
kz-install-ubuntu-pc02.sh.
More examples can be seen through the \fBkz install --cat\fR command.
.sp
.sp
.br
.B Table 1. Record types and their processing
.TS
allbox tab(:);
lb | lb.
T{
Record type
T}:T{
Description
T}
.T&
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
#1 APP
T}:T{
Contains the APP name.
T}
T{
#1-APP
T}:T{
Ditto, not always used, see [1].
T}
T{
#2 Command
T}:T{
APP uninstall command.
T}
T{
.sp
T}:T{
Will be skipped (is empty).
T}
T{
#...
T}:T{
Will be skipped (is a comment).
T}
T{
Opdracht
T}:T{
Command to install APP
T}
.TE
.sp
.sp
.br
[1]
.br
Line '#1-APP' is for a command specific to a distribution or a computer.
.br
This line is not shown with option \fB-a\fR, \fB--apps\fR, and is not used to
look up commands at a given \fIAPP\fR.
.br
This line is used when processing the installation file.
.sp
.sp
.br
.B Table 2. Lines in sample file kz-install-ubuntu-pc02.sh
.TS
box tab(:);
lb | lb.
T{
Record type
T}:T{
Description
T}
.T&
- | -
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
#1 gnome-gmail
T}:T{
Name of the APP.
T}
T{
sudo apt-get install --yes gnome-gmail
T}:T{
Install command.
T}
T{
#2 sudo apt-get remove --yes gnome-gmail
T}:T{
Remove command; for option -r, --remove.
T}
T{
.sp
T}:T{
Empty line.
T}
T{
## Only for pc02!
T}:T{
Comment.
T}
T{
#1-gast
T}:T{
Only install on pc02 with Ubuntu.
T}
T{
sudo useradd --create-home ... gast
T}:T{
Install command.
T}
T{
#2 sudo userdel --remove gast
T}:T{
Remove command.
T}
.TE
.\"
.\"
.sp
.SH OPTIONS
.TP
\fB-a\fR, \fB--apps\fR
Show a list of apps to install.
.TP
\fB-c\fR, \fB--cat\fR
Display the contents of installation files.
.br
Each file is preceded by a comment line with the file name.
.TP
\fB-f\fR, \fB--files\fR
Show a list of installation files.
.TP
\fB-r\fR, \fB--remove\fR
Remove apps.
.TP
\fB--server\fR
Install apps and change system settings for a server.
.TP
\fB-s\fR, \fB--simulate\fR
No action, but simulate the installation, and show the commands that would be
executed.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.TP
\fB-g\fR, \fB--gui\fR
Start in graphics mode (gui=graphical user interface).
.TP
\fB--\fR
Signals the end of options and disables further option processing.
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value not equal
to 0.
.\"
.\"
.SH FILES
/usr/bin/kz-install-<distribution>-desktop.sh
.RS
Default installation file.
.RE
.sp
/usr/bin/kz-install-<distribution>-desktop-<computername>.sh
.RS
Default installation file for <computername>.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX.apps
.RS
Temporary installation file containing commands associated with specified apps.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX.cmds
.RS
Temporary installation file containing all commands to run.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX.sims
.RS
Temporary simulation file.
.RE
.sp
~/Setup/Apps
.RS
List of installed apps. For control. Created by kz-backup.
.RE
.\"
.\"
.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
https://karelzimmer.nl/html/en/linux.html#documents
.RE
.IP " 2." 4
Home / Setup / Apps
.RS 4
The Apps file contains names of previously installed packages.
.br
Can be used to check the installation for completeness.
.RE
.IP " 3." 4
IaC and Day 1 Operations
.RS 4
\fBkz install\fR is mainly used for \fBIaC\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
.\"
.\"
.SH EXAMPLES
.sp
\fBkz install\fR
.RS
Install everything in the default installation files.
.br
Starter \fBApps\fR is also available for this in a graphical work environment.
.RE
.sp
\fBkz install google-chrome\fR
.RS
Install Google Chrome.
.RE
.sp
\fBkz install --remove google-chrome\fR
.RS
Remove Google Chrome.
.RE
.sp
\fBkz install --cat google-chrome\fR
.RS
Show installation commands for Google Chrome.
.RE
.sp
\fBkz install --cat --remove google-chrome\fR
.RS
Show remove commands for Google Chrome.
.RE
.\"
.\"
.SH AUTHOR
Written by Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
<https://creativecommons.org/publicdomain/zero/1.0>, 2009-2023.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1),
\fBkz-setup\fR(1),
\fBkz-update\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz install\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website
.br
<https://karelzimmer.nl/html/en/linux.html#scripts>.
