.\"############################################################################
.\"# SPDX-FileComment: Man page for kz-install.sh
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ-INSTALL-CMD" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-install-cmd - run the kz-install command (wrapper script)

.SH SYNOPSIS
.nf
.B pkexec /usr/bin/kz-install-cmd <command>
.YS

.SH DESCRIPTION
When called by \fBkz-install\fR, \fBkz-install-cmd\fR executes the command
passed as an argument to the call.

.SH SEE ALSO
\fBkz-install\fR(1),
\fBkz\fR(1)
