.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-install
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-INSTALL" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-install - install apps

.SH SYNOPSIS
.SY kz\ install
[<options>] [--] [\fI<app>\fR...]
.YS

.SH DESCRIPTION
\fBkz install\fR installs apps and changes system settings.
.sp
In a desktop environment command \fBkz install\fR can be executed by searching
for \fBapps\fR, click on \fBKZ Install apps\fR pictogram.
.sp
First install Linux, \fBkz install\fR is a post install script.
.sp
Use \fBkz setup\fR (after \fBkz install\fR) to set up apps and change user
settings.
.sp
\fBkz install\fR processes installation files that contains commands for
installing apps and changing system settings.
.sp
By default, \fBkz install\fR processes the installation files
/usr/bin/kz-install.sh and /usr/bin/kz-install.sh.gpg, which contains commands
for all computers included in it.
.br
Commands with personal information such as a username are included in encrypted
installation file /usr/bin/kz-install.sh.gpg.
This file is decrypted before the commands are used.
.sp
The commands that \fBkz install\fR provides are arranged in such a way that the
result remains the same even if they are executed repeatedly (idempotent).
.sp
When processing the installation files, the commands for any and the current
computer are selected and copied to a command file.
.br
The commands in the command file are executed.
.br
Upon successful completion the computer will restart.
.sp
If warnings or errors are found, an overview of these messages is given.
.sp
For the format of the installation files see \fBman kz install.sh\fR and
\fBman kz install.sh.gpg\fR.
.sp
Optionally, apps to be processed can be specified with argument \fI<app>\fR.
.br
Per specified app, the commands are selected from the installation file and are
copied to the command file.
.sp
With option \fB-b\fR, \fB--browse\fR you can browse through the installation
files.
.sp
Option \fB-c\fR, \fB--cat\fR lists the contents of the command file.
.sp
With option \fB-f\fR, \fB--file\fR \fI<file>\fR another installation file can
be specified. This option can be used repeatedly.
.sp
With option \fB-g\fR, \fB--gui\fR, \fBkz install\fR is run in graphical mode. A
desktop environment is required.
.sp
Option \fB-l\fR, \fB--list\fR lists all apps available in the installation
files.
.sp
With option \fB-r\fR, \fB--remove\fR the installation can be undone.
.sp
To uninstall a app, on a Debian or Debian-based system you can use:
    sudo apt-get remove --purge --assume-yes <app>
.br
On a Red Hat or Red Hat-based system use:
   sudo dnf remove --assumeyes <app>
.sp
If the installation of apps fails for some reason, on a Debian or Debian-based
system you can try the following:
    sudo dpkg --configure --pending
    sudo apt-get update --fix-missing
    sudo apt-get install --fix-broken
.br
On a Red Hat or Red Hat-based system try the following:
    sudo dnf clean all
    sudo dnf makecache

.SH OPTIONS
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB-b\fR, \fB--browse\fR
Browse through the installation files.
.TP
\fB-c\fR, \fB--cat\fR
Display the contents of the command file.
.TP
\fB-f\fR, \fB--file\fR \fI<file>\fR
Process the specified file. This option can be used repeatedly.
.TP
\fB-g\fR, \fB--gui\fR
Run in graphical mode (gui=graphical user interface). A desktop environment is
required.
.TP
\fB-l\fR, \fB--list\fR
Show a list of available apps to install or remove.
.TP
\fB-r\fR, \fB--remove\fR
Remove the apps.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Show the version, author, and copyright.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH FILES
/usr/bin/kz-install.sh
.RS
Installation file.
.RE
.sp
/usr/bin/kz-install.sh.gpg
.RS
GPG-encrypted installation file.
.RE
.sp
/usr/share/kz/kz-public-key.gpg
.RS
OpenPGP public key for package kz. Needed to decrypt kz-install.sh.gpg.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX-decryptd.sh.gpg
.RS
Decrypted installation file containing additional commands that are added to
the command file, for example kz-install-SkQLswclj3-decryptd.sh.gpg.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX-commands.sh.
.RS
Command file, e.g. kz-install-SYpGEKVWZI-commands.
.RE
.sp
/tmp/kz-install-XXXXXXXXXX-error.log
.RS
Error log file, e.g. kz-install-agr1ZErXoI-error.log.
.RE
.sp
~/Settings/users.txt
.RS
Instructions for adding additional users.
.RE

.SH EXAMPLES
.EX
.sp
\fBkz install\fR
.RS
Install everything in the default installation file.
Starter \fBKZ Install apps\fR is also available for this in a desktop \
environment.
.RE
.sp
\fBkz install google-chrome\fR
.RS
Install Google Chrome.
.RE
.sp
\fBkz install --remove google-chrome\fR
.RS
Remove Google Chrome.
.RE
.sp
\fBkz install --cat google-chrome\fR
.RS
Show install commands for Google Chrome.
.RE
.sp
\fBkz install --cat --remove google-chrome\fR
.RS
Show remove commands for Google Chrome.
.RE
.EE

.SH SEE ALSO
\fBkz_common.sh\fR(1),
\fBkz-install-pkexec\fR(1),
\fBkz-menu\fR(1),
\fBkz-setup\fR(1),
\fBkz-update\fR(1),
\fBkz\fR(1),
\fBkz-install.sh\fR(5),
\fBkz-install.sh.gpg\fR(5)

.SH KZ
Part of the \fBkz\fR(1) package.

.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
.UR https://karelzimmer.nl/en
.UE
.RE
.IP " 2." 4
~/Settings/apps.txt
.RS 4
The apps file contains names of previously installed packages. This file can be
used to check the installation for completeness.
.RE
.IP " 3." 4
IaC and Day 1 Operations
.RS 4
\fBkz install\fR is mainly used for \fBIaC\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
