.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-install-pkexec
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-INSTALL-PKEXEC" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-install-pkexec - wrapper script for kz-install

.SH SYNOPSIS
.nf
.B pkexec /usr/bin/kz-install-pkexec <command>
.YS

.SH DESCRIPTION
Execute the install command requiring root privileges.

.SH SEE ALSO
\fBkz-install\fR(1),
\fBpkexec\fR(1),
\fBpolkit\fR(8)

.SH KZ
Part of the \fBkz\fR(1) package.
