.\"#############################################################################
.\"# Man page for kz-ivp.
.\"#
.\"# Written Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
.\"# <https://creativecommons.org/publicdomain/zero/1.0>, 2023.
.\"#############################################################################
.\"
.TH "KZ-IVP" "1" "2023" "kz 2.4.7" "Kz Manual"
.\"
.\"
.SH NAME
kz-ivp \- Checking scripts.
.\"
.\"
.SH SYNOPSIS
.B kz ivp
[OPTION...]
.\"
.\"
.SH DESCRIPTION
\fBkz ivp\fR performs an Installation Verification Procedure (IVP).
.sp
Runs checks that check scripts and related files.
.sp
Command \fBkz ivp\fR is also called from \fBkz deploy\fR.
.\"
.\"
.SH OPTIONS
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.
.\"
.\"
.SH NOTES
.IP " 1." 4
Day 1 Operations and CI/CD
.RS 4
\fBkz ivp\fR is mainly used for \fBDay 1 Operations\fR and \fBCI/CD\fR. See
\fBkz\fR(1) for an explanation..RE
.\"
.\"
.SH AUTHOR
Written by Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
<https://creativecommons.org/publicdomain/zero/1.0>, 2023.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-deploy\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator, Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz ivp\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website <https://karelzimmer.nl/html/en/linux.html#scripts>.
