.\"############################################################################
.\"# SPDX-FileComment: Man page for kz-install
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################
.\"
.TH "kz-install" "1" "Manual kz" "kz version 4.2.1" "Manual kz"
.\"
.\"
.SH NAME
kz-install \- Install apps.
.\"
.\"
.SH SYNOPSIS
.B kz install
[OPTION...] [\fIAPP\fR...] [\fIFILE\fR...]
.\"
.\"
.SH DESCRIPTION
\fBkz install\fR installs apps and changes system settings.
.sp
In a graphical work environment command \fBkz install\fR can be executed by
searching for \fBapps\fR, click on \fBApps install\fR.
.sp
Use \fBkz setup\fR (after \fBkz install\fR) to set up apps and change user
settings.
.sp
\fBkz install\fR processes an input file ("install file") that contains
commands for installing apps and modifying system settings.
.sp
For the format of the input files see the section \fBFILE FORMAT\fR below.
.sp
By default, \fBkz install\fR processes the input file
/usr/bin/kz-install-<distribution>-<edition>.sh, for example
kz-install-ubuntu-desktop.sh.
.br
The <distribution> and <edition> (desktop or server) are populated with the
values from the current computer.
.sp
This input file contains commands for all computers included in it for Ubuntu
desktop.
.br
When processing the input file, the commands for any and the current computer
are selected and copied to a command file.
.sp
Option \fB-a\fR, \fB--apps\fR lists all apps available in the input file.
.sp
It is possible to specify \fIAPP\fRs. Per specified \fIAPP\fR, the commands are
selected from the input file and are copied to the command file.
.sp
The commands in the command file are executed.
Upon successful completion the computer will restart.
.sp
Option \fB-c\fR, \fB--cat\fR lists the contents of the command file.
.sp
With option \fB-f\fR, \fB--file\fR \fIFILE\fR another input file can be
specified, the filename must start with \fBkz-install-\fR and end with
\fB.sh\fR.
.sp
With option \fB-g\fR, \fB--gui\fR start \fBkz install\fR in graphical mode.
.sp
The \fB-l\fR, \fB--list\fR option displays a list of install files.
.sp
With option \fB-r\fR, \fB--remove\fR the installation can be undone, the mode
then changes from Install to Remove.
.sp
A -- signals the end of options and disables further option processing.
.\"
.\"
.SH FILE FORMAT
The format of the supplied input file is
kz-install-<distribution>-<edition>.sh, for a user supplied input file it is
kz-install-*.sh.
.br
The records are processed in the order they appear in the files.
.sp
The commands supplied by with \fBkz install\fR are arranged in such a way that
the result remains the same when executed repeatedly (idempotent).
.sp
See \fBTable 1\fR which \fBtypes\fR of records there are and how these records
are processed.
.sp
See \fBTable 2\fR for an \fBexample\fR of these records in sample file
kz-install-ubuntu-desktop.sh for computer pc02.
More examples can be seen through the \fBkz install --cat\fR command.
.sp
.sp
.B Table 1. Record types and their processing
.TS
allbox tab(:);
lb | lb.
T{
Record
T}:T{
Description
T}
.T&
l | l
l | l
l | l
l | l
l | l.
T{
T}:T{
Blank line
T}
T{
# Install APP <app name> HOST <computer name>...
T}:T{
Install the application <app name> on computer <computer name>
T}
T{
# Remove APP <app name> HOST <computer name>...
T}:T{
Remove the application <app name> from computer <computer name> (option remove)
T}
T{
#...
T}:T{
Comment line
T}
T{
Command
T}:T{
Install/Remove command.
T}
.TE
.sp
.sp
.B Table 2. Lines in sample file kz-install-ubuntu-desktop.sh
.TS
box tab(:);
lb | lb.
T{
Record
T}:T{
Description
T}
.T&
- | -
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
# Install APP gnome-gmail HOST *
T}:T{
Install gnome-gmail on any computer, see [1].
T}
T{
sudo apt-get install --yes gnome-gmail
T}:T{
T}
T{
T}:T{
T}
T{
# Remove APP gnome-gmail HOST *
T}:T{
Remove gnome-gmail from any computer, see [1].
T}
T{
sudo apt-get remove --yes gnome-gmail
T}:T{
T}
T{
T}:T{
T}
T{
# Install APP ufw HOST pc02
T}:T{
Install ufw only on pc02, see [2].
T}
T{
sudo apt-get install --yes gufw
T}:T{
T}
T{
T}:T{
T}
T{
# Install APP kvm HOST pc01 pc02
T}:T{
Install kvm on pc01 and pc02, see [3].
T}
T{
sudo apt-get install --yes qemu-kvm
T}:T{
T}
T{
T}:T{
T}
T{
# Install APP google-earth HOST -nohost
T}:T{
Do not install Google Earth by default, see [4].
T}
T{
sudo apt-get install --yes google-earth
T}:T{
T}
.TE
.sp
.sp
[1]
.br
The line with 'HOST *' causes the associated commands to run on all computers.
.sp
[2]
.br
The line with 'HOST pc02' ensures that the associated commands are executed
only on pc02.
.br
The APP can still be installed on another computer with the command 'kz instal\
l google-earth'.
.sp
[3]
.br
The line with 'HOST pc01 pc02' ensures that the associated commands are
executed only on pc01 and pc02 by default.
.br
The APP can still be installed on another computer with the command 'kz instal\
l kvm'.
.sp
[4]
.br
The line with 'HOST -nohost' ensures that the associated commands are not
executed by default (NOTE: '-nohost' is not a valid computer name).
.br
The APP can still be installed with the command 'kz install google-earth'.
.\"
.\"
.sp
.SH OPTIONS
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB-a\fR, \fB--apps\fR
Show a list of apps to install.
.TP
\fB-c\fR, \fB--cat\fR
Display the contents of the command file.
.TP
\fB-f\fR, \fB--file\fR \fIFILE\fR
Specify input file \fIFILE\fR.
.TP
\fB-g\fR, \fB--gui\fR
Start in graphical mode (gui=graphical user interface).
.TP
\fB-l\fR, \fB--list\fR
Show a list of standard files.
.TP
\fB-r\fR, \fB--remove\fR
Remove apps.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.TP
\fB--\fR
Signals the end of options and disables further option processing.
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.
.\"
.\"
.SH FILES
/usr/bin/kz-install-debian-desktop.sh
.RS
Install file for Debian desktop.
.RE
.sp
/usr/bin/kz-install-ubuntu-desktop.sh
.RS
Install file for Ubuntu desktop.
.RE
.sp
/tmp/kz-install-<distribution>-<edition>-XXXXXXXXXX.sh
.RS
Command file, e.g. kz-install-ubuntu-desktop-SYpGEKVWZI.sh.
.RE
.sp
~/.kz/apps
.RS
List of installed apps for checking. Created by kz-backup.
.RE
.\"
.\"
.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
https://karelzimmer.nl/en, under Linux
.RE
.IP " 2." 4
Home / .kz / apps
.RS 4
The apps file contains names of previously installed packages. This file can be
used to check the installation for completeness.
.RE
.IP " 3." 4
IaC and Day 1 Operations
.RS 4
\fBkz install\fR is mainly used for \fBIaC\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
.\"
.\"
.SH EXAMPLES
.sp
\fBkz install\fR
.RS
Install everything in the default install file.
Starter \fBApps install\fR is also available for this in a graphical work
environment.
.RE
.sp
\fBkz install google-chrome\fR
.RS
Install Google Chrome.
.RE
.sp
\fBkz install --remove google-chrome\fR
.RS
Remove Google Chrome.
.RE
.sp
\fBkz install --cat google-chrome\fR
.RS
Show install commands for Google Chrome.
.RE
.sp
\fBkz install --cat --remove google-chrome\fR
.RS
Show remove commands for Google Chrome.
.RE
.\"
.\"
.SH AUTHOR
Written by Karel Zimmer <info@karelzimmer.nl>.
.br
CC0 1.0 Universal <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1),
\fBkz-setup\fR(1),
\fBkz-update\fR(1),
\fBhttps://karelzimmer.nl/en\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator, Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz install\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website <https://karelzimmer.nl/en>, under Linux.
