.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-menu
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-MENU" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-menu - execute the kz commands through a menu

.SH SYNOPSIS
.SY kz\ menu
[<options>]
.YS

.SH DESCRIPTION
\fBkz menu\fR runs commands through a menu.
.sp
In a desktop environment command \fBkz menu\fR can be executed by
searching for \fBmenu\fR, click on \fBKZ Installation menu\fR pictogram.
.sp
Show a menu that runs a number of commands in succession so that, for example,
Debian Linux can be installed and used immediately.
.sp
The choices in the Installation menu follow the chapters in the Checklist
installation.
.sp
With option \fB-g\fR, \fB--gui\fR, \fBkz menu\fR runs in graphical mode. A
desktop environment is required.

.SH OPTIONS
.TP
\fB-g\fR, \fB--gui\fR
Run in graphical mode (gui=graphical user interface). A desktop environment is
required.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Show the version, author, and copyright.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH SEE ALSO
\fBkz\fR(1),
\fBkz-backup\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-install\fR(1),
\fBkz-restore\fR(1),
\fBkz-setup\fR(1),
\fBkz-wifi\fR(1)

.SH KZ
Part of the \fBkz\fR(1) package.

.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
.UR https://karelzimmer.nl/en
.UE
.RE
.IP " 2." 4
Day 1 Operations
.RS 4
\fBkz menu\fR is mainly used for \fBDay 1 Operations\fR. See \fBkz\fR(1) for an
explanation.
.RE
