.\"############################################################################
.\"# SPDX-FileComment: Man page for kz-nas
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################
.\"
.TH "kz-nas" "1" "Kz Manual" "kz 4.2.1" "Kz Manual"
.\"
.\"
.SH NAME
kz-nas\ - Mount network drive.
.\"
.\"
.SH SYNOPSIS
.B kz nas
[OPTION...]
.\"
.\"
.SH DESCRIPTION
\fBkz nas\fR mounts a NAS during startup.
.sp
In a graphical work environment command \fBkz nas\fR can be executed by
searching for \fBnas\fR, click on \fBMount network drive\fR.
.sp
A systemd mount file is created and activated.
.sp
The systemd mount file to be created is constructed with default values.
.br
When running this script, these default values are shown between [] and can be
specified.
.sp
Make sure the NAS has a fixed IP address. This requires:
 -  the MAC address of the NAS (looks like aa:bb:cc:dd:ee:ff)
 -  access the NAS via a web browser
 -  access the router via a web browser

  1. Select the MAC address of the NAS in the router IP address outside the
     range of DHCP automatically distributes the IP addresses
     (often 192.168.0.200).
  2. Select the fixed IP address in the NAS and turn off DHCP.
.sp
Use command \fBsudo systemctl disable mnt-kz-nas.mount\fR to deactivate the
systemd mount file.
.sp
NAS is an acronym, and abbreviation, of network-attached storage.
.\"
.\"
.SH OPTIONS
.TP
\fB-g\fR, \fB--gui\fR
Start in graphical mode (gui=graphical user interface).
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.
.\"
.\"
.SH FILES
/etc/kz-nas.login
.RS
NAS-login data.
.RE
.sp
/etc/systemd/system/mnt-kz-nas.mount
.RS
Systemd mount file.
.RE.\"
.\"
.SH NOTES
.IP " 1." 4
Day 1 Operations
.RS 4
\fBkz nas\fR is mainly used for \fBDay 1 Operations\fR. See \fBkz\fR(1) for an
explanation.
.RE
.\"
.\"
.SH AUTHOR
Written by Karel Zimmer <info@karelzimmer.nl>.
.br
CC0 1.0 Universal <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH SEE ALSO
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1),
\fBmount.cifs\fR(8),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator, Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz nas\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website <https://karelzimmer.nl/en>, under Linux.
