.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-post-migrate
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-POST-MIGRATE" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-post-migrate - post-migration script

.SH SYNOPSIS
.SY kz-post-migrate
.YS

.SH DESCRIPTION
Search for Windows-specific files and delete them after migrating to Linux.
.br
The search starts in the current directory and includes all subdirectories.
.br
First the files are searched for and displayed, then there is the option to
delete them.

.SH KZ
Part of the \fBkz\fR(1) package.
