.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-restore
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-RESTORE" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-restore - restore Home folder

.SH SYNOPSIS
.SY kz\ restore
[<options>]
.YS

.SH DESCRIPTION
\fBkz restore\fR restores a backup copy of the Home folder.
.sp
In a desktop environment command \fBkz restore\fR can be executed by
searching for \fBback\fR, click on \fBKZ Restore Home folder\fR pictogram.
.sp
The backup is expected on a mounted USB medium such as a USB external hard disk
in directory \fBBACKUP-<username>@<computername>\fR, for example
/media/karel/backupdisk/BACKUP-karel@pc-of-karel for user Karel on pc-of-karel.
.sp
In a desktop environment when the backup is restored, the previously set
desktop background will be restored, see the \fBFILES\fR section below..
.sp
With option \fB-g\fR, \fB--gui\fR, \fBkz restore\fR runs in graphical mode. A
desktop environment is required.
.sp
With option \fB-s\fR, \fB--source\fR \fIDIRECTORY\fR another location can be
specified. For example /media/karel/usbstick instead of
/media/karel/backupdisk.
.sp
Tool rsync is used to restore the backup.
.br
Files in the Home folder that are not in the backup are not deleted (rsync's
--delete option is not used).
.sp
In a desktop environment, the desktop background, if available, will be
restored.
.sp
If errors are found, an overview of the error messages is given.
.sp
With command \fBkz backup\fR the Home folder can be backed up.

.SH OPTIONS
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB-g\fR, \fB--gui\fR
Run in graphical mode (gui=graphical user interface). A desktop environment is
required.
.TP
\fB-s\fR, \fB--source \fIDIRECTORY\fR
Use the backup in the specified directory.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Show the version, author, and copyright.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH FILES
/tmp/kz-restore-XXXXXXXXXX-error.log
.RS
Error log file, e.g. kz-restore-error.log-qvrTOfa4wa.
.RE
.sp
~/Settings/desktop.ico
.RS
Backup of desktop background, if available.
.RE

.SH EXAMPLES
.EX
.sp
\fBkz restore\fR
.RS
Restore everything in the backup.
Starter \fBKZ Restore Home folder\fR is also available for this purpose in a
desktop environment.
.RE
.sp
\fBkz restore --source/media/karel/usbstick\fR
.RS
Restore the backup of the Home folder of Karel on /media/karel/usbstick from
the karel@pc-of-karel directory.
.RE
.EE

.SH SEE ALSO
\fBkz\fR(1),
\fBkz-backup\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1)

.SH KZ
Part of the \fBkz\fR(1) package.

.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
.UR https://karelzimmer.nl/en
.UE
.RE
.IP " 2." 4
Day 1 Operations
.RS 4
\fBkz restore\fR is mainly used for Day 1 Operations. See \fBkz\fR(1) for an
explanation.
.RE
