.\"############################################################################
.\"# Man page for kz-restore.
.\"#
.\"# Written in 2019 by Karel Zimmer <info@karelzimmer.nl>, Creative Commons
.\"# Public Domain Dedication
.\"# <https://creativecommons.org/publicdomain/zero/1.0>.
.\"############################################################################
.\"
.TH KZ-RESTORE 1 "Kz Manual" "kz 365" "Kz Manual"
.\"
.\"
.SH NAME
kz-restore \- Restore backup.
.\"
.\"
.SH SYNOPSIS
.B kz restore
[OPTION...]
.\"
.\"
.SH DESCRIPTION
\fBkz restore\fR restores a backup copy of the Home folder.
.sp
In a graphical work environment command \fBkz restore\fR can be executed by
searching for \fBback\fR, click on \fBRestore\fR.
.sp
The backup is expected on a mounted USB medium such as a USB external hard disk
in directory \fBbackup-<computer name>-<user name>\fR, for example
/media/jan/backupdisk/backup-pc02-jan.
.sp
When the backup is restored, the previously set desktop wallpaper and favorites
will be restored from Home / Settings.
.sp
With option \fB-s\fR, \fB--source\fR \fIDIRECTORY\fR another location can be
specified. For example /tmp instead of /media/jan/backupdisk (unwise because
/tmp is emptied after a reboot).
.sp
Option \fB--dry-run\fR performs a trial run without making any changes. It is
usually used in seeing what an rsync command will do before actually executing
it.
.sp
rsync is used to restore the backup.
.br
Files in the Home folder that are not in the backup are not deleted (rsync's
--delete option is not used).
.sp
With command \fBkz backup\fR the Home folder can be backed up.
.\"
.\"
.SH OPTIONS
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB--dry-run\fR
Perform a test run without making any changes.
.TP
\fB-s\fR, \fB--source \fIDIRECTORY\fR
Use backups in the \fIDIRECTORY\fR.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.TP
\fB-g\fR, \fB--gui\fR
Start in graphics mode (gui graphical user interface).
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value not equal
to 0.
.\"
.\"
.SH FILES
~/Setup/Background
.RS
Set desktop wallpaper.
.RE
.sp
~/Setup/Favorites
.RS
Set favorites in the favorites bar (dash/dock).
.RE
.\"
.\"
.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
https://karelzimmer.nl/html/en/linux.html#documents
.RE
.IP " 2." 4
Day 1 Operations
.RS 4
\fBkz restore\fR is mainly used for Day 1 Operations. See \fBkz\fR(1) for an
explanation.
.RE
.\"
.\"
.SH EXAMPLES
.sp
\fBkz restore\fR
.RS
Restore everything in the backup.
.br
Starter \fBRestore\fR is also available for this purpose in a graphical work
environment.
.RE
.sp
\fBkz restore --dry-run\fR
.RS
Show files that would be restored from the backup.
.RE
.sp
\fBkz restore\
 --source smb://fileserver/backups\fR
.RS
Restore the backup from SMB share backups on fileserver from backup-pc02-jan
directorie.
.RE
.\"
.\"
.SH AUTHOR
Written in 2007 by Karel Zimmer <info@karelzimmer.nl>, Creative Commons
Public Domain Dedication <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz-backup\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz restore\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website
.br
<https://karelzimmer.nl/html/en/linux.html#scripts>.
