.\"############################################################################
.\"# SPDX-FileComment: Man page for kz-setup
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################
.\"
.TH "kz-setup" "1" "Manual kz" "kz version 4.2.1" "Manual kz"
.\"
.\"
.SH NAME
kz-setup \- Set up apps
.\"
.\"
.SH SYNOPSIS
.B kz setup
[OPTION...] [\fIAPP\fR...] [\fIFILE\fR...]
.\"
.\"
.SH DESCRIPTION
\fBkz setup\fR sets up apps and changes user settings.
.sp
In a graphical work environment command \fBkz setup\fR can be executed by
searching for \fBapps\fR, click on \fBSet up apps\fR.
.sp
Use (first) \fBkz install\fR to install apps and changes system settings.
.sp
\fBkz setup\fR processes an input file ("set up file") that contains
commands for setting up apps and changing user settings.
.sp
For the input file format, see the \fBFILE FORMAT\fR section below.
.sp
By default, \fBkz setup\fR processes the input file
/usr/bin/kz-setup-<distribution>-<edition>.sh, for example
kz-setup-ubuntu-desktop.sh.
.sp
The <distribution> and <edition> (desktop or server) are populated with the
values from the current computer.
.sp
This input file contains commands for all users included in it for Ubuntu
desktop.
.sp
When processing the input file, the commands for any and the current user are
selected and copied to a command file.
.sp
Option \fB-a\fR, \fB--apps\fR lists all apps available in the input file.
.sp
It is possible to specify \fIAPP\fRs. Per specified \fIAPP\fR, the commands are
selected from the input file and are copied to the command
file.
.sp
The commands in the command file are executed.
Upon successful completion the user will be logged out.
.sp
Option \fB-c\fR, \fB--cat\fR gives the contents of the command file.
.sp
With option \fB-f\fR, \fB--file\fR \fIFILE\fR another input file can be
specified, the filename must start with \fBkz-setup-\fR and end with
\fB.sh\fR.
.sp
With option \fB-g\fR, \fB--gui\fR start \fBkz setup\fR in graphical mode.
.sp
The \fB-l\fR, \fB--list\fR option displays a list of set up files.
.sp
With option \fB-r\fR, \fB--reset\fR the setting can be undone, the mode then
changes from Setup to Reset.
.sp
A -- signals the end of options and disables further option processing.
.\"
.\"
.SH FILE FORMAT
The format of the supplied input file is kz-setup-<distribution>-<edition>.sh,
for a user supplied input file it is kz-setup-*.sh.
.br
The records are processed in the order they appear in the files.
.sp
The commands supplied by with \fBkz setup\fR are arranged in such a way that
the result remains the same when executed repeatedly idempotent).
.sp
See \fBTable 1\fR for which \fBtypes\fR records there are and how these records
are processed.
.sp
See \fBTable 2\fR for an \fBexample\fR of these records in
kz-setup-ubuntu-desktop.sh sample file.
More examples can be seen through the \fBkz setup --cat\fR command.
.sp
.sp
.B Table 1. Record types and their processing
.TS
allbox tab(:);
lb | lb.
T{
Record
T}:T{
Description
T}
.T&
l | l
l | l
l | l
l | l.
T{
T}:T{
Blank line
T}
T{
# Setup APP <app name> USER <user name>@<computer name>...
T}:T{
Set up application <app name> for user <user name>@<computer name>
T}
T{
# Reset APP <app name> USER <user name>@<computer name>...
T}:T{
Reset application <app name> for user <user name>@<computer name> (option
reset)
T}
T{
#...
T}:T{
Comment line
T}
T{
Command
T}:T{
Setup/Reset command
T}
.TE
.sp
.sp
.B Table 2. Lines in kz-setup-ubuntu-desktop.sh sample file
.TS
box tab(:);
lb | lb.
T{
Record
T}:T{
Description
T}
.T&
- | -
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
# Setup APP google-chrome USER *
T}:T{
Set up google-chrome for any user, see [1]
T}
T{
kz-gset --addfavbef=google-chrome
T}:T{
T}
T{
T}:T{
T}
T{
# Setup APP google-chrome USER *
T}:T{
Reset google-chrome for any user, see [1]
T}
T{
kz-gset --delfav=google-chrome
T}:T{
T}
T{
T}:T{
T}
T{
# Setup APP gnome USER john@pc02
T}:T{
Set up gnome only for John, see [2]
T}
T{
gsettings set org.gnome.shell...
T}:T{
T}
T{
T}:T{
T}
T{
# setup APP kvm USER jane@pc01 john@pc02
T}:T{
Set up kvm for Jane and John, see [3]
T}
T{
kz-gset --addfavaft=virt-manager
T}:T{
T}
T{
T}:T{
T}
T{
# Setup APP google-earth USER -nouser
T}:T{
Do not set up Google Earth by default, see [4]
T}
T{
kz-gset --addfavaft=google-earth
T}:T{
T}
.TE
.sp
.sp
[1]
.br
The line with 'USER *' causes the associated commands to run for every user.
.sp
[2]
.br
The line with 'USER john@pc02' ensures that the associated commands are
executed only for John on pc02.
.br
The APP can still be set up on another computer with the command 'kz setup goo\
gle-earth'.
.sp
[3]
.br
The line with 'USER jane@pc01 jan@pc02' ensures that the associated commands
are executed only for Jane on pc01 and for John on pc02 by default.
.br
The APP can still be set up on another computer with the command 'kz setup kvm\
'.
.sp
[4]
.br
The line with 'USER -nouser' ensures that the associated commands are not
executed by default (NOTE: '-nouser' is not a valid user name).
.br
The APP can still be set up with the command 'kz setup google-earth'.
.\"
.\"
.sp
.SH OPTIONS
.TP
\fB-a\fR, \fB--apps\fR
Show a list of apps to set up.
.TP
\fB-c\fR, \fB--cat\fR
Display the contents of the command file.
.TP
\fB-f\fR, \fB--file\fR \fIFILE\fR
Specify input file \fIFILE\fR.
.TP
\fB-g\fR, \fB--gui\fR
Start in graphical mode (gui=graphical user interface).
.TP
\fB-l\fR, \fB--list\fR
Show a list of standard files.
.TP
\fB-r\fR, \fB--reset\fR
Reset apps.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.TP
\fB--\fR
Signals the end of options and disables further option processing.
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.
.\"
.\"
.SH FILES
/usr/bin/kz-setup-debian-desktop.sh
.RS
Set up file for Debian desktop.
.RE
.sp
/usr/bin/kz-setup-ubuntu-desktop.sh
.RS
Set up file for Ubuntu desktop.
.RE
.sp
/tmp/kz-setup-<distribution>-<edition>-XXXXXXXXXX.sh
.RS
Command file, e.g. kz-setup-ubuntu-desktop-SYpGEKVWZI.sh.
.RE
.\"
.\"
.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
https://karelzimmer.nl/en, under Linux
.RE
.IP " 2." 4
Personal folder / .kz / favorites
.RS 4
The Favorites file contains previously set favorites.
Can be used to check the favorites for completeness.
.RE
.IP " 3." 4
IaC and Day 1 Operations
.RS 4
\fBkz setup\fR is mainly used for \fBIaC\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
.\"
.\"
.SH EXAMPLES
.sp
\fBkz setup\fR
.RS
Set everything in the default set up file.
Starter \fBSetup apps\fR is also available for this in a graphical work
environment.
.RE
.sp
\fBkz setup google-chrome\fR
.RS
Set up Google Chrome.
.RE
.sp
\fBkz setup --reset google-chrome\fR
.RS
Reset Google Chrome.
.RE
.sp
\fBkz setup --cat google-chrome\fR
.RS
Show set up commands for Google Chrome.
.RE
.sp
\fBkz setup --cat --reset google-chrome\fR
.RS
Show reset commands for Google Chrome.
.RE
.\"
.\"
.SH AUTHOR
Written by Karel Zimmer <info@karelzimmer.nl>.
.br
CC0 1.0 Universal <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-install\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl/en\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator, Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz setup\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website <https://karelzimmer.nl/en>, under Linux.
