.\"############################################################################
.\"# Man page for kz-setup.
.\"#
.\"# Written in 2019 by Karel Zimmer <info@karelzimmer.nl>, Creative Commons
.\"# Public Domain Dedication
.\"# <https://creativecommons.org/publicdomain/zero/1.0>.
.\"############################################################################
.\"
.TH KZ-SETUP 1 "Kz Manual" "kz 365" "Kz Manual"
.\"
.\"
.SH NAME
kz-setup \- Set up apps.
.\"
.\"
.SH SYNOPSIS
.B kz setup
[OPTION...] [\fIAPP\fR...] [\fIFILE\fR...]
.\"
.\"
.SH DESCRIPTION
\fBkz setup\fR sets up apps and changes user settings.
.sp
In a graphical work environment command \fBkz setup\fR can be executed by
searching for \fBapps\fR, click on \fBSet up apps\fR.
.sp
Use (first) \fBkz install\fR to install apps and change system settings.
.sp
\fBkz setup\fR handles so-called setup files that contain commands for setting
up apps and changing settings.
.sp
By default, \fBkz setup\fR handles the following two setup files:
.br
- /usr/bin/kz-setup-<distribution>-desktop.sh
.br
- /usr/bin/kz-setup-<distribution>-desktop-<computername>-<username>.sh (if
present)
.sp
<distribution>, <computername>, and <username> are populated with values from
the current computer and user.
.sp
For example, kz-setup-ubuntu-desktop.sh and
kz-setup-ubuntu-desktop-pc02-jan.sh.
.br
These setup files contain commands for ubuntu desktop general and ubuntu
desktop on pc02 for jan.
.sp
For the setup file format, see the \fBFILE FORMAT\fR section below.
.sp
If no \fIAPP\fRs or \fILE\fRs are specified, the names of the default settings
files present will be included in the list of files to be processed.
.sp
With option \fB--server\fR server is used instead of desktop.
.sp
Option \fB-f\fR, \fB--files\fR lists settings files.
.sp
It is possible to specify \fIFILE\fRs; these files should be starting with
\fBkz-setup-\fR and ending with \fB.sh\fR.
.br
Anything else is considered an \fIAPP\fR, see below.
.br
The specified \fIFILE\fRs are included in the list of files to be processed.
.sp
Option \fB-a\fR, \fB--apps\fR lists apps available in all setup files (files
starting with \fBkz-setup-\fR and ending with \fB.sh\fR).
.sp
It is possible to specify \fIAPP\fRs.
.br
For each specified \fIAPP\fR, the first available app is found in all settings
files and is copied to a temporary file together with the corresponding
commands.
.br
The name of this temporary file is included in the list of settings files to be
processed.
.sp
Option \fB-c\fR, \fB--cat\fR gives the contents of the settings files.
.sp
The setting can be undone with option \fB-r\fR, \fB--reset\fR.
.sp
A -- signals the end of options and disables further option processing.
.\"
.\"
.SH FILE FORMAT
The files to be processed should start with \fBkz-setup-\fR and end with
\fB.sh\fR.
.sp
The records are processed in the order they appear in the files.
.br
The commands supplied by default with \fBkz setup\fR are arranged in such a way
that the result remains the same when executed repeatedly.
.sp
See \fBTable 1\fR for which \fBtypes\fR records (first two positions on a line)
there are and how these records are processed.
.sp
See \fBTable 2\fR for an \fBexample\fR of these records in
kz-setup-ubuntu-desktop-pc02-jan.sh sample file.
More examples can be seen through the \fBkz setup --cat\fR command.
.\"
.\"
.sp
.br
.B Table 1. Record types and their processing
.TS
allbox tab(:);
lb | lb.
T{
Record type
T}:T{
Description
T}
.T&
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
#1 APP
T}:T{
Contains the APP name.
T}
T{
#1-APP
T}:T{
Ditto, not always used, see [1].
T}
T{
#2 Opdracht
T}:T{
APP reset command.
T}
T{
.sp
T}:T{
Will be skipped (is empty).
T}
T{
#...
T}:T{
Will be skipped (is a comment).
T}
T{
Opdracht
T}:T{
Command to set up APP
T}
.TE
.sp
.sp
.br
[1]
.br
Line '#1-APP' is for a command specific to a distribution or a computer or a
user.
.br
This line is not shown with option \fB-a\fR, \fB--apps\fR, and is not used to
look up commands at a given \fIAPP\fR.
.br
This line is used when processing the set up file.
.sp
.sp
.br
.B Table 2. Lines in kz-setup-ubuntu-desktop-pc02-jan.sh sample file
.TS
box tab(:);
lb | lb.
T{
Record type
T}:T{
Description
T}
.T&
- | -
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l
l | l.
T{
#1 google-chrome
T}:T{
Name of the APP.
T}
T{
kz-gset --addfavbef=google-chrome
T}:T{
Setup command.
T}
T{
#2 kz-gset --delfav=google-chrome
T}:T{
Reset command; for option -r, --reset.
T}
T{
.sp
T}:T{
Empty line.
T}
T{
## Only for jan on pc02!
T}:T{
Comment.
T}
T{
#1-gnome
T}:T{
Only set up for Jan on pc02 with Ubuntu.
T}
T{
gsettings set org.gnome.shell...
T}:T{
Setup command.
T}
T{
#2 gsettings reset org.gnome.shell...
T}:T{
Reset command.
T}
.TE
.\"
.\"
.sp
.SH OPTIONS
.TP
\fB-a\fR, \fB--apps\fR
Show a list of apps to set up.
.TP
\fB-c\fR, \fB--cat\fR
Display the contents of setup files.
.br
Each file is preceded by a comment line with the file name.
.TP
\fB-f\fR, \fB--files\fR
Display a list of setup files.
.TP
\fB-r\fR, \fB--reset\fR
Reset apps.
.TP
\fB--server\fR
Set up apps and change user settings for a server.
.TP
\fB-s\fR, \fB--simulate\fR
No action, but simulate the setup, and show the commands that would be
executed.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.TP
\fB-g\fR, \fB--gui\fR
Start in graphics mode (gui=graphical user interface).
.TP
\fB--\fR
Signals the end of options and disables further option processing.
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value not equal
to 0.
.\"
.\"
.SH FILES
/usr/bin/kz-setup-<distribution>-desktop.sh
.RS
Default setup file.
.RE
.sp
/usr/bin/kz-setup-<distribution>-desktop-<computername>-<username>.sh
.RS
Default setup file for <computername> and <username>.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX.apps
.RS
Temporary setup file containing commands associated with specified apps.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX.cmds
.RS
Temporary setup file containing all commands to be executed..
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX.sims
.RS
Temporary simulation file.
.RE
.sp
~/Setup/Background
.RS
Set desktop wallpaper. For control. Created by kz-backup.
.RE
.sp
~/Setup/Favorites
.RS
Set favorites in the favorites bar (dash/dock). For control. Created by
kz-backup
.RE
.sp
~/Setup/Userphote
.RS
Set user photo. For control. Created by kz-backup.
.RE
.\"
.\"
.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
https://karelzimmer.nl/html/en/linux.html#documents
.RE
.IP " 2." 4
Personal folder / Settings / Favorites
.RS 4
The Favorites file contains previously set favorites.
.br
Can be used to check the favorites for completeness.
.RE
.IP " 3." 4
IaC and Day 1 Operations
.RS 4
\fBkz setup\fR is mainly used for \fBIaC\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
.\"
.\"
.SH EXAMPLES
.sp
\fBkz setup\fR
.RS
Set everything in the default setup files.
.br
Starter \fBSetup apps\fR is also available for this in a graphical work
environment.
.RE
.sp
\fBkz setup google-chrome\fR
.RS
Setup Google Chrome.
.RE
.sp
\fBkz setup --reset google-chrome\fR
.RS
Reset Google Chrome.
.RE
.sp
\fBkz setup --cat google-chrome\fR
.RS
Show setup commands for Google Chrome.
.RE
.sp
\fBkz setup --cat --reset google-chrome\fR
.RS
Show reset commands for Google Chrome.
.RE
.\"
.\"
.SH AUTHOR
Written in 2013 by Karel Zimmer <info@karelzimmer.nl>, Creative Commons
Public Domain Dedication <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-install\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz setup\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website
.br
<https://karelzimmer.nl/html/en/linux.html#scripts>.
