.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-setup
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-SETUP" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-setup - set up apps and change user settings

.SH SYNOPSIS
.SY kz\ setup
[<options>] [--] [\fI<app>\fR...]
.YS

.SH DESCRIPTION
\fBkz setup\fR sets up apps and changes user settings.
.sp
In a desktop environment command \fBkz setup\fR can be executed by searching
for \fBapps\fR, click on \fBKZ Set up apps\fR pictogram.
.sp
Use (first) \fBkz install\fR to install apps and changes system settings,
\fBkz setup\fR is a post install setup script.
.sp
\fBkz setup\fR processes settings files that contains commands for setting up
apps and changing user settings.
.sp
By default, \fBkz setup\fR processes the settings files /usr/bin/kz-setup.sh
and /usr/bin/kz-setup.sh.gpg, which contains commands for all computers
included in it.
.br
Commands with personal information such as a username are included in encrypted
settings file /usr/bin/kz-setup.sh.gpg.
This file is decrypted before the commands are used.
.sp
The commands supplied by with \fBkz setup\fR are arranged in such a way that
the result remains the same when executed repeatedly (idempotent).
.sp
When processing the settings files, the commands for any and the current
computer are selected and copied to a command file.
.br
The commands in the command file are executed.
.br
Upon successful completion the user will be logged out.
.sp
If errors are found, an overview of the error messages is given.
.sp
For the format of the settings files see \fBman kz setup.sh\fR and
\fBman kz setup.sh.gpg\fR.
.sp
Optionally, apps to be processed can be specified with argument \fI<app>\fR.
.br
Per specified app, the commands are selected from the settings file and are
copied to the command file.
.sp
With option \fB-b\fR, \fB--browse\fR you can browse through the settings files.
.sp
Option \fB-c\fR, \fB--cat\fR gives the contents of the command file.
.sp
With option \fB-f\fR, \fB--file\fR \fI<file>\fR another settings file can be
specified. This option can be used repeatedly.
.sp
With option \fB-g\fR, \fB--gui\fR, \fBkz setup\fR is run in graphical mode. A
desktop environment is required.
.sp
Option \fB-l\fR, \fB--list\fR lists all apps available in the settings files.
.sp
With option \fB-r\fR, \fB--reset\fR the setting can be undone.

.SH OPTIONS
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB-b\fR, \fB--browse\fR
Browse through the settings file.
.TP
\fB-c\fR, \fB--cat\fR
Display the contents of the command file.
.TP
\fB-f\fR, \fB--file\fR \fI<file>\fR
Process the specified file. This option can be used repeatedly.
.TP
\fB-g\fR, \fB--gui\fR
Run in graphical mode (gui=graphical user interface). A desktop environment is
required.
.TP
\fB-l\fR, \fB--list\fR
Show a list of apps to set up.
.TP
\fB-r\fR, \fB--reset\fR
Reset the apps.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Show the version, author, and copyright.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH FILES
/usr/bin/kz-setup.sh
.RS
Settings file.
.RE
.sp
/usr/bin/kz-setup.sh.gpg
.RS
GPG-encrypted settings file.
.RE
.sp
/usr/share/kz/kz-public-key.gpg
.RS
OpenPGP public key for package kz. Needed to decrypt kz-install.sh.gpg.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX-decryptd.sh.gpg
.RS
Decrypted settings file containing additional commands that are added to the
command file, for example kz-setup-SkQLswclj3-decryptd.sh.gpg.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX-commands.sh.
.RS
Temporary command file, e.g. kz-setup-SYpGEKVWZI-commands.
.RE
.sp
/tmp/kz-setup-XXXXXXXXXX-error.log
.RS
Error log file, e.g. kz-setup-agr1ZErXoI-error.log.
.RE
.sp
~/Settings/avatar.ico
.RS
Backup of user avatar, if available.
.RE
.sp
~/Settings/avatar.txt
.RS
Instructions for restoring the user avatar, if available.
.RE
.sp
~/Settings/xfce.txt
.RS
Instructions to setup the Xfce Panel and Whisker Menu.
.RE

.SH EXAMPLES
.EX
.sp
\fBkz setup\fR
.RS
Set up everything in the default settings file.
Starter \fBKZ Setup apps\fR is also available for this in a desktop \
environment.
.RE
.sp
\fBkz setup google-chrome\fR
.RS
Set up Google Chrome.
.RE
.sp
\fBkz setup --reset google-chrome\fR
.RS
Reset Google Chrome.
.RE
.sp
\fBkz setup --cat google-chrome\fR
.RS
Show set up commands for Google Chrome.
.RE
.sp
\fBkz setup --cat --reset google-chrome\fR
.RS
Show reset commands for Google Chrome.
.RE
.EE

.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBkz-install\fR(1),
\fBkz-menu\fR(1),
\fBkz-setup.sh\fR(5),
\fBkz-setup.sh.gpg\fR(5)

.SH KZ
Part of the \fBkz\fR(1) package.

.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
.UR https://karelzimmer.nl/en
.UE
.RE
.IP " 2." 4
~/Settings/favs.txt
.RS 4
The Favorites file contains previously set favorites.
Can be used to check the favorites for completeness.
.RE
.IP " 3." 4
IaC and Day 1 Operations
.RS 4
\fBkz setup\fR is mainly used for \fBIaC\fR and \fBDay 1 Operations\fR. See
\fBkz\fR(1) for an explanation.
.RE
