.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz-update
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-UPDATE" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-update - update and cleanup system

.SH SYNOPSIS
.SY kz\ update
[<options>]
.YS

.SH DESCRIPTION
\fBkz update\fR updates and cleanup the system.
.sp
All Debian and RPM packages, Flatpak apps, and snaps are updated.
.sp
If the update fails for some reason, on a Debian or Debian-based system you can
try the following:
    sudo dpkg --configure --pending
    sudo apt-get update --fix-missing
    sudo apt-get install --fix-broken
.br
On a Red Hat or Red Hat-based system try the following:
    sudo dnf clean all
    sudo dnf makecache
.sp
If for some reason a new kernel needs to be built, run 'sudo update-initramfs
-u'.
.br
The need to run this command manually is only under very unusual circumstances
- a post-install script will handle it automatically when a new kernel package
is installed.
.RE

.SH OPTIONS
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Show the version, author, and copyright.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.py\fR(1)

.SH KZ
Part of the \fBkz\fR(1) package.

.SH NOTES
.IP " 1." 4
Day 2 Operations
.RS 4
\fBkz update\fR is mainly used for \fBDay 2 Operations\fR. See \fBkz\fR(1) for
an explanation.
.RE
