.\"# ##########################################################################
.\"# Man page for kz-wifi.
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ-WIFI" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz-wifi - show WiFi information

.SH SYNOPSIS
.SY kz\ wifi
[<options>]
.YS

.SH DESCRIPTION
\fBkz wifi\fR shows WiFi details.
.sp
In a desktop environment command \fBkz wifi\fR can be executed by
searching for \fBwifi\fR, click on \fBWifi data\fR pictogram.
.sp
With option \fB-g\fR, \fB--gui\fR, \fBkz wifi\fR runs in graphical mode. A
desktop environment is required.

.SH OPTIONS
.TP
\fB-g\fR, \fB--gui\fR
Run in graphical mode (gui=graphical user interface). A desktop environment is
required.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-m\fR, \fB--manual\fR
Show the manual page.
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-v\fR, \fB--version\fR
Show the version, author, and copyright.

.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.

.SH NOTES
.IP " 1." 4
Checklist install
.RS 4
.UR https://karelzimmer.nl/en
.UE
.RE
.IP " 2." 4
Day 1 Operations
.RS 4
\fBkz wifi\fR is mainly used for \fBDay 1 Operations\fR. See \fBkz\fR(1) for an
explanation.
.RE

.SH SEE ALSO
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1)

.SH KZ
Part of the \fBkz\fR(1) package.
