.\"############################################################################
.\"# Man page for kz-wifi.
.\"#
.\"# Written by Karel Zimmer <info@karelzimmer.nl>.
.\"# CC0 1.0 Universal <https://creativecommons.org/publicdomain/zero/1.0>.
.\"############################################################################
.\"
.TH "KZ-WIFI" "1" "Kz Manual" "kz 4.2.1" "Kz Manual"
.\"
.\"
.SH NAME
kz-wifi\ - Show WiFi information.
.\"
.\"
.SH SYNOPSIS
.B kz wifi
[OPTION...]
.\"
.\"
.SH DESCRIPTION
\fBkz wifi\fR shows WiFi details.
.sp
In a graphical work environment command \fBkz wifi\fR can be executed by
searching for \fBwifi\fR, click on \fBWifi data\fR.
.\"
.\"
.SH OPTIONS
.TP
\fB-u\fR, \fB--usage\fR
Show the available options.
.TP
\fB-h\fR, \fB--help\fR
Show a short description of the available options.
.TP
\fB-v\fR, \fB--version\fR
Display the version, author, and copyright.
.TP
\fB-g\fR, \fB--gui\fR
Start in graphical mode (gui=graphical user interface).
.\"
.\"
.SH EXIT STATUS
Normally exit value 0 is returned; if an error occurs, the exit value is not
equal to 0.
.\"
.\"
.SH NOTES
.IP " 1." 4
Day 1 Operations
.RS 4
\fBkz wifi\fR is mainly used for \fBDay 1 Operations\fR. See \fBkz\fR(1) for an
explanation.
.RE
.\"
.\"
.SH AUTHOR
Written by Karel Zimmer <info@karelzimmer.nl>.
CC0 1.0 Universal <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH SEE ALSO
\fBkz_common.sh\fR(1),
\fBkz-menu\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator, Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Command \fBkz wifi\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website <https://karelzimmer.nl/html/en/linux.html#scripts>.
