.\"# ##########################################################################
.\"# SPDX-FileComment: Man page for kz_common.sh
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"# ##########################################################################

.TH "KZ_COMMON.SH" "1" "4.2.1" "kz" "User commands"
.ad l

.SH NAME
kz_common.sh - common module for kz Bash scripts

.SH SYNOPSIS
.SY source\ kz_common.sh
.YS

.SH DESCRIPTION
This module provides access to common functions for kz Bash scripts.
.LP
General functions such as:
.br
- first actions when starting a script (kz.init)
.br
- final actions when terminating a script (term)

.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.py\fR(1)

.SH KZ
Part of the \fBkz\fR(1) package.
