.\"############################################################################
.\"# SPDX-FileComment: Man page for kz_common.sh
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ_COMMON.SH" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz_common.sh - Common module for shell scripts

.SH SYNOPSIS
.SY source\ kz_common.sh
.YS

.SH DESCRIPTION
This module provides access to global constants and functions.
.LP
General variables such as:
.br
- exit values (OK, ERR)
.br
- terminal attributes (BOLD, RED)
.sp
General functions such as:
.br
- initial actions when starting a script (init)
.br
- process options such as usage and help (process_options)
.br
- check usage of superuser, root (become_root)
.sp
This module also provides script hardening and error handling.

.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.py\fR(1),
.UR https://karelzimmer.nl/nl/en
.UE
