.\"############################################################################
.\"# SPDX-FileComment: Man page for kz_common.py
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ_COMMON.PY" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz_common.py - Common module for Python scripts

.SH SYNOPSIS
.SY import\ kz_common
.YS

.SH DESCRIPTION
This module provides access to global constants and functions.
.LP
General variables such as:
.br
- exit values (kz_common.OK, kz_common.ERR)
.sp
General functions such as:
.br
- process options (kz_common.process_options)
.br
- check usage of superuser, root (kz_common.become_root_check)

.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
.UR https://karelzimmer.nl/en
.UE
