.\"############################################################################
.\"# SPDX-FileComment: Man page for kz_common.py
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################
.\"
.TH "KZ_COMMON.PY" "1" "4.2.1" "kz" "User commands"
.\"
.\"
.SH NAME
kz_common.py \- Common module for Python scripts
.\"
.\"
.SH SYNOPSIS
.B import kz_common
.\"
.\"
.SH DESCRIPTION
This module provides access to global constants and functions.
.sp
General variables such as:
.br
- exit values (kz_common.OK, kz_common.ERR)
.sp
General functions such as:
.br
- process options (kz_common.process_options)
.br
- check usage of superuser, root (kz_common.become_root_check)
.\"
.\"
.SH AUTHORS
Written by Karel Zimmer <info@karelzimmer.nl>.
.br
License CC0 1.0 <https://creativecommons.org/publicdomain/zero/1.0>.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1),
\fBhttps://karelzimmer.nl/en\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator, Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Module \fBkz_common.py\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website <https://karelzimmer.nl/en>, under Linux.
