.\"############################################################################
.\"# SPDX-FileComment: Man page for kz_common.py
.\"#
.\"# SPDX-FileCopyrightText: Karel Zimmer <info@karelzimmer.nl>
.\"# SPDX-License-Identifier: CC0-1.0
.\"############################################################################

.TH "KZ_COMMON.PY" "1" "4.2.1" "kz" "User commands"

.SH NAME
kz_common.py - common module for kz Python scripts

.SH SYNOPSIS
.SY import\ kz_common
.YS

.SH DESCRIPTION
This module provides access to common functions for kz Python scripts.
.LP
General functions such as:
.br
- initial actions when starting a script (init)
.br
- check usage of superuser, root (become_check)

.SH SEE ALSO
\fBkz\fR(1),
\fBkz_common.sh\fR(1)

.SH KZ
Part of the \fBkz\fR(1) suite.
