.\"#############################################################################
.\"# Man page for kz_common.sh.
.\"#
.\"# Written Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
.\"# <https://creativecommons.org/publicdomain/zero/1.0>, 2023.
.\"#############################################################################
.\"
.TH "KZ_COMMON.SH" "1" "2009-2023" "kz 2.4.7" "Kz Manual"
.\"
.\"
.SH NAME
kz_common.sh \- Common module for shell scripts.
.\"
.\"
.SH SYNOPSIS
.B source kz_common.sh
.\"
.\"
.SH DESCRIPTION
This module provides access to general variables and functions.
.sp
General variables such as:
.br
- exit values (ok, err)
.br
- terminal attributes (green, red)
.sp
General functions such as:
.br
- initial actions when starting a script (init_script)
.br
- process options such as usage and help (process_common_options)
.br
- check usage of superuser, root (check_user_root)
.sp
This module also provides script hardening and error handling.
.\"
.\"
.SH AUTHOR
Written by Karel Zimmer <info@karelzimmer.nl>, CC0 1.0 Universal
<https://creativecommons.org/publicdomain/zero/1.0>, 2009-2023.
.\"
.\"
.SH SEE ALSO
\fBkz\fR(1),
\fBhttps://karelzimmer.nl\fR
.\"
.\"
.SH KZ
Part of the \fBkz\fR(1) package, named after its creator, Karel Zimmer.
.\"
.\"
.SH AVAILABILITY
Module \fBkz_common.sh\fR is part of the \fBkz\fR package and is available on
Karel Zimmer's website <https://karelzimmer.nl/html/en/linux.html#scripts>.
